### ISSUE TITLE
Docs: Elaborate how to get started using ffe in other projects

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#103]
Readme.md currently describes how to clone the repo, run builds and start a local server. Some documentation on how to import components and styling and into your own project/consuming the system in general might come in handy as well.

**Comment by wkillerud** [comment]
I can write a suggestion for further discussion

**Comment by wkillerud** [comment]
The first iteration is live on https://design.sparebank1.no/kom-i-gang.html#kom-i-gang_for-utviklere :tada:

**Comment by wkillerud** [comment]
I posted the updated docs in our internal channels and got a :+1: I think we're good for the 1.0 milestone. I'll close this issue for now - if new users run into trouble we'll improve the docs as we go.
