### ISSUE TITLE
Should we use Greenkeeper?

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#106]
[Greenkeeper](https://greenkeeper.io/) is a cool service which is open to us now that we're on GitHub. 

What is Greenkeeper?

> Greenkeeper sits between npm and GitHub, observing all of the modules you depend on. When they get updated, your project gets a new branch with that update. Your CI tests kick in, and we watch them to see whether they pass.
>
> Based on the test results and your current version definitions we will open up clear, actionable issues for you.

Also:

> We support Open Source Software: Greenkeeper will always be free for public repositories!

**Comment by selbekk** [comment]
I think we should!

**Comment by antidecaf** [comment]
Sounds good to me!

**Comment by wkillerud** [comment]
Opened #108
