### ISSUE TITLE
Ingen disabled-styling på radioknapper

### ISSUE THREAD

**Issue by henninghuseby** [SpareBank1/designsystem#1064]
**Beskrivelse av feilen**
Radioknapper får ikke noe spesifikk styling når den er disabled

**Steg for å gjenprodusere**
legge til `disabled="true"`

**Forventet oppførsel**
Forventer at radioknappen får en distinktiv styling når jeg sender inn disabled attributtet

**Comment by pethel** [comment]
Vill bare legge til att jag tror de flesta skjermleser ignorerar elementer med disabled. Burde nok heller løsas med aria-disabled och styling hvis dette er ønskelig og støtta.

**Comment by antidecaf** [comment]
Et ux-prinsipp som i alle fall gjelder for knapper er at man skal unngå å bruke disabled state og heller legge inn beskrivende tekst eller annet som forklarer flyten videre. Antar problemstillingen vil være ganske lik for radioknapper. 

@sirioc: Har du noen innspill?

**Comment by sirioc** [comment]
Ja, i prinsippet har vi ikke disabled states, det gir ikke en optimal brukeropplevelse. Vi prøver vi å løse slike caser med å feks gjøre endringer på skjemaet dersom man føler et behov for å ha disabled state. Nå vet jeg ikke hva behovet deres er @henninghuseby ? Men ta gjerne kontakt om dere vil sparre litt på andre muligheter :)
