### ISSUE TITLE
Set up Greenkeeper

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#108]
[Greenkeeper](https://greenkeeper.io/) is a cool service which is open to us now that we're on GitHub. 

What is Greenkeeper?

> Greenkeeper sits between npm and GitHub, observing all of the modules you depend on. When they get updated, your project gets a new branch with that update. Your CI tests kick in, and we watch them to see whether they pass.
>
> Based on the test results and your current version definitions we will open up clear, actionable issues for you.

Also:

> We support Open Source Software: Greenkeeper will always be free for public repositories!

If it requires any setup such as access tokens etc then make sure to use the dedicated design system account (ping _kwltrs_ for help on this).

**Comment by selbekk** [comment]
Do you want to do this @kwltrs, since you have the login info to set it up correctly? If not, slide by my desk or pass me an email with the credentials or something. It looks pretty simple to set up, but you need to add it as the correct user.

**Comment by kwltrs** [comment]
We need to wait for greenkeeper to support monorepos, see https://github.com/greenkeeperio/greenkeeper/issues/594

**Comment by wkillerud** [comment]
Right, I hadn't considered the (lack of) monorepo support...

**Comment by selbekk** [comment]
I don|t see why we need to wait for that in order to use Greenkeeper at a top level. That's where most of our dev dependencies and all styleguide dependencies are anyways?

**Comment by wkillerud** [comment]
https://github.com/greenkeeperio/greenkeeper/issues/594#issuecomment-395048730

> This has been shipped! :ship: 

:shipit:

**Comment by ivarni** [comment]
https://twitter.com/greenkeeperio/status/1007245789679243266

**Comment by antidecaf** [comment]
Fixed in #361
