### ISSUE TITLE
Contrast on focus ring is low for certain elements, backgrounds

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#11]
See attached images. Can we change what color we use for the focus ring?

![color-contrast-blue-background](https://user-images.githubusercontent.com/1223410/36670650-3f62f68c-1af9-11e8-9d87-66657bd41947.png)
![color-contrast-radio-switch](https://user-images.githubusercontent.com/1223410/36670652-3f8e48f0-1af9-11e8-9cbc-e1b4c34deaa7.png)

**Comment by selbekk** [comment]
Thoughts on this @adidick @hodoea ?

**Comment by hodoea** [comment]
hmm @wkillerud I work only on mobile patterns, so I might be wrong now: but it seems on the `åpne sider` when you hover a green button(such as the one you have shown above) it only becomes darker. where is your button from? See my image below
<img width="334" alt="skjermbilde 2018-02-27 kl 16 28 16" src="https://user-images.githubusercontent.com/8971560/36737564-acbbf4ee-1bdb-11e8-8681-e3558e56b62f.png">

**Comment by hodoea** [comment]
The full picture 
<img width="823" alt="skjermbilde 2018-02-27 kl 16 31 55" src="https://user-images.githubusercontent.com/8971560/36737607-c2b5ae66-1bdb-11e8-9ce1-6f2bba78d4b0.png">

**Comment by wkillerud** [comment]
Not sure where the original screenshot is from (it's from the internal issue tracker archives :female_detective: ), but in the Forsikring apps for PM all focusable elements get that border around them when focused (like when you hit Tab on a computer keyboard and the browser highlights an element).

I see Åpne sider get the same focus border on some elements, but not all - some use the web browser default :thinking:

**Comment by adidick-zz** [comment]
Yes, we could change it. We'll have to take a look at all possible foreground/background colour combos and see what would work best. It's something I can take up in GD forum.

**Comment by selbekk** [comment]
I'll assign this to you then @adidick - do you mind updating us when you've had a talk with your colleagues at the GD forum?

**Comment by selbekk** [comment]
Any update here @adidick ? :)

**Comment by ivarni** [comment]
This has been a problem since forever. We're not doing any custom focus-styles so we just get whatever default the browser has and that does not play nice with our colours most of the time.

We have a similar issue with focus on radio-buttons, especially when they're active.

**Comment by wkillerud** [comment]
> We're not doing any custom focus-styles so we just get whatever default the browser has

We do, actually. At least for [buttons](https://github.com/SpareBank1/designsystem/blob/405a4559cfcf27b0556f82ea6e347d5da92dd9e4/packages/ffe-buttons/less/base-button.less#L75-L76) and [form fields](https://github.com/SpareBank1/designsystem/blob/405a4559cfcf27b0556f82ea6e347d5da92dd9e4/packages/ffe-form/less/input-field.less#L20-L22). The focus ring is "Chrome-like", but for instance in Firefox it's different from the default for these elements (the default is a black dotted border).

**Comment by adidick-zz** [comment]
Hi all, sorry, looks like I missed this one! What would be the best technical solution here? @wkillerud @ivarni @selbekk We have different coloured button variations throughout our design that will prove troublesome with the blue focus colour we use. What about if we added a 1px white border to the outside of the button (which lies inside the focus blue blur colour)? Atlassian do it (I'm not sure technically how) and it makes it a lot easier to see when a coloured element is in focus.
https://www.atlassian.com/

**Comment by selbekk** [comment]
@adidick I'm sure we could technically solve it - but how about using our orange color instead? It's easier to spot, and it's according to our design.

Regardless of color, could you attach an image of the effect you're looking to implement?

**Comment by adidick-zz** [comment]
@selbekk Looking into it there seems to be a few different possibilities. How do you usually assign focus styles to elements in code? Is it a set standard you use for everything or specific to each element, e.g. Action button in FFE?
I'm thinking it could be good to define some variants that basically work depending on what the element is and what colour background it's sitting on. For example:
1. Normal blue version - for light elements on light backgrounds
2. A contrasting colour (e.g. white) - for coloured elements on coloured/dark backgrounds

The main thing is to make sure that the focus is easily visible in all use cases.

**Comment by ivarni** [comment]
We can have different focus styles on different components, we don't have to use the same solution everywhere.

**Comment by adidick-zz** [comment]
@ivarni What about two style variants on one component? 
E.g. Action button on white background, Action button on dark background

**Comment by selbekk** [comment]
That's a bit harder to accomplish in a generic way.

**Comment by antidecaf** [comment]
Any news on this issue? Has this been discussed within GD? @adidick

**Comment by adidick-zz** [comment]
Jeg husker ikke hvem jeg snakket med om det før sommer men jeg har laget et forslag på hvordan vi kunne gjør det og det er lagt inn i ny sketch malet. Vi kan godt ta en titt på det på DS forum på torsdag. Her er eksemplet:
![image](https://user-images.githubusercontent.com/8871429/43778748-c8a2be6e-9a56-11e8-9d44-ed379bb44016.png)
