### ISSUE TITLE
Make RadioButtonInputGroup Description support Node in addition to String

### ISSUE THREAD

**Issue by TobiasHansen** [SpareBank1/designsystem#1112]
In the documentation regarding the Description prop it is descriped that the Description is to `To just render a static, always visible tooltip, use this.`, but while Tooltip has the propType `oneOfType([node, string])` the Description only supports `string`. 

We would like to change the proptype of the Description to be the same as the Tooltip prop.

We can implement this change and make a PR, but would like to check if people agree first.

**Comment by kwltrs** [comment]
Høres fornuftig ut. Kom gjerne med en PR :slightly_smiling_face:
