### ISSUE TITLE
PhoneNumber component is missing fieldMessage

### ISSUE THREAD

**Issue by TobiasHansen** [SpareBank1/designsystem#1113]
The PhoneNumber component uses `numberInvalid` and `countryCodeInvalid` to describe if the values is invalid, this renders a red box around the component. This is different from most other components that uses fieldMessage, that allows for rendering a text describing the error.

We would like to  replace the `numberInvalid` and `countryCodeInvalid` with `numberFieldMessage` and countryCodeFieldMessage.

We can implement this if people agree with the changes.

**Comment by kwltrs** [comment]
Det gir mening. Kjør på :+1:

**Comment by kwltrs** [comment]
Fixed i #1127
