### ISSUE TITLE
Muliggjøre å bla per år for dato komponent

### ISSUE THREAD

**Issue by HHSande** [SpareBank1/designsystem#1114]
Det er kun mulig å bla måned for måned i dato komponenten, man har lyst til å bruke denne komponenten for å sette fødselsdato, da blir det tungvindt å bla måned for måned.
Ved å kunne bla år for år blir dette enklere.

**Comment by andrea-sb1** [comment]
@HHSande Det er supert å ta opp dette i felles designforum eller UX-forum, gjerne med skisser til hvordan dere tenker det kan løses :-)
