### ISSUE TITLE
Avvikle Travis CI

### ISSUE THREAD

**Issue by kwltrs** [SpareBank1/designsystem#1123]
P.t. bruker designsystemet travis-ci til to ting: 1. bygge og publisere github pages, og 2. kjøre tester på pull request.
 
For å redusere systemer man trenger å forholde seg til burde travis-ci erstattes med github actions.

**Comment by antidecaf** [comment]
Travis har i tillegg innskrenket gratiskvotene sine etter at de flyttet alt fra .org til .com. Som følge av det er byggene våre nå midlertidig deaktivert:

> Builds have been temporarily disabled for public repositories due to a negative credit balance.

**Comment by HeleneKassandra** [comment]
Denne kan vel lukkes? @kwltrs
