### ISSUE TITLE
Firkantede hjørner på alle ffe-knapper i Firefox på RHEL8

### ISSUE THREAD

**Issue by gwtwod** [SpareBank1/designsystem#1130]
**Beskrivelse av feilen**
Når man flytter musen over ffe-knapper får de en firkantet boks rundt som forsvinner igjen med en gang. Virker som det skjer for alle med Firefox på RHEL8.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til f.eks. sparebank1.no
2. Flytt musen over (nesten) hvilken som helst ffe-button
3. Se feilen

**Skjermskudd**
![mouseover](https://user-images.githubusercontent.com/40236320/122523628-89d20600-d017-11eb-84f9-5a68e18e7e73.gif)

**Desktop (fyll ut feltene ):**
 - Operativssystem: Red Hat Enterprise Linux release 8.4 (Ootpa)
 - Nettleser: Firefox
 - Versjonsnummer: 78.11.0esr (64-bit) - Standard versjon fra repo i RHEL8

**Comment by antidecaf** [comment]
Hei! Av knappene i skjermopptaket er det kun `Sjekk pris på livsforsikring` som er stylet med ffe.

Dette ser for øvrig ut til å skyldes en bug i en relativt gammel versjon av Firefox (Extended Support Release), som følger med RHEL8. ESR er en versjon av Firefox myntet på store organisasjoner, som skal være mer stabil og gjennomtestet men ofte mangler nye features. Bugen er ikke mulig i å gjenskape i nyere Firefox. Vi lar derfor denne ligge. :)
