### ISSUE TITLE
ExpandButton feiler på wave-evaluering

### ISSUE THREAD

**Issue by lindkjop** [SpareBank1/designsystem#1139]
**Beskrivelse av feilen**
ExpandableButton feiler på wave-evaluering, muligens på grunn av et manglende alt-attributt.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Logg inn i test med en testkunde som har finansieringsbevis. (Sender detaljer på slack) 
2. Ha wave installert i nettleseren (https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)
3. Høyreklikk og "Wave this page"
4. Se at wave har 1 error - no button text. 

**Forventet oppførsel**
Wave gir ingen error. 

**Skjermskudd**
![Wave](https://user-images.githubusercontent.com/3727600/123432756-fa09fa00-d5ca-11eb-842e-5917402aa99e.png)

**Desktop (fyll ut feltene ):**
Ikke relevant

**Mobil (fyll ut feltene):**
Ikke relevant

**Tilleggsinformasjon**
For å reprodusere og verifisere at løsningen funker kan man lage en dummy-side som tar i bruk ExpandButton, også kjøre wave-evaluering på den siden.

**Comment by HeleneKassandra** [comment]
VI fant ut at det ikke er expandknappen denne reagerer på, så lukker issuet :)
