### ISSUE TITLE
ffe-button-group do not wrap buttons onto multiple lines

### ISSUE THREAD

**Issue by torbein** [SpareBank1/designsystem#114]
#### Package this issue related to:
designsystem/packages/ffe-buttons/less/button-group.less
#### Issue:
As shown in the screenshot below the buttons in ffe-button-group div do not wrap when the width of the parent is to small. 
![screenshot from 2018-03-22 12-10-46](https://user-images.githubusercontent.com/1019313/37769139-4fcb710e-2dd0-11e8-9952-2eeb9e630507.png)

#### Expected behavior:
Buttons that have ffe-buttons-group as parent should wrap when the width is to small.
#### Actual behavior:
Buttons that have ffe-buttons-group as parent do not wrap when width is to small.
#### Steps to reproduce
Go to http://design.sparebank1.no/styleguidist/index.html#buttongroup and resize the screen to 480px in width.

**Comment by ivarni** [comment]
Looks like `display: flex;` was added [here](https://github.com/SpareBank1/designsystem/commit/57f5219bb20aa1637ccefac5a26c20cce94efdb3#diff-c5c60a5af22b7c2a1bd3fbe80e08c51bR2)

`.ffe-button-group` should have had `flex-direction: column` on small screens I think.

**Comment by antidecaf** [comment]
^ To expand on that, children of `.ffe-button-group` do seem to have `flex-direction: column`, but the property needs to be assigned to the parent element in order to work as expected.

**Comment by ivarni** [comment]
I can only see `flex-direction: column` on the `.ffe-inline-button` class, but either way buttons on small screens should stack vertically and take the full width while they should line up horizontally on larger screens.

I'm not sure what should happen on larger screens if there are too many buttons to fit in horizontally, I've never seen that happen.

**Comment by wkillerud** [comment]
@torbein, are you still working on this or can I take a look? :)

**Comment by torbein** [comment]
@wkillerud sorry. No I am not working on this issue. Forgot to remove my self as assignee. You are welcome to have a look at the issue. Should be pretty pretty straightforward to fix as mentioned above :)
