### ISSUE TITLE
Inline javascript required to process less files

### ISSUE THREAD

**Issue by oskaremil** [SpareBank1/designsystem#115]
There are two places where inline javascript is used in the less files:

- packages\ffe-form\less\dropdown.less:2:@bare-color: replace(~`'@{color}'`, '#', '');
- packages\ffe-searchable-dropdown-react\less\searchable-dropdown.less:2:  @bare-color: replace(~`"@{color}"`, "#", "");

Inline javascript makes it harder for angular-cli based projects to use all the components as the less-loader in webpack cannot be modified with options not provided by angular-cli.

The angular-cli team has already decided to not support more loader-options so I have to ask here if it is possible to rewrite these to classes to do the same without the use of inline javascript.

Temporary workaround, instead of importing the entire ffe-form package with `@import '@sb1/ffe-form/less/form';`, import files one by one and skip dropdown:
```
/* Mixins */
@import '@sb1/ffe-form/less/radioblob-mixin';

/* Inputs*/
@import '@sb1/ffe-form/less/input-field';
@import '@sb1/ffe-form/less/textarea';
@import '@sb1/ffe-form/less/checkbox';
@import '@sb1/ffe-form/less/radio-input';
@import '@sb1/ffe-form/less/radio-button';
@import '@sb1/ffe-form/less/radio-switch';
@import '@sb1/ffe-form/less/radio-block';
@import '@sb1/ffe-form/less/file-upload';

/* Form Layout */
@import '@sb1/ffe-form/less/input-group';
@import '@sb1/ffe-form/less/form-label';
@import '@sb1/ffe-form/less/fieldset';
@import '@sb1/ffe-form/less/tooltip';

/* Validation */
@import '@sb1/ffe-form/less/field-info-message';
@import '@sb1/ffe-form/less/field-error-message';
@import '@sb1/ffe-form/less/field-success-message';

select,
textarea,
input:not([type='radio']):not([type='checkbox']) {
    appearance: none;
}
```

**Comment by selbekk** [comment]
Hm... FWIW, the lines you're referring to are not inline JavaScript, but [LESS functions](http://lesscss.org/functions/). 

What are the problems you're experiencing? Does it crash while building? Can you please post the errors your set up produces?

**Comment by oskaremil** [comment]
Markdown formatting removed my backticks and displayed the functions with code formatting insted. Correct output is:

```
packages\ffe-form\less\dropdown.less:2:    @bare-color: replace(~`'@{color}'`, '#', '');
packages\ffe-searchable-dropdown-react\less\searchable-dropdown.less:2:  @bare-color: replace(~`"@{color}"`, "#", "");
```

I know `replace` is a LESS function and replace is not the problem. LESS preprocessor parses everything between backticks as javascript. I'll throw in a [link to a blog post](https://www.bennadel.com/blog/2638-executing-javascript-in-the-less-css-precompiler.htm) since, as the author, I could not find any documentation about it.

That said, I am not able to reproduce it and you may close this comment

**note to self** in case the error returns The problem might have been triggered by the use of `stylePreprocessorOptions` in angular-cli.json. That requires less package to be installed with less-loader as a dependency. A new project will not default to use stylePreprocessorOptions
