### ISSUE TITLE
Nedtrekksliste med CheckBox

### ISSUE THREAD

**Issue by isakbjugn** [SpareBank1/designsystem#1156]
AccountSelectorMulti er en fin komponent, men lar seg ikke umiddelbart generalisere til andre skjemaelementer. Hva med å lage en nedtrekksmeny som tar CheckBox som listeelementer?

**Comment by HeleneKassandra** [comment]
Hei, Jeg sliter med å forstå hva du egentlig etterspør her? 
Er ikke dette det samme som: https://design.sparebank1.no/styleguidist/index.html#!/AccountSelectorMulti
