### ISSUE TITLE
Nye farger tatt i bruk uten å markere breaking change

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#1166]
**Beskrivelse av feilen**
Nye farger fra ffe-core er tatt i bruk i andre pakke(er?) uten å markere breaking change.
Dette gjelder i hvert fall ffe-context-message, men det kan godt gjelder flere pakker.
Det er heller ikke kommunisert gjennom spesifikk peerDep i ffe-context-message.

**Steg for å gjenprodusere**
Vi har dependency på
```
"@sb1/ffe-context-message": "^4.0.13",
"@sb1/ffe-core": "^15.4.0",
```
som gjør at vi får installert ffe-context-message 4.0.25.
Med 4.0.24 og 4.0.25 tas nye farger fra ffe-core i bruk, men ffe-context-message har en peerDep på ffe-core "*".

Dette gjør at bygget vårt brekker fordi fargene som brukes i ffe-context-message 4.0.25 ikke finnes i ffe-core ^15.4.0.

**Forventet oppførsel**
ffe-context-message burde vært releaset i ny major når det tas i bruk nye farger fra enannen pakke.
ffe-context-message burde ha en peerDep som forteller hvilken versjon av ffe-core man må ha.

**Skjermskudd**
![image](https://user-images.githubusercontent.com/435037/130415097-521cb826-aaad-4825-9f7a-9901ecc0cc74.png)

**Tilleggsinformasjon**
Endring innført av @HeleneKassandra og godkjent av @antidecaf 
Det er jo for sent å fikse at det er releaset uten breaking change, men peerDep kan ryddes opp i. Gå gjerne over andre pakker også.
Semver er viktig! :smiley:

**Comment by antidecaf** [comment]
Her har det gått litt fort i svingene ja, takk for heads up! @kwltrs er på saken, som du kan se :)

**Comment by kwltrs** [comment]
Har pushet en ny hotfix release [@sb1/ffe-context-message@4.0.27](https://www.npmjs.com/package/@sb1/ffe-context-message/v/4.0.27l) som burde løse dette issue her. @henrikhermansen kan du verifisere det?

**Comment by kwltrs** [comment]
Ser ut som ting har falt på plass.
