### ISSUE TITLE
Add contact information to frontpage of design.sparebank1.no

### ISSUE THREAD

**Issue by kwltrs** [SpareBank1/designsystem#117]
Maybe it should be easier to find out who and how to contact us, i.e. move the information given in https://github.com/SpareBank1/designsystem/blob/7e918f7429c388602ef9fd53f56deba08dfc3199/styleguide-content/kom-i-gang/hjelp.md to the frontpage. Yay or nay?

**Comment by antidecaf** [comment]
Yay.

**Comment by selbekk** [comment]
Yay!
