### ISSUE TITLE
import av JS-variabler som er tint() funker ikke

### ISSUE THREAD

**Issue by NghiNg** [SpareBank1/designsystem#1175]
**Beskrivelse av feilen**
import { greyCharcoal, white } from 'ffe-core';
Slik import virker ikke for 70% og 30% fargene som det er brukt tint() på.

**Steg for å gjenprodusere**
Den kommer ikke opp i liste over farger som kan eksporteres.

**Forventet oppførsel**
At 70 og 30 fargene skal kunnes importeres.

**Comment by kwltrs** [comment]
La inn en PR som burde løse dette -> #1024.

**Comment by kwltrs** [comment]
Kan du ta en titt på om [@sb1/ffe-core@19.1.0](https://github.com/SpareBank1/designsystem/releases/tag/%40sb1%2Fffe-core%4019.1.0) løser dette issue?

**Comment by NghiNg** [comment]
Hei, ja, det ser ut til å virke nå.

**Comment by kwltrs** [comment]
:+1:
