### ISSUE TITLE
Accessibility - empty elements

### ISSUE THREAD

**Issue by sebasso** [SpareBank1/designsystem#118]
#### Which package is this issue related to?
ffe-tables-react, ffe-searchable-dropdown
#### Describe your issue (screenshots welcome!)
Certain elements does not have any content which poses a challenge for
those using assistive technologies as shown under with the plugin _WAVE_ in chrome.
![empty-button-content](https://user-images.githubusercontent.com/3595057/37836421-ad56d52e-2eb2-11e8-9ae5-a39f3d4137a5.png)
![empty-header-table](https://user-images.githubusercontent.com/3595057/37836440-b48a5924-2eb2-11e8-96ca-fd7e8f731e2c.png)

#### What is the expected behavior? 
The expected behavior is to have content that describe each html-element.
#### What is the actual behavior?
The actual behavior does not have content that describe each html-element.
#### Steps to reproduce
install wave:
https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh
Change the columns object in Table.md to have an empty header like this:
`header: ''`
Then run npm start and go to the table section and click on the wave icon.

#### Possible solution
Create an additional property where one can turn set something like:
`text-indent: -9999px;` in order to hide the content from the view.

**Comment by antidecaf** [comment]
What exactly is the problem in `ffe-searchable-dropdown`? A few more details on how to reproduce this would be good.

As far as the empty header to the right goes, hiding contents to pass validation isn't really an ideal solution. A couple of alternatives:
* Render a `td` in stead of a `th` if it's empty (apparently table cells do not require data, as opposed to headers)
* Specify an `aria-role` (though I'm not sure which one)
* Delete the `th` altogether and give the previous one `colspan="2"` to make sure the headers align with the content cells
