### ISSUE TITLE
ffe-buttons-react: TertiaryButton only supports rightIcon if there is also a leftIcon

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#12]
`TertiaryButton` doesn't support an icon on the right side of the label unless there is also an icon on the left side. This is an unintended effect of the `simpleContent` prop in `Button` being set to `true` (which renders a simpler markup without support for icons.) unless there is a `leftIcon`.

Quickfix: set `simpleContent` to `false` if there is either a `leftIcon` or a `rightIcon` ([here](https://github.com/SpareBank1/designsystem/blob/e7b68cd44af010bd9e7debc621137f3a6fe84874/packages/ffe-buttons-react/src/TertiaryButton.js#L19))

Perhaps better: get rid of the whole `simpleContent` concept and restructure the components internally to support the different use cases in a simpler way

**Comment by selbekk** [comment]
I'm on this, but I think I'll fix it by rewriting the way buttons are implemented. The current implementation is bogged down with tech debt and decisions that didn't scale - and a new approach is needed.
