### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#120]
#### Which package is this issue related to?

N/A

#### Describe your issue (screenshots welcome!)

http://design.sparebank1.no/ should redirect to https://design.sparebank1.no/

#### What is the expected behavior? 

That all the things are encrypted with SSL

#### What is the actual behavior?

It's possible to go to the designguide via HTTP

#### Steps to reproduce

goto http://design.sparebank1.no/

**Comment by kwltrs** [comment]
There's a checkbox for that: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by ivarni** [comment]
If it was designed by us it would probably have been a radiobutton 🤣.

Tested now and was redirected. LGTM.
