### ISSUE TITLE
AccountSelector listen lukkes ikke når fokus flyttes til en annen AccountSelector i React >17.0.0

### ISSUE THREAD

**Issue by ghost** [SpareBank1/designsystem#1208]
**Beskrivelse av feilen:**
Dersom to eller flere AccountSelector-instanser lever på samme side, vil ikke event-handlingen fungere som forventet i React >17.0.0. Resultatet av dette er at ResultList-en til komponentene ikke lukkes dersom fokus flyttes fra en AccountSelector til en annen. 

Dette fungerer som forventet i bla.a. React 16.14.0.

**Steg for å gjenprodusere:**
1. Kjør opp designsystemet med React >=17.0.1
2. Gå til `/AccountSelector`
3. Trykk i inputfeltet til en av AccountSelector-ene, trykk deretter i input-feltet til en annen AccountSelector på samme side
4. Observer at begge ResultList-ene er åpne samtidig.

**Forventet oppførsel:**
ResultList-en lukker seg dersom fokus flyttes til en annen AccountSelector, tilsvarende som når fokus flyttes ut av komponenten og til en annen komponent.

**Skjermskudd:**
![account-selector](https://user-images.githubusercontent.com/74609491/134019993-82297918-abfe-46c9-992e-3bda3fa107ac.png)

**Desktop:**
 - Operativssystem: Linux
 - Nettleser: Firefox Developer Edition
 - Versjonsnummer: 87.0b2

**Comment by HeleneKassandra** [comment]
Lukker denne da jeg ikke klarer å gjenskape problemet, mulig det har blitt fikset i en av de siste commitene. Bare å åpne på nytt dersom det forsatt er ett problem
