### ISSUE TITLE
Ikke mulig å se at ny primary-button har fokus

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#1212]
**Beskrivelse av feilen**
FFE har aldri hatt gode fokus-styles på knapper men med det nye designet har det blitt enda vanskeligere å se om en `<PrimaryButton />` har fokus.

**Steg for å gjenprodusere**
Naviger til og fra en primary-button med Tab.

**Forventet oppførsel**
Det bør være mulig å se at knappen har fokus

**Skjermskudd**
Her er fokus på Primary-knappen
![image](https://user-images.githubusercontent.com/379849/134849022-4f155ae3-0ab1-4ee0-a80d-9fc7d7a70b92.png)

Her er fokus flyttet til Tertiary-knappen ved siden av
![image](https://user-images.githubusercontent.com/379849/134849061-da4f5610-d9c9-49b8-a8ed-2c72e086b3b3.png)

**Desktop (fyll ut feltene ):**
 - Operativssystem: RHEL 8.,4
 - Nettleser Chrome
 - Versjonsnummer 93.0.4577.82

**Comment by kwltrs** [comment]
Works on my machine (også RHEL 8 og chrome 93). Noe oppskrift hvordan jeg kan gjenskape det?

**Comment by ivarni** [comment]
Det enkleste hadde kanskje vært å oppdatere styleguidist til nyeste versjon, men alternativt:

```
                        <div className="ffe-button-group">
                            <PrimaryButton onClick={() => {}}>
                                Gå videre
                            </PrimaryButton>
                            <TertiaryButton onClick={() => {}}>
                                Tilbake
                            </TertiaryButton>
                        </div>
```

```
    "@sb1/ffe-buttons": "^13.0.1",
    "@sb1/ffe-buttons-react": "^14.0.1",
```

**Comment by ivarni** [comment]
Hvordan er det ment å se ut? Hvilke styles er det som skal styre focus? Alt jeg finner er en focus-style som setter bakgrunnsfargen til det samme som den har i utgangspunket

```
.ffe-button--primary:focus {
    background-color: #005aa4;
}
```

EDIT: https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-buttons/less/base-button.less#L217,L203

**Comment by antidecaf** [comment]
Slik skal det se ut (fokus på "Neste"):

<img width="785" alt="Screenshot 2021-09-27 at 10 21 26" src="https://user-images.githubusercontent.com/463847/134871367-2818354a-73ca-4b90-9436-698a8a417393.png">

Det stemmer at Styleguidist henger etter. Den løsninga blir byttet med noe nytt ut ganske snart.

Stilene som er inne i bildet er et [pseudo-element](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-buttons/less/base-button.less#L75), der opacity toggles ved states.

**Comment by ivarni** [comment]
Denne regelen gir fokus-ringen `opacity: 0` i min browser:
```
.ffe-button:focus:not(:focus-visible)::after {
    opacity: 0;
}
```
Det er altså samme bug som er innført på checkbox-komponenten, der jeg heller ikke ser keyboard-fokus.

Hadde det vært mye jobb å bygge styleguiden på nytt med siste versjon av komponentene sånn at vi kan vite at vi snakker om samme versjon av alt?

**Comment by antidecaf** [comment]
Du kan kjøre styleguiden lokalt, da får du oppdaterte komponenter. Å bygge styleguidist på nytt er dessverre ikke mulig akkurat nå.

**Comment by ivarni** [comment]
Hm.. det fungerer der ja, da må det være noe annet muffins men fungerer det i styleguiden så er jo ikke feilen her.

Kjekt å vite at jeg kan kjøre den lokalt for å få siste versjon av ting, lettere å jobbe med dette da.

**Comment by ivarni** [comment]
Aner ikke hvorfor det ikke virker i vår løsning men får nesten bare krysse fingrene for at det bare feiler på min maskin

**Comment by antidecaf** [comment]
@ivarni 

> Denne regelen gir fokus-ringen `opacity: 0` i min browser:
> 
> ```
> .ffe-button:focus:not(:focus-visible)::after {
>     opacity: 0;
> }
> ```

Vi snublet akkurat over samme feil i den nye dokumentasjonen av designsystemet. Hos oss så det ut til at det var en postcss-plugin som gjorde en aldri så liten (og desto vanskeligere å oppdage) omskrivning:

Fra
`:focus:not(:focus-visible)::after`

til
`:focus:not(.focus-visible)::after`

Fra pseudo-element til klasse, der altså. Kan det være noe lignende som skjer hos dere?

**Comment by ivarni** [comment]
@antidecaf 
Jeg fant aldri ut av det, men da jeg sjekket med devtools så jeg begge reglene i inspectoren og jeg måtte disable begge før fokus-ringen dukket opp.

**Comment by ivarni** [comment]
Disablet `'focus-visible-pseudo-class'` feature'n fra postcss og fokus-stylingen fungerer igjen
