### ISSUE TITLE
Får ikke valgt elementer i SearchableDropdown vha museklikk

### ISSUE THREAD

**Issue by marmje** [SpareBank1/designsystem#1221]
**Beskrivelse av feilen**
Om man følger **eksempelkoden** som ligger ute for SearchableDropdown-komponentene her: https://design.sparebank1.no/komponenter/dropdown/ fungerer det ikke å velge elementer i listene med museklikk (men det fungerer med tastaturnavigering, og hvis man søker først, og deretter klikker på et av søketreffene).

**Steg for å gjenprodusere**
Kan testes ut her:
https://design.sparebank1.no/komponenter/dropdown/

**Forventet oppførsel**
Valg av elementer med museklikk og tastatur bør fungere likt.

**Desktop (fyll ut feltene ):**
 - Operativssystem: Linux
 - Nettleser: Chrome, Firefox

**Tilleggsinformasjon**
- Vanlig Dropdown-komponent ser ut til å fungere.
- SearchableDropdown med flagget highCapacity=true satt ser også ut til å fungere.
- Ganske sikker på at eksempelkoden fungerte i forrige versjon av design.sparebank1.no. 
- Har ikke selv gravd i koden, og vet ikke om det er selve komponenten eller bruken av den i eksempelkoden som er feil her.

**Comment by kwltrs** [comment]
Kort oppdatering: har funnet ut at denne bug kom inn i versjon [9.0.11](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-searchable-dropdown-react/CHANGELOG.md#9011-2021-04-14) av searchable-dropdown.

**Comment by kwltrs** [comment]
Fikset i #1260
