### ISSUE TITLE
Fikse fokusmarkeringer i header

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1224]
Noen av fokusmarkeringene i header-komponenten må oppdateres med den nye fokusstylingen (se skjermbilder) :-)

<img width="1680" alt="Skjermbilde 2021-10-12 kl  12 23 44" src="https://user-images.githubusercontent.com/77671758/136942090-de29c67b-0998-4967-a3f7-96bbe3e3b124.png">

<img width="1680" alt="Skjermbilde 2021-10-12 kl  12 24 08" src="https://user-images.githubusercontent.com/77671758/136942105-5e5f8e35-70a4-4d05-9e67-95de4412bb62.png">

<img width="1680" alt="Skjermbilde 2021-10-12 kl  12 24 43" src="https://user-images.githubusercontent.com/77671758/136942139-c8b04a9e-6432-41fd-8ea0-e0753e6e6bbf.png">

<img width="1678" alt="Skjermbilde 2021-10-12 kl  12 24 54" src="https://user-images.githubusercontent.com/77671758/136942162-9c67e33e-708e-4067-8de2-86c1bcd683b7.png">

<img width="1680" alt="Skjermbilde 2021-10-12 kl  12 24 24" src="https://user-images.githubusercontent.com/77671758/136942206-518510d3-74fc-4a5d-bffc-6417f0dc41a8.png">

**Comment by HeleneKassandra** [comment]
Finnes det noen skisser på hvordan disse fokusmarkeringene skal se ut?

**Comment by andrea-sb1** [comment]
> Finnes det noen skisser på hvordan disse fokusmarkeringene skal se ut?

Ikke skisse på akkurat disse (enda), men tenker samme fokus-styling som vi har ellers :)

- 2 px border
- avrundede hjørner (muligens rette hjørner akkurat i dropdown-lista)
- ffe-farge-vann (light mode)
- ffe-farge-hvit (dark mode)

Knapper, skjema og meldinger kan være gode referanser
