### ISSUE TITLE
Fjerne border i header

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1225]
Det skal ikke være border mellom menyen («Oversikt Betaling Kort ...») og innholdet over. Lager et issue på å fjerne denne :-)

<img width="1368" alt="Group 4036" src="https://user-images.githubusercontent.com/77671758/136942856-ff839e15-8602-4e8f-8016-a2a7779d701c.png">

**Comment by HeleneKassandra** [comment]
Denne kan egentlig ikke løses av oss.  Headeren er ikke en react komponent, det er kun styling, så alle teamene har implementert html kode på sin egen måte. Har fjernet streken fra eksempelet da :)
