### ISSUE TITLE
Forbedre styling av component-overview

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1258]
Component-overview trenger litt styling for å fungere optimalt til bruk under utvikling. Noen forslag til å begynne med:

* Begrense layouten i bredden (f.eks gir ikke 2000px brede eksempler på `<input>` mening) 
* Tydeligere skille mellom eksemplene og component-overview sitt interface (f.eks mer luft?)
* Endre farger i dark mode (default tekstfarge er fjell, ikke lesbart på sort bakgrunn)
* Mulighet for å vise eksemplene i mobil størrelse uten å endre bredde på hele browservinduet
* Tydeligere lenker/ikoner for navigasjon (Hjem/Edit i bunnen)

**Comment by HeleneKassandra** [comment]
Helt enig! I forhold til de automatiske testene er det også viktig at alle eksemplene er wrappet i en form for div eller noe med ett klassenavn som jeg kan sjekke mot, og at den div'en ikke inneholder noen andre elementer som kan forstyrre UU-testresultatet.
