### ISSUE TITLE
RadioButtonInputGroup: name er optional, men det genereres ikke automatisk et navn for gruppen

### ISSUE THREAD

**Issue by etse** [SpareBank1/designsystem#1264]
**Beskrivelse av feilen**
Vi har en enkel komponent som bruker en radio-switch. Vi oppdaget da at `RadioButtonInputGroup` ikke krevde at man sendte inn name, og definerte den slik som dette:
```
<RadioButtonInputGroup label={"en label"}>
    {(inputProps: RadioSwitchProps) => (
        <RadioSwitch {...inputProps} leftLabel="Ja" leftValue={true} rightLabel="Nei" rightValue={false} />
    )}
</RadioButtonInputGroup>
```

**Forventet oppførsel**
Siden name er optional og ikke sendt inn forventer jeg at komponenten genererer et navn automatisk for radio-knappen. Eventuelt at name er satt til required så dette ikke kompilerer.

**Comment by antidecaf** [comment]
Takk for bugrapport! Send gjerne en PR dersom du har mulighet og en fiks for hånden. :) 
Ellers tar vi tak i dette så snart vi kan.

**Comment by HeleneKassandra** [comment]
Hei, La nettopp inn en PR der jeg prøver å fikse dette issuet.
Valgte å gå for å bare gjøre name required, siden jeg tror det kan fort lede til veldig dårlig navngivning om vi prøver oss på en generert en.

**Comment by etse** [comment]
Veldig fint :) Tror man burde oppdatere index.d.ts også: https://github.com/SpareBank1/designsystem/blob/a6ad97e6592d49c21fb4f5cd4de5bb519fc7cabf/packages/ffe-form-react/src/index.d.ts#L123

Kan få laget en PR på det
