### ISSUE TITLE
Inputs som er disabled vises forskjellig i Firefox og Chrome

### ISSUE THREAD

**Issue by lundal** [SpareBank1/designsystem#1266]
**Beskrivelse av feilen**
Inputs som er disabled vises forskjellig i Firefox og Chrome. I Firefox får de grå bakgrunn, mens i Chrome er de transparente.

Med dark-mode vises de likt.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til https://design.sparebank1.no/komponenter/skjemaelementer/
2. Legg til disabled i første kodeeksempel

**Forventet oppførsel**
Lik bakgrunn i alle nettlesere. Enten hvit eller grå.

**Skjermskudd**

_Firefox_
![firefox](https://user-images.githubusercontent.com/1502260/141118975-4846c2ae-c8bc-4319-88f8-966963dd873f.png)

_Chrome_
![chrome](https://user-images.githubusercontent.com/1502260/141118968-bc192b7e-3472-4f64-b852-291a9b1c17e6.png)

**Desktop 1:**
 - Operativssystem: RHEL 8
 - Nettleser: Firefox
 - Versjonsnummer 91

**Desktop 2:**
 - Operativssystem: RHEL 8
 - Nettleser: Chrome
 - Versjonsnummer 95

**Tilleggsinformasjon**
Det virker ikke som om skjemakomponenter har egne stiler for disabled lenger. Er det meningen at dette skal bort?

**Comment by antidecaf** [comment]
Hei!

Det stemmer at vi ikke har styling for disablet input eller knapper, så det du ser i skjermbildene er browser default. Grunnen til det er at det fra et UX-perspektiv har vært ønskelig at man unngår å bruke disabled state, og heller legger inn beskrivende tekst eller annet som forklarer videre flyt der det er nødvendig. Disabled state er problematisk med tanke på brukeropplevelse og universell utforming, blant annet fordi det gjør skjemaelementer utilgjengelig for fokus via tab/tastatur.

Hvor problematisk det er avhenger nok av use-case og litt sånt, så det kan kanskje være en start å ta diskusjonen opp igjen på UX-forum, designforum, en egnet kanal på Slack, eller noe i den duren. :)

**Comment by lundal** [comment]
Da høres det ut som vi bør ta en runde på stedene vi bruker disablede inputs og se om det kan løses bedre på andre måter. Hvis ikke får vi ta opp diskusjonen.
