### ISSUE TITLE
Endre fra 32 til 22 padding for knappene (Figma og FFE)

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1267]
For å unngå at mange knapper brekker over to linjer på mobil kan vi endre paddingen på venstre og høyre side til 24 piksler

Magnus Trevisan Kjeldsen og jeg har sett på det og tror det vil fungere bra å gå ned litt på paddingen :)

**Comment by antidecaf** [comment]
Det bør kanskje heller være 24 px?
22 er ikke en verdi som finnes i spacing-oppsettet vårt, ref [design.sparebank1.no/profil/spacing](https://design.sparebank1.no/profil/spacing/).

**Comment by andrea-sb1** [comment]
Godt poeng! Endrer beskrivelsen :)
