### ISSUE TITLE
InputGroup plasserer Tooltip på egen linje når Label går over flere linjer

### ISSUE THREAD

**Issue by lundal** [SpareBank1/designsystem#1277]
**Beskrivelse av feilen**
InputGroup plasserer Tooltip på egen linje når Label går over flere linjer. Årsaken er at Tooltip legges etter Label og ikke inni. RadioButtonInputGroup har ikke det samme problemet for der plasser Tooltip inni legend. Problemet viser seg oftest på mobil pga smal skjerm.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til https://design.sparebank1.no/komponenter/skjemaelementer/#inputgroup
2. Finn en InputGroup med tooltip
3. Gjør labelen så lang at den går over flere linjer
4. Se feilen

**Forventet oppførsel**
Jeg hadde forventet at Tooltip kom på siste linje inni Labelen, slik den gjør i RadioButtonInputGroup. 

**Skjermskudd**
_Lang label i InputGroup:_
![Screenshot from 2021-11-22 14-35-34](https://user-images.githubusercontent.com/1502260/142871118-3645e3f8-26e7-420d-94e4-03ac460fd33c.png)

_Lang label i RadioButtonInputGroup:_
![Screenshot from 2021-11-22 14-35-09](https://user-images.githubusercontent.com/1502260/142871200-5a3ae363-f5ba-47d0-ae05-f429ed27ab4d.png)

**Desktop**
 - Operativssystem: RHEL8
 - Nettleser: Firefox
 - Versjonsnummer: 94

**Tilleggsinformasjon**
Nåværende workaround er å manuelt plassere Tooltip inni Label:
```jsx
<InputGroup label={
    <Label>
        {label}
        <Tooltip>{tooltip}</Tooltip>
    </Label>
}/>
```

**Comment by antidecaf** [comment]
Interaktive/klikkbare elementer skal helst ikke nøstes inni `label`, [ref MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns). Eksempelet med `RadioButtonInputGroup`/`legend` har ikke den samme begrensningen.

Enig i at plasseringen ikke er optimal, men det bør løses med CSS.
