### ISSUE TITLE
formatCurrency stripper alle postfixer ved decimaler

### ISSUE THREAD

**Issue by espkva** [SpareBank1/designsystem#1286]
**Beskrivelse av feilen**
formatCurrency stripper vekk postfix hvis beløpet er i øre. Dette er gjort for å forhindre bruken av ,– med desimaler som ikke er lov ifølge: http://www.sprakradet.no/svardatabase/sporsmal-og-svar/kronebelop-rekkjefolgje-komma-og-strek/

Men i de tilfellene andre typer postfix sendes inn så blir de også strippet.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Formater et desimalbeløp med egendefinert postfix som ikke er lik ,–
2. Beløpet formateres uten postfix

**Forventet oppførsel**
Beløpet formatteres med postfix så lenge postfix er godkjent i kombinasjon med desimaler

Edit: Prøvde å opprette PR, men fikk permission denied
Edit2: PR: https://github.com/SpareBank1/designsystem/pull/1287/files

**Comment by kwltrs** [comment]
Resolve in #1287
