### ISSUE TITLE
Legge til index.d.ts i ffe-decorators-react og ffe-file-upload-react

### ISSUE THREAD

**Issue by kwltrs** [SpareBank1/designsystem#1291]
Pakkene ffe-decorators-react og ffe-file-upload-react mangler typescript definitions som må legges inn.

**Comment by kwltrs** [comment]
ffe-file-upload-react fikk typescript deklarasjoner i #1397

**Comment by tuva-odegard** [comment]
Lukker siden ffe-decorators ikke finnes mer og ffe-file-upload er 100% typescript nå.
