### ISSUE TITLE
Alfabetisering i dokumentasjonen

### ISSUE THREAD

**Issue by sverrejb** [SpareBank1/designsystem#1297]
I oversikten over komponenter er det tilsynelatende ingen meningsbærende rekkefølge. I så fall vil kanskje en alfabetisering gjøre det enklere å finne det man ser etter.
![image](https://user-images.githubusercontent.com/3786663/146773817-c646225d-473b-49b2-aa91-a51fc62a0dc4.png)

**Comment by HeleneKassandra** [comment]
Dokumentasjonen ligger i ett annet repo, har fikset og merget dette issuet, og det kommer live neste gang dokumentasjonen releaser i løpet av dagen :)
