### ISSUE TITLE
ffe-formatters.formatCurrency runder feil i noe tilfeller

### ISSUE THREAD

**Issue by kwltrs** [SpareBank1/designsystem#1320]
Funksjonen `formatCurrency` i pakken `ffe-formatters` runder tal med tre desimaler av nedover når den tredje desimal er 5. Det kan forventes at den runder oppover. F.eks `formatCurrency(1.225)` blir til `"kr 1,22"` men burde være `"kr 1,23"`.

Commiten 15ad684495a04adbf501204e427db4d6fe27a9bf i branchen "fix-ffe-formatters-decimal-round" demonstrerer denne oppførselen med en feilende test case.

**Comment by pethel** [comment]
@kwltrs 

Jag tror denne kan lukkes. Skulle begynne og se på den lagade en test som kjørde grønt. 

```
    test('.....', () => {
        expect(formatCurrency('1.225', { prefix: '', postfix: 'kr' })).toBe(
            `1,23kr`,
        );
    })

```

**Comment by tuva-odegard** [comment]
<img width="434" alt="image" src="https://github.com/SpareBank1/designsystem/assets/155720728/bbfed74e-6a14-4699-b0ca-f35fae61b65d">
Det samme skjer online i designsystemet. Lukker den :)
