### ISSUE TITLE
ffe-accordion: Har skjult avhengighet til ffe-collapse

### ISSUE THREAD

**Issue by arzmir** [SpareBank1/designsystem#1323]
**Beskrivelse av feilen**
Accordion/AccordionItem er ikkje self-contained når det kjem til stilar og det er ikkje dokumentert at man avhenger av å hente eksplisitt må inkludere stilen `ffe-collapse-transition` frå `ffe-collapse`. 

Konsekvensen er at:
1. Accordion ikkje animerar sånn som på https://design.sparebank1.no/komponenter/accordion/
2. Eventuelt dynamisk innhald i `AccordionItem.children[]` klippes som følge av at `height`-property-en på `.accordion-item--open > .ffe-collapse-transition` forblir statisk (ein talverdi i staden for auto)

**Steg for å gjenprodusere**
1. Importer `Accordion`/`AccordionItem`
2. Unngå å importer stil frå `@ffe-collapse` (spesifikt `ffe-collapse-transition`)
2. Lag ein komponent som har fast innhald
3. Lag ein annan med dynamisk innhald (stateful som re-rendrar etter litt tid)
4. Legg desse inn som barn av kvar sin `AccordionItem`
6. Ekspander AccordionItem og sjå at desse ikkje animerar. 
7. Inspiser DOM-en og sjå at når man ekspanderer både den faste og den dynamiske så forblir den statiske høgda som skal vere midlertidig satt ved animering.

Repo med kode som reproduserer (inkluderer `ffe-collapse-transition`, men er berre å kommentere ut stilen)
https://github.com/arzmir/repro-sb1-ffe-issue-1323

**Forventet oppførsel**
1. At beskrivelsen på https://design.sparebank1.no/komponenter/accordion/ er komplett sånn at man får lik komponentoppførsel når man drar Accordion inn i eige prosjekt.
2. At Accordion takler og animerar barn med dynamisk innhald og som re-rendrar seg sjølv.

**Skjermskudd**
Slik det ser ut på https://design.sparebank1.no/komponenter/accordion/ 
![image](https://user-images.githubusercontent.com/417607/154032455-2322e191-94fc-46bc-b857-9bd4d8df9636.png)

Slik det ser ut i reproduksjonen:
![image](https://user-images.githubusercontent.com/417607/154032669-4b4cbf41-7575-43d8-bc73-ab62e9549d50.png)

**Desktop (fyll ut feltene ):**
 - Operativssystem: Linux RHEL8
 - Nettleser: Firefox 
 - Versjonsnummer: 91.5.0esr

**Desktop (fyll ut feltene ):**
 - Operativssystem: Linux RHEL8
 - Nettleser: Chrome
 - Versjonsnummer: 98.0.4758.80

**Desktop (fyll ut feltene ):**
 - Operativssystem: Mac OS Monterey 12.1
 - Nettleser: Vivaldi
 - Versjonsnummer: 5.0.2497.48

**Comment by kwltrs** [comment]
Takk for at du meldte inn dette :+1:  Tenker vi oppdaterer dokumentasjonen og påpeker avhengigheten til stylingen i ffe-collapse-react.
