### ISSUE TITLE
Grid aka rad? 

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#133]
<img width="953" alt="skjermbilde 2018-03-28 kl 10 25 45" src="https://user-images.githubusercontent.com/8971560/38017510-8f191da6-3272-11e8-9980-643069f4fa7c.png">

Hva er bakgrunnen for dette? Hva menes det med en rad?

**Comment by Heilysto** [comment]
Test

**Comment by hodoea** [comment]
@Heilysto

**Comment by selbekk** [comment]
En grid er satt sammen av rader og kolonner. Grid-et vi har laget har støtte for å ha utfallende farger på radene.

**Comment by hodoea** [comment]
@selbekk Ok :) Vi ser på spacing og grid og vi tror at vi ikke bruker helt samme grid som dere. 
Bruker dere CSS grid?  CC @Heilysto @julesoslo

**Comment by selbekk** [comment]
Hei! Det skal vi få ordnet opp i. Vårt grid har følgende spacing-verdier:

Kolonner: 4 på små enheter, 6 på mellomstore enheter, 12 på store enheter.
Bredde: 1280px;
Gutters (plass mellom kolonner) på små enheter: 20px;
Gutters (plass mellom kolonner) på store enheter: 20px;
Gutters (plass mellom kolonner) på små enheter i condensed versjon (for BM typisk): 10px;
Gutters (plass mellom kolonner) på store enheter i condensed versjon (for BM typisk): 20px;

Ser dette omtrentlig riktig ut?

**Comment by selbekk** [comment]
var det noen forskjeller @hodoea? Lukker denne, så kan du opprette et nytt issue om du ønsker endringer i hvordan vi har implementert gridet :)

**Comment by hodoea** [comment]
Ja, sorry glemte å lukke den!
