### ISSUE TITLE
Hvor er disse to fargene brukt?

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#135]
<img width="840" alt="skjermbilde 2018-03-28 kl 12 43 48" src="https://user-images.githubusercontent.com/8971560/38024575-bc56a0dc-3285-11e8-8300-2a73eb0316c1.png">

Vi vet at de er i bruk et eller annet sted, men de er ikke en del av verktøy kassen. Hadde vært super nyttig for oss å få vite i hvilken kontekst de er i bruk der ute. :) Jobber med å frem et forslag på mapping farge visning og bruksområder til systemet. :)

**Comment by antidecaf** [comment]
"Lys blå" tilsvarer `Blue Deep Sky` i designsystemet. Ser ikke umiddelbart noe mønster i hvilken kontekst den er brukt i og hvorfor, men et søk på fargenavnet gir treff i 53 filer fordelt på et ukjent antall apper i både bank og forsikring. Den brukes tilsynelatende i linker, paginering, ikoner, grafer og lignende.

"Lys blå 50%" tilsvarer `Blue Sky` og er å finne i 17 filer fordelt på 7 apper så vidt jeg kan se. Brukes for det meste som bakgrunnsfarge og til borders.

**Comment by selbekk** [comment]
Lys blå (som i FFE er kalt `ffe-blue-deep-sky`) brukes i hovedsak på lenker. tekst på hvite knapper (sekundære knapper) og på aktive radioknapper.

Lys blå 50% (som i FFE-er kalt `ffe-blue-sky`) brukes i `chart-donut` her i FFE, i tillegg til tooltips i seopp, litt rundt om på åpne nettsider og et par andre spredte steder i bl.a. sparing, bm-filer og bm-likvididet.

**Comment by selbekk** [comment]
Jamen søren a @antidecaf  👍 Flott teamwork!

**Comment by hodoea** [comment]
Dere altså. :D Tuuusen takk for svar! Se her: @Heilysto  @julesoslo

**Comment by selbekk** [comment]
Regner med at du fikk svar godt nok @hodoea ? Lukker denne jeg.
