### ISSUE TITLE
ffe-datepicker-react: Tab prison in Firefox

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#137]
#### Which package is this issue related to?

`ffe-datepicker-react`

#### Describe your issue

If the input field for the datepicker is focused pressing Tab always opens the calendar. When pressing Tab again the calendar is closed and the input field is given focus. Pressing Tab again opens the calendar. Pressing tab again gives the input field focus. Pressing tab again opens the calendar... :policeman: The cursor is imprisoned in the datepicker :policewoman: 

#### What is the expected behavior? 

Pressing Tab when the calendar is open should give the next tabbable element focus.

#### What is the actual behavior?

The previous tabbable element (the input field) is given focus. There is no way forward in the form without using a mouse.

#### Steps to reproduce

https://design.sparebank1.no/styleguidist/index.html#!/Datepicker/0

1. Focus the input field and press Tab. The calendar should open.
2. Press tab again. The element "View Code" should get focused. Instead we're back in the input field.

**Comment by ksawerysb1** [comment]
@wkillerud which browser? Chrome seems to work fine. In Firefox I believe there is some sort of race condition here because pressing tab with longer intervals always closes the datepicker, while pressing it with rapid succession changes the focus to the next input field without closing the datepicker, but it closes after a few more presses...

**Comment by ivarni** [comment]
Works for me in 
Chrome 65.0.3325.162
IE 11.2125.14393.0
Edge 38.14393.2068.0

Reproduced in
Firefox 59.0.2

**Comment by wkillerud** [comment]
Right, I'm using Firefox. Running Nightly 61.0a1, but I see Ivar reproduced it in Stable.

So it's a browser specific race condition - nice :smile:

**Comment by ksawerysb1** [comment]
@wkillerud found a solution, creating a PR soon

**Comment by ksawerysb1** [comment]
@wkillerud @ivarni @selbekk Created PR: https://github.com/SpareBank1/designsystem/pull/151

**Comment by wkillerud** [comment]
Fixed in #151
