### ISSUE TITLE
Typescript-feil på InputGroup med Input-element i function-as-child ved oppgradering til ffe-form-react 9.1.1

### ISSUE THREAD

**Issue by mortenk** [SpareBank1/designsystem#1380]
**Beskrivelse av feilen**
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: InputProps | Readonly<InputProps>): Input', gave the following error.
    Type '{ id: string; 'aria-invalid': string; 'aria-describedby': string; onChange: ChangeHandler; onBlur: ChangeHandler; ref: RefCallBack; name: string; ... 7 more ...; className: string; }' is not assignable to type 'Readonly<InputProps>'.
      Types of property ''aria-invalid'' are incompatible.
        Type 'string' is not assignable to type 'boolean | "true" | "false" | "grammar" | "spelling" | undefined'.
  Overload 2 of 2, '(props: InputProps, context: any): Input', gave the following error.
    Type '{ id: string; 'aria-invalid': string; 'aria-describedby': string; onChange: ChangeHandler; onBlur: ChangeHandler; ref: RefCallBack; name: string; ... 7 more ...; className: string; }' is not assignable to type 'Readonly<InputProps>'.
      Types of property ''aria-invalid'' are incompatible.
        Type 'string' is not assignable to type 'boolean | "true" | "false" | "grammar" | "spelling" | undefined'.

**Steg for å gjenprodusere**
Psuedokode:
<InputGroup>
{inputProps => <Input {...inputProps} />
</InputGroup>

I @types/react 18 er aria-invalid definert slik:
'aria-invalid'?: boolean | 'false' | 'true' | 'grammar' | 'spelling' | undefined;
Mens i InputGroupProps: 'aria-invalid': string;

**Comment by kwltrs** [comment]
Resolved by #1396
