### ISSUE TITLE
Knappen for FileUpload-komponenten fungerer ikke etter å ha gått ut av filopplasting og prøver på nytt på Android i Mobilbanken

### ISSUE THREAD

**Issue by larskarlsen** [SpareBank1/designsystem#1391]
**Beskrivelse av feilen**
I komponenten FileUpload fungerer ikke knappen for å laste opp fil på Android hvis man har klikket på den og gått ut fra filopplastningen og prøver å klikke på "Last opp" på nytt.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen (Android)
1. Klikk på knappen på FileUpload-komponenten for å laste opp fil.
2. Klikk deg ut av filopplastningen.
3. Klikk på knapppen på FileUpload-komponenten for å laste opp fil igjen.
4. **Feil**: Knappen reagerer ikke

**Forventet oppførsel**
Du skulle ha fått opp filopplastningen på nytt.

**Mobil (fyll ut feltene):**
 - Enhet: Nexus 5x
 - Operativssytem: Android
 - Mobilbanken

**Tilleggsinformasjon**
Kan være vanskelig å få testet det i mobilbanken siden komponenten ikke brukes så mye der, men hvis dere får lagret utkast på et skjema vil det dukke opp i Mine oppgaver, som er tilgjengelig i mobilbanken. Jeg kan eventuelt bistå med å sette opp testcase(Utvikler i Område Kundedialog).

https://user-images.githubusercontent.com/16797792/169304730-308cfc94-e3af-4aa9-a39e-dc85931c448d.mp4

**Comment by kwltrs** [comment]
Takk for tilbudet å bistå med å sette opp en test case :smiley: Vi tar kontakt og avtaler noe.

**Comment by tuva-odegard** [comment]
Har fått testcase fra Simen Røste Odden og bekreftet at det fortsatt skjer. Har spurt team mobilbankplattform om de kan bistå i fiks

**Comment by oysteinmolnes** [comment]
Fiks i Android-appen er på vei: https://sb1u.atlassian.net/browse/MOB-1577.
Fiksen var å implementere en callback for kansellering av filvelgeren.

**Comment by ThereseBoerter** [comment]
@tuva-odegard - er det noe mer vi må gjøre her eller har fixen til Øystein fikset det for oss også?

**Comment by tuva-odegard** [comment]
@ThereseBoerter Håper det! Supert at det ble fikset @oysteinmolnes 🤩  Testcaset jeg fikk fra Simen fungerer ikke lenger, så jeg får ikke testet.

**Comment by tuva-odegard** [comment]
Det er fikset! 🤩
