### ISSUE TITLE
@sb1/ffe-file-upload 7.0.6 sertifikatfeil

### ISSUE THREAD

**Issue by LG111111** [SpareBank1/designsystem#1392]
![image](https://user-images.githubusercontent.com/2741562/169969336-97840941-345a-42d1-94c9-be59649445a4.png)

**Comment by kwltrs** [comment]
I'm not sure how an untrusted certification relates to this npm package. Could you share how we can reproduce this bug? Thanks in advance.

**Comment by LG111111** [comment]
While trying to import and use this package I got this error. I searched in stash and saw that noone use this version (7.0.6), so not sure is it not working just for me.

**Comment by kwltrs** [comment]
Kom frem til at dette ikke er et problem i designsystemet og jeg lukker dette issue.
