### ISSUE TITLE
Difficult to visually see which selected radio switch button that are active

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#140]
#### Which package is this issue related to?
ffe-form

#### Describe your issue (screenshots welcome!)
It is difficult to visually see which of two (ore more) sets of radio switch buttons that are active/focused. 

This is not a big issue when navigating with mouse, but when the user navigates with the keyboard the blue ring around an already selected radio switch is hardly noticable.

This can be confusing for the user especially when tabbing around in a partly pre-filled form.

The image below shows an example of how this is displayed, the upper radio switch is not active, but the lower is.

![image](https://user-images.githubusercontent.com/36953762/38362232-5bca76a2-38d0-11e8-8137-a043bfefe58d.png)

#### What is the expected behavior? 
It should be considered to show the active field in a more noticable way, or at least add some kind of animation to draw the user's attention to the focused field when tabbing into it.

#### What is the actual behavior?
See the image above.

#### Steps to reproduce
This can be reproduced by tabbing around in the component library in the design system, https://design.sparebank1.no/styleguidist/index.html#radioswitch.

**Comment by selbekk** [comment]
Related to / duplicate of #11

I agree!

**Comment by ivarni** [comment]
Yeah, we can probably close either this one or #11, we don't need two :)

Any news on how we're going to solve this @adidick ?

**Comment by hdaljord** [comment]
Sorry, read all the issue topics but somehow I missed #11, I can close this one, as it's the duplicate :)

**Comment by adidick-zz** [comment]
I've added a comment to #11 
Atlassian have a subtle white border around their buttons that lies inside the focus colour. Could be a good option for us too. 
https://www.atlassian.com/
