### ISSUE TITLE
file-upload-react: Viser fil med feil to ganger.

### ISSUE THREAD

**Issue by khtufteland** [SpareBank1/designsystem#1401]
**Beskrivelse av feilen**

Når man laster opp en fil med feil vises denne to ganger.

**Steg for å gjenprodusere**

Last opp en fil med ugyldig filformat.

**Forventet oppførsel**

Forventer at den vises kun en gang.

**Tilleggsinformasjon**

Mener det er tilstrekkelig å endre
https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-file-upload-react/src/FileItem.js#L30
til dette:
```js
file.document && !file.error (
```

**Comment by antidecaf** [comment]
Hei og takk for feilrapporten!

Om du har mulighet, send oss gjerne en pull request med denne fiksen hvis den er testet OK der du har filopplasting implementert. Våre egne eksempler er dummy-implementasjoner som ikke gjør noen faktisk opplasting, så det gjør det litt krøkkete å debugge akkurat dette i denne konteksten. :)
