### ISSUE TITLE
Endre breakpoints for typografi på tablet

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1403]
Fonter har iht profilen forskjellige størrelser på desktop, tablet og mobil. Tablet-størrelsene vises mellom `@breakpoint-sm` og `@breakpoint-md` - det vil si mellom 480px og 768px. Tableter har imidlertid gjerne bredere skjerm enn 768px, spesielt i landscape. Derfor kan det være lurt å vurdere å endre breakpoints.

**Comment by tuva-odegard** [comment]
Vi tenker å følge microsoft sine guidelines, så breakpointet for tablets landskape kan bli støttet helt opp til 1007px. https://learn.microsoft.com/en-us/windows/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design
