### ISSUE TITLE
Mulighet for å sende inn flere props til TabGroup og Tab

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#1404]
Vi ønsket å implementere tastaturnavigering for faner, men hindres i å bruke React-komponentene pga. manglende properties.

Ønsker å få inn tre properties

TabGroup: 
* ref

Tab: 
* onKeyUp
* tabIndex

Propertiene må sendes inn til de respektive HTML-elementene og ligge både i propTypes og ts-definisjonene.

Dersom https://github.com/SpareBank1/designsystem/issues/1338 løses trenger jeg ikke lenger denne.

**Comment by HeleneKassandra** [comment]
Jeg lukker denne, da vi må løse #1338 uansett  for å være WCAG compliant.
