### ISSUE TITLE
onBlur til AccountSelelector

### ISSUE THREAD

**Issue by isakbjugn** [SpareBank1/designsystem#1409]
Ser i [ffe-account-selector-react/src/index.d.ts ](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-account-selector-react/src/index.d.ts) at AccountSelectorMulti har onBlur-funksjonen, men at denne ikke er arvet til AccountSelector. Er dette av en bestemt grunn? Foreslår å legge til onBlur, som i dag må løses ved å pakke AccountSelector i en egen innpakningskomponent som har onBlur, og la denne hendelsen boble oppover.

**Comment by kwltrs** [comment]
Tror du må forklare problemet litt mer. [AccountSelector](https://github.com/SpareBank1/designsystem/blob/53ccad317f807c43b4a4fc9ef5d4b62102d75a09/packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.js) arver ikke fra AccountSelectorMulti, som jeg ser det.

**Comment by isakbjugn** [comment]
Nei, du har rett, jeg var nok litt rask og så at props-interfacene for AccountSelector og AccountSelectorMulti arvet fra samme interface. Det jeg problematiserer er at AccountSelector ikke har noen onBlur-funksjon, slik at en ikke kan fange blur-hendelser fra komponenter dypere nede (som [InputField](https://github.com/SpareBank1/designsystem/blob/febddb6c589805e98928a3920956a5f63cbda8d4/packages/ffe-account-selector-react/src/subcomponents/input-field/InputField.js), som har en onBlur-prop.). 

Dette kan løses ved å pakke AccountSelector inn i en div og gi denne en onBlur, men det beste hadde vært å kunne sette en onBlur direkte på AccountSelector.

**Comment by kwltrs** [comment]
Takk, da skjønner jeg hva det gjelder :+1:

**Comment by kwltrs** [comment]
Jeg så litt på AccountSelector. Uten at jeg kjenner til deres use case, men kan kanskje [onClose](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-account-selector-react/src/index.d.ts#L41) løse deres behov til en `onBlur`-callback?

**Comment by tuva-odegard** [comment]
Bekreftet med @isakbjugn at dette spesifikke tilfellet ikke finnes lenger. Mest sannsynlig gjør onClose jobben bra nok. Lukker og så får vi evt ta det hvis det kommer opp som et problem igjen
