### ISSUE TITLE
Justere ButtonGroup så det kommer frem at knappene hører sammen med skjermlesere og annen kompenserende teknologi

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1414]
### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/buttons/ButtonGroup/wcag-1.3.1_informasjon_og_relasjoner.yml

### Beskrivelse
Det kommer ikke frem at knappene i ButtonGroup hører sammen med kompenserende teknologi. Usikker på hvordan det best kan løses.

Her er tre av W3Cs godkjente teknikker for å ivareta krav 1.3.1:
[Using grouping roles to identify related form controls (W3C)](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA17.html)
[Using ol, ul and dl for lists or groups of links (W3C)](https://www.w3.org/WAI/WCAG21/Techniques/html/H48.html)
[Providing a description for groups of form controls using fieldset and legend elements (W3C)](https://www.w3.org/WAI/WCAG21/Techniques/html/H71.html)

I bootstrap button group brukes role="group" og aria-label på div-en, som i den første W3C-teknikken:
https://getbootstrap.com/docs/4.0/components/button-group/

<img width="1064" alt="Skjermbilde 1" src="https://user-images.githubusercontent.com/77671758/179981230-a54461d1-fabd-4962-9601-49a86322a523.png">

I button group på funka.com er knappene kodet som lenker og ligger inne i en liste, som i W3C-teknikk nummer to:
https://www.funka.com

<img width="836" alt="Skjermbilde 2" src="https://user-images.githubusercontent.com/77671758/179982045-33d7f9d1-e02d-45da-a0d0-a8933333b33f.png">

I button group på gov.uk ligger knappene inne i en liste:
https://www.gov.uk

<img width="914" alt="Skjermbilde 3" src="https://user-images.githubusercontent.com/77671758/179982314-8fd8f25c-3d67-42d4-a8e1-c8f938283bab.png">

I button group på politiet.no brukes fjeldset med legend, som i den tredje W3C-teknikken:
https://www.politiet.no/personvern-og-informasjonskapslar/
 
<img width="887" alt="Skjermbilde 4" src="https://user-images.githubusercontent.com/77671758/179982739-b82ace8a-1ec8-4749-9dd1-e6b2333990e5.png">

Nå er komponenten vår lagt opp sånn at vi noen ganger må bruke flere knappegrupper sammen for at den visuelle plasseringen skal blir riktig, som i dette eksempelet hvor «Forrige» og «Neste» ligger i en gruppe og «Avbryt» ligger i en annen gruppe. Det kan være forvirrende at knapper som hører sammen presenteres som ulike grupper med skjermleser eller annen kompenserende teknologi, så det må vi kanskje ta tak i som en del av dette issuet.

<img width="943" alt="Skjermbilde 5" src="https://user-images.githubusercontent.com/77671758/179984193-19933299-408b-4250-ae16-18f7f14742d3.png">

**Comment by ThereseBoerter** [comment]
@SindreSafvenbom  - gjøre en vurdering på om dette må gjøres. Skal vi eller teamene gjøre dette?
