### ISSUE TITLE
Sørge for at ikonene i CheckList har tekstalternativ

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1417]
**Krav**
Ikke-tekstlig innhold skal ha et tekstalternativ, sånn at en beskrivelse av innholdet er tilgjengelig med kompenserende teknologi som for eksempel skjermlesere (det finnes noen unntak). 
[WCAG 2.0, 1.1.1 Ikke-tekstlig innhold (Nivå A)](https://www.uutilsynet.no/wcag-standarden/111-ikke-tekstlig-innhold-niva/87)

Mener at ikonene i CheckList er viktige for å forstå meningen med komponenten, og at vi bør sørge for at de har tekstalternativ. 

**Test**
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/lists/CheckList/wcag-1.1.1_ikke_tekstlig_innhold.yml

**Beskrivelse av feilen**
Nå er ikonene kodet i CSS, med aria-label på liste-elementene. Det leses ikke opp noe for ikonene når komponenten testes med skjermleser (VoiceOver) på iOS.

W3C fraråder å bruke CSS når det er meningen at innholdet skal presenteres av kompenserende teknologi, fordi det kan føre til at innholdet ignoreres (https://www.w3.org/WAI/WCAG21/Techniques/css/C9). Det ser også ut til at det er varierende støtte for aria-label i lister: https://www.scottohara.me/blog/2020/05/02/labelled-lists.html.

Vi kan blant annet vurdere å legge inn ikonene som inline-svg-er med:
- role="img" og <title>, eller
- role="img», <title> og aria-labelledby=«[ID]»

«SVG pattern 5» og «SVG pattern 8» i [Deques artikkel om tilgjengelige SVG-er](https://www.deque.com/blog/creating-accessible-svgs/).

**Ny test**
Når vi har fikset det bør vi teste opp igjen krav 1.1.1 for CheckList.

**Comment by HeleneKassandra** [comment]
Funket ikke fiksen?
