### ISSUE TITLE
Darkmode på native select-html elementer

### ISSUE THREAD

**Issue by henninghuseby** [SpareBank1/designsystem#1435]
**Beskrivelse av feilen**
Blir litt krøll med nettleser native dropdown når en har satt darkmode på f.eks mac

**Steg for å gjenprodusere**
https://design.sparebank1.no/komponenter/skjemaelementer/
 
**Skjermskudd**
<img width="772" alt="image" src="https://user-images.githubusercontent.com/65295516/185203947-8fd04790-1f94-48f9-b407-8aede2a0ea18.png">

**Desktop (fyll ut feltene ):**
 - Operativssystem: mac
 - Nettleser Chrome, Safari

**Comment by antidecaf** [comment]
Dette er ikke en bug, men forventet oppførsel. `<option>` er i praksis ikke mulig å style med CSS, og får utseende fra OS-nivå. Default utseende med Chrome/Mac og dark mode er som i screenshotet. Egen styling på nedtrekkslister krever at man skriver egen markup, a la `ffe-searchable-dropdown`.
