### ISSUE TITLE
Datofelt ser rart ut på native datovelger i iOS

### ISSUE THREAD

**Issue by henninghuseby** [SpareBank1/designsystem#1452]
**Beskrivelse av feilen**
Datoen er helt i toppen og midtjustert på native datovelger på iOS

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til ' mobilbanken'
2. Klikk på 'Mer'
3. Klikk på 'Periode'
4. Velg 'Egendefinert'
5. Klikk på datofeltet
6. Se feilen

**Forventet oppførsel**
Forventer at datofeltet ser likt ut som på datovelgeren, horisontalt midtjustert og til venstre i inputfeltet

**Skjermskudd**
![E225E412-D671-4957-812F-CAA1791ABEC2_1_201_a](https://user-images.githubusercontent.com/65295516/192464337-f5ce6eb7-f606-4537-a28d-f1bb3840a006.jpeg)

**Mobil (fyll ut feltene):**
 - Enhet: [iPhone 11 Pro]
 - Operativssytem: [iOs]
 - Nettleser [nettbank native]
 - Versjonsnummer [8.9.5]

**Comment by HeleneKassandra** [comment]
Litt usikker på om de bruker ffe komponenten på i mobilbanken, eller om de benytter en native komponent. Ville sjekket dette først :)

**Comment by henninghuseby** [comment]
Datofeltet bruker <[DateInput](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-datepicker-react/src/index.d.ts#L45)> med `type=date`. Ikke sikker på om det er andre måter å gjøre det på men til nå den måten pm-betaling har brukt datovelgeren når det er native webview

**Comment by kwltrs** [comment]
`DateInput` er ikke tenkt å brukes stand-alone. Bruk `<input type=date class=ffe-input-field>` isteden.
