### ISSUE TITLE
Fileupload komponentet ser ikke riktig ut på mobil

### ISSUE THREAD

**Issue by jonaskris** [SpareBank1/designsystem#1455]
**Beskrivelse av feilen**
Fileupload komponentet ser ikke riktig ut på mobil, da det virker å mangle noe whitespace og knapp er veldig stor.

Virker som dette har skjedd mellom versjoner:
"@sb1/ffe-file-upload": "6.0.12" 
"@sb1/ffe-file-upload-react": "5.0.9"
og
"@sb1/ffe-file-upload": "7.0.8",
"@sb1/ffe-file-upload-react": "6.1.1",

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til https://design.sparebank1.no/komponenter/skjemaelementer/#fileupload i nettleser
2. Reduser skjermbredde til 767 og/eller 479

**Forventet oppførsel**
Se skjermskudd

**Skjermskudd**
Slik så det ut før:
![temp](https://user-images.githubusercontent.com/31920690/192728794-77167095-e1d6-4635-855d-d35803405a75.png)

Slik ser det ut nå:
![temp1](https://user-images.githubusercontent.com/31920690/192728808-fde783a1-753f-4758-8021-798f871f2e59.png)

**Desktop (fyll ut feltene ):**
 - Operativssystem: Linux
 - Nettleser Firefox

**Comment by antidecaf** [comment]
Takk for bugrapporten! Har lagt opp en PR med fiks nå.
