### ISSUE TITLE
ffe-file-upload-react

### ISSUE THREAD

**Issue by jonaskris** [SpareBank1/designsystem#1464]
Etterlyser mulighet til å endre farge på "X" ikon i liste av opplastede filer.

Ikonet er satt i css som background-image. Kan jo farges ved bruk av filter, men er ikke en optimal løsning. Hadde vært fint om ikonet heller setter sin farge basert på fargen av teksten ved siden av.

Formålet er relatert til theming i kredittbanken (partnerbanker), hvor det ikke er ønskelig med den typiske blå SB1 fargen.

Slik ser det ut uten noe spesiell styling på FileItem:
![02](https://user-images.githubusercontent.com/31920690/194307074-21197df7-e63a-442d-a76e-11b28b90cec4.png)
Ved endring av farge på selve teksten (ikke gjort i bildet), blir ikke fargen på X ikonet endret.

----------
Edit: Gjelder forsåvidt også ffe-dropdown, hvor "pil ned"-ikonet ikke kan farges.

----------

Kan også nevnes at hover-fargen på "slett"-teksten ikke ser helt riktig ut:
![Hover farge file upload](https://user-images.githubusercontent.com/31920690/194307427-fc7fdd52-edf9-4a77-a11b-dc249e924acb.png)

**Comment by antidecaf** [comment]
^ Pull requesten nevnt over innfører theming i ffe-file-upload, og i samme slengen har jeg lagt opp til at ikonet følger fargen på teksten i slettknappen. Fargen er trukket ut i to variabler: `--ffe-v-fileupload-btn-delete-color` og `--ffe-v-fileupload-btn-delete-color-hover`. :)
