### ISSUE TITLE
Litt rar styling på accordion elementet

### ISSUE THREAD

**Issue by henninghuseby** [SpareBank1/designsystem#1465]
**Beskrivelse av feilen**
Det blir litt mye spacing i bunnen av accordion elementet og elementet får arver en focus styling fra `<button>`

**Steg for å gjenprodusere**
klarer ikke gjenprodusere feilen i designsystemet

**Forventet oppførsel**
Focus: 
![Skjermbilde 2022-10-11 kl  10 35 48](https://user-images.githubusercontent.com/65295516/195040889-4df0d8d7-c8b6-4154-b324-b70ecd7cfd7d.png)
uten focus: 
![Skjermbilde 2022-10-11 kl  10 36 40](https://user-images.githubusercontent.com/65295516/195041014-a0d2cedb-d1a4-4798-b2f9-2db295ccdee8.png)

**Skjermskudd**
![Skjermbilde 2022-10-11 kl  10 39 08](https://user-images.githubusercontent.com/65295516/195041601-0df2909f-eb00-4653-89de-c3cc4545b2a5.png)

![Skjermbilde 2022-10-11 kl  10 21 06](https://user-images.githubusercontent.com/65295516/195040104-4d99cd34-a453-482f-ad86-7e0a16c89629.png)

**Comment by kwltrs** [comment]
Det blir litt vanskelig å akseptere en PR om det er ukjent hvor problemet kommer fra. Om det ikke lar seg gjenprodusere er det kanskje ikke et problem i ffe?

**Comment by henninghuseby** [comment]
Ser nå at [button stylingen ](https://github.com/SpareBank1/designsystem/pull/1466/files#diff-af4636ea62e1c33e1efc6b228df45a7c6b0ae9a175c07e6ee96757e42ff64aecR42) er noe veldig generell kode fra pm-betaling så det er jeg enig bør bort fra denne PR-en, men heading problemet er noe som kommer fra ffe så lar den være
