### ISSUE TITLE
Gjør alt-tekst obligatorisk i ImageCard

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1484]
**Test**
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/ImageCard/wcag-1.1.1_ikke_tekstlig_innhold.yml

**Beskrivelse** 
For å legge inn bilder i `ImageCard` må man inkludere hele `<img>`-taggen i `image`-propen:

![Screenshot 2022-10-27 at 16 01 11](https://user-images.githubusercontent.com/463847/198306035-7cc5b0ba-7ff4-4c05-ac65-a7e7914f5740.png)

Dette åpner potensielt for brukerfeil. Konsumenter må bl.a. selv sørge for at alt-tekst (som er lovpålagt) kommer med, og det er heller ikke noe som står i veien for at man kan legge inn annen markup enn `<img>`.

Foreslår å skille ut `image`-propen i nye props for f.eks. `imageUrl` og `altText`, slik at strukturen blir mer forutsigbar og alt-tekst kan være obligatorisk.

**Comment by HeleneKassandra** [comment]
Veldig for dette, eneste utfordringen her er at det da ikke lenger blir mulig å sende med klassenavn på selve bildet, med mindre vi legger til en prop for det også.
