### ISSUE TITLE
Shortcut-btn og cards tekst blir overstyrt av link styling

### ISSUE THREAD

**Issue by HeleneKassandra** [SpareBank1/designsystem#1485]
I darkmode blir teksten i shortcut-button overstyrt av link stylingen som er satt på body, som gjør at teksten får fargen lyng. 
Det ser ut til at det kun gjelder ":visited" 
![Skjermbilde 2022-10-27 kl  16 49 50](https://user-images.githubusercontent.com/39946146/198323440-62ca2237-5d40-45e4-b023-196c86d15382.png)

**Comment by andrea-sb1** [comment]
Det ser ut som vi har samme problem i kortkomponentene

<img width="645" alt="Skjermbilde av CardBase" src="https://user-images.githubusercontent.com/77671758/198521678-d941eeea-c7c4-4b03-8b09-493f56687cd2.png">

<img width="469" alt="Skjermbilde av IconCard" src="https://user-images.githubusercontent.com/77671758/198521684-e93ff64c-75d6-4f85-8b4e-ef09b6da8d5b.png">

<img width="321" alt="Skjermbilde av ImageCard" src="https://user-images.githubusercontent.com/77671758/198521687-e506bac9-16a4-4cb1-8ed7-2fd93379db9b.png">

<img width="643" alt="Skjermbilde av TextCard" src="https://user-images.githubusercontent.com/77671758/198521696-9abff4e9-33b7-4150-81c5-3ae5e33892b2.png">
