### ISSUE TITLE
Forbedre kort-komponentene for skjermlesere og annen kompenserende teknologi

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1499]
### Tester
[IconCard, WCAG 1.3.1 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/IconCard/wcag-1.3.1_informasjon_og_relasjoner.yml)
[IconCard, WCAG 4.1.2 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/IconCard/wcag-4.1.2_navn_rolle_verdi.yml)
[ImageCard, WCAG 1.3.1 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/ImageCard/wcag-1.3.1_informasjon_og_relasjoner.yml)
[ImageCard, WCAG 4.1.2 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/ImageCard/wcag-4.1.2_navn_rolle_verdi.yml)
[TextCard, WCAG 1.3.1 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/TextCard/wcag-1.3.1_informasjon_og_relasjoner.yml)
[TextCard, WCAG 4.1.2 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/TextCard/wcag-4.1.2_navn_rolle_verdi.yml)
[CardBase, WCAG 1.3.1 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/CardBase/wcag-1.3.1_informasjon_og_relasjoner.yml)
[CardBase, WCAG 4.1.2 ](https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/CardBase/wcag-4.1.2_navn_rolle_verdi.yml)

### Beskrivelse
Det er viktig at det kommer tydelig frem med skjermlesere og annen kompenserende teknologi at kortene er klikkbare og hvilket innhold som hører sammen (strukturen i kortene). 

I dag ligger alt innholdet i kortet i et a-element. Det gjør at kompenserende teknologi presenterer kortet som klikkbart (det er bra), men det byr også på noen utfordringer.

### Utfordring 1
Med skjermleser VoiceOver i Safari på iOS leses hver del av innholdet i kortet som en separat link. Dermed høres det ut som en rekke uavhengige linker som fører til ulike steder. Det er vanskelig/umulig å forstå at innholdet hører sammen og at det er snakk om ett kort som fører til én side.

Eksempel:
<img width="1061" alt="Skjermbilde av ImageCard" src="https://user-images.githubusercontent.com/77671758/199944670-bbbe835b-5bab-46c8-812e-69e1c4a3f1db.png">
Skjermleser (VoiceOver i Safari på iOS) leser opp:
_«Kortnavn, lenke»
«Tittel, lenke»
«En liten undertekst, lenke»
«Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat., lenke»_

### Utfordring 2
Når alt innholdet i kortet ligger i samme a-element leses det opp som en sammenhengende tekst i skjermleser (med unntak av VoiceOver i Safari på iOS som beskrevet over). Med mindre kortet bare inneholder f.eks. kortnavn og tittel, blir den sammenhengende linkteksten som leses opp ofte veldig lang.

Eksempel:
<img width="1061" alt="Skjermbilde av ImageCard" src="https://user-images.githubusercontent.com/77671758/199945096-0d4e9552-dacc-409f-b70d-393436dfd8a8.png">
Skjermleser (VoiceOver i Safari på macOS) leser opp:
_«lenke, Kortnavn Tittel En liten undertekst Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat»_

Tenker vi bør se på hvordan vi kan gjøre at kortene fungerer enda bedre med skjermlesere og annen kompenserende teknologi, med tanke på hva som kan gi den beste brukeropplevelsen og hva som ivaretar kravene. 

### Mulige løsninger
For å få frem at innholdet i kortet hører sammen og relasjonen mellom kortene, kan vi blant annet vurdere å lage en CardGroup hvor vi legger kortene i et liste-element (ul/ol) og hvert kort i et li-element.

Vi kan også vurdere å gjøre tittelen i kortet til heading og at bare denne er kodet som link (har a-tagg). Det ser ut til at det finnes måter å gjøre hele kortet klikkbart på, selv om bare tittelen er kodet som link. Mer om det og diverse muligheter for kort på https://inclusive-components.design/cards/.

Ikke åpenbart hva som vil være den beste løsningen her. Det finnes tilsynelatende ingen tydelige standarder eller retningslinjer for hvordan kort skal kodes. Vi må nok grave litt i det sammen og for eksempel høre med en eller flere som bruker skjermleser eller annen kompenserende teknologi rundt preferanser.

**Comment by pethel** [comment]
Korten kan vare vilket element så firtt fram att lage lister om man vil feks. Title i korten kan også vare vilket element man vill.
