### ISSUE TITLE
Justere ContextMessage, MessageBox og SystemMessage så det kommer frem at innholdet hører sammen, at det er en melding, og hvilken type melding, med kompenserende teknologi

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1526]
**Tester**
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/ContextMessage/wcag-1.3.1_informasjon_og_relasjoner.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/MessageBox/wcag-1.3.1_informasjon_og_relasjoner.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/SystemMessage/wcag-1.3.1_informasjon_og_relasjoner.yml

**Beskrivelse**
Det kommer ikke frem at innholdet i meldingen hører sammen, at det er en melding, og hvilken type melding med kompenserende teknologi.

I ContextMessage har den overordnede div-en aria-describedby som refererer til brødteksten pluss at variantene med heading har aria-labelledby som refererer til headingen. Disse leses ikke opp av skjermleser i testen, med unntak av variantene med heading når de testes med VoiceOver i Chrome på macOS. Selv der aria-labelledby og aria-describedby leses opp, vil det nok fortsatt i mange tilfeller være vanskelig å forstå at det er en melding, og hvilken type melding, basert på headingen og brødteksten.

**Forslag**
Vi kan blant annet vurdere å legge til aria-label på den overordnede div-en som beskriver at det er en feilmelding/infomelding/nyhetsmelding/tipsmelding/suksessmelding, samt legge til role="group" for meldingene som ikke har role="alert". For ContextMessage vil aria-label erstatte aria-describedby og aria-labelledby.

**Comment by andrea-sb1** [comment]
Ser at vi mangler role="group" på:

- SystemMessage, error, alert false
- MessageBox, error, alert false

Tester opp igjen meldingskomponentene, WCAG-krav 1.3.1, når vi har fikset det :)

**Comment by HeleneKassandra** [comment]
Skjønner ikke helt denne? 
Det er satt role="group" på alle meldingene, bortsett fra når alert er satt til true, fordi da blir det "role=alert"

**Comment by andrea-sb1** [comment]
> Skjønner ikke helt denne?
> Det er satt role="group" på alle meldingene, bortsett fra når alert er satt til true, fordi da blir det "role=alert"

Ser ut som role="group" mangler for akkurat SystemMessage og MessageBox, error, alert false

<img width="831" alt="Skjermbilde 1" src="https://user-images.githubusercontent.com/77671758/218431248-da7971b0-6b63-468c-80f2-f52fab11cdd8.png">

<img width="829" alt="Skjermbilde 2" src="https://user-images.githubusercontent.com/77671758/218431257-21eb9454-0335-4330-b5b5-eb821b55a2b4.png">
