### ISSUE TITLE
Kode overskriftene i ContextMessage og MessageBox som overskrift i stedet for div

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1527]
**Tester**
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/ContextMessage/wcag-1.3.1_informasjon_og_relasjoner.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/MessageBox/wcag-1.3.1_informasjon_og_relasjoner.yml

**Beskrivelse**
Nå er overskriftene i ContextMessage og MessageBox kodet som div-er. Vi bør vurdere om det blir mer semantisk riktig å kode disse som overskrifter.

**Comment by HeleneKassandra** [comment]
@andrea-sb1  Sånn som det er i dag er div default, men brukerne kan sende med headerElement som endrer det. Hvilket H element tror du det gir mening å sette som default her?  Vi vet ingenting om konteksten rundt, så antar at div er satt som standard for å ikke ødelegge med noe hierarki

**Comment by andrea-sb1** [comment]
> @andrea-sb1 Sånn som det er i dag er div default, men brukerne kan sende med headerElement som endrer det. Hvilket H element tror du det gir mening å sette som default her? Vi vet ingenting om konteksten rundt, så antar at div er satt som standard for å ikke ødelegge med noe hierarki

@HeleneKassandra Tenker kanskje h2 som default (?) med mulighet til å endre til annet overskriftsnivå (h3, h4 osv.) ved behov – og samme CSS-styling som i dag uavhengig av valgt h-nivå :)

**Comment by HeleneKassandra** [comment]
Ok! Tenker dette er en god løsning, bare greit å være klar over at dette vil ødelegge for de som evt bruker h-elementet til å justere tekst størrelse osv i meldingsboks.
