### ISSUE TITLE
Fikse styling for lenker i meldingskomponentene, dark mode

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1528]
**Tester**
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/MessageBox/wcag-1.4.3_kontrast_minimum.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/ContextMessage/wcag-2.4.7_synlig_fokus.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/MessageBox/wcag-2.4.7_synlig_fokus.yml

**Beskrivelse**
Dark mode:
- Lenketeksten i MessageBox har for lav fargekontrast mot bakgrunnen. Lenketeksten i ContextMessage har ikke for lav kontrast, men den stemmer ikke med standard styling for lenker, så vi bør ta en kikk på den også.

- Kontrasten mellom fokusmarkeringen og bakgrunnen er under anbefalt minimumskontrast for ikke-tekstlig innhold (3:1) når lenker brukes i variantene error, info og success i ContextMessage og MessageBox.

- SystemMessage har ingen lenker i eksemplene, men punktene over bør også fikses der hvis det er mulig med lenker.

**Forslag**
Endre til samme lenkestyling som i light mode. Det vil fungere siden bakgrunnsfargen i meldingene er den samme i light mode og dark mode.

**Comment by antidecaf** [comment]
Note to self:
Lenker i meldingsbokser trenger også litt tlc - `.ffe-link-text` vises med default farge, men siden meldingsboksene har lyse bakgrunner også i dark mode blir det krøll med kontrastene.
