### ISSUE TITLE
DatePicker: "The attribute aria-selected is not supported by the role button"

### ISSUE THREAD

**Issue by kwltrs** [SpareBank1/designsystem#1534]
I ffe-datepicker-react klager [den a11y-plugin til eslint](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/role-supports-aria-props.md) at man bruker feil aria-attributt i kalenderen:

```
warning  The attribute aria-selected is not supported by the role button  jsx-a11y/role-supports-aria-props
```
Dette gjelder [ClickableDate](https://github.com/SpareBank1/designsystem/blob/96e66a3cde106a5e6057492c4b7c245f64f09e99/packages/ffe-datepicker-react/src/calendar/ClickableDate.js#L67) og [NonClickableDate](https://github.com/SpareBank1/designsystem/blob/96e66a3cde106a5e6057492c4b7c245f64f09e99/packages/ffe-datepicker-react/src/calendar/NonClickableDate.js#L8) som er dagene i kalenderen.

![image](https://user-images.githubusercontent.com/493924/205263944-97aa4d54-5509-438f-8ffb-052f50cceeb6.png)

Her må man finne ut om dette er et reelt problem og hvilken `role` eller alternativ til `aria-selected` er bedre.

**Comment by HeleneKassandra** [comment]
De knappene det er snakk om er vel teknisk sett mer radiobuttons? Siden man bare kan velge 1? 
For hvis vi bytter til radiobuttons, så kan man bruke aria-checked.

**Comment by antidecaf** [comment]
Det er reelt nok, `aria-selected` støttes ikke av `role=button`. 

[MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected):

> The `aria-selected` attribute indicates the current "selected" state for [`gridcell`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/gridcell_role), [`option`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/option_role), [`row`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/row_role) and [`tab`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role) roles.

Ingen av rollene slår meg som spot on ved første øyekast. Å skrive om til faktiske radiobuttons tror jeg er langt fra trivielt, men kanskje det er en mulighet å bruke en kombinasjon av `role=radio` og `aria-checked`. Et annet mulig alternativ er å beholde `role=button` men bruke [`aria-current`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) i stedet.
