### ISSUE TITLE
Justere Accordion så det kommer frem at innholdet hører sammen med skjermlesere og annen kompenserende teknologi

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1540]
**Test**
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Accordion/Accordion/wcag-1.3.1_informasjon_og_relasjoner.yml

**Beskrivelse**
Det kommer ikke frem at innholdet (alle seksjonene) i Accordion hører sammen med kompenserende teknologi.

**Mulig løsning**
Vi kan blant annet vurdere å legge til role="group" og aria-label på den overordnede div-en.

**Comment by HeleneKassandra** [comment]
Noen forslag til hva som bør stå i aria-label? Siden det er rundt alle "accordionItem" så er det ikke rett frem å finne en passende label? Skal vi bare kalle det "accordion"?

**Comment by andrea-sb1** [comment]
> Noen forslag til hva som bør stå i aria-label? Siden det er rundt alle "accordionItem" så er det ikke rett frem å finne en passende label? Skal vi bare kalle det "accordion"?

Foreslår «Trekkspillmeny» (norsk variant av accordion) :)
