### ISSUE TITLE
Spinner: Vurdere om definere farge og font i stedet for å arve fra parent-element

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1553]
Nå ser det ut til at teksten i Spinner arver farge og font fra parent-elementet. Bør vi definere det i selve komponenten i stedet, for å ha mer kontroll på fonten og fargene som brukes?

Har foreløpig satt uu-testen for krav «1.4.3 Kontrast» til «ikke-testet»: https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Spinner/Spinner/wcag-1.4.3_kontrast_minimum.yml. Hvis vi velger å definere fargene i komponenten kan vi teste kravet. Hvis ikke kan vi legge det til under «ikke-relevante krav» siden fargene defineres utenfor komponenten.

**Comment by antidecaf** [comment]
Spinner-komponenten i seg selv inneholder ingen tekst eller markup som legger til rette for at man kan legge inn tekst, det er kun selve spinneren. Eksemplene i component-overview inneholder riktignok noe tekst, men dette ligger "ved siden av" og er ikke en del av komponenten. Så du har rett i at fargene defineres utenfor.

**Comment by HeleneKassandra** [comment]
Fargen blir vel ikke definert utenfor komponenten?  
Den blir definert i  `border: 3px solid @color`  i  ::before definisjonen i mixins.less fila.

Edit: 
Har laget en PR for å flytte innholdet i mixins.less inn i spinner.less fila, men tror ikke det skal ha gjort noen forskjell.
Funket i hverfall å bytte farge på spinneren ved å endre border-color.

**Comment by antidecaf** [comment]
Det er ikke border-color, men font og tekstfarge det er snakk om. Som i eksempelet i component-overview:
![Screenshot 2023-01-16 at 14 17 15](https://user-images.githubusercontent.com/463847/212687276-88202ac5-55d1-440e-ad82-18dfc23e4c87.png)
Poenget mitt var altså at denne teksten ikke er en del av komponenten. :)
