### ISSUE TITLE
Justere farger, komponenter og dokumentasjon i tråd med ny Skog-farge

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1562]
Det er bestemt at Skog-fargen i SpareBank 1-paletten får nye fargeverdier. Bakgrunnen er at det har manglet en grønnfarge i paletten som fungerer godt på knapper, ikoner og liknende – med god nok fargekontrast. Skog er gjort noe lysere og friskere så den fungerer til bruk på knapper, ikoner osv., samtidig som kontrasten er god nok for blant annet hvit tekst på Skog knapp.

Nye fargekoder:
Skog: #00754E
Skog 70%: #4D9E83
Skog 30%: #B3D6CA

**Gjøre:**
- [x] Endre ffe-farge-skog til #00754E (så vidt jeg skjønner vil ffe-farge-skog-70 og ffe-farge-skog-30 endres automatisk, basert på endringen i ffe-farge-skog?)
- [x] Endre grønnfargene i samtlige ffe-komponenter som bruker grønn (se Figma-branchen «Oppdatere fargepalett og komponenter i tråd med justert Skog-farge»)
- [x] Fjerne ffe-farge-nordlys-wcag
- [x] Oppdatere Skog-fargene i oversikten på https://design.sparebank1.no/profil/farger/
- [ ] Publisere endringene i Figma (branchen ligger klar, så vi kan publisere så fort vi publiserer i ffe)

**Comment by HeleneKassandra** [comment]
Sånn som det er med fargene nå, så kjører vi en "tint" funksjon som regner ut nøyaktig 70% tint av fargen. Vil du jeg skal skrive inn de spesifikke fargekodene? Eller skal vi bruke tint som vi gjør på alle de andre fargene?

**Comment by HeleneKassandra** [comment]
Endring i dokumentasjon: 
https://github.com/sparebank1utvikling/designsystem-docs/pull/202
