### ISSUE TITLE
Tooltip får ikke med seg fargene fra theme.less

### ISSUE THREAD

**Issue by nurrebass1** [SpareBank1/designsystem#1566]
**Beskrivelse av feilen**
Ved oppgradering til nyeste versjon av ffe-form, så mangler variablene for farger og fargene uteblir dermed. Dette fører til at theme.less må importeres i tillegg manuelt. Dette er ikke dokumentert i README f.eks og måtte feilsøkes manuelt. 

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til 'en applikasjon som bruker tooltip'
2. Klikk på 'inspect element og se at farge variablene  var(--ffe-v-tooltip-icon-color) etc er utilgjengelige (grået ut)'

**Forventet oppførsel**
Fargene skal være der når ffe-form/tooltip.less er importert, men theme.less må også importeres.

**Comment by antidecaf** [comment]
Takk for tilbakemeldinga, vi ser på det snarest råd!
