### ISSUE TITLE
Accordion-komponenten justerer ikke høyde ved endring av innhold

### ISSUE THREAD

**Issue by linezak** [SpareBank1/designsystem#1585]
**Beskrivelse av feilen**
Dersom innholdet i en AccordionItem endrer seg forblir høyden statisk slik at det enten blir for mye eller for lite plass til innholdet. 

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Lag en Accordion med en AccordionItem
2. Plasser en ExpandButton og en Collapse inni AccordionItem
3. Åpne AccordionItem
4. Trykk på ExpandButton for å vise innholdet i collapse
5. Innholdet vises ikke fordi AccordionItem er for liten 

**Forventet oppførsel**
AccordionItem justerer seg etter innholdet sin størrelse når innholdet endrer seg.  

**Skjermskudd**
Hvordan det er i dag:
![image](https://user-images.githubusercontent.com/116721288/226877692-d12eeb62-2885-4f93-b1c0-1a6e721ebfc8.png)
![image](https://user-images.githubusercontent.com/116721288/226877762-e49aa75d-4b1e-4539-850f-08f615827de4.png)
Ønsket visning: 
![image](https://user-images.githubusercontent.com/116721288/226878415-c0f655ac-ffd1-49ed-9b73-718f07d4a6db.png)

**Comment by HeleneKassandra** [comment]
Hei, 
Det stemmer at høyden er statisk og regnes ut når man ekspander komponenten, som igjen fører til den visuelle buggen du referer til.

Det vi derimot lurer på er om dette er et problem som bør løses, da eksempelet du referer til ikke tar i bruk accordion på tiltenkt måte. Man kan ta i bruk lenker og knapp i accordion, men hvis man har behov for å expandere mer innhold i en accordion, så ville jeg heller revurdert om accordion er riktig valg i dette scenarioet.
