### ISSUE TITLE
Bytte om på aria-expanded="true"/"false" for Tooltip external

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1587]
### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Form/Tooltip/wcag-4.1.2_navn_rolle_verdi.yml

### Beskrivelse
For external-varianten av Tooltip leser skjermlesere opp knappen som minimert når teksten vises (pga. aria-expanded="false") og utvidet når teksten er skjult (pga. aria-expanded="true"). Det blir da forvirrende å bruke akkurat den varianten med skjermleser. Det må også fikses for at komponenten skal ivareta [WCAG-krav 4.1.2 Navn, rolle, verdi (Nivå A)](https://www.uutilsynet.no/wcag-standarden/412-navn-rolle-verdi-niva/121).

<img width="1680" alt="Skjermbilde av Tooltip external med skjermleser" src="https://user-images.githubusercontent.com/77671758/227509070-dbaed5cd-309c-417b-b321-b093bb69c531.png">

### Forslag
Bytte til aria-expanded="true" når teksten vises, og "false" når den er skjult :)

**Comment by HeleneKassandra** [comment]
Den setter allerede aria-expanded="true"/"false" etter om den er åpen eller lukket, er problemet at aria-expanded ligger på feil tag?  Nå ligger aria-expanded på knappen, som også har en aria-controls med id til "collapse"

Edit:  Så  nå at denne feilen kun ser ut til å dukke opp i tooltip-external scenarioet.  Det skyldes at man ikke sender med isOpen propertyen i eksempelet. Litt usikker på hva bruksscenarioet for den external versjonen faktisk er, og om vi burde gjøre isOpen propertyen obligatorisk på tooltip eller ikke
