### ISSUE TITLE
@sb1/ffe-icons har avhengigheter med sikkerhetsbrudd i siste versjon

### ISSUE THREAD

**Issue by simenblikeng** [SpareBank1/designsystem#1588]
Hei,
Ser [ffe-icons](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-icons/package.json) i siste versjon bruker avhengigheten `svgstore 2.0.3` som videre ut i treet bruker `css-what 2.1.3`.

```
└─┬ @sb1/ffe-icons@12.17.0
  └─┬ svgstore@2.0.3
    └─┬ cheerio@0.22.0
      └─┬ css-select@1.2.0
        └── css-what@2.1.3
```

css-what kommer opp som et sikkerhetsbrudd.  
![image](https://user-images.githubusercontent.com/127311779/228473555-73c0b7d4-0c0a-4515-99d3-f047d6666d88.png)

---
**Forslag til løsning:**
Oppdatere svgstore til `svgstore 3.0.1` som er ett år gammelt (2.0.3 som nå er i bruk er 5 år gammel)

Den bruker den nyere versjon av `cheerio` som ikke bruker `css-select` så da er problemet borte.  

---

**EDIT**: Ser at css-select også bruker `nth-check 1.0.1` som også er sikkerhetsbrudd ifølge rapporten vår. 
![image](https://user-images.githubusercontent.com/127311779/228476958-6b7c6cd8-71b5-42d7-b142-693352d997c4.png)
Å oppdatere `svgstore` vil også fikse dette.

**Comment by HeleneKassandra** [comment]
Hei, Takk for at du sa fra! Har laget PR som retter dette nå :)
