### ISSUE TITLE
Ekspandert accordion får statisk høyde (ffe-collapse-react)

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1592]
**Beskrivelse av feilen**
`ffe-collapse-react` setter høyde med pikselverdi på ekspandert `Accordion` i noen tilfeller, og `height: auto` i andre. Det er litt uklart hva som avgjør om det blir det ene eller det andre. Høyden endres med [useEffect i Collapse.js](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-collapse-react/src/Collapse.js#L24).

**Steg for å gjenprodusere**
Logg inn i nettbank og se eksempel på en Accordion som får statisk høyde, f.eks under **Lån** -> **Mine lån** -> **Billån** -> **Gjør endringer** 

**Forventet oppførsel**
Høyden skal i utgangspunktet settes til `auto` når Accordion ekspanderes. [Våre egne eksempler på design.sparebank1.no](https://design.sparebank1.no/komponenter/accordion/) oppfører seg som forventet, noe som gjør denne litt kinkig å gjenskape og feilsøke.

**Comment by HeleneKassandra** [comment]
Jeg mistenker dette skyldes en kombinasjon at vi i setExpanded setter height, og useEffecten har "height" i dependecy array, så alle endringer til height vil trigge useEffecten.  Jeg la nemlig merke til at når jeg åpnet og lukket den for å åpne igjen, så står det "height: 84px" i ett sekund, før den plutselig endrer seg til auto.

Hvis man legger inn en console.log i if-statement på linje 26, så vil man også se at man får console.log 2 ganger når man trykker for å åpne. 

Det jeg tror skjer, er at om du får height auto eller height: x px avhenger av hvilken "useEffect" som blir trigget sist.  Om det er den som kjører når du endrer isOpen, eller om det er den som kjøres når height har blitt endret i setExpanded.

**Comment by HeleneKassandra** [comment]
Lukker denne da grunnen til at det er sånn er for å få animasjonen til å fungere som den skal selv om brukerne har "position:absolute" på innholdet.  

Potensielle tilfeller der dette er ett problem er  når den tilfeldigvis kjører "px" høyde useeffecten sist, og brukerne f.eks har en expand inni accordion - som jeg personlig mener er litt uheldig. 

Tldr;  dette er ikke en bug, men en feature(?)
