### ISSUE TITLE
Fikse problem med ID i InputGroup med Datepicker

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1609]
### Tester
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Form/InputGroup/wcag-1.1.1_ikke_tekstlig_innhold.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Form/InputGroup/wcag-1.3.1_informasjon_og_relasjoner.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Form/InputGroup/wcag-4.1.1_parsing_oppdeling.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Form/InputGroup/wcag-4.1.2_navn_rolle_verdi.yml

### Beskrivelse
For at skjermlesere og annen kompenserende teknologi skal presentere ledeteksten (labelen) til et skjemafelt når det kommer i fokus, må ledeteksten være programmatisk knyttet til skjemafeltet.

Nå mangler input-elementet i InputGroup med Datepicker en ID som label-elementet kan referere til. Nå refererer label-elementet til en ID som ikke finnes.

Div-en med input-elementet har også en aria-label, som jeg tenker blir overflødig når vi sørger for at labelen blir programmatisk knyttet til inputfeltet i Datepicker. Det er også varierende støtte for aria-label på div-er uten role/interaktiv role (https://www.davidmacd.com/blog/does-aria-label-override-static-text.html).

### Forslag
Sørge for at input-elementet i InputGroup med Datepicker får ID og at label-elementet refererer til denne ID-en (som vi gjør i de andre variantene av InputGroup). Fjerne aria-labelen på div-en med input-elementet.

**Comment by antidecaf** [comment]
I [dette eksempelet](https://sparebank1.github.io/designsystem/datepicker_Datepicker) har label et `for`-attributt og input-feltet en `id` som peker på hverandre. Det skal egentlig være riktig måte å knytte de to mot hverandre på. Så alt ligger til rette for å rendre Datepicker riktig, men det ser ut som id ikke er påkrevd i komponenten, så mulig løsninga er å endre på det.
