### ISSUE TITLE
Flytte div med Tooltip ut av legend-elementet i RadioButtonInputGroup

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1614]
### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Form/RadioButtonInputGroup/wcag-4.1.1_parsing_oppdeling.yml

### Beskrivelse
Får valideringsfeil på at div-en med Tooltip er child av legend-elementet i RadioButtonInputGroup.

Tooltip som child av legend-elementet gjør også at skjermlesere leser opp aria-labelen for Tooltip («Vis hjelpetekst») som en del av legend-beskrivelsen for radioknappene. Det kan oppleves forvirrende.

NB, gjelder ikke variant hvor Tooltip ligger tilknyttet hver enkelt radioknapp (utenfor legend-elementet).

### Forslag til løsning
Flytte div-en med Tooltip ut av legend-elementet.

**Comment by HeleneKassandra** [comment]
Hvis vi flytter tooltip ut av legend så vil den havne visuelt på linjen under. Dette kan man vanligvis style i CSS, men problemet er at legend må være "child" element av fieldset, så vi kan ikke wrappe legend med f.eks en span sånn som vi gjør andre steder. 

Legend er også visstnok litt vanskeligere å style, så for å få til dette så må vi muligens fjerne fieldset og legend og erstatte det med div´s og aria-role.  Ville det fungert? Eller er ikke det tilstrekkelig?
