### ISSUE TITLE
Datepicker lukkes ikke ved klikk utenfor

### ISSUE THREAD

**Issue by frederikgdl** [SpareBank1/designsystem#1647]
**Beskrivelse av feilen**
Vi har et skjema med flere Datepickers på en side. Vi har opplevd at noen av de ikke blir lukket ved klikk utenfor, spesielt når feltet er tomt.
Det samme skjer på designsiden, men da må feltet tømmes og man må trykke på kalenderknappen to ganger. Usikker på om dette er samme feil, men virker relatert.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til [https://design.sparebank1.no/komponenter/skjemaelementer/#datepicker](https://design.sparebank1.no/komponenter/skjemaelementer/#datepicker)
2. Fjern datoen fra et av Datepicker-feltene
3. Trykk på kalenderknappen to ganger.
4. Trykk utenfor for å lukke. Kalenderen blir ikke lukket.
5. Kan gjøres på flere Datepickers samtidig.

**Forventet oppførsel**
At kalendervisningen lukkes ved trykk utenfor.

**Skjermskudd**
<img width="1392" alt="Screenshot 2023-08-04 at 09 41 57" src="https://github.com/SpareBank1/designsystem/assets/8751346/6ed3ce75-14da-45f3-bf33-d04a81b8186f">

**Desktop**
 - Operativssystem: macOS Ventura 13.4.1
 - Nettleser: Chrome
 - Versjonsnummer: 115.0.5790.170

**Comment by antidecaf** [comment]
Takk for bugrapporten! Noen hos oss ser på det ved anledning. Hvis du har noen teorier om hvor det skjærer seg hører vi gjerne om det. :)

**Comment by frederikgdl** [comment]
Etter litt testing virker det som problemet er her https://github.com/SpareBank1/designsystem/blob/a5f1156b11a8eae702e71db18baf66c0ed1471ac/packages/ffe-datepicker-react/src/datepicker/Datepicker.js#L154

Når man trykker utenfor blir `globalClickHandler` kalt, den kaller videre `closeCalendar`.
I `closeCalendar` blir først `displayDatePicker` fra state satt til `false`, så blir `validateDateIntervals` kalt.
I `validateDateIntervals` blir staten satt igjen til `this.state` i linjen vist over.
Disse kallene til `setState` vil bli batchet sammen, så staten er ikke oppdatert når state brukes her, så `displayDatePicker` vil fortsatt være `true`.
Merk dette skjer fordi `value` er en tom string her.

Når state settes basert på tidligere state som i linjen over bør man bruke callback-varianten av `setState`, altså `this.setState((prevState, props) => ...)`.

Her bør kanskje det som skjer i `validateDateIntervals` være wrappet i en callback, eller på en annen måte unngå å bruke previous state.

Jeg skulle gjerne sendt inn en PR på dette, men jeg får ikke installert repoet på min maskin nå :/
