### ISSUE TITLE
HTML-eksempler i Komponenter

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#166]
Vi har en del React-komponenter, men ikke alle brukere har/kan bruke React. Et eksempel var for et internt system der et par folk gjerne skulle brukt InfoMessageBox, men ikke hadde noen pipeline for å bygge JavaScript. De trengte bistand for å få HTML-versjonen av det de ville bruke. Det hadde vært fint å få en fane for et rent HTML-eksempel som er copy/paste i stedet for å tvinge folk til å komme på at de kan Inspect Element for å få strukturen.

**Comment by antidecaf** [comment]
Vi ser på dokumentasjon av styling og markup med KSS - se #160.
