### ISSUE TITLE
formatAccountNumber.js formaterer internasjonale konto nr litt rart

### ISSUE THREAD

**Issue by henninghuseby** [SpareBank1/designsystem#1668]
**Beskrivelse av feilen**
Etter endringen på [formatAccountNumber.js](https://github.com/SpareBank1/designsystem/commit/d1ad119956e606945a69131f514bfd756473a448#diff-a7e9fe958b85178c24640732c4d62ef70c167e939a8d34043fe34fe02d505504) ser internasjonale kontonr litt rare ut

**Forventet oppførsel**
<img width="732" alt="image" src="https://github.com/SpareBank1/designsystem/assets/65295516/dd6efdbe-067a-4b4d-9c27-72d1c7c67715"> 

**Skjermskudd**
<img width="643" alt="image" src="https://github.com/SpareBank1/designsystem/assets/65295516/4c59e72b-6866-4ceb-ae92-7ec2fef551aa">

**Comment by henninghuseby** [comment]
tipper fjerningen av [denne](https://github.com/SpareBank1/designsystem/commit/17be715ea029ae473b9d1eef92049036ea27fc58#diff-a7e9fe958b85178c24640732c4d62ef70c167e939a8d34043fe34fe02d505504R4) har laget litt bug for utenlandske kontonr

**Comment by HeleneKassandra** [comment]
Er det en satt lengde på utenlanske kontonummer? Eller varierer det?

**Comment by henninghuseby** [comment]
De kan variere, vi kaller en tjeneste for å sjekke om landet har regler eller ikke (i /betaling/mottakere/utland/ny) og ser at det varierer veldig hva vi får tilbake

**Comment by henninghuseby** [comment]
Evt kan vi også la være å bruke formatAccountNumber.js når det er utenlandske konto nr

**Comment by HeleneKassandra** [comment]
Man vil jo gjerne formattere utenlanske kontonummer også, prøver bare å tenke på hvordan vi best kan løse det.
Grunnen til at den gamle funksjonen ble erstattet er at man ønsket at formateringen skulle skje mens man skrev, og ikke når man hadde tastet inn 11 siffer. 

Så spørsmålet er hvordan vi vil formatere nummer som er lenger enn 11, skal det f.eks alltid være space mellom hvert 4 nummer?

**Comment by henninghuseby** [comment]
Ser noen bruker space mellom hver 4 karakter så ja kanskje det er veien å gå, jeg kan lage en PR
