### ISSUE TITLE
Ferdig bygget CSS sjekket inn på GitHub for nedlasting?

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#167]
Ikke alle brukere av designsystemet har/kan bruke Less. Et eksempel var for et internt system der et par folk gjerne skulle brukt InfoMessageBox, men ikke hadde noen pipeline for å bygge CSS fra Less. De trengte bistand fra en utvikler for å få satt opp et minimumsprosjekt med Less, `ffe-core`, og `ffe-message-box`.

Kunne vi tilbudt ferdig bygget CSS for disse slags bruk, for eksempel sjekket inn her på GitHub så det bare er å laste ned? F.eks. en `dist/`-mappe i hver pakke som blir bygget med minimalt av det som trengs fra `core` (farger, variabler, mixins o.l) for å unngå å dra inn Normalize og mer bloat enn strengt nødvendig.

**Comment by ivarni** [comment]
Jeg føler da at vi kanskje optimaliserer for et veldig lite mindretall? Hvor stort tror vi dette problemet er?

**Comment by wkillerud** [comment]
Jeg ser det ikke som noen optimalisering for dem. Det går jo ikke på bekostning av noe annet enn tid å sette opp?

Det blir en ekstratjeneste som vi kan sette opp én gang som Travis kan ta seg av etter det, ala bygging av designsystemet til gh-pages.

Når det er sagt har jeg jo ikke noe tall på hvor mange dette gjelder. Første gang jeg er blitt involvert i det, men @gbrownlee og @adidick vet kanskje om flere som kunne ønske seg noe sånt?

**Comment by ivarni** [comment]
Fair enough, optimalisering var kanskje ikke et godt ord. Så lenge det er etterspørsel og ikke så mye jobb å vedlikeholde så er det vel ikke i veien for noen.

**Comment by gbrownlee** [comment]
Enig i at det neppe er så mange som vil ha dette behovet. Samtidig ønsker vi nok heller ikke å oppmuntre til å bruke systemet på denne måten. Når det er sagt, så er det selvsagt bedre at det brukes uten et forhold til underliggende funksjonalitet enn at det ikke brukes i det hele tatt. Med andre ord: Jeg støtter forslaget med en vedlagt advarsel at den må hostes selv og at man mister veldig mange fordeler ved å bruke det på denne måten.

**Comment by selbekk** [comment]
Det er fint å ha for å POCe opp ting på codesandbox, som ikke støtter LESS.

**Comment by antidecaf** [comment]
Holder det med en kopi av `ffe.css`, som er i bruk på styleguiden? I tilfelle er det mulig å få tak i her: https://design.sparebank1.no/ffe.css

**Comment by ivarni** [comment]
Inneholder den alle komponentene?

Jeg tenker det er lettere for konsumentene å holde det oppdatert om det ligger i npm-pakka, gitt at de bruker npm da.

**Comment by kwltrs** [comment]
> Inneholder den alle komponentene?

Nesten, ffe-account-seletor-react har litt css som ikke er med.
Filen bygges fra https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-all.less

 > Jeg tenker det er lettere for konsumentene å holde det oppdatert om det ligger i npm-pakka, gitt at de bruker npm da.

Helt sikkert er det enklere å bruke css'en med en npm-pakke. Men dette betyr en del endringer i byggsystemet og med tanke på at behovet virker rett lite så koster det kanskje mer enn det smaker.
