### ISSUE TITLE
Nullstill-knapp i AccountSelectorMulti nullstiller ikke

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1679]
**Beskrivelse av feilen**
Knappen for å nullstille input-feltet i AccountSelectorMulti nullstiller ikke input, men kollapser nedtrekkslista. Klikker man på chevron eller utenfor nedtrekkslista blir feltet derimot nullstilt. Begge knappene gjør tilsynelatende det den andre egentlig skal.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til https://design.sparebank1.no/komponenter/kontovelger/#accountselectormulti
2. Skriv noe i input-feltet
3. Klikk på X (nullstill) eller chevron (expand/collapse)
4. Se feilen

**Forventet oppførsel**

Nullstill-knappen bør nullstille input, chevron bør åpne og lukke nedtrekkslista.

**Skjermskudd**

![](https://i.imgur.com/NzykvsA.gif)

**Comment by HeleneKassandra** [comment]
Dette er ikke egentlig en bug, det er bare eksempelet vårt som mangler "onReset" funksjon. 
Legger det til i MultiEksempelet når jeg erstatter ikonene
