### ISSUE TITLE
Chevron i dokumentasjon rendres feil

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1690]
**Beskrivelse av feilen**
Ikonet i knappen for å toggle kode på design.sparebank1.no rendres uten styling i Firefox. Bør byttes til ffe-symbols

**Steg for å gjenprodusere**
Se https://design.sparebank1.no/komponenter/ikoner/ i Firefox

**Skjermskudd**
![image](https://github.com/SpareBank1/designsystem/assets/463847/d96b8560-3f0d-4981-8021-551e2680c148)

**Comment by HeleneKassandra** [comment]
Denne ble fikset i merget PR i docs repo
