### ISSUE TITLE
Prop i SearchableDropdown angitt som string, skal være tall

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1692]
**Beskrivelse av feilen**
SearchableDropdown gir en warning på `weight` fra `ffe-symbols-react`, på [linje 337](https://github.com/SpareBank1/designsystem/blob/0736ee0bce4dd21174e299060370cf81d2b1a97a/packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js#L337). Propen er angitt som string men skal være tall.

**Skjermskudd**
![image](https://github.com/SpareBank1/designsystem/assets/463847/6adb027f-5985-4838-a735-96e522b5fe90)

**Comment by HeleneKassandra** [comment]
FIkset i #1694
