### ISSUE TITLE
Responsiv spacing i Grid

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1693]
Grid har muligheter for å overstyre margin, padding og gap ved hjelp av modifiere. Disse modifierne tar imidlertid ikke hensyn til skjermstørrelse, noe som betyr at f.eks `.ffe-grid-row--padding-3xl` eller `<GridRow padding="3xl">` vil gi 64 px padding både på mobil, tablet og desktop. Denne verdien kan passe fint på desktop men være altfor mye på mobil.

Foreslår derfor at det innføres modifiere med mulighet til å overstyre spacing på hvert [breakpoint](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-core/less/breakpoints.less), som eksempelvis kan se ut som noe a la dette:

`padding="3xl" padding-sm="sm"`

eller

`padding={{mobile: 'sm', desktop: '3xl'}}`

**Comment by raglie-sb1** [comment]
Foreslår at vi ser på dette på tvers med innføring av variabler i Figma. 
Da kan vi lage felles system for responsiv spaceing/gutter.
