### ISSUE TITLE
Add visual regression tests

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#17]
We need some way of regression testing our CSS. There is [prior art on this in SB1](https://labs.sparebank1.no/2017/10/09/visuell-regressiontestning-i-praktiken/), but we need it to work in our new CI world.

**Comment by ivarni** [comment]
Any status on this? I feel like at least a [few](https://github.com/SpareBank1/designsystem/issues/173) [recently](https://github.com/SpareBank1/designsystem/issues/188) [closed](https://github.com/SpareBank1/designsystem/issues/191) issues might have been caught earlier if we had them running?

I thought our visual tests was already running in docker containers and that it would be easy to move that over to Travis? What's the issue that stopped us from doing so from the get-go?

**Comment by antidecaf** [comment]
Unfortunately we no longer have the example implementations used for visual tests (and thus no documentation of styling either). We've been experimenting with kss for this purpose (see #166/#160). You can see the output of this in `/dist/markup` after running `npm run kss:build`. There's a bit of an ongoing struggle to figure out how to include the kss output in the styleguidist styleguide, but for visual regression tests it could probably be quite useful.

**Comment by ivarni** [comment]
I see. I thought it was just a matter of taking the old [specs](https://stash.intern.sparebank1.no/projects/FFE/repos/ffe-buttons/browse/visual-tests?at=refs%2Ftags%2F5.0.0) and figuring out how to run the [gemini helper](https://stash.intern.sparebank1.no/projects/FFE/repos/ffe-visual-tests-support/browse) on Travis but if there's source code we no longer have access to then that's a bit unfortunate indeed.

**Comment by antidecaf** [comment]
Possibly decent option: [Puppeteer](https://github.com/GoogleChrome/puppeteer)

**Comment by ivarni** [comment]
If this ever gets revisited, [cypress](https://www.cypress.io/) has a [plugin](https://github.com/meinaart/cypress-plugin-snapshots) for doing image snapshots. Cypress is also generally awesome.
