### ISSUE TITLE
Uheldig breakpoint for menyen på iPad

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#171]
![305e4ad0-03a7-4a20-be7c-b4f2f7d87680](https://user-images.githubusercontent.com/1223410/38742301-74adee98-3f3c-11e8-905a-e7515366d5f5.png)

På iPad i portretmodus overlapper logoen deler av menyen

**Comment by wkillerud** [comment]
En annen litt uheldig sak, denne gangen i landskapsmodus med Universell utforming i menyen til venstre (teksten flyter på utsiden av sidebaren)

![5ee2d7a0-7f7c-4fc1-aa44-55b29f24d723](https://user-images.githubusercontent.com/1223410/38742713-95d108c0-3f3d-11e8-8c1c-f6ad172c1da4.png)

**Comment by antidecaf** [comment]
iPad? Bra catch. Mulig løsning er å brekke til mobil-layout på en høyere oppløsning.

**Comment by antidecaf** [comment]
Linker i sidebaren er en nøtt på visse skjermstørrelser. Ikke bare headinger, men også "normale" lenker, spesielt når ordene blir lengre enn bredden på sidebaren. Her er tre varianter som alle har sine drawbacks:

`word-break: normal` (slik ser det ut i dag):

![image](https://user-images.githubusercontent.com/463847/38805064-cd5b1be4-4174-11e8-8893-a2d4f9288968.png)

`text-overflow: ellipsis`:

![image](https://user-images.githubusercontent.com/463847/38805083-e36bb92a-4174-11e8-8f8e-3ce96620b931.png)

`word-break: break-word`:

![image](https://user-images.githubusercontent.com/463847/38805107-f24e7bb2-4174-11e8-9d1c-c6368d3e6e84.png)

Ingen av disse løsningene kan vel sies å være optimale. Andre alternativer er å skru ned tekststørrelsen eller øke antall kolonner i griden (men i så fall klager ffe-grid over at antall kolonner i konsollen). Innspill?

**Comment by wkillerud** [comment]
`break-word` funker i hvertfall ikke :no_good_man: Jeg stemmer for `ellipsis`. Øker vi antall kolonner blir den fort for bred på større skjermer også.
