### ISSUE TITLE
Bytte ikon i Accordion Item

### ISSUE THREAD

**Issue by havardthom** [SpareBank1/designsystem#1710]
**Beskrivelse av problem:**
Accordion Item bruker `expand_more` ikon med hjemmelaget wrapper for å lage sirkel rundt ikon. 

![image](https://github.com/SpareBank1/designsystem/assets/34199185/a4855901-80bc-4a33-ae28-ed340bd565f7)

**Forslag til løsning**
Foreslår å bytte ut til `expand_circle_up` og `expand_circle_down` ikon som er sirklet, for å være mer konsistent med andre ikoner 

![image](https://github.com/SpareBank1/designsystem/assets/34199185/adbba07c-831b-403f-9f7e-c86aa8beb1ac)

I samme slengen ville det vært nyttig med en `fillOnHover` prop på `Symbol` komponenten hvis det er vanlig oppførsel i designbiblioteket.

**Comment by HeleneKassandra** [comment]
For å forklare litt bakgrunnen til hvorfor det er sånn som det er i dag:
Dagens situasjon er at vi henter ikonene fra ulike font-filer, og disse er blant annet splittet på filled og ikke filled ikoner. 
Grunnen til at jeg gikk for expand_more ikonet, og lagde en sirkel bak i css istedenfor  expand_circle_up var for å kunne style hover effekten i CSS uten å måtte laste inn enda en font-fil til bruk i 1 komponent. 

Så hadde vi ikke hatt de store utfordringene vi har med lasting av store ikon font-filer, så hadde jeg vært helt enige med deg! 
Lar derfor issuet bli stående, da det nok blir mer relevant når vi  har landet på en løsning i arbeidet som gjøres nå med å se på en annen måte å importere ikonene på enn gjennom font-fil.  Men da vet du hvertfall hvorfor det er som det er i dag! 
God ide med fillOnHover-prop :)

**Comment by pethel** [comment]
Det ikonet med sirkel ligner ikke i skisserna i Figma. Hvis man ønsker bruka det nya ikonet så man bli enig med Figma

**Comment by HeleneKassandra** [comment]
Jeg så på denne igjen etter endringen av ikonene, og det er ikke verdt jobben å gjøre den endringen. Da må vi laste 2 svg-er, og virker veldig unødvendig. Så anbefales at den lukkes

**Comment by pethel** [comment]
Da lukker vi.
