### ISSUE TITLE
Docs: Relaterte komponenter linker funker ikke

### ISSUE THREAD

**Issue by HeleneKassandra** [SpareBank1/designsystem#1714]
**Beskrivelse av feilen**
Linkene i relaterte komponenter lista i dokumentasjonen linker ikke til de faktiske sidene. 

<img width="493" alt="Skjermbilde 2023-11-22 kl  12 57 11" src="https://github.com/SpareBank1/designsystem/assets/39946146/1dcd1437-c7f7-4dcc-9b47-83bf1c17d5c5">

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til https://design.sparebank1.no/komponenter/knapper/#relaterte-komponenter
2. Klikk på en av linkene
4. Se feilen

**Forventet oppførsel**
Burde gå til siden den skal linke til 
**Skjermskudd**
Hvis det er hensiktsmessig og mulig kan ofte et skjermskudd beskrive bedre og kortere enn ord. 

**Desktop (fyll ut feltene ):**
 - Operativssystem: [feks Windows 3.11]
 - Nettleser [feks Internet Explorer 6]
 - Versjonsnummer [feks 42]

**Mobil (fyll ut feltene):**
 - Enhet: [feks Nokia 3210]
 - Operativssytem: [feks Android]
 - Nettleser [feks Chrome]
 - Versjonsnummer [feks 22]

**Tilleggsinformasjon**
Øvrig informasjon som kan være relevant.

**Comment by antidecaf** [comment]
Kan det være like greit å fjerne disse helt? Knapper ser ut til å være den eneste komponent-siden som har link til Relaterte komponenter, og ut fra url-ene ser disse ut som en levning fra styleguidist.

**Comment by tuva-odegard** [comment]
Fixed with https://github.com/sparebank1utvikling/designsystem-docs/pull/262
