### ISSUE TITLE
Gjøre så fokusborder ikke dukker opp ved valgt element i RadioSwitch og RadioBlock

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1717]
### Beskrivelse
Ved valgt radioknapp i RadioSwitch og  RadioBlock vises en ekstra border rundt knappen, som egentlig bare skal vises når knappen får tastaturfokus.

Synes å huske at vi fikset samme problem i noen av Button-komponentene, så kanskje vi kan bruke samme løsning her.

<img width="554" alt="Skjermbilde av RadioSwitch som viser overflødig border ved valgt element" src="https://github.com/SpareBank1/designsystem/assets/77671758/ab96f69d-e4d4-403f-bd32-1f9caa016acb">

<img width="555" alt="Skjermbilde av RadioBlock som viser overflødig border ved valgt element" src="https://github.com/SpareBank1/designsystem/assets/77671758/ca579bbf-4ac7-4164-b78f-2e1d891449dd">

**Comment by pethel** [comment]
Har ordnet. Verfisier gjerne og lukk hvis løsnignen er som forventet

**Comment by pethel** [comment]
Ser bra ut i doc
