### ISSUE TITLE
Fikse problem med todimensjonal skroll ved fontskalering i Accordion og TertiaryButton

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1718]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Tester
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Accordion/Accordion/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Buttons/TertiaryButton/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, flyter innhold (tekst og ikoner) ut over containeren til komponenten samt skjermen og introduserer horisontal skroll. Det gjelder ved bruk av ord med en viss lengde. 

Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

Accordion med standard tekststørrelse:
<img width="321" alt="Accordion med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/8ea7aa94-8f7f-4a40-a1b3-29d71d896798">

Accordion med tekststørrelse 200%:
<img width="321" alt="Accordion med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/f97f000c-db2c-440a-a1e7-b8d1c0514218">

TertiaryButton med standard tekststørrelse:
<img width="310" alt="TertiaryButton med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/b5ff276e-a9bf-41c1-ad29-cacf9051192f">

TertiaryButton med tekststørrelse 200%:
<img width="298" alt="TertiaryButton med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/0a03f8a0-986e-4fcc-bc4b-09684521e01a">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

<img width="319" alt="Accordion med tekst 200 prosent størrelse og foreslått endring" src="https://github.com/SpareBank1/designsystem/assets/77671758/76c8107d-f1d1-4000-8694-7898990a1d65">

**Comment by antidecaf** [comment]
Fikset i #1814
