### ISSUE TITLE
Fikse problem med todimensjonal skroll ved fontskalering i TaskButton

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1719]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Tester
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Buttons/TaskButton/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, flyter teksten i TaskButton ut over containeren til komponenten samt skjermen og introduserer horisontal skroll. Det gjelder ved bruk av ord og setninger med en viss lengde. 

Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

TaskButton med standard tekststørrelse:
<img width="307" alt="TaskButton med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/675584e9-c581-4101-84e5-6dfd2321ab13">

TaskButton med tekststørrelse 200%:
<img width="319" alt="TaskButton med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/f1baf62d-bc7f-4936-a4bb-587a4a02a7cf">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
- text-wrap: Endre fra `nowrap` til `wrap`
- `line-height`: Endre fra piksler til rem
- Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

<img width="310" alt="Accordion med tekst 200 prosent størrelse og foreslåtte endringer" src="https://github.com/SpareBank1/designsystem/assets/77671758/9da7acd6-1007-4f4a-812c-4ea6cb94edc1">

**Comment by antidecaf** [comment]
Fikset i #1807
