### ISSUE TITLE
Fikse feil ved fontskalering i ImageCard og TextCard

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1720]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Tester
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/ImageCard/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/TextCard/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, blir deler av teksten i ImageCard og TextCard kuttet så den ikke er synlig. Det gjelder ved bruk av ord med en viss lengde.

ImageCard med standard tekststørrelse:
<img width="294" alt="ImageCard med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/6a877284-289c-42e7-b57b-71c278142f75">

ImageCard med tekststørrelse 200%:
<img width="294" alt="ImageCard med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/6bff736e-a18e-434f-8290-704c1c47e6d3">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

<img width="295" alt="ImageCard med tekst 200 prosent størrelse og foreslått endring" src="https://github.com/SpareBank1/designsystem/assets/77671758/cbb1b655-5b75-4c3a-83c6-1d5e937059b6">

**Comment by antidecaf** [comment]
Fikset i #1768/#1814
