### ISSUE TITLE
Fikse problem med todimensjonal skroll ved fontskalering i CardBase, IconCard og StippledCard

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1721]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Tester
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/CardBase/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/IconCard/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Cards/StippledCard/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, flyter tekst ut over containeren til komponenten samt skjermen og introduserer horisontal skroll.

Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

CardBase med standard tekststørrelse:
<img width="324" alt="CardBase med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/e50571a4-8af7-4521-be50-de612ad53d5a">

CardBase med med tekststørrelse 200%:
<img width="319" alt="CardBase med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/0fe9fb61-ef4b-4790-9da0-bab3a18f6d9d">

IconCard, default og condensed, med standard tekststørrelse:
<img width="321" alt="IconCard med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/28b51f01-90b9-41ae-80dd-ff844f0b3b7a">
<img width="316" alt="IconCard, condenced, med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/2238e0dd-0d8a-45d9-bd9c-92834632bf36">

IconCard, default og condensed, med tekststørrelse 200%:
<img width="320" alt="IconCard med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/81a6b36c-e9a3-4c9c-8e79-f94ac30e3cb2">
<img width="322" alt="IconCard, condensed, med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/4e8a3b4c-c2c8-44c5-b5fe-e16d4171b06a">

StippledCard, default og condensed, med standard tekststørrelse:
<img width="307" alt="StippledCard, bare tekst, med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/2f847cc9-d26e-45aa-8155-98701ba5b7d9">
<img width="312" alt="StippledCard, ikon og tekst, med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/005c180d-82f5-45b8-81de-b40f4edce13e">
<img width="319" alt="StippledCard, condensed, med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/92c15fd3-9f50-4bf8-a97f-54abb8597366">

StippledCard, default og condensed, med tekststørrelse 200%:
<img width="317" alt="StippledCard, bare tekst, med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/d68a5afb-aa44-4004-ad4e-d7f3527f9ace">
<img width="320" alt="IconCard StippledCard, ikon og tekst, med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/f60c2178-34ae-4e9b-9f30-44db36d042a2">
<img width="318" alt="StippledCard, condensed, med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/e780cc8a-25f4-4fd3-9660-82bbc7dbdcf7">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

CardBase, IconCard condenced og StippledCard condensed med tekststørrelse 200% og `word-break: break-word;`:
<img width="321" alt="CardBase med tekst 200 prosent størrelse og foreslått endring" src="https://github.com/SpareBank1/designsystem/assets/77671758/f5cb0630-57c7-4e47-8de7-b4cfa40a4a5b">
<img width="328" alt="IconCard, condensed, med tekst 200 prosent størrelse og foreslått endring" src="https://github.com/SpareBank1/designsystem/assets/77671758/7ccf40d5-ade0-42df-a3f0-25c105a04979">
<img width="317" alt="StippledCard, condensed, med tekst 200 prosent størrelse og foreslått endring" src="https://github.com/SpareBank1/designsystem/assets/77671758/d8b5354f-5236-48e9-a17d-836368312788">

**Comment by antidecaf** [comment]
Fikset i #1768/#1814
