### ISSUE TITLE
Fikse feil ved fontskalering i ContextMessage og SystemMessage

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1728]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Tester
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/ContextMessage/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/SystemMessage/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, blir deler av teksten i ContextMessage (error, info, success, tips) og SystemMessage (error, info, success, news) kuttet så den ikke er synlig. Lukk-ikonet er heller ikke synlig. Det gjelder ved bruk av ord med en viss lengde, i både headinger og body text.

ContextSuccessMessage med standard tekststørrelse:
<img width="319" alt="ContextSuccessMessage med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/ca94a9d8-a129-4fae-9d7b-1cacfdacf524">

ContextSuccessMessage med tekststørrelse 200%:
<img width="318" alt="ContextSuccessMessage med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/ce83617a-513c-417f-b522-720e51d3d642">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

<img width="319" alt="ContextSuccessMessage med tekst 200 prosent størrelse og foreslått endring" src="https://github.com/SpareBank1/designsystem/assets/77671758/605c72b0-c852-461d-9449-bb258a0dbef2">

**Comment by antidecaf** [comment]
Denne er fikset i #1768. Kan nok forbedres ytterligere ved å vurdere om ikonet og teksten skal ligge ved siden av hverandre eller under hverandre på små skjermer, men det er vanskelig å gjøre dette kun ved å detecte tekstskalering.
