### ISSUE TITLE
Fikse feil ved fontskalering i MessageBox

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1740]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Messages/MessageBox/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, endrer ikke overskriftene i MessageBox (error, info, success, tips) størrelse siden disse er kodet med px. Vi må sørge for at all tekst er kodet på en måte så den kan skalere i størrelse, i tråd med lovkravet.

Ved bruk av ord med litt lengde, i mobilvisning, flyter innhold ut over containeren til komponenten samt skjermen og intoduserer horisontal skroll. Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

Sirkelen rundt ikonet endrer ikke størrelse ved skalering, noe som gjør at det blir lite luft mellom ikonet og sirkelen. Sirkelen plasseres også på toppen av meldingsboksen i stedet for at den overlapper. Dette er ikke brudd på lovkravet, men noe vi bør fikse for best mulig brukeropplevelse.

MessageBox med standard tekststørrelse:
<img width="321" alt="MessageBox med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/4dc59e36-7502-44e9-99ef-153056365ac4">

MessageBox med tekststørrelse 200%:
<img width="323" alt="MessageBox med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/66225805-fc42-4e6b-8354-d47ca384d172">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
- Endre fra px til skalerbart format som f.eks. rem for overskriftene
- Legge til `word-break: break-all`, `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?
- Løsning for å fikse problemene med plassering og størrelse på sirkel

**Comment by antidecaf** [comment]
Fikset i #1768
