### ISSUE TITLE
Fikse problem med todimensjonal skroll ved fontskalering i Emphasized Text, Heading, MicroText, Paragraph, SmallText og StrongText

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1756]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Tester

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Typography/EmphasizedText/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Typography/Heading/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Typography/MicroText/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Typography/Paragraph/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Typography/SmallText/wcag-1.4.4_endring_av_tekstst_rrelse.yml

https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Typography/StrongText/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, flyter teksten i Emphasized Text, Heading, MicroText, Paragraph, SmallText og StrongText ut over containeren til komponenten samt skjermen og introduserer horisontal skroll. Det gjelder ved bruk av ord med en viss lengde.

Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

Headinger med standard tekststørrelse:
<img width="321" alt="Headinger med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/546e4dc4-5fbe-4c8c-8516-fe4afe841a5e">

Headinger med tekststørrelse 200%:
<img width="322" alt="Headinger med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/68e4aa4b-1836-4d43-bbbf-48f613f4b62c">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

**Comment by antidecaf** [comment]
Fikset i #1814
