### ISSUE TITLE
SmallText har forskjellig line-height om det er <span> eller <p>

### ISSUE THREAD

**Issue by noralroste** [SpareBank1/designsystem#1757]
**Beskrivelse av feilen**
Line height er forskjellig om en bruker en <span> eller en <p>. Ser ut som om det er avhengig om det er `display: block` eller `display:inline-block`

**Steg for å gjenprodusere**
![image](https://github.com/SpareBank1/designsystem/assets/116730465/7dbde1fd-9758-4553-8ce7-a87d11818115)'

**Comment by pethel** [comment]
Mergat en fix på dette.
