### ISSUE TITLE
Fikse problem med todimensjonal skroll ved fontskalering i Tooltip

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1759]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Form/Tooltip/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, flyter teksten i Tooltip ut over containeren til komponenten samt skjermen og introduserer horisontal skroll. Det gjelder ved bruk av ord med en viss lengde. Spørsmålstegn-ikonet overlapper også borderen til sirkelen rundt.

Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

Tooltip med standard tekststørrelse:
<img width="319" alt="Tooltip med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/21768fec-65c0-489e-9498-5e4d3f392c5a">

Tooltip med tekststørrelse 200%:
<img width="319" alt="Tooltip med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/72202663-5cec-4bfe-9017-28d474260722">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

Pluss finne løsning for at ikonet ikke overlapper borderen rundt.

**Comment by antidecaf** [comment]
Fikset i #1790/#1814
