### ISSUE TITLE
RFC: consistent i18n across FFE

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#176]
We have a few different approaches to internationalization across the various components in FFE, depending on who wrote the first implementation way back when :older_man: As a developer it would be nice to have a consistent API across components so it's predictable what will be needed and what the different parts are called.

Examples: 

* [Datepicker](https://github.com/SpareBank1/designsystem/blob/d1d1a845d927a0c4513353bf24a9dee50c1f2283/packages/ffe-datepicker-react/src/datepicker/Datepicker.js#L379) with its `language` prop
* [AccountSelector](https://github.com/SpareBank1/designsystem/blob/d1d1a845d927a0c4513353bf24a9dee50c1f2283/packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.js#L126) with its `locale` prop

Both take the same ISO code for the locale. Unfortunately (in my opinion) both also require them instead of defaulting to `nb` (not all apps using FFE support multiple locales).

I'm opening this issue to get feedback on what would be a nice API for i18n for our components.

**Comment by benmatthews** [comment]
`Locale` applies to more things than just language e.g. date formatting, decimal formatting, monetary conventions etc. so if we go for `language` as a prop might we end up in a situation where we also need a `locale` prop?  and that would be unfortunate, the `AccountSelector` uses locale to format currency for example.

+1 for an optional 'locale' or 'i18n' prop and defaulting to `nb`.

**Comment by wkillerud** [comment]
Good point about `locale` vs `language`. I agree, `locale` should be the way to go since we do/should adapt more than just the language (like dates, currency).
