### ISSUE TITLE
Fikse problem med dropdown-eksempel i dokumentasjonen

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1778]
### Beskrivelse av feilen
Feilmelding vises i stedet for eksempelet på SearchableDropdown, highCapacity.

<img width="1677" alt="Skjermbilde av siden om dropdown i dokumentasjonen" src="https://github.com/SpareBank1/designsystem/assets/77671758/952ff932-783e-4430-ba4d-c598519b73c9">

**Comment by pethel** [comment]
Har fjernet denne fra  dokumentasjonen
