### ISSUE TITLE
Clarify comment about an IE11-issue in ffe-account-selector-react

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#18]
This code comment mentions an issue with IE11, which is supposed to be fixed in React 16. As React 16 is out by now, the comment might need an update.
https://github.com/SpareBank1/designsystem/blob/d5bb1f7fa7b15411b707999469ee3814c3ae9a81/packages/ffe-account-selector-react/src/subcomponents/input-field/InputField.js#L14-L21

**Comment by wkillerud** [comment]
Depending on the outcome of #44 we may drop this workaround and comment altogether. For now I think the comment is fine.

**Comment by wkillerud** [comment]
From #44 we'll be dropping support for React 15, so this workaround can be removed. I'll do it as a separate commit when working on #44.

**Comment by kwltrs** [comment]
Keep in mind that the comment pre-dates  the release of React 16 and we need to verify that this known issue is solved.

**Comment by wkillerud** [comment]
I tried removing the React 15 workaround and tested in IE11. No characters were dropped when I was typing. I think we can safely go back to only using `onChange`. PR incoming.
