### ISSUE TITLE
ffe-radio-button: Radio switch redesign

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#181]
#### Which package is this issue related to?

`ffe-radio-button`

#### Describe your issue

The current radio switch implementation does not accurately reflect the one in Sketch.

In particular:

* The FFE version is too wide
* The distance between text and radio marker is too large
* The active state colors are different

**Sketch**

![image](https://user-images.githubusercontent.com/1223410/38869135-efcd9bb8-4249-11e8-87b9-4a46dec5c845.png)

**FFE**

![screen shot 2018-04-17 at 14 18 46](https://user-images.githubusercontent.com/1223410/38869238-41bc0cb6-424a-11e8-81fa-05fab29f5912.png)

The FFE implementation should be updated to reflect the latest design.

**Comment by wkillerud** [comment]
## Some details from Zeplin

### Unselected state

**Switch**

The rounded border/container for the radio button and label.

```css
border-radius: 22px;
background-color: @ffe-white;
border: solid 2px @ffe-grey-silver;
```

**Radio button**

```css
width: 16px;
height: 16px;
background-color: @ffe-white;
border: solid 2px @ffe-grey;
```

**Switch label**

```css
font-family: MuseoSansRounded-500;
font-size: 18px;
font-style: normal;
font-stretch: normal;
line-height: 1.33;
letter-spacing: normal;
text-align: left;
color: @ffe-blue-azure;
```

### Selected state

**Switch**

```css
border-radius: 22px;
background-color: @ffe-blue-royal;
```

**Radio button**

```css
width: 20px;
height: 20px;
background-color: @ffe-blue-azure;
border: solid 5px @ffe-white;
```

**Switch label**

```css
font-family: MuseoSansRounded-500;
font-size: 18px;
font-style: normal;
font-stretch: normal;
line-height: 1.33;
letter-spacing: normal;
text-align: left;
color: @ffe-white;
```

**Comment by selbekk** [comment]
Fixed by mine and Adi's walk through I think.
