### ISSUE TITLE
Hjelpetekstikon vises ikke riktig i InputGroup

### ISSUE THREAD

**Issue by lundal-sb1** [SpareBank1/designsystem#1812]
**Beskrivelse av feilen**
Hjelpetekstikonet blir plassert på en egen linje. Sirkelen ser også ut til å ha blitt mindre, slik at det ikke er helt plass til spørsmålstegnet.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til https://design.sparebank1.no/komponenter/skjemaelementer/
2. Finn en InputGroup
3. Se feilen

**Forventet oppførsel**
Hjelpetekstikonet skulle blitt plassert til høyre for navnet. Sirkel som er stor nok for spørsmålstegnet.

**Skjermskudd**

![Screenshot from 2024-02-27 13-41-22](https://github.com/SpareBank1/designsystem/assets/110812287/0e529b55-9a8b-41eb-bd32-522fd4a01252)

**Desktop (fyll ut feltene ):**
 - Operativssystem: RHEL 8.9
 - Nettleser: Firefox 115 / Chrome 122

**Comment by pethel** [comment]
https://github.com/SpareBank1/designsystem/pull/1822 (størelsen er fikxed i en annen pr)

**Comment by pethel** [comment]
løst
