### ISSUE TITLE
Legge til spacing-variabler som CSS custom properties

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1823]
I forbindelse med innføringen av [theming](https://design.sparebank1.no/profil/theming/) har de fleste variabler blitt lagt til som CSS custom properties i [theme.less](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-core/less/theme.less). Spacing finnes imidlertid fortsatt kun som [Less-variabler](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-core/less/spacing.less). Disse bør også legges til i theme.less.

**Comment by lundal-sb1** [comment]
Bør dette regnes som en bug, siden Accordion bruker `--ffe-spacing-xs` og denne ikke dras inn by default?

**Comment by pethel** [comment]
Ser att denne er løst
