### ISSUE TITLE
Sette opp og visualisere fordeler/ulemper for bruk av MUI og SB1U Deignsystem og nye prosesser for bidrag

### ISSUE THREAD

**Issue by ThereseBoerter** [SpareBank1/designsystem#1831]
Gjøre en analyse. Bruke denne listen inn i diskusjon i møte 12. april. Bra om teamet gjør seg opp en mening. Hvordan treffer dette strategien? Finnes det noen strategi? Hvordan treffer det ulike initiativ innenfor design i hele SB1U?  Hvilke andre initiativer er det på huset? Risks? Vedlikehold? Kostnader?

Pros-cons for begge designsystemene, pros-cons for sentralisert desentralisering
Visualisere bidragsmodell for central volunteer guild-contribution (DS som sentraliseringsQA) (Shared Powerpoint?)

**Comment by SindreSafvenbom** [comment]
1. Hva har MUI som SB1 DS ikke har (per nå)
- Hvilke behov dekkes ikke per i dag? Vil MUI etterkomme dette
3. Cost/benefit av MUI kontra internt DS
4. Individiualiseringsmuligheter for MUI (design og kode)
5. Hvilke standarder følger MUI
6. Native teknologi, full blocker?
7. Hvilke *NYE* problemer får vi med MUI
8. Blir det mindre mulighet for tjenestespesifikke tilpasninger?
- hva skjer med custom komponenter ved MUI sentral update
- Kan vi i det hele tatt ha custom komponenter med MUI?
9. Får vi bare det samme problemet med individuelle biblioteker om 12 måneder?
10. Hva blir strategien hvis vi snur 100% til MUI
11. Hva er BM Finansierings erfaring med MUI?

Skal Sparebank1 tillate team-spesifikke designsystemer uten avhengigheter
