### ISSUE TITLE
Fikse feil ved fontskalering i Feedback

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1835]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Feedback/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, overlapper «Send tilbakemelding»-knappen deler av teksten i feilmeldingen så den ikke er synlig.

Feedback med standard tekststørrelse:
<img width="317" alt="Feedback med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/88c28bf8-b1df-49cc-8a97-bf5d0b23e8ef">

Feedback  med tekststørrelse 200%:
<img width="317" alt="Feedback med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/ecbedb9f-3bed-4260-b455-70657dfd2905">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Usikker på hvordan vi best løser denne :)

**Comment by pethel** [comment]
Denne feilen går egentligen ikke på feedback men på inout group. Input group setter av en hvis højde under under seg før feilmeldningen. Det er vell før att slippa hopp. Utførdringen blir når meldningen brekker på flere lonjer eller fontstørelsen er større. Tror dessverre ikke det ermulig att ha det slik. En melding kan ju ha olika lengde så man kan ikke bruke fonstørelse på platsen som settes av.

**Comment by pethel** [comment]
Mener denne er i orden nå
![Screenshot from 2024-04-16 14-08-09](https://github.com/SpareBank1/designsystem/assets/2248579/a6395ac4-9beb-42ef-b55d-e619235a9a73)
