### ISSUE TITLE
Fikse problem med todimensjonal skroll ved fontskalering i PreformattedText

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1839]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Typography/PreformattedText/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, flyter tekst i PreformattedText ut over skjermen og introduserer horisontal skroll. 

Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

PreformattedText  med standard tekststørrelse:
<img width="316" alt="PreformattedText med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/b680240d-fc82-4f5c-8236-6d264d0e2926">

PreformattedText med tekststørrelse 200%:
<img width="319" alt="PreformattedText med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/cd15534c-4a95-414d-aecf-2ae03783392f">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

**Comment by pethel** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

Her tror jag ikke vi burde gjøra så mye? Hele poenget med `<pre/>` er ju att den beholder linjeskift osv. 

Testade att setta på en overflow-wrap: anywhere;. Det har ingen effekt. Det ser ikke ut som det finnes noen motsvarande aria, det gir vell mening det da dette bare er en visuell ting. 

Så jag tror rett og slett ikke vi kan gjøra noe her hvis skall beholde den funsjionaliteten som  `<pre/>`  har.

**Comment by pethel** [comment]
Lukker med det jag kommenterat
