### ISSUE TITLE
Fikse problem med todimensjonal skroll ved fontskalering i DetailsList

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1840]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/DetailsList/DetailsList/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, i mobilvisning, flyter tekst i DetailsList ut over skjermen og introduserer horisontal skroll. Det gjelder ved bruk av ord med en viss lengde.

Dette skal ikke være brudd på lovkravet siden innholdet fortsatt er tilgjengelig og forståelig, ved hjelp av skroll. Mener fortsatt vi bør løse det siden todimensjonal skroll bør unngås, i tråd med [WCAG 2.1/2.2, 1.4.10 Reflow (ekstern lenke)](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

DetailsList  med standard tekststørrelse:

<img width="317" alt="DetailsList med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/757f40d5-a2c0-4267-86b8-34e8d859f20e">

DetailsList med tekststørrelse 200%:
<img width="318" alt="DetailsList med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/d69ba203-4ac9-4a25-96f8-cbd403eb0785">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Legge til `word-break: break-all` eller `overflow-wrap: anywhere;`. Kanskje `overflow-wrap: anywhere;` er beste løsning, for å unngå at ord brekkes der de heller kan havne på ny linje?

**Comment by pethel** [comment]
![image](https://github.com/SpareBank1/designsystem/assets/2248579/0695f863-cde3-4a7c-932c-f53b959373fb)
![image](https://github.com/SpareBank1/designsystem/assets/2248579/84cc68a2-41c7-4ffb-8ecc-669efeb8a97e)

Denne ser ut att vare i orden.
