### ISSUE TITLE
Fikse feil ved fontskalering i ChartDonut

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1841]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/ChartDonut/ChartDonut/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200%, overlapper deler av teksten i ChartDonut sirkelen så teksten blir vanskeligere å tyde. Teksten flyter også ut over sirkelen.

ChartDonut med standard tekststørrelse:
<img width="316" alt="ChartDonut med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/76e43785-7f55-4ae7-b45e-d1809f3f88bf">

ChartDonut med tekststørrelse 200%:
<img width="315" alt="ChartDonut med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/0cbc844b-b54b-40f0-b180-3109228cf31d">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Vet ikke hvordan vi best løser denne.

**Comment by pethel** [comment]
Burde sirkelen også definieras i rem? Da vill den vokse med texten. Det blir ju ikke en kun text-zoom da men kanskej er greit. Annars att sirkelen ligger bak texten men da må man vell ha bakgrund på texten pga av kontrakster.

**Comment by pethel** [comment]
Fikset slik att donuten også blir større når fonten skaleras.
