### ISSUE TITLE
Fikse feil ved fontskalering i FileUpload

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1842]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/FileUpload/FileUpload/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200% i FileUpload, desktopvisning, kuttes teksten i knappen så den ikke er synlig. Tekst flyter også ut over «boksen».

FileUpload, desktopvisning, med standard tekststørrelse:
<img width="1313" alt="FileUpload på desktop med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/cee4ed7b-da99-46ab-9b4d-a7395c488261">

FileUpload, desktopvisning, med tekststørrelse 200%:
<img width="1324" alt="FileUpload på desktop med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/bb1913a6-708f-4f73-9a19-6c923992a2aa">

Med tekststørrelse 200% er det også lite luft mellom og rundt teksten i knappen, i mobilvisning. Det samme gjelder luft mellom knappen og stiplet border.

FileUpload, mobilvisning, med standard tekststørrelse:
<img width="317" alt="FileUpload på mobil med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/4ca1d059-d5c4-47f7-8c0f-dc232371fbca">

FileUpload, mobilvisning, med tekststørrelse 200%:
<img width="317" alt="FileUpload på mobil med tekst 200 prosent størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/25845402-8777-486b-bfae-6fb567850f94">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemene.

**Comment by pethel** [comment]
Denne skal vare i orden nå
