### ISSUE TITLE
Fikse feil ved fontskalering i Datepicker

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1843]
### Lovkrav
https://www.uutilsynet.no/wcag-standarden/144-endring-av-tekststorrelse-niva-aa/96

### Test
https://github.com/sparebank1utvikling/designsystem-uustatus/blob/main/reports/Datepicker/Datepicker/wcag-1.4.4_endring_av_tekstst_rrelse.yml

### Beskrivelse
Ved skalering av tekststørrelse til 200% i Datepicker blir deler av tallet som er markert i kalenderen usynlig. Innholdet i kalenderen flyter også ut over kalender-rammen.

Datepicker med standard tekststørrelse:
<img width="317" alt="Datepicker med tekst standard størrelse" src="https://github.com/SpareBank1/designsystem/assets/77671758/aac20814-b2d7-41f6-a2f9-92c1f5be8a4b">

Datepicker med tekststørrelse 200%:
<img width="314" alt="Datepicker med tekst 200 prosent størrelse - 1" src="https://github.com/SpareBank1/designsystem/assets/77671758/9680a01a-9c8c-459b-a476-3bc89d0eff15">

<img width="317" alt="Datepicker med tekst 200 prosent størrelse - 2" src="https://github.com/SpareBank1/designsystem/assets/77671758/f0ebc358-f529-42dc-add0-a0fd7a90a72b">

Det er også mulig for kunder/brukere å velge enda større tekststørrelse enn 200% (200% er bare minimumskravet, i loven). Det vil bare forsterke problemet.

### Forslag til løsning
Usikker på hvordan vi best løser denne.

**Comment by pethel** [comment]
Fikset
