### ISSUE TITLE
Situasjonsspesifikke språk attributt på https://design.sparebank1.no/

### ISSUE THREAD

**Issue by SindreSafvenbom** [SpareBank1/designsystem#1847]
Enkelte steder på https://design.sparebank1.no/ bruker vi engelsk språk og ord. Disse må markeres med riktig lang="" attributt for å følge uu-krav

**Comment by tuva-odegard** [comment]
Klarer ikke finne at dette er mulig med gatsby.. Ved stikkprøver ser det ut som at det stort sett er komponentnavn som er på engelsk, resten av testdata er på norsk. Ser tre muligheter, mulig svaret er en kombinasjon

1. Vente til vi får ny documentasjons-teknologi og håpe det kan løses bedre der. 
2. Akseptere at det ikke går og lukke casen 
3. Finne de få tilfellene dette gjelder faktisk testdata (ikke komponentnavn som TableRow, men for eksempel "Primary" i Primary button-teksten på knappen) og forsøke å oppdatere de. Kan bli litt rotete da det også blir en del av dokumentasjon-koden?

@SindreSafvenbom @pethel @antidecaf Noen tanker?
