### ISSUE TITLE
Overflow-issues på knapper

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1849]
Knapper ser jevnt over litt suboptimale ut i mange tilfeller, i etterkant av at fikser for fontskalering har blitt innført. Bør vurdere en litt strammere vurdering av når tekst skal brekke over flere linjer.

![image](https://github.com/SpareBank1/designsystem/assets/463847/a517b69c-0348-4a73-b1c7-e00e0eef2529)

**Comment by pethel** [comment]
Er ikke den som bruker knappen som ordner med flex feks. Att en kolumn krymper men ikke den andre?

**Comment by antidecaf** [comment]
Det samme gjelder i tabeller:

![image](https://github.com/SpareBank1/designsystem/assets/463847/1cdc5085-f81d-48be-a750-68956a5296f8)

**Comment by HeleneKassandra** [comment]
Som Peter sier, her er det vel hvordan man bruker knappene som bestemmer når den knekker?  Samme med tabell, så kan vel brukerne sette på egne klassenavn der de setter min-width osv?   Tenker det er ganske vanskelig for FFE å sette en god standard for når ting skal "knekke"

**Comment by hdaljord** [comment]
Det er ganske mye jobb å gå gjennom alle løsninger man har ved oppgradering til denne versjonen om man skal gå gjennom så å si alle tekstelementer, tabeller og knapper for å "fikse det rundt"...

**Comment by pethel** [comment]
> Det er ganske mye jobb å gå gjennom alle løsninger man har ved oppgradering til denne versjonen om man skal gå gjennom så å si alle tekstelementer, tabeller og knapper for å "fikse det rundt"...

Med all respekt før den jobben som må legges ned. Vad ville alternativet ha vart hvis man skall opfylla lovkravet på 200% text zoom?

**Comment by hdaljord** [comment]
Løsningen vår fungerte fint med 200% text zoom før denne endringen kom i FFE. Noen steder har vi benyttet oss av soft-hyphens for å styre hvor tekst brekker.

**Comment by pethel** [comment]
Knapper og tabell ser bra ut i dokumentasjonen nå. Har endret hvordan knapper brekker og endret lite på dokuemntasjonen av tabellen.
![image](https://github.com/SpareBank1/designsystem/assets/2248579/a132fccd-d794-4eb0-8244-63111f585b22)
![image](https://github.com/SpareBank1/designsystem/assets/2248579/6098494b-3d7e-4176-a01f-a9d6c427233c)
