### ISSUE TITLE
Two button groups aligns on the same line

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#185]
#### Which package is this issue related to?
ffe-buttons

#### Describe your issue (screenshots welcome!)
Given this HTML...
```
<div class="ffe-button-group ffe-button-group--thin">
    <button class="ffe-button ffe-button--primary" type="submit">
        <span class="ffe-button__label">Neste</span>
        <div aria-hidden="true" aria-label="Vennligst vent" class="ffe-button__spinner"></div>
    </button>
</div>
<div class="ffe-button-group ffe-button-group--thin">
    <a class="ffe-inline-button ffe-inline-button--tertiary">
        <span class="ffe-inline-button__label">Avbryt</span>
    </a>
</div>
```
...this is rendered.
![image](https://user-images.githubusercontent.com/435037/38943702-592fc408-4332-11e8-8c7e-2608e7fd244d.png)

#### What is the expected behavior? 
I expect the button group to be a block-level element, and thus the two should not be aligned.

I report this as a question, as I want opinions on how a button group should behave.

#### What is the actual behavior?
The two button groups aligns, instead of breaking into separate lines.

#### Steps to reproduce
The supplied HTML.

**Comment by wkillerud** [comment]
I find it odd to have sibling button groups. What is the use case?

The button group is mainly designed to handle the layout of the buttons inside it, not the outside world. That being said it used to be block level, so I suppose this is a regression.

**Comment by henrikhermansen** [comment]
The use case is simply to place one button above the other, while getting the margins supplied by button group.

It seems wrapping each button group in a `<div>` solves the issue. So if we intend for two button groups to align, that's an acceptable solution for us.

**Comment by ivarni** [comment]
Wasn't the whole point of the button group to ensure the buttons **aren't** aligned vertically on bigger screens?

**Comment by wkillerud** [comment]
We need the button groups to be `inline-flex` on large screens due to #173 (the group takes 100 % width on small screens, so there `flex` is fine). Since wrapping the groups in a `div` is an acceptable workaround I think we can close this issue. Feel free to disagree if there's something I've missed 😉
