### ISSUE TITLE
Fikse manglende padding i Checkbox og RadioButton

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1860]
### Beskrivelse
Ser ut til at paddingen over og under radioknappene og checkboksene (FFE) har forsvunnet med nye endringer. Paddingen skal blant annet gjøre at vi ivaretar WCAG 2.1-retningslinjen på minimum 44x44 px klikkbar flate: https://www.w3.org/WAI/WCAG21/Understanding/target-size.html

#### FFE
![Checkbox i FFE](https://github.com/SpareBank1/designsystem/assets/77671758/b0ccaa72-150e-4ae3-9243-9ee30538e2ff)

![RadioButton i FFE](https://github.com/SpareBank1/designsystem/assets/77671758/0671e244-66af-44ce-ad8e-2d2bd3e5c919)

#### Figma
![Checkbox i Figma](https://github.com/SpareBank1/designsystem/assets/77671758/7d7f0b5f-3189-4981-b073-e738c0395f5c)

![RadioButton i Figma](https://github.com/SpareBank1/designsystem/assets/77671758/ea9e656a-ced0-48b6-bce4-6c8e4eeecc6c)

**Comment by pethel** [comment]
Har avklart att det skall vare padding: 

Før att få det likt figma må radio button .ffe-form-label ha kjennskap til varandra. Annars blir det radio/checkbox sin padding + labeln sin padding. 
![image](https://github.com/SpareBank1/designsystem/assets/2248579/19fbbc6b-c00c-446f-a76d-3e912196f143)

**Comment by pethel** [comment]
Den her burde vare i orden nå
