### ISSUE TITLE
ffe-dropdown: Native expander visible under chevron

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#188]
#### Which package is this issue related to?

ffe-dropdown

#### Describe your issue (screenshots welcome!)

![image](https://user-images.githubusercontent.com/379849/38985962-3efcd8f2-43cb-11e8-9764-3d95667c19b9.png)

The native select expander is visible in [the designguide example](https://design.sparebank1.no/styleguidist/index.html#dropdown)

#### What is the expected behavior? 

The native select expander should be unvisible.

**Comment by wkillerud** [comment]
Will be fixed in 2ff3ddc #184

**Comment by ivarni** [comment]
Ah ok, it was difficult to guess that this would be a duplicate of that from just looking at the issue title :)

**Comment by wkillerud** [comment]
Yeah, it was more that I discovered the same issue while working on something else :sweat_smile:
