### ISSUE TITLE
(DesignforumWorthy) Redesign av ContextMessage, MessageBox, SystemMessage, dark mode

### ISSUE THREAD

**Issue by Frederoche** [SpareBank1/designsystem#1888]
### Beskrivelse
(Beskrivelse kommer)

### Mål
Ikke satt

### Status
Ikke påbegynt

**Comment by pethel** [comment]
Kunde vurderas att gjøras med denne?
https://github.com/SpareBank1/designsystem/issues/917

**Comment by pethel** [comment]
Dette ble ordnet sammen med https://github.com/SpareBank1/designsystem/issues/917
