### ISSUE TITLE
Legge til Sparebank1 org under Sparebank1 Utvikling

### ISSUE THREAD

**Issue by Frederoche** [SpareBank1/designsystem#1891]

**Comment by ThereseBoerter** [comment]
Det er snakk om å flytte alle repo-ene til Designsystem fra Sparebank1 org til Sparebank1Utvikling org, det kan tas etter at gihub migrering er ferdig

**Comment by ThereseBoerter** [comment]
Skal vi fortsette å være Open Source eller ikke? må tas stilling til.

**Comment by ThereseBoerter** [comment]
Vi skal fortsette å være open source.
