### ISSUE TITLE
Vi har kartlagt alle brukere og potensielle brukere av designsystemet i SpareBank 1-alliansen og hvilke løsninger som brukes i dag

### ISSUE THREAD

**Issue by Frederoche** [SpareBank1/designsystem#1893]
Vi har:
 - Sent undersøkelse
 - Hatt møte med BM
 - Hatt møte med Hverdagsøkonomi

**Comment by ThereseBoerter** [comment]
Mangler oversikt oversikt hva de bruker i SB1U Trondheim.

Ta kontakt med Jacob Berg Lund

**Comment by ThereseBoerter** [comment]
Møte med Trondheim tirsdag 23.04
