### ISSUE TITLE
Should our main README.md be in English?

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#19]
Although most of our documentation is in Norwegian, our Github and code language is English. Should we therefore consider translating the README.md and CONTRIBUTING.md documents to English?

**Comment by wkillerud** [comment]
I like having technical documentation in English, but:

- the working language of pretty much 100 % of the design system consumers today is Norwegian
- the primary design system documentation language is Norwegian
- due to the above we allow issues written in Norwegian

Maybe the core documents such as the root README and CONTRIBUTING should stick to Norwegian for now?

**Comment by eirikv** [comment]
I my opinion, I think we should be consistent and use the same language all over. On a positive note, if we go for English might get more people to contribute.

**Comment by selbekk** [comment]
I'm closing this for now, since there isn't a lot of people putting forward their opinions. I'm cool with it staying Norwegian - but the mixing of languages is a bit of a... downer.
