### ISSUE TITLE
ffe-datepicker-react: clicking on the change month causes a focus issue

### ISSUE THREAD

**Issue by ksawerysb1** [SpareBank1/designsystem#190]
#### Which package is this issue related to?
ffe-datepicker-react
#### Describe your issue (screenshots welcome!)
Clicking on one of the change month casues the datepicker to close on next click within datepicker.
#### What is the expected behavior? 
The datepicker should be able to change month multiple times with click input.
#### What is the actual behavior?
The datepicker changes month just once and then closes on next click. There seems to be a focus issue where the next click looks to the blur handler like leaving the datepicker that should close it.
#### Steps to reproduce
Click on change month once, then the second click will close the datepicker on focus (so before we relase the mouse button, just pressing it is enough)

**Comment by wkillerud** [comment]
Seems it may have been introduced in v 3.0.8. 3.0.7 doesn't have this issue.

**Comment by ksawerysb1** [comment]
I created a PR on Friday with a fix. Should be out soon.

**Comment by ksawerysb1** [comment]
Issue was solved in ffe-datepicker-react 3.1.3, closing.
