### ISSUE TITLE
Vurdere andre verktøy enn Gatsby

### ISSUE THREAD

**Issue by ThereseBoerter** [SpareBank1/designsystem#1903]
Gjøre en analyse av andre verktøy:

Storybook
Figma (https://www.figma.com/blog/introducing-code-connect/), https://help.figma.com/hc/en-us/articles/23920389749655-Code-Connect
Docusauras

**Comment by pethel** [comment]
Forslag som blitt nevnt på huset når man frågar runt litt

Storybook
Figma (https://www.figma.com/blog/introducing-code-connect/)
Docusauras

**Comment by ThereseBoerter** [comment]
Vurdere om vi kan bruke Figma - gjøres internt i teamet.

Bestille RFE på Storybook @Frederoche

**Comment by Frederoche** [comment]
Ser videre på Figma Code Connect (Stevie fra hverdagsøkonomi)

**Comment by ThereseBoerter** [comment]
Anita har fått skrevet RFE - venter på avklaring fra Sikkerhet.

**Comment by antidecaf** [comment]
Storybook er godkjent fra Sikkerhet.
Setter det opp på en branch lokalt i designsystemet for å teste og utforske og finne ut mer om hvor godt det passer for oss.

**Comment by ThereseBoerter** [comment]
Undersøke og vurdere Figma Code Connect

**Comment by ThereseBoerter** [comment]
Ta kontakt med posisjon og merkevare. Evt ta kontakt med Figma support. Gjør litt research om de kan være en erstaning for Figma.

https://www.figma.com/developers/code-connect

Kan vi få en demo fra Figma digitalt?

**Comment by ThereseBoerter** [comment]
Parkert frem til vil har hatt demo med Figma.

**Comment by ThereseBoerter** [comment]
Trener et CMS rundt komponenter - @AnitaStoyle  undersøker bruk av Sanity

**Comment by ThereseBoerter** [comment]
Besluttet å bruke Storybook til Komponenter. Lage en egen task på denne. Bruke dagens dokumentasjon med lenk til Storybook.
