### ISSUE TITLE
Expand and collapse account-selector on arrow button click

### ISSUE THREAD

**Issue by TorgeirHeim** [SpareBank1/designsystem#192]
![account-selector](https://user-images.githubusercontent.com/1838311/38997074-e3e47962-43ec-11e8-8e4f-b7c316eba7f6.png)

The account selector does not collapse when the arrow icon is pressed. This is especially annoying in browser where clicking outside an input field doesn't cause the field to loose focus (e.g Safari iOS). The only way to collapse the account-selector is to select an account (or click on an element that can receive focus). 

Does anyone oppose implementing the arrow as a button and expand/collapse on click?

**Comment by wkillerud** [comment]
Huh, yeah that gets pretty annoying. Probably just forgotten during development - it makes sense that it's a toggle. I say go for it 👍 

Not to be a scope creeper 👹, but I see `SearchableDropdown` has the same issue. If you end up working on this issue, would you mind fixing it there as well? 👼
