### ISSUE TITLE
Legge til mulighet for hvit spinner

### ISSUE THREAD

**Issue by MariaOverlierBerg** [SpareBank1/designsystem#1927]
Vi bruker spinneren på farge-vann-bakgrunn, og har en litt hacky måte å overskrive stylinga på som kanskje heller burde bli gjort i designsystemet. Dersom det ikke er kun oss det kunne vært relevant for.

**Comment by pethel** [comment]
![image](https://github.com/SpareBank1/designsystem/assets/2248579/0c2f5579-c471-45f6-a939-438a91f1112d)

**Comment by pethel** [comment]
Har implementert dette
