### ISSUE TITLE
MultiAccountSelector - Velg alle burde være midtstilt

### ISSUE THREAD

**Issue by SaraElisabethIdris** [SpareBank1/designsystem#1935]
"Velg alle" er nå plassert litt høyt, burde kanskje være midtstilt

![Screenshot 2024-04-24 at 14 05 46](https://github.com/SpareBank1/designsystem/assets/141620424/682a625b-e752-4ae3-8491-4811f0359f8a)

**Comment by pethel** [comment]
Mergat fix på denne
