### ISSUE TITLE
Mindre fontstørrelser i Safari

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1948]
Ragnhild og jeg opplever at fontstørrelsene er mindre i Safari. At BodyText f.eks. er 13px i stedet for 16px. Dette bør vi undersøke :)

**Comment by antidecaf** [comment]
Ser ut til at det er denne som overstyrer default font-størrelse. 

<img width="288" alt="image" src="https://github.com/SpareBank1/designsystem/assets/463847/ded5c1a4-c231-4ece-b174-70d655364e39">

Jeg er usikker på hva hensikten med regelen er, men gjetter at det har noe med fontskalering å gjøre.

**Comment by JoakimLindquister** [comment]
Hei! Fjernet ikke denne fiksen hele støtten for tekstskalering på iOS? Nå vil den alltid være 100% selv om bruker har valgt en tekst-zoom i iphone settings.
