### ISSUE TITLE
Legge til alt-tekster for bildene på design.sparebank1.no

### ISSUE THREAD

**Issue by andrea-sb1** [SpareBank1/designsystem#1953]
Oppdatere alt-tekst for bilder på sidene:

- [x] Index
- [x] Kom i gang
- [x] Universell utforming
- [x] Om designsystemet - prinsipper
- [x] FAQ

**Profil**
- [x] Stil og tone
- [x] Farger
- [x] Ikoner
- [x] Typografi
- [x] Spacing
- [x] Illustrasjoner
- [x] Animasjoner
- [x] Former
- [x] Bilder
- [x] Logo
- [x] Theming

**Komponenter**
- [x] Accordion
- [x] Bølge
- [x] Collapse
- [x] Detaljliste
- [x] Diagram
- [x] Faner
- [x] Formatering
- [x] Grid
- [x] Header
- [x] Ikoner
- [x] Knapper
- [x] Kontovelger
- [x] Kort
- [x] Lister
- [x] Meldinger
- [x] Nedtrekkslister
- [x] Skjemaelementer
- [x] Spinnere
- [x] Tabeller
- [x] Tilbakemelding
- [x] Typografi

**Bidra**
- [x] Guide for Figma
- [x] Guide til dokumentering

**Comment by raglie-sb1** [comment]
Finner ikke ut hvordan man kan gi <title> til svg-eksempelene under [animasjon](https://design.sparebank1.no/profil/animasjoner/). Hvor hentes eksemplene inn @antidecaf?

**Comment by raglie-sb1** [comment]
@SindreSafvenbom bekreftet at disse animasjonene ikke trenger beskrivende tekst, så da sier vi oss ferdig med denne.
