### ISSUE TITLE
Add support for bleeding grid column backgrounds

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#197]
#### Which package is this issue related to?
ffe-grid / ffe-grid-react

#### Describe your issue (screenshots welcome!)
Our designs specify a column with a background color - where the background color "bleeds" out into both gutters. This is currently not possible from userland without adding some pretty hefty hacks.

#### What is the requested behavior? 
To be able to specify background colors for columns, and make them fill the surrounding gutters as well. Not sure if we should implement this for small devices too or not.

#### What is the actual behavior?
Currently, there is no built in way to create this behavior from userland without overwriting a ton of CSS rules.

**Comment by wkillerud** [comment]
Do you have any screenshots describing the issue? I'm having trouble picturing it :see_no_evil:

**Comment by selbekk** [comment]
Sorry for the delay - here's one from the documentation:

![image](https://user-images.githubusercontent.com/1307267/39214099-a4b4a066-4813-11e8-9694-2b539cef974e.png)

In addition, there should be some screenshots of the actual design we're implementing, but I don't have access to those until tomorrow morning. I'll make sure to post them asap.
