### ISSUE TITLE
Ønskeliste: Modalvindu

### ISSUE THREAD

**Issue by SindreSafvenbom** [SpareBank1/designsystem#1990]
Første runde blir å velge et designuttryk/funksjonsutvalg fra Ønskelisten slik at vi har et konkret eksempel. Settes som designtask til dette er gjort. Blir deretter overført til Utvikling task

![Image](https://github.com/SpareBank1/designsystem/assets/161836106/a3437e67-9312-4d83-98aa-ca088712a3d3)

- [x] Kode 
- [x] Dokumentasjon
- [x] Figma

**Comment by pethel** [comment]
Kan modalen klare dette også? Det gjør vår hjemmesnikkrade modal. Vi har samme modal i bunn som den vanliga modalen bare presentert annleddes. Vet att ett team til har en slik eller iaf hade uten att jag husker vilket. 

https://www.sparebank1.no/nb/ostlandet/privat/sparing/spare-i-fond/fondsoversikt.html klikke på ett kort her bare

![image](https://github.com/SpareBank1/designsystem/assets/2248579/7404b578-6518-4df9-bcb9-bf5c83cd5379)

**Comment by raglie-sb1** [comment]
Da har jeg publisert Modal-komponenten i [Figma](https://www.figma.com/design/RSfHoXdiZ10nSqj3Cyyo4yIs/branch/nu1tSgasMr0Z5M4NdNxCAF/Profil-og-komponenter?m=auto&node-id=19826-7961&t=M3RxpcnjzAPEEBwA-1). 
Vi burde kanskje ta en gjennomgang sammen @pethel for å bare se om vi dekker det samme :)
