### ISSUE TITLE
Refaktorering av kort

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#1997]
Kort er per i dag lenker by default. Kortene er i sin helhet wrappet i en <a>, noe som skaper en utfordring rundt UU fordi skjermlesere vil lese opp alt innhold som en lenke.

Kortene bør i stedet være implementert som <div>, som i sin tur kan inneholde lenker. Vi kan deretter sørge for at kortene er klikkbare vha JavaScript.

Eksempler:
[Kort i W3 designsystem](https://design-system.w3.org/components/cards.html#block-link-cards)
[Codepen som W3-kortene er basert på](https://codepen.io/vikas-parashar/pen/qBOwMWj)

Vi bør samtidig diskutere hvorvidt kortene skal være klikkbare/lenker som default eller om dette bør være opt-in.

**Comment by pethel** [comment]
Er vell stark knytet till denne https://github.com/SpareBank1/designsystem/issues/1499

**Comment by pethel** [comment]
"Vi bør samtidig diskutere hvorvidt kortene skal være klikkbare/lenker som default eller om dette bør være opt-in." Her er mina tankar att det ikke før vare default. 999 av 1000 kort jag sett burde ikke vart en lenke.
