### ISSUE TITLE
RadioButtonInputGroup buger når man tester elementene i skjemaet

### ISSUE THREAD

**Issue by raglie-sb1** [SpareBank1/designsystem#1998]
Det skjer litt rare ting når man tester skjemaet under RadioButtonInputGroup.
- Før man har klikket så hopper tastaturnavigering over den første gruppen
- Man må klikke to ganger på elementer i den første gruppen for at de skal bli selected
- Når elementer i den første gruppen blir selected, blir også første element i RadioBlock (nederst) også valgt
- Når man velger ett alternativ i gruppe nr 2 (favorittlukt) blir det også valgt elementer i første element RadioGroup og radioBlock også valgt
- Man kan ikke velge andre alternativ (Nei) i RadioBlock. 
- RadioSwitch blir ikke påvirket av problemene

Usikker på om dette er ett problem i bare dokumentasjonen, eller om det er komponentene generelt.

https://design.sparebank1.no/komponenter/skjemaelementer/#radiobuttoninputgroup

![Image](https://github.com/SpareBank1/designsystem/assets/167987263/9671653c-d509-4e8c-b01c-223fbae500b4)

**Comment by pethel** [comment]
Veldig mye av problematiken her er att feltene har samme `name` og er brukt flere ganger på siden. En annen del av problemet var att det manglade kode før att velge. Derfor inget ble valgt. Det gjeller RadioBlock som er hårdkodade til att alltis stå på "Ja"
