### ISSUE TITLE
Consider replacing handlebars with gatsby for static styleguide contents

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#2]
We use Handlebars and a custom setup to generate static content around React Styleguidist for content that is not React component demos and documentation. [Gatsby](https://github.com/gatsbyjs/gatsby) was raised as a suggestion to replace the custom setup.

Use this issue to discuss this suggestion.

**Comment by selbekk** [comment]
Gatsby has an open PR for creating a styleguide-based site - basically what we want. https://github.com/gatsbyjs/gatsby/pull/3304

I'll look into creating a PR for a similar application for us.

**Comment by antidecaf** [comment]
Nice. For now I'll create a PR using handlebars to get an MVP up and running.

**Comment by wkillerud** [comment]
> Gatsby breaks with yarn/lerna workspaces 

https://github.com/gatsbyjs/gatsby/issues/2135

**Comment by wkillerud** [comment]
Experimented a bit with this on localhost using https://github.com/bradfrost/gatsby-style-guide-guide as a base. Unfortunately Gatsby was never made with a Lerna workspace in mind, and breaks on startup :cry: Until that is resolved this is a no-go.
