### ISSUE TITLE
No spacing between tabs in a tab group

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#201]
#### Which package is this issue related to?
ffe-tabs

#### Describe your issue (screenshots welcome!)
In our code we've grouped our tab buttons inside a `ffe-button-group`. Before the rewrite of ffe-buttons the button group added 10px left margin on all `ffe-tab-button` (except the first). After the rewrite of ffe-buttons there's no mention of tab buttons anymore.

This could all be fine, because I see now we have a `TabGroup` which applies the class `ffe-tab-button-group`. This class doesn't actually exist, and the tab group doesn't really do anything.
So the actual problem now is that there's no spacing between tab buttons.
Is this really how it's ment to look? Image from the style guide:
![image](https://user-images.githubusercontent.com/435037/39132387-04a358e4-4712-11e8-8007-cf9fa6eb72c4.png)

#### What is the expected behavior? 
10px (or so) spacing between tab buttons in a tab group.

#### What is the actual behavior?
No spacing between tab buttons, even in a tab group.

#### Steps to reproduce
See for yourself in [our style guide](https://design.sparebank1.no/styleguidist/index.html#tabgroup)

**Comment by selbekk** [comment]
Agree, this is a regression from my rewrite of ffe-buttons. My bad!
