### ISSUE TITLE
Could `RadioSwitch`  accept boolean values?

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#202]
#### Which package is this issue related to?

ffe-radio-button-react

#### Describe your issue (screenshots welcome!)

I'm using `RadioSwitch` for a property that can either "on" or "off" and in my state I prefer working with boolean data types for these kind of things

```javascript
const foo = "false";

if (foo) {
  console.log('oops')
}
```
Is something that *can* happen.

Unfortunately [RadioSwitch](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-radio-button-react/src/RadioSwitch.js#L43) only allows me to pass values as strings, while React supports booleans for inputs values.

I'd like to ask before working on a PR so I don't spend time on something that gets declined, so is it possible to add support for this?

#### What is the expected behavior? 

I'd like to be able to provide values as booleans to radio-buttons instead of using stringeans.

**Comment by selbekk** [comment]
Sounds like a good idea :) Go for it!

**Comment by wkillerud** [comment]
Fixed in #210
