### ISSUE TITLE
(DesignforumWorthy) Ønskeliste: Nytt nivå for feilmelding (oransje)

### ISSUE THREAD

**Issue by raglie-sb1** [SpareBank1/designsystem#2047]
![Image](https://github.com/SpareBank1/designsystem/assets/161836106/1c915782-19a5-4e32-8467-bbca8b4fa23d)

**Comment by pethel** [comment]
Vi har ikke laget en ny type feilmeldning men bruke type tips på melningen og ett eget ikon.
