### ISSUE TITLE
Centered GridCols expands beyond their offset in IE

### ISSUE THREAD

**Issue by nicolhag** [SpareBank1/designsystem#205]
#### Which package is this issue related to?
`ffe-grid-react` and `ffe-grid`
#### Describe your issue (screenshots welcome!)
When a `GridCol` with `div` as content is centered by passing `center={true}`, the specified offset is not taken into account in IE - the content flows beyond the offsets.
#### What is the expected behavior? 
When centering a `GridCol` in IE, I would expect the content to still be aligned with the specified offset.
#### What is the actual behavior?
![screenshot from 2018-04-24 13-17-46](https://user-images.githubusercontent.com/7604910/39184179-bc5cee68-47c2-11e8-8618-49b6f04ac0fc.png)
#### Steps to reproduce
Pass `center={true}` to a `GridCol`, with `offset: 1`, and open it in IE.

**Comment by wkillerud** [comment]
I think this is a [browser issue that you need to work around yourself](https://github.com/philipwalton/flexbugs#flexbug-2) by setting a max-width on the content `div`. 

> When using align-items: center on a flex container in the column direction, the contents of flex item, if too big, will overflow their container in IE 10-11.
Workaround
>
> Most of the time, this can be fixed by simply setting max-width: 100% on the flex item. If the flex item has a padding or border set, you'll also need to make sure to use box-sizing: border-box to account for that space. If the flex item has a margin, using box-sizing alone will not work, so you may need to use a container element with padding instead.

**Comment by selbekk** [comment]
Can't we add max-width to `ffe-grid__column > *`? That would probably solve most issues?

**Comment by wkillerud** [comment]
That could work I suppose. Sounds like a potentially breaking change though.

**Comment by ivarni** [comment]
Why would it be breaking?

**Comment by wkillerud** [comment]
If someone has given a `max-width` to a child of a column we would now be overwriting that value.

**Comment by ivarni** [comment]
I decided to take a look at this and then I realized...
https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-grid/less/ffe-grid.less#L101

We're already setting `max-width`?

**Comment by wkillerud** [comment]
Yes, on the column itself. The workaround is to set it on the children @ivarni.

**Comment by ivarni** [comment]
Aaah, I didn't think of the children!

@nicolhag are you able to test if that fixes this issue?

**Comment by selbekk** [comment]
Now you are @ivarni ;-)

**Comment by antidecaf** [comment]
@ivarni Have you thought of the children yet?

**Comment by ivarni** [comment]
@antidecaf https://github.com/SpareBank1/designsystem/pull/348 😨
