### ISSUE TITLE
Tekst på knapper innenfor en RadioInputGroup arver fontstyling fra label 

### ISSUE THREAD

**Issue by hagenek** [SpareBank1/designsystem#2076]
Tekst på knapper innenfor en RadioInputGroup arver fontstyling fra label 

```ts    
  <RadioButtonInputGroup
        label={<StrongText>{`${text('FOLKEREGISTER_TEXT_LABEL')} ${name}?`}</StrongText>}
        name="shareAccessWithPartner"
        selectedValue={shareAccessWithPartner.value}
        onChange={onChange}
      >
        {(inputProps) => (
          <div>
            <RadioSwitch
              leftLabel={text('ACCESS_YES') as string}
              leftValue={'Yes'}
              rightLabel={text('ACCESS_NO') as string}
              rightValue={'No'}
              {...inputProps}
            />
            <InfoAboutShareAction shareAccessWithPartner={shareAccessWithPartner.value} />
          </div>
        )}
      </RadioButtonInputGroup>
```

**Forventet oppførsel**

Styling skal kun bli påført label. 

**Skjermskudd**

![Screenshot 2024-06-10 at 16 22 15](https://github.com/SpareBank1/designsystem/assets/31440138/d9fd770c-99f7-49d7-8ab2-7fa699e82e5c)

**Comment by antidecaf** [comment]
Hei! Jeg trenger en utdypning på hva som egentlig er bugen her. Hvilken styling arves fra hvilken label? Selve RadioSwitchen er implementert som et label-element så vidt jeg kan se, men jeg kan ikke se at det arver noe fra `.ffe-form-label` sånn umiddelbart.

**Comment by hagenek** [comment]
Aha, her ser jeg at jeg har misforstått. Radioswitchen har faktisk bold text styling som default. Det arves ikke, men er satt i komponenten. Jeg hadde en figma skisse hvor skriften ikke var bold, derfor jeg ble forvirret.
