### ISSUE TITLE
Different left padding of input field and dropdown

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#208]
#### Which package is this issue related to?
ffe-form

#### Describe your issue (screenshots welcome!)
`.ffe-input-field` has a left padding of 13px while `.ffe-dropdown` has a left padding of 10px.

#### What is the expected behavior? 
I expect input fields and dropdowns to have the same left paddings for proper form alignment.

#### What is the actual behavior?
Input fields and dropdowns have different left paddings which gives uneven form alignment.

**Comment by hodoea** [comment]
I don´t see it @henrikhermansen ...What exactly do you mean by left-padding? 
<img width="1166" alt="skjermbilde 2018-04-26 kl 10 28 26" src="https://user-images.githubusercontent.com/8971560/39294696-a7368a82-493c-11e8-81a9-f71ddcc96331.png">

**Comment by henrikhermansen** [comment]
I'm sorry, @hodoea , I should've supplied a screenshot to clearify.

Padding is the distance between the border and the text inside the field.

In this image "Velg fond" is a searchable dropdown (which uses `.ffe-dropdown`) with 10px between border and text, while "Beløp" is a normal input (with `.ffe-input-field`) with 13px between border and text.
![image](https://user-images.githubusercontent.com/435037/39348972-84b19520-49f9-11e8-9ac2-7f72f41e750a.png)

**Comment by wkillerud** [comment]
_How_ did you notice this? :male_detective: :smile: Agree that this should be consistent.

**Comment by henrikhermansen** [comment]
Haha, good question @wkillerud  :smiley: 
[The removal of `.ffe-dropdown`](https://github.com/SpareBank1/designsystem/pull/194/files#diff-365f7a8e56da589a3a56475dceb71a4bL75) from `ffe-account-selector-react` caused a visual regression in our gemini tests.

**Comment by hodoea** [comment]
Can you change it to 13 px same as ffe-input-field? :) @henrikhermansen
