### ISSUE TITLE
Overflødig padding i feedback-komponent

### ISSUE THREAD

**Issue by MariaOverlierBerg** [SpareBank1/designsystem#2092]
Hei! 

Etter det har blitt lagt på ekstra padding i InputGroup ser det ut som det blir litt vel mye padding i feedback-komponenten. Kanskje det ikke lenger trengs padding på knappene.

Ellers er det også ulik padding rundt hele feedbacken, så når vi wrapper det inn i et card, så blir ikke paddingen lik rundt hele. Men dette er ikke så nøye. Bare en liten observasjon.

![Skjermbilde 2024-06-17 kl  16 46 48](https://github.com/SpareBank1/designsystem/assets/58166609/60f206f3-f62f-4b76-a0ca-5be70391266f)![Skjermbilde 2024-06-17 kl  16 47 01](https://github.com/SpareBank1/designsystem/assets/58166609/78574d6c-e6b2-478b-84fd-db882542c478)

**Comment by tuva-odegard** [comment]
Fikset ved å endre rekkefølge på css imports 👍
