### ISSUE TITLE
Feil dokumentasjonen av InputGroup

### ISSUE THREAD

**Issue by hagenek** [SpareBank1/designsystem#2097]
Fra kode i eksempel: https://github.com/SpareBank1/designsystem/blob/develop/component-overview/examples/form/InputGroup-extraMarginFalse.jsx
            
```
            <InputGroup
                extraMargin={false}
                label="Telefonnummer"
                tooltip="Vi bruker telefonnummer for å sende deg kvittering på SMS"
                fieldMessage={showErrors ? 'Ugyldig telefonnummer' : null}
            >
```
            
            Gir typefeil.
            
`       fieldMessage={showErrors ? 'Ugyldig telefonnummer' : undefiined}
`       
       Gir ikke typefeil.

**Comment by tuva-odegard** [comment]
@hagenek Takk for inspill! Vi fikset det ved å også tillate null, ikke bare oppdatere dokumentasjonen 😄
