### ISSUE TITLE
DatePicker lar deg ikke velge dato med datovelger når skjermleser er aktiv

### ISSUE THREAD

**Issue by SindreSafvenbom** [SpareBank1/designsystem#2109]
DatePicker fungerer fint med tastaturnavigasjon og interaksjon, men av en eller annen grunn ikke når skjermleser er aktivert.

**Comment by tuva-odegard** [comment]
Ser ut som det fungerer som det skal 💯  (bekreftet med Sindre). Mulig det var React-bump eller noe som gjorde susen.
