### ISSUE TITLE
Make the status label of cards dynamic width

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#211]
#### Which package is this issue related to?
ffe-cards

#### Describe your issue (screenshots welcome!)

Currently:

![image](https://user-images.githubusercontent.com/1307267/39364400-2606f530-4a2e-11e8-9187-acdc96c68db6.png)

This is too wide and looks weird.

#### What is the expected behavior? 

Make the background color of the status text centered like now, but only 10 pixels wider than the text: 

![image](https://user-images.githubusercontent.com/1307267/39364487-6a613592-4a2e-11e8-9a83-6e146c1b4e12.png)

**Comment by wkillerud** [comment]
> This is too wide and looks weird.

Personally I like it better than the dynamic width alternative :man_shrugging:

**Comment by ivarni** [comment]
I'm with @wkillerud on that. I think this is going to look even wierderer when there are several different stati in the same list of cards and they all get different width backgrounds.

**Comment by selbekk** [comment]
The devs are rising up against us @adidick ! Whatcha think - should we consider keeping it as is?

**Comment by adidick-zz** [comment]
Interesting. What I think is weird is that we have a big half-empty block of beige that takes up space and reduces the effect of the other details in the card that are arguably more important. I think this is something I should probably take back to the drawing board (as the existing solution was a quick and dirty one from way back) and take a look at it from a broader perspective. There are plenty of other situations where this kind of status will be needed so I think they should all be taken into consideration so we can come up with something that works better. I have seen other examples of status that use a coloured circle that for example could work better here aligned with the text. I'll investigate and come back with something when I get the chance. In the meantime, I think we should set this one on ice.

**Comment by adidick-zz** [comment]
Also, do you guys have a list of all of the possible status alternative that exist currently that I can use to test out some new ideas?

**Comment by wkillerud** [comment]
Some other cases that I can remember:

* Start date for insurances if in the future (for instance "GJELDER FRA 01.07.2018")
* The text "MIDLERTIDIG" if there is a pending health declaration
* The text "FORNYES" if the insurance is in renewal

**Comment by selbekk** [comment]
Closing this for now, as we're looking at a full redesign of these cards.

**Comment by ivarni** [comment]
Why is that a reason to close it? If anything it makes it more relevant...

**Comment by selbekk** [comment]
This issue was made as a simple "todo" for when me and Adi worked together on tweaking designs. There is a different issue for the redesign of cards, which this should factor into imo.

**Comment by ivarni** [comment]
I don't see this issue being referenced from any other issues though, perhaps you can create that link so this doesn't get lost in the sands of time?

**Comment by selbekk** [comment]
Sure. Closed due to the redesign issue #260
