### ISSUE TITLE
Ønskeliste: Paginering

### ISSUE THREAD

**Issue by tuva-odegard** [SpareBank1/designsystem#2112]
![Image](https://github.com/SpareBank1/designsystem/assets/161836106/f3121f96-80a2-4f65-ab8f-21d680a2749c)

Team BM Betaling har kommet med forslag om paginering 
Ser det har kommet et forslag under, usikker på hvem det er fra. 

Kan lages som et førsteutkast, men må nok diskuteres mer med BM betaling

- [x] Kode 
- [x] Dokumentasjon
- [x] Figma

**Comment by raglie-sb1** [comment]
Liten misforståelse her rundt hvem som har laget forslag, men det er ikke fra oss i teamet. 
Vi burde ta en runde på behov og retningslinjer for bruk før lansering. 
HØ bruker infinte scroll, og sier at de egentlig ikke har behov for paginering. 
Kan se at BM har større behov for å linke til en konkret side i en liste med transaksjoner.

**Comment by raglie-sb1** [comment]
Dokumentasjon for paginering i designsystemet.no
https://storybook.designsystemet.no/?path=/docs/komponenter-pagination--docs

**Comment by raglie-sb1** [comment]
Opprettet en branch for komponenten i Figma
https://www.figma.com/design/RSfHoXdiZ10nSqj3Cyyo4yIs/branch/nu1tSgasMr0Z5M4NdNxCAF/Profil-og-komponenter?m=auto&node-id=19680-2191&t=zF0ljYxZbz8sCwLf-1
