### ISSUE TITLE
Ønskeliste - GroupCard

### ISSUE THREAD

**Issue by tuva-odegard** [SpareBank1/designsystem#2116]
Team boligreisen har [meldt inn ønske om](https://www.figma.com/design/uSg1Lz02to7HEZNzqBqi3p/%C3%98nskeliste?m=auto&node-id=2331-46078&t=xYq5HTN73kVsBqRe-1) et sammenslått design av card, altså en gruppe med kort 

![Image](https://github.com/SpareBank1/designsystem/assets/155720728/19f6743e-4598-4a0b-8603-2694ffeb8b07)

De har laget en komponent som vi kan se på for å bygge det

- [ ] Komponent
- [x] Figma
- [ ] Dokumentasjon

**Comment by pethel** [comment]
Vi har også denne så fint att få inn!
![image](https://github.com/SpareBank1/designsystem/assets/2248579/23c2b149-37f8-4597-b8b5-27c695882e6f)
Vi har også denne varianten
![image](https://github.com/SpareBank1/designsystem/assets/2248579/4d33e8eb-b989-4390-8a1b-db9508dc8726)

**Comment by HeleneKassandra** [comment]
Sterkt ønsket av oss i PM Oversikt også!

**Comment by MariaOverlierBerg** [comment]
Sterkt ønske av oss i PM Betaling også! 🤩 Har en egen som vi bruker i forfall, historikk, faste avtaler, mottakere og AvtaleGiro. Ganske lik oversikt sin. 😊 
![Skjermbilde 2024-07-17 kl  16 03 24](https://github.com/user-attachments/assets/5f0b13e6-b122-45cd-85ce-281060cd4227)
![Skjermbilde 2024-07-17 kl  16 06 10](https://github.com/user-attachments/assets/b5e5a497-9b8d-4b36-9624-0bb43bb88264)
![Skjermbilde 2024-07-17 kl  16 06 26](https://github.com/user-attachments/assets/502eefae-cc53-4a35-ab49-1d3f46cc6c58)

**Comment by raglie-sb1** [comment]
Da er denne ferdig og publisert i Figma.
