### ISSUE TITLE
AccountSelector får ikke kontovalgene lest opp med skjermleser

### ISSUE THREAD

**Issue by SindreSafvenbom** [SpareBank1/designsystem#2132]
Kontoalternativene i dropdown menyen blir ikke lest opp av skjermleser

![Image](https://github.com/SpareBank1/designsystem/assets/161836106/d5c78027-2728-412c-9eeb-62ff38e32828)

**Comment by tuva-odegard** [comment]
Etter masse research med både Sindre og Peter: 
Tydeligvis er Safari problemet. 
Man kan få opp søkeresultatene hvis man skriver inn noe, men ikke før man skriver noe. Vi har testet mange forskjellige designsystem, og de oppfører seg likt.
