### ISSUE TITLE
Kunne DetailsCard hatt bakgrunn @ffe-grey-charcoal-darkmode i stedet for @ffe-farge-natt på darkmode?

### ISSUE THREAD

**Issue by MariaOverlierBerg** [SpareBank1/designsystem#2137]
På betalingssidene våre bruker vi @ffe-grey-charcoal-darkmode i lister og cards og diverse, og ser at blant annet oversikt også gjør dette. Hadde det vært mulig å brukt den på DetailListCard-komponenten i @sb1/ffe-lists-react? Det blir hvert fall litt mindre konsekvent på sidene våre når vi har tatt den i bruk. 

![Skjermbilde 2024-07-01 kl  10 46 53](https://github.com/SpareBank1/designsystem/assets/58166609/f2a8106e-eb40-4741-8a3e-ffa18d5ea509)![Skjermbilde 2024-07-01 kl  10 42 48](https://github.com/SpareBank1/designsystem/assets/58166609/b0b4b42d-bc62-44ba-bec1-32900d4da6c2)![Skjermbilde 2024-07-01 kl  10 42 59](https://github.com/SpareBank1/designsystem/assets/58166609/f4b4423d-c0b6-4cec-a266-23012046d342)![Skjermbilde 2024-07-01 kl  10 43 10](https://github.com/SpareBank1/designsystem/assets/58166609/703be7db-732d-4359-92bd-f4fdc454c11c)

**Comment by pethel** [comment]
Takk før att du spør. Den blå versionen er vad som ligger i figma så dette må vell bli ett spørsmål før design da.

**Comment by MariaOverlierBerg** [comment]
Burde jeg legge dette inn i ønskelista i figma i stedet? 😊

**Comment by antidecaf** [comment]
`@ffe-grey-charcoal(-darkmode)` hører til den gamle fargepaletten og bør helst ikke brukes. Fargen er egentlig kun fortsatt tilgjengelig i og med at den er deprecated og ikke fullt ut slettet ennå. Det samme gjelder alle farger som _ikke_ starter på `@ffe-farge` i [colors.less](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-core/less/colors.less). Så velg gjerne en av fargene fra [den nåværende paletten](https://design.sparebank1.no/profil/farger/), om noe. :)

**Comment by MariaOverlierBerg** [comment]
Aha! Skjønner! 😄  Da går vi nok for @ffe-farge-koksgraa som ligner mest. Vi brukte farge-natt før, men etter prat med desginer, synes vi det ser best ut med en lysere svart / mørkere grå enn mørkeblå på darkmode. 😊

**Comment by HeleneKassandra** [comment]
Jeg legger til grey-charcoal som ett farge alternativ i detailListCard i darkmode, den er som Anders sier en gammel farge og bør egentlig ikke brukes, men siden vi mangler retningslinjer og alternativer i darkmode.  Så legger jeg den til uansett, sånn at vi får hvertfall byttet over til denne komponenten, også får vi heller fjerne fargen senere når man har retningslinjer
