### ISSUE TITLE
Ny komponent til Figma: Illustration Card

### ISSUE THREAD

**Issue by tuva-odegard** [SpareBank1/designsystem#2138]
https://www.figma.com/design/uSg1Lz02to7HEZNzqBqi3p/%C3%98nskeliste?m=auto&node-id=2331-16615&t=7Yj3Yzbey88hy2Ux-1
Illustration Card
Har blitt utviklet (#2136), så den må legges inn som en mulighet i Figma også

**Comment by tuva-odegard** [comment]
Setter til medium i stedet for low siden komponenten allerede er laget og pushet og dokumentasjonen er ute

**Comment by raglie-sb1** [comment]
Har en teknisk utfordring i Figma med å bruke illustrasjoner fra illustrasjonsbiblioteket inn i IllustrationCard da Figma håndterer dårlig
- å skalere en illustrasjon med riktig Aspect ratio
- å bytte illustrasjon med en annen illustrasjon med annen størrelse (gir feil dimensjoner og blir strukket/krympet etc)

Vi kan bare late som at dette ikke er vårt (men designeres som bytter illustrasjon sitt) problem og lansere kortet og vente på at Figma kommer med en fiks for aspect ratio (kanskje om ett år?), eller så må vi lage en png-versjon av alle svg-ene i illustrasjons-biblioteket. Da de kan skaleres. Dette fikser forsåvidt bare første problemet.
