### ISSUE TITLE
Tekst usynlig ved hover på shortcutButton I darkmode

### ISSUE THREAD

**Issue by raglie-sb1** [SpareBank1/designsystem#2169]
https://sparebank1.github.io/designsystem/buttons_ShortcutButton

![Image](https://github.com/user-attachments/assets/df66c907-f15a-496f-a58a-66c13081296e)

**Comment by antidecaf** [comment]
Hvilken browser og OS? Fargen ser ikke helt riktig ut i screenshotet ditt, så lurer på om det er noe spesielt i eksempelet? F.eks en eller annen aktiv css-overstyring via inspektoren eller noe lignende. Testet akkurat med Chrome, Safari og Edge på Mac, og teksten er synlig for meg i alle tilfeller.

<img width="341" alt="image" src="https://github.com/user-attachments/assets/cf11baec-2984-473d-ae97-8c83bb9b4edd">

**Comment by tuva-odegard** [comment]
ahhh jeg tror jeg har funnet det ut: hoveren fungerer ikke ordentlig når man toggler på darkmode, men har lightmode på i browseren. Hvis jeg skrur på dark mode i browseren, som du sikkert har gjort Anders, så fungerer det som det skal. Regner vi det som godt nok og kan lukkes? Det er vel ikke noe scenario hvor man skal ha dark mode uten å sette dark mode, eller?

**Comment by tuva-odegard** [comment]
Løsningen er en opprydding i fargevariablene som blir brukt. Blir mest sannsynlig løst når vi bruker semantiske farger.

**Comment by ThereseBoerter** [comment]
Lukker denne saken da den vil bli løst av https://github.com/orgs/SpareBank1/projects/4/views/1?pane=issue&itemId=46210196
