### ISSUE TITLE
Buttons in an inline button group doesn't align text correctly

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#219]
#### Which package is this issue related to?
ffe-buttons

#### Describe your issue (screenshots welcome!)
When wrapping buttons in an inline button group styled anchor tags doesn't get vertically aligned text.
The problem is only visible if some other button in the button group has text which is wrapped to two lines.
![image](https://user-images.githubusercontent.com/435037/39510637-a74273e4-4dea-11e8-8554-6dee97790c2b.png)
The first and the last buttons are actually anchor tags. See supplied HTML.

I don't know if the same is true for other buttons than secondary, but I would assume it's at least true for all `ffe-button`s.

Note that this issue specifically applies to inline button groups. Non-inline groups works as intended.

#### What is the expected behavior? 
Text should be aligned the same whether it's an anchor or a button that's styled...

#### What is the actual behavior?
...but it's not :P 

#### Steps to reproduce
```
<div class="ffe-button-group ffe-button-group--inline">
    <a class="ffe-button ffe-button--secondary ffe-button--condensed" href="/some-url">
        <span class="ffe-button__label">Endre</span>
        <div aria-hidden="true" aria-label="Vennligst vent" class="ffe-button__spinner"></div>
    </a>
    <button class="ffe-button ffe-button--secondary ffe-button--condensed">
        <span class="ffe-button__label">Stopp</span>
        <div aria-hidden="true" aria-label="Vennligst vent" class="ffe-button__spinner"></div>
    </button>
    <button class="ffe-button ffe-button--secondary ffe-button--condensed">
        <span class="ffe-button__label">Slett</span>
        <div aria-hidden="true" aria-label="Vennligst vent" class="ffe-button__spinner"></div>
    </button>
    <a class="ffe-button ffe-button--secondary ffe-button--condensed" href="/some-other-url">
        <span class="ffe-button__label">Flytt til aksjesparekonto</span>
        <div aria-hidden="true" aria-label="Vennligst vent" class="ffe-button__spinner"></div>
    </a>
</div>
```

**Comment by selbekk** [comment]
Definitely a bug - but button text should not wrap!

**Comment by henrikhermansen** [comment]
What's more is `tertiary` buttons doesn't look good in an inline group either.
Just have a look in [the designguide](https://design.sparebank1.no/styleguidist/index.html#!/ButtonGroup/5)

PS! Don't mind the second row, it's actually a `thin` button group, not an `inline` one. My bad!

**Comment by selbekk** [comment]
What's the status here @henrikhermansen ? if you're no longer working on this, you might want to de-assign yourself :)

**Comment by henrikhermansen** [comment]
@selbekk I unassigned the same day I assigned myself. I haven't been assigned to this for 24 days ;)

**Comment by selbekk** [comment]
Aha! Sorry, I must have misread the overview page then. Carry on!
