### ISSUE TITLE
Oppdatering IconCard for right-aligned ikon

### ISSUE THREAD

**Issue by SindreSafvenbom** [SpareBank1/designsystem#2196]
Kommet inn et ønske om å oppdatere IconCard komponenten med right-aligned ikon for å gjøre komponenten mer anvendbar.

Alf Bjørn Hustoft tilbyr seg å bidra med PR slik at vi bare trenger å kvalitetssikre.

- [x] Komponenten oppdateres også i Figma for å tilrettelegge for endringen.

**Comment by raglie-sb1** [comment]
Denne bør utvides til å gjelde alle korttyper (muligens unntatt imageCard). 
I ønskelista er det lagt inn flere eksempler på Group card hvor man har ikon til høyre. 

![Image](https://github.com/user-attachments/assets/206d42bf-c50c-4c5c-b2be-929c247ca8e4)

**Comment by raglie-sb1** [comment]
Andre eksempler fra @pethel 

![Image](https://github.com/user-attachments/assets/1e296e4d-c67f-4770-a791-b4be4da86f9a)
![Image](https://github.com/user-attachments/assets/67970f3e-7a89-4a7f-8d22-d43f95207359)
![Image](https://github.com/user-attachments/assets/6b015f86-6fdb-4c13-b42c-5802c69e0131)

**Comment by raglie-sb1** [comment]
Jeg har gjort denne som en del av de andre kort-endringene jeg har holdt på med denne uka. 
Publiseres mest sannsynlig i morgen.
