### ISSUE TITLE
ffe-message-box(-react): 'action' variant

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#22]
In [ffe-message-box](https://github.com/SpareBank1/designsystem/blob/b33dd658781bcffe5ddbf64957b8f9df89ea6a94/packages/ffe-message-box/less/ffe-message-box.less#L24) we have a version called `action` but it's not implemented in the React world. Is it a version we need, or can it perhaps be removed?

**Comment by selbekk** [comment]
@adidick and @hodoea - what do you think?

**Comment by selbekk** [comment]
@wkillerud the code says "action", not "active". Typo?

**Comment by adidick-zz** [comment]
I've never used a grey message box so it's possibly not needed. If it's not implemented in the React world that probably means it's not anywhere either, right? Which means we probably can't search for it in use. A grey version of the message box doesn't exist in the sketch template so I'm not sure how how it ended up here and what it should be used for.

**Comment by selbekk** [comment]
It looks like this: 

![image](https://user-images.githubusercontent.com/1307267/36721377-08789c28-1bab-11e8-9c55-e47a2e152b35.png)

It's not used a lot (but a few places) internally, so it can probably be removed in the next major of ffe-message-box, especially if there's no use for it and it breaks with design guidelines.

**Comment by adidick-zz** [comment]
Yeah, that looks like it does the same things as a blue info box, so unless someone else has a good reason to use it we can surely throw it out.

**Comment by adidick-zz** [comment]
@selbekk I've posted in the graphic design channel on Slack to see if there's anyone else who knows where it came from.

**Comment by selbekk** [comment]
Thanks! I noticed that it was in use on the kundeklienter BM team - hope that helps!

**Comment by hodoea** [comment]
Regarding the team ´kundeklienter BM´. Are we talking insurance or bank? @selbekk So far no one has replied in the GD-forum channel regarding its usage..

**Comment by selbekk** [comment]
This is the forsikring team, as far as I could tell.

**Comment by selbekk** [comment]
Should we deprecate and later remove the `--action` modifier then @adidick @hodoea ? Consumers should use the `tips` modifier instead?

**Comment by adidick-zz** [comment]
It seems like it's something that's not in use or at least in principle shouldn't have a use. Since we haven't heard from anyone else about I'm happy if you remove it.

**Comment by hodoea** [comment]
@espenvoll @sirioc @christofferaunesb1 @helenetho @heilysto @chribran1  @mario-pereira
SE HER #test (dette er ikke svar på issuet men en test for å tagge nye brukere av Github :P )

**Comment by sirioc** [comment]
OK

**Comment by christofferaunesb1** [comment]
OK

**Comment by espenvoll** [comment]
OK

**Comment by Heilysto** [comment]
Ok, mottatt! Regner med det kommer en lenke til issue her også?


Fra: Hodo Elmi Aden <notifications@github.com<mailto:notifications@github.com>>
Svar til: SpareBank1/designsystem <reply@reply.github.com<mailto:reply@reply.github.com>>
Dato: fredag 9. mars 2018 10.52
Til: SpareBank1/designsystem <designsystem@noreply.github.com<mailto:designsystem@noreply.github.com>>
Kopi: Heidi Lyngvær Stolen <heidi.stolen@sparebank1.no<mailto:heidi.stolen@sparebank1.no>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Emne: Re: [SpareBank1/designsystem] ffe-message-box(-react): 'action' variant (#22)


@espenvoll<https://github.com/espenvoll> @sirioc<https://github.com/sirioc> @christofferaunesb1<https://github.com/christofferaunesb1> @Helenetho<https://github.com/helenetho> @Heilysto<https://github.com/heilysto>@ChriBran1<https://github.com/chribran1> Hva tenker dere om denne?

**Comment by ChriBran1** [comment]
Aight
Med vennlig hilsen,
Christian Brandt

Grafisk Designer
Designavdelingen SpareBank 1 Banksamarbeidet
e-post: christian.brandt@sparebank1.no<mailto:siri.corneliussen@sparebank1.no>
tel: 967 06 649

Fra: Hodo Elmi Aden <notifications@github.com<mailto:notifications@github.com>>
Svar til: SpareBank1/designsystem <reply@reply.github.com<mailto:reply@reply.github.com>>
Dato: fredag 9. mars 2018 10.52
Til: SpareBank1/designsystem <designsystem@noreply.github.com<mailto:designsystem@noreply.github.com>>
Kopi: Christian Brandt <christian.brandt@sparebank1.no<mailto:christian.brandt@sparebank1.no>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Emne: Re: [SpareBank1/designsystem] ffe-message-box(-react): 'action' variant (#22)


@espenvoll<https://github.com/espenvoll> @sirioc<https://github.com/sirioc> @christofferaunesb1<https://github.com/christofferaunesb1> @Helenetho<https://github.com/helenetho> @Heilysto<https://github.com/heilysto>@ChriBran1<https://github.com/chribran1> Hva tenker dere om denne?

**Comment by sirioc** [comment]
@Heilysto

**Comment by hodoea** [comment]
@Heilysto @ChriBran1

**Comment by mario-pereira** [comment]
OK

**Comment by hodoea** [comment]
@Heilysto

**Comment by hodoea** [comment]
@ChriBran1

**Comment by hodoea** [comment]
@Heilysto @ChriBran1 TEST

**Comment by hodoea** [comment]
@helenetho

**Comment by Helenetho** [comment]
hi ppl

**Comment by hodoea** [comment]
@krisoren test

**Comment by Krisoren** [comment]
@hodoea test tilbake
