### ISSUE TITLE
Modal fungerer ikke serverside

### ISSUE THREAD

**Issue by olemartin** [SpareBank1/designsystem#2221]
**Beskrivelse av feilen**
Får `document is not defined` når vi bruker Modal serverside

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen:
Kjører kode som bruker Modal serverside

**Forventet oppførsel**
Modalen bør håndtere at document og/eller window er utilgjengelig.

**Comment by pethel** [comment]
https://github.com/SpareBank1/designsystem/pull/2223

**Comment by pethel** [comment]
Har mergat PR. Issue er opent i venten på verifikasjon att allt er i orden

**Comment by pethel** [comment]
Denne har blitt verifisert nå
