### ISSUE TITLE
Farge for text på secondary-, shortcut- og expand-knapper er flyttet

### ISSUE THREAD

**Issue by henninghuseby** [SpareBank1/designsystem#2250]
**Beskrivelse av feilen**
Endring i spesifisitet i [ffe-buttons](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-buttons/less/base-button.less#L109) gjør det veldig vanskelig å overstyre tekstfarge for secondary-, shortcut- og expand-knapper uten å referere til ffe-klasser i vår egen styling.  Ser ut som om det ble introdusert i [19.0.1](https://github.com/SpareBank1/designsystem/commit/3efcf675caa97cd765109e1968e57216ce0f5cd0#diff-02c625d4102c6b006da7b5b88d1fb63bec57ab87db6116d4cf84345b59f7f608R108).

**Steg for å gjenprodusere**
Før oppgradering til 19.0.2:
![image](https://github.com/user-attachments/assets/d13ced5c-4054-4ae9-9453-e70ef790d204)

Etter oppgradering til 19.0.2:
![image](https://github.com/user-attachments/assets/360170f3-0633-41ea-9311-1f26aa5ed438)

**Comment by pethel** [comment]
Vi skall gjøre vårt beste før att løsa dette med `:where` men grunden til att dette skjer knapparna består av flere elementer og olika modifiers. Man vill alltså måtta bruke (0,2,0) i spesifitet som egentligen ikke er spesiellt mye.  Osikker på vart fargen kom fra før den endringen vi gjorde men hvis dere provat att bytte farge på ett ikon i feks taskbutton vill dere støtt på samma sak som dere gjør nå.

Farger arves ikke og i tillegg kan man vilja ha olika farger på feks ett ikon i samme knapp. 
```
.ffe-button--primary {
   .ffe-button__label {
        color: red;
    }
}

.ffe-button--action {
    .ffe-button__label {
        color:  blue;
    }
}

````

**Comment by pethel** [comment]
Hvis det var markupen og ett extra element kring "label" som var problemet må vi nok dessverre si att det er en implementasjonsdetalj som omgivningen ikke skall trenga att forholde seg til. Jag skjønner att dette ikke er vad man ønsker høra men det  blir vannsklig(ofta omulig) att laga komponenter der allt kan styra med en klasse fra top. Det går vell på buttons kanske, men da kun texten og ikke ikoner og slik men vad med lite mer kompliserade komponenter som InputGroup eller vad som helst egentligen som inneholder ett par elementer. 

Men vi jobbar mot att få på plats slik att alla komponenter skall kunna vara på coloredBg men vi er ikke der helt enda. 
Oavsett, hur som helst. Takk før att dere påpekade detta.
