### ISSUE TITLE
Tests for formatPercentage in ffe-formatters fail under certain conditions

### ISSUE THREAD

**Issue by kwltrs** [SpareBank1/designsystem#23]
Two test cases of ffe-formatter fail on certain yet to be discovered conditions on two machines in my possession (Linux + Mac). It seems Number.toLocaleString prefixes negative numbers with either an hyphen minus (char code 45) or a minus sign (char code 8722), whereas the later causes the test to break.

https://github.com/SpareBank1/designsystem/blob/209c8f5d7d7e6d1d19d308b779fe35b75338016c/packages/ffe-formatters/src/formatPercentage.spec.js#L17

https://github.com/SpareBank1/designsystem/blob/3e3cff94ade0f398dc24f22c0df75a9d34d62c69/packages/ffe-formatters/src/formatPercentage.spec.js#L33-L35

https://github.com/SpareBank1/designsystem/blob/209c8f5d7d7e6d1d19d308b779fe35b75338016c/packages/ffe-formatters/src/formatPercentage.js#L12-L15

**Comment by wkillerud** [comment]
What locale do you have set on those machines?

**Comment by kwltrs** [comment]
en-US, but should it matter as toLocaleString gets called with nb-NO?

**Comment by selbekk** [comment]
are you running the same version of node on both machines? In that case, which version are you running?

**Comment by kwltrs** [comment]
v9.6.1 and v8.9.1. I've had this problem before, but chose to ignore it as it was on my private machine and it seemed to work everywhere else.

**Comment by selbekk** [comment]
Could it be due to differences in the way node implements `Date.prototype.toLocaleString`?
