### ISSUE TITLE
classnames is wrongly declared as a devDependency in ffe-form-react

### ISSUE THREAD

**Issue by paandahl** [SpareBank1/designsystem#232]
#### Describe your issue (screenshots welcome!)

In the `package.json` of ffe-form-react, `classnames` is described as a devDependency. It is however imported and used directly in components, so the build will fail if it's not in place.

I think this dependency should be changed either to a normal dependency (for bundling) or to a peer dependency (to flag to the user that the lib should be provided by the including project).

BR, Preben Ludviksen, Team Finansiering

**Comment by wkillerud** [comment]
Yes, sounds to me like it should be a direct dependency :)

**Comment by selbekk** [comment]
Seems like a bug. I'll fix it =)
