### ISSUE TITLE
Manglene info i README.md til ffe-tables 

### ISSUE THREAD

**Issue by henninghuseby** [SpareBank1/designsystem#2386]
**Beskrivelse av feilen**
Det mangler informasjon i [README.md](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-tables/README.md) til ffe-tabels om at en også må importere [less fila til ffe-collaps-react](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-collapse-react/less/collapse.less) for å få "Ekspanderbare rader" til å fungere riktig

**Comment by pethel** [comment]
Hei, takk før att du melder. 

Dette er dokumentert i ffe-table-react , alltså react pakken. Det ble tatt up på sista frontendtechmøte og ble føreslått att vi legger det i react pakken og ikke less-pakken. 

![image](https://github.com/user-attachments/assets/641b11d5-4870-4a82-bb2f-835861f714bc)
