### ISSUE TITLE
Midstilling tekst i chip

### ISSUE THREAD

**Issue by tuva-odegard** [SpareBank1/designsystem#2391]
Etter vi publiserte Chip ble det oppdaget at teksten ikke er helt midstilt, antageligvis pga. line-height. Jeg prøvde meg litt frem, men usikker på hvordan det kan løses. 
![image](https://github.com/user-attachments/assets/4c204c05-6144-4cd5-8740-b1e0d474116e)

**Comment by pethel** [comment]
@tuva-odegard Sette line-heigth til `1`(da blir den lika høy som texten)  på elementet der texten ligger også justera avstanderna:

```
line-height: 1;
```

**Comment by tuva-odegard** [comment]
Jeg tenker denne kan lukkes, ettersom det viser seg at teksten faktisk er midstilt, hvis man har en tekst som har bokstaver som går under linja ("g"). 
![Image](https://github.com/user-attachments/assets/d39ec050-6404-450d-bcab-9e0cc2ee6d9f)
