### ISSUE TITLE
ffe-icons: Consider creating a separate package for the SVG assets

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#24]
Some consumers would only like the SVGs and use them directly in their app. Today we force these users to download PhantomJS as part of `svg-sprite`. This is a requirement to generate an SVG sprite of multiple icons at build-time. However, not all consumers want or need this feature.

Proposed solution:

- Create a new package `ffe-icons-assets` that only holds the SVGs
- Release a version of `ffe-icons` that uses `ffe-icons-assets` as its source for SVGs. If it is set as a devDependency and the SVG assets are copied and bundled in the same place as before when publishing we can avoid a breaking change.
- `ffe-icons-react` carries on, business as usual

This way we support these three use cases:

- I use React
- I don't use React and I just need one or two SVGs and don't want or need sprites
- I don't use React and I need several SVGs and should probably bundle them in a sprite

**Comment by kwltrs** [comment]
Is there an alternative to `svg-sprite`? This could solve the dependency to PhantomJS issue.

**Comment by wkillerud** [comment]
Good point. 

[svgstore](https://github.com/svgstore/svgstore) looks promising at first glance ([blogpost about it here](https://medium.com/@OlegVaraksin/workflow-for-creating-svg-sprites-with-npm-scripts-7cae7014619)).

**Comment by wkillerud** [comment]
I have a [branch with a working build using svgstore](https://github.com/SpareBank1/designsystem/tree/24-icons), but some of the icons are broken. I'll see if I get the time to work on this later at some point.

**Comment by wkillerud** [comment]
A breaking change was needed for `ffe-icons` and `ffe-icons-react` got a new major version as well. There were no changes in the API for the latter, only a new major due to the risk of visual regressions. But no more PhantomJS :tada:
