### ISSUE TITLE
Let's define a color for input placeholders

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#240]
#### Which package is this issue related to?
ffe-form

#### Describe your issue (screenshots welcome!)
In #237 we addressed the issue of placeholders in IE getting the same color as the text color.

After bumping ffe-form in our app, I noticed the placeholder of an input field now differed from the placeholder of a searchable dropdown.

While a HTML dropdown can't have a placeholder out of the box, the searchable dropdown is technically an input field, so it can have a placeholder. However, it's styled with `.ffe-dropdown`, so it doesn't get our new placeholder styling from #237 

What's more is I just did an attempt to apply placeholder color to a dropdown, which worked fine, but again it differed from our styled input placeholder.

In the following screenshot we see three variants of a placeholder color:
![image](https://user-images.githubusercontent.com/435037/40233414-2f4c47be-5aa3-11e8-93c5-433396cf0d26.png)
The first is truly `@ffe-grey-charcoal`, which we decided for #237 should be our placeholder color.
The second is a searchable dropdown with default Chrome placeholder color.
The third is an input field with `.ffe-input-field`. Because of #237 the color here should've been the same as the first one, but it's definately not.

According to [an article about placeholder](https://css-tricks.com/almanac/selectors/p/placeholder/) Firefox applies some opacity to your placeholder color, but Chrome 47 does not. Now, with Chrome 66, it seems like that's no longer true; Chrome is now adding opacity to placeholders.

I tried adding some opacity to the input field placeholder, as well as my dropdown placeholder, to make our `@ffe-grey-charcoal` placeholder match default Chrome placeholder. It seems a value of `.75` is a match here, but of course this means our actual placeholder color doesn't exist in our color palette.

#### Suggestions and questions
- add `::placeholder` color to `.ffe-dropdown` as well, to fix the searchable dropdown
- add opacity to both placeholders, to make sure they look consistent
  - should this be `.75` to match default Chrome placeholder, simply `1` to use the color from our palette, or perhaps something else?
- add some styling and code to allow for a placeholder-color on regular dropdowns

**Comment by henrikhermansen** [comment]
After some deliberation with my UX resource I have some updated opinions/suggestions:
- still add `::placeholder` to `.ffe-dropdown`, with the goal of making searchable dropdowns and account selectors appear the same as regular dropdowns
- opacity should be added to placeholders as the current color of `.ffe-input-field` is probably too bright due to browser default opacity
- don't change anything about regular dropdowns because they don't really have placeholders

Lots to read and consider here. I hope for some insightful feedback next week :smiley:

**Comment by selbekk** [comment]
This is definitely something we should normalize somehow. 

Ref your last question - we can create a "placeholder" for dropdowns by styling the "selected disabled" option elements.

**Comment by henrikhermansen** [comment]
Yeah, that's exactly what I did to create the color on the "Velg portefølje" dropdown.
I see the confusion about what's suggestions and what's questions :)

One way to do this could be to add a class to the placeholder option, and a class to the dropdown while the placeholder is selected. Styling could be something like this:
```
.ffe-dropdown {
  option {
    &.ffe-dropdown__placeholder {
      color: @ffe-grey-charcoal;
    }
    color: @ffe-black;
  }

  &--placeholder-selected {
    color: @ffe-grey-charcoal;
  }
}
```

Edit: There's a question tho: do we want to have placeholders in dropdowns, and if so, do we want to style the placeholder option and the dropdown?

**Comment by wkillerud** [comment]
Regarding default browser opacity, is this something we can work around with a reset?

**Comment by henrikhermansen** [comment]
@wkillerud we can set the opacity to whatever we want. Set it to 1 to make placeholders have the color we give them. Set it to 0.75 together with @ffe-grey-charcoal to make the placeholder appear very much like default placeholder in Chrome.

**Comment by henrikhermansen** [comment]
By the way, if we go for opcaity 1 charcoal and black might be a little too similar?
![image](https://user-images.githubusercontent.com/435037/40354123-75a97d36-5db3-11e8-9b4d-388de58b74cc.png)

If we don't go for opacity 1, I don't think we can get a matching text color on the dropdown, as giving the dropdown opacity would fade the entire dropdown. With input fields we can actually set opacity on the placeholder text.

**Comment by wkillerud** [comment]
This is something for the GD crowd, but I'd say we should set opacity 1 and use a color that makes sense (perhaps not charcoal). That way we're sure we use the same presentation across browsers and that the text isn't suddenly unreadable because of some browser-applied opacity.

**Comment by henrikhermansen** [comment]
GD crowd?

We decided upon charcoal in #237 because it's the only one with high enough contrast to white to pass WCAG AA.
Speaking of WCAG, the default placeholder in Chrome is actually not WCAG AA compliant. I suppose this raises the question: does a placeholder need to be WCAG compliant?

Our @ffe-grey with opacity 1 is extremely close to default Chrome placeholder.
I can't really tell the difference.
Can you?
![image](https://user-images.githubusercontent.com/435037/40356597-d40dbbb6-5db9-11e8-9d95-1eb5d308cb8b.png)
(The bottom one is default, the top one is @ffe-grey with opacity 1)

**Comment by adidick-zz** [comment]
It sounds like it would be safest to go with charcoal at opacity 1. The downside is that the charcoal might look similar to black but we still have the placeholder text to describe what the user needs to do. And then, at worst, they will still get an error message if they don't see the placeholder text and leave the field blank. I think that gives us the most control and keeps everything standardised meaning that any other small discrepancies are created by default browser silliness. Sound good?

**Comment by henrikhermansen** [comment]
Sounds good indeed!
After a brief chat with Adi we also decided to leave regular dropdowns as they are, but apply `::placeholder` to `.ffe-dropdown`. This will give the correct placeholder color to searchable dropdown and account selector, which in fact are input fields that can have a placeholder property.
