### ISSUE TITLE
Oppdatere Multiselect i Figma

### ISSUE THREAD

**Issue by martingaard** [SpareBank1/designsystem#2403]
Oppdatere Figma slik at det samsvarer med kode

**Comment by pethel** [comment]
@martingaard AccountSelectorMulti. Vanlig Murlitselect er i ordren. Denne som jag bad dere opdatera hade en egen implmentasjon av mulitselect som også var synlig i figma,  https://design.sparebank1.no/komponenter/kontovelger/
![image](https://github.com/user-attachments/assets/4917d758-39f9-4d4a-932f-c19daca1bfce)

Dokumentasjonen har opdaert version nå

**Comment by tuva-odegard** [comment]
Ser ut som duplikat av https://github.com/SpareBank1/designsystem/issues/2402
