### ISSUE TITLE
Strip padding from ffe-grid

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#241]
#### Which package is this issue related to?

ffe-grid

#### Describe your issue (screenshots welcome!)

I'm using the `.ffe-grid` class on a `<ul>` element. In webkit, padding is then added to the `<ul>` element via `-webkit-padding-start` which is applied by the browser directly to the element.

![image](https://user-images.githubusercontent.com/379849/40345574-04eea288-5d9a-11e8-9bac-79c7bca99a91.png)

#### What is the expected behavior? 

I expect my grid to occupy the full width of the screen, it does not do that when the content gets padding.

**Comment by selbekk** [comment]
Seems like stripping / setting padding and margin values is a fair assumption to make.

**Comment by ivarni** [comment]
Ah, perfect. I just came to create an issue for this now and someone was nice enough to have already done it yesterday. I'll look into this right now! 😜
