### ISSUE TITLE
Ikoner for bærekraft fond

### ISSUE THREAD

**Issue by raglie-sb1** [SpareBank1/designsystem#2410]
Vi trenger ikoner for bærekraftmerking av fond. 
![Image](https://github.com/user-attachments/assets/2af404e8-67b9-41dd-b118-6a50bdad8aca)

https://www.sparebank1.no/nb/bank/privat/sparing/spare-i-fond/esg.html

Forespurt av @pethel

**Comment by raglie-sb1** [comment]
Har sendt melding til Karoline og spurt om de har noe på dette i posisjon og merkevare.

**Comment by pethel** [comment]
Jag tror vi bare har satt igang egentligen. Men burde vi legge dom her når vi laget dom?

**Comment by pethel** [comment]
Jag lukker denne får dere opne på nytt hvis dere er oenig. Det ble an annen skala en den på bildeerna oså
