### ISSUE TITLE
New component: StepIndicator

### ISSUE THREAD

**Issue by paandahl** [SpareBank1/designsystem#243]
A new design component is in the works, that will show the steps of a process, and indicate the users progress.

I am creating this issue to have an identifier - the preliminary discussions have taken place in the Designsystem-channel on HipChat.

I don't have the permission to assign issues, but this issue can be assigned to me. I will try to coordinate with the designers, and then submit a PR for review from my own fork.

(Preben Ludviksen, Team Finansiering)

**Comment by antidecaf** [comment]
@benwixen Any progress on this?
