### ISSUE TITLE
Accessibility error message in ffe-account-selector-react

### ISSUE THREAD

**Issue by eksb1** [SpareBank1/designsystem#244]
#### Which package is this issue related to?
ffe-account-selector-react
#### Describe your issue (screenshots welcome!)
Accessibility error message: A button is empty or has no value text for close button and expand-list button in account selector.

#### What is the expected behavior? 
These buttons/symbols are not available with Tab, so area value could be disabled. 

#### Steps to reproduce
could be reproduced by using Wave-extension in Chrome

**Comment by selbekk** [comment]
#258 fixed this.
