### ISSUE TITLE
Documentation for ffe-message-box-react is wrong

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#252]
#### Which package is this issue related to?

`ffe-message-box-react`

#### Describe your issue (screenshots welcome!)

The [docs](https://design.sparebank1.no/styleguidist/index.html#messagebox) for `ffe-message-box-react` tell me I can do stuff like

```javascript
import { MessageBox } from '@sb1/ffe-message-box-react';
import { SuccessMessageBox } from '@sb1/ffe-message-box-react';
import { TipsMessageBox } from '@sb1/ffe-message-box-react';
import { InfoMessageBox } from '@sb1/ffe-message-box-react';
import { ErrorMessageBox } from '@sb1/ffe-message-box-react';
```

But the [exports](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-message-box-react/src/index.js) are:
```javascript
export {
    SuccessMessage,
    ErrorMessage,
    InfoMessage,
    TipsMessage,
    InfoMessageList,
    InfoMessageListItem,
};
```

**Comment by ivarni** [comment]
How do we want to fix this? Having the `Box` suffix matches the package name which makes it more intuitive but changing the exported names to match would be a breaking change.

Which approach is prefered?

**Comment by wkillerud** [comment]
The string is built by [getComponentPathLine in styleguide.config.js](https://github.com/SpareBank1/designsystem/blob/0aab6f817f7c49dca05a72d71e29fe8e2118fb0f/styleguide.config.js#L29), which uses the JS file name as the export name. It was assumed this relationship would be 1:1, but apparently not.

I'd suggest renaming the files, honestly. The `Box` suffix should be well enough covered by the package name in my opinion. If you disagree then you can extend `getComponentPathLine` with some extra logic for custom names in this case.

**Comment by ivarni** [comment]
In that case I'd prefer we don't expose the `Message(Box)` component.

We probably shouldn't do that anyway, since it's more of a base-class and an implementation detail?

**Comment by wkillerud** [comment]
> In that case I'd prefer we don't expose the Message(Box) component.
> We probably shouldn't do that anyway, since it's more of a base-class and an implementation detail?

My comment on #253 is relevant to your last comment. If we end up keeping it unexported then for sure it shouldn't have a fake import statement.

**Comment by ivarni** [comment]
I think it's counter-intuitive to expose it since we then also need to teach consumers about the little magic strings that produce the 5 different kinds of message-boxes we have defined? If we go that route we might as well expose *just* the MessageBox in my opinion.

**Comment by wkillerud** [comment]
Four, and we don't need any more than to remove the `* @ignore` line in `propTypes` in `MessageBox` along with a "you probably want one of these four instead" pointer. 

The four wrapper components still bring value in semantics and convenience.

**Comment by ivarni** [comment]
My main point is that we don't need both. There's nothing you can do with a `MessageBox` that you can't do with one of the wrappers

**Comment by wkillerud** [comment]
No, but if we open for overriding one of the two things that distinguish an `InfoMessage` from other boxes (for a lack of a better word) then I feel the name loses meaning, and the name is important when communicating.

**Comment by ivarni** [comment]
How is that different from supplying `type="info"` while overriding the icon? It's just a more cumbersome way of doing the exact same thing. It's *still* an `InfoMessage`, we just lost some syntactic sugar.

**Comment by wkillerud** [comment]
Yeah, maybe.

In that case it should be excluded and be named `Base*` like the other packages we have. I can make a PR.

**Comment by ivarni** [comment]
I had already started on one, but if you want to handle this feel free :)
