### ISSUE TITLE
Icons can not be supplied as-is to ffe-message-box-react

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#253]
#### Which package is this issue related to?

`ffe-message-box-react`

#### Describe your issue (screenshots welcome!)

I'm trying to provide a custom icon to [MessageBox](https://design.sparebank1.no/styleguidist/index.html#messagebox).

It seems like the CSS that's [normally applied to the default icons](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-message-box-react/src/SuccessMessageBox.js) does not get set when providing a custom icon. I would, as a consumer, like to not have to provide these styles myself.

#### What is the expected behavior? 

I was hoping for something like this:
![image](https://user-images.githubusercontent.com/379849/40472801-c6a42686-5f3a-11e8-819b-cf02e3e21951.png)

#### What is the actual behavior?

I got this:
![image](https://user-images.githubusercontent.com/379849/40472708-89f48668-5f3a-11e8-9c00-a76a475db78e.png)

#### Steps to reproduce

```xml
<TipsMessage
    icon={<HandlevognIkon />}
    title="Forutsetninger for kjøp"
>
```

**Comment by wkillerud** [comment]
I was sure we exported the raw `MessageBox`, but looking at it now I see we don't.

I was about to say if you need something outside the defaults you should use `MessageBox` directly, even if it's just a different icon. A `TipsMessage` isn't a proper `TipsMessage` without the `LyspareIkon` IMO.

```jsx
// My imagined end result
import React from 'react';
import { HandlevognIkon } from '@sb1/ffe-icons-react';
import { MessageBox } from '@sb1/ffe-message-box-react';

const iconStyles = {
    width: '36px',
    height: '36px',
};

const MyCustomMessage = props => (
    <MessageBox
        type="tips"
        icon={<HandlevognIkon style={iconStyles} />}
        {...props}
    />
);

export default MyCustomMessage;
```

Does this make sense? If so we should start exporting `MessageBox`.

If not then I think it makes sense to still require consumers provide the icon styles. We aren't guaranteed that 40x40 will look good with all icons.

**Comment by ivarni** [comment]
> We aren't guaranteed that 40x40 will look good with all icons

Any other size could lead to the icon not fitting into it's little crevice on top of the box so I'd rather add some text pointing out that the icon should come from `ffe-icons-react` to be honest. Even with different icons I got a feeling we want these boxes to look sort of similar and all kinds of different sizes won't help with that.

**Comment by wkillerud** [comment]
Allright. The style stuff we have today can be moved to `MessageBox` and made so it's applied by default but still overridable. ~~I'll be making changes in that area in #252 so I can take a look at this while at it~~. Ah, you already started - go ahead :)

**Comment by ivarni** [comment]
Say we add the `iconStyles`, should we take care to preserve any existing style object on the passed `icon` element?

I am thinking something like
```javascript
{React.cloneElement(icon, { style: iconStyles, ...icon.props })}
```
instead of just
```javascript
{React.cloneElement(icon, { style: iconStyles })}
```

That way, we keep any inline styles like `fill` that might have been passed or is it better to not support changing the colour of the icon away from the [defaults](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-message-box/less/ffe-message-box.less#L78) we already have by simply ignore any passed `style` prop? As it is right now, `fill` can be overriden from userland with a CSS class while size can not since it's applied inline.

**Comment by ivarni** [comment]
I am leaning towards simply overriding any passed `style` prop, or possibly detecting it and just setting the sizes so that icons always are of the same size (so they fit where they're meant to go). As can be seen in the initial screenshot, custom sizes might break the whole thing entirely.
