### ISSUE TITLE
There seems to be a problem in the ButtonGroup

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#254]
#### Which package is this issue related to?

`ffe-buttons` and/or `ffe-buttons-react`

#### Describe your issue (screenshots welcome!)

When looking at the [docs for ButtonGroup](https://design.sparebank1.no/styleguidist/index.html#buttongroup) there seems to be an issue with the inline variant where some of the buttons are vertically challenged when it comes to placement

#### What is the expected behavior? 

![image](https://user-images.githubusercontent.com/379849/40473226-dfe757ca-5f3b-11e8-9877-24816c39aa89.png)

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/379849/40473201-d18c9ab4-5f3b-11e8-9842-0e9da5b0c06d.png)

**Comment by ivarni** [comment]
Something's up with the small-screen view as well

![image](https://user-images.githubusercontent.com/379849/40473663-1ff591aa-5f3d-11e8-9463-24b0d5c4a408.png)

**Comment by antidecaf** [comment]
Fixed via #276/#277
