### ISSUE TITLE
New type of card(?) for overview and landing pages

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#260]
#### Which package is this issue related to?
ffe-cards and ffe-cards-react, I suppose

#### Describe your issue (screenshots welcome!)
We have a new type of card (or whatever it is to be named) which is already in use on banking overview beta, and is soon to come to various banking landing pages.
I suppose insurance will use this as well, but I don't know.

There are two types of cards.
The bigger and badder one:
![image](https://user-images.githubusercontent.com/435037/40616776-727052b0-628c-11e8-9133-2c20724329da.png)
The leaner and meaner one:
![image](https://user-images.githubusercontent.com/435037/40616780-746b0a06-628c-11e8-8e6b-0a6840cdc3e3.png)

I suppose the latter could be viewed as a condensed version of the first, but they clearly have distinct uses. Condensing here is not something that would be done for smaller size screens or anything. They should both be responsive in each their way.

Is this going to be categorized as a card?
If so, what should the card name be?
If not, what is it really?

While these "cards" are still a design WIP, they're already implemented in one place, and will surely be implemented in many more. I say surely, because this is now a well processed idea from the overview team (I believe).
Thus it makes sense to add them here, so we can all work together on making the best solution, rather than implementing many different versions before we try to merge them all together.

**Comment by ivarni** [comment]
Are they going to be used around grids and is (e.g.) the text then going to be expected to line up with other grid column content? Same question for the lean one re the condensed grid.

To me this *feels* like it's not really much more than a border-shadow around a box, especially if we could use the grid for laying out the internal parts of it (in which case it is tempting to just suggest adding support for border-shadow on grid-cols).

If it can't be implemented with grid-elements I'd suggest making the implementation as flexible as possible, maybe just a border around a box with an icon on the left and whatever the consumer wants to put there on the right.

**Comment by henrikhermansen** [comment]
For now my idea is to put these as components inside grid columns.

I'm not sure how specific or flexible we want these to be.
I think this is something we should have design involved in.

I've been working on some code, and so far it's not as flexible as you describe it. This is because I believe there are certain design limitations/requirements to these cards that needs to be taken into account.
The component is very similar to the ProductCard. This is because we need to control the content a bit, due to said design considerations.
However, I've tried to keep the css simple. So far it's 89 lines, which is ways better than our ffe-link-card which is 237 lines (not counting comments).

I'll put up a PR tomorrow, so you can see for yourself.
I'm excited to see if we can find a better way to make this styling and component more flexible without allowing too much stray from the intended design.

**Comment by henrikhermansen** [comment]
Hmm about using the grid. The grid is using padding to create space, but we want space between the cards, so simply adding box shadow to the grid won't work.

**Comment by ivarni** [comment]
For the record, and in hindsight, I think putting `ffe-cards` in as a FFE component was a mistake. After receiving different specs from different designers here over the last 4-5 years it's fairly clear to me that they are treating those cards as just a border they can put stuff into and I usually end up implementing it by just literally sticking a border around a `div` and calling it a day.

That's why I am wary about adding more product cards :) I've no doubt the implementation can be done simple, I'm just not sure how easy it's going to be to re-use later. If we are going to add it then I think at least we should have design on board with some clearly defined rules about *what* can go into these boxes and *how* it should look. And they need to be prepared to stick to those rules. That's my opinion on it anyway.

**Comment by henrikhermansen** [comment]
I totally see your points here. A general purpose card for putting all sorts of things into definately needs to be made very simple and general purpose to keep it manageable here. The cards we have today has failed on this point.

I do, however, have the impression these new cards are supposed to have a specific design, with less freedom for each team.
If this is the case, I think it's an advantage to make them less general purpose here, to help ensure they look the same for everyone, with minimal effort from each team.
If it's not the case, and these cards should allow for major differences between teams, my current implementation would not work. Or like you say, maybe it shouldn't be in the design system at all.

I'll get a PR up today, so we can have a look and share some thoughts on the implementation.
