### ISSUE TITLE
ffe-buttons: Button text should not wrap

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#264]
#### Which package is this issue related to?

`ffe-buttons`

#### Describe your issue

If a button label becomes long enough it starts wrapping over two lines. The buttons are not designed for this, and the end result is kind of odd looking.

#### What is the expected behavior? 

Button labels should never wrap

#### What is the actual behavior?

They
wrap

**Comment by wkillerud** [comment]
Should be solvable by adding `white-space: nowrap;`, but this may cause some breakage if people depend on the wrapping behavior today.

**Comment by selbekk** [comment]
Should we consider it a breaking change then, or should we stick with the API-specification of breaking?

**Comment by wkillerud** [comment]
It's tricky sometimes with CSS. We may not break any API, but for instance going from `display: block;` to `display: inline;` would cause major problems if released as a patch. This property similarly will have consequences for layout. In most cases it shouldn't be a problem, but we don't know that for sure. The safest is to mark it as a breaking change and explain the possible consequence of upgrading, and let consumers make the call.
