### ISSUE TITLE
ffe-account-selector-react: wrong class on AccountSelectorMulti statusbar-button

### ISSUE THREAD

**Issue by ksawerysb1** [SpareBank1/designsystem#270]
#### Which package is this issue related to?
ffe-account-selector-react
#### Describe your issue (screenshots welcome!)
AccountSelectorMulti statusbar Button styling in is off 
#### What is the expected behavior? 
Button should have a standard ffe-button styling.
Class should be ffe-button ffe-button--primary
#### What is the actual behavior?
Button has a class that does not match styling.
Class is ffe-primary-button
#### Steps to reproduce
https://design.sparebank1.no/styleguidist/index.html#!/AccountSelectorMulti/1
Click on "Velg konto", the "Ferdig" button has inconsistent styling with designsystem ffe-button

**Comment by antidecaf** [comment]
Fixed in #271
