### ISSUE TITLE
Føringer for bruk av kolonner i griden

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#281]
#### Hvilken del av designsystemet gjelder det?

Gjelder feilmeldingene som printes ut av `ffe-grid-react` ved visse konfigurasjoner av griden.

For medium:

> The grid should have 6 columns for `md` screens, please stick to a total of 6 columns. For "md" screensizes this means you need to stick to multiples of 2 for cols+offset.

For mindre skjermer:

> The grid should have 4 columns for `sm` screens, please stick to a total of 4 columns. For "sm" screensizes this means you need to stick to multiples of 3 for cols+offset.

Det er ingen sånne føringer for `large`.

#### Beskriv problemet

Det er ikke alltid jeg får et design som passer mønsteret som disse feilmeldingene sier jeg skal holde meg til. Sånn jeg ser det er det to muligheter her:

* Føringene fra feilmeldingene over gjøres kjent og brukes i design (virker ganske restriktivt om du spør meg)
* Vi fjerner feilmeldingene og lar de 12 Grid-kolonnene brukes fritt (jeg er i denne campen)

En tredje mulighet er forsåvidt å gjøre ingenting  - beholde meldingene for at man skal ha en god grunn til å gå utenfor. I så fal vil jeg gjerne at det logges som warnings og ikke errors.

**Comment by wkillerud** [comment]
Spørsmålet blir - hva synes dere?

**Comment by ivarni** [comment]
Det har vært en diskusjon rundt dette før. Gridden ble definert til å ha 4 kolonner på mobil, 6 på pad og 12 på desktop. Jeg er i den campen jeg alltid har vært i, nemlig at det ikke er opp til oss å overstyre det.

**Comment by ivarni** [comment]
Så lenge man bruker gridden til *layout* og ikke til å designe innholdet i komponenter er ikke dette et veldig stort problem i mitt hode.

**Comment by antidecaf** [comment]
> Vi fjerner feilmeldingene og lar de 12 Grid-kolonnene brukes fritt

Jeg er også i denne campen.
