### ISSUE TITLE
margin-top: ffe-bullet-list

### ISSUE THREAD

**Issue by eirikv** [SpareBank1/designsystem#290]
Første elementet i en ffe-bullet-list burde ikke ha margin-top.
Fikk input fra designer at dette skaper for mye mellomrom mellom overskriften eller innledningseksten og listen. I praksis er denne marginen lagt til for å ha mellomrom mellom elementene i listen og er egentlig ikke noe vits å ha for første elementet.

Noen innvendinger?

**Comment by wkillerud** [comment]
Høres greit ut for min del. Det er kanskje noe som designeren bør ta innom fagforumet? Eller bare få "Approve" fra i hvertfall en kollega eller to - ala code review 😉

**Comment by antidecaf** [comment]
@eirikv Hva er status på denne?

**Comment by eirikv** [comment]
@antidecaf, må nesten delegere denne saken videre til @selbekk, så får han ta en sjefsavgjørelse (når han er tilbake).

**Comment by selbekk** [comment]
cc @hodoea @adidick er dette noe som er okei for dere? Det vil si fjerning av topp-margin for første liste-element.

**Comment by adidick-zz** [comment]
Jeg har tatt en rask titt på design.sparebank1.no på bullet lister og nummererte lister og det ser ut som en "no-brainer" for meg.

**Comment by sirioc** [comment]
Enig! 👍
