### ISSUE TITLE
Add support for always showing a tooltip

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#291]
#### Which package is this issue related to?

`ffe-form-react`

#### Describe your issue (screenshots welcome!)

I've been getting several designs lately where the input-group is rendered with an always visible non-toggleable tooltip

![image](https://user-images.githubusercontent.com/379849/41521075-11bf07f4-72d1-11e8-99b0-4585089fd4d1.png)

It would be nice to have support for this out of the box so I can use the already existing `tooltip` prop instead of rendering my own helptext. This would help make sure these stay visiually consistent with the toggleable ones.

For reference, this is what the current ones look like

![image](https://user-images.githubusercontent.com/379849/41521133-5097fbde-72d1-11e8-9305-7b4a0dbbac3c.png)

I propose adding a new prop, `ubiquitousTooltip` (no, I'm joking I hate try to spell that word).

Maybe we can call it `staticTooltip` and have it be a `bool`? Setting it would simply remove the ❓ box and always show the tooltip.

**Comment by wkillerud** [comment]
I agree, this is something we should support. Could be we should just call it something completely different though, and make it unrelated to the `tooltip` prop. `description` or `helpText` maybe? Then you'd use that prop for the text instead of using `tooltip`+`staticTooltip`.

**Comment by selbekk** [comment]
As I mentioned in the pull request, I'm a bit wary of adding another prop that's... "almost" equal to an existing one, but doing this in userland is not pretty either:

```js
<InputGroup 
  tooltip={
    <SmallText>Tooltip text goes here</SmallText>
  } 
/>
```

A different approach is to pass it in as a child:

```js
<InputGroup label="Label is here">
  {inputProps => (
    <>
      <SmallText>Tooltip text goes here</SmallText>
      <Input {...inputProps} />
    </>
  )}
</InputGroup>
```

They may not look as pretty, but at least it's using the built in flexibility of the component to its advantage. If anything, I think adding a new prop for making the tooltip visible by default is a better, "easier to understand" approach than passing a prop with a slightly different name than `tooltip` that overrides the `tooltip` prop if both are set.

**Comment by ivarni** [comment]
I was trying to avoid having to move the implementation to userland because when rendering this myself with the function-thing there's no guarantee any more that it will be in sync with whatever the current implementation of `Tooltip` is and I'd like this to look the same as an expanded tooltip. The second approach above is what I used the *first* time I encountered this variation but since this is the *second* time I'd prefer a more generic way. As for what the prop is called I personally don't have strong opinions on it, my initial suggestion was to just have a "always expanded" flag but I'm fine with `helpText` too.

Let me know when you've come to an agreement on it :)

**Comment by wkillerud** [comment]
It's _almost_ equal @selbekk, in the sense that they are both texts that describe an input field. Still different enough to warrant a new prop IMO. It's an always-visible text. A tooltip usually isn't. So providing a "don't be a tooltip, Tooltip" prop makes less sense to me than just calling it something else.

**Comment by selbekk** [comment]
I understand where you're coming from @wkillerud - but I think we're just in disagreement here. I think having two props where one excludes the other is a pattern we should try to avoid.

That being said - I _could_ be convinced that naming this extra prop `description` and throwing an error / showing a warning if both are set, could be good enough. Deal?

**Comment by ivarni** [comment]
How about I just add both?

**Comment by ivarni** [comment]
Or I'll just rename the prop then, if that makes everyone happy.
