### ISSUE TITLE
SearchableDropdown passes more props than it should to InputField

### ISSUE THREAD

**Issue by paandahl** [SpareBank1/designsystem#293]
#### Which package is this issue related to?
`ffe-searchable-dropdown-react`

#### Describe your issue (screenshots welcome!)
`<InputField>` passes on rest-parameters to its `<input>`, but doesn't filter out all non-input parameters first, triggering error messages in the console in dev-mode. 

#### What is the expected behavior? 
`<InputField>` should filter out all non-input parameters before passing the rest to the `<input>`.

This bug was introduced with my own PR, #287. This should have been uncovered in testing, but I stuffed up. :)

**Comment by ivarni** [comment]
I think this can be closed now?

(Tip: If you add `Closes #293`, `Fixes #293` or any of the [other](https://help.github.com/articles/closing-issues-using-keywords/) keywords in the commit message you'll never have to worry about forgetting to close after merging)
