### ISSUE TITLE
Remove or reduce padding in message-boxes on small screens

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#294]
#### Which package is this issue related to?

`ffe-message-box`

#### Describe your issue (screenshots welcome!)

On small (narrow) screens, the message-boxes spend a lot of real estate on horizontal padding

![image](https://user-images.githubusercontent.com/379849/41526181-b5da9710-72e3-11e8-9653-533e2d6ab8e0.png)

In this case, 80px of a total available 355px is used for padding. This seems excessive. Can we have it reduced (on small screens) to e.g. 10 on each side (for a total of 20) or 15 on each side (for a total of 30)?

@adidick or anyone else, any thought on this?

**Comment by ivarni** [comment]
In my latest design draft, which is presumably based on something in sketch it looks like this on small screens

![image](https://user-images.githubusercontent.com/379849/41526351-41957202-72e4-11e8-84ce-cc46dee7c2ad.png)

**Comment by ivarni** [comment]
I'm gonna go ahead and fix this locally while I wait for some feedback here because I can't believe it's intentional that we waste 20% of the real estate on padding...

**Comment by adidick-zz** [comment]
Don't do it! 
We're going to take it up in DS forum tomorrow. 10px margin between text and outer box is not enough and makes things super squashed and harder to read. 10px on the outside of a background box though makes sense. There's also talk about implementing an 8 point grid system so we can make everything easier to standardise, so I think we can have a good discussion about it all tomorrow.

**Comment by adidick-zz** [comment]
@ivarni Jeg har tatt en titt på designet på dette på mobil og ser ut for meg at det funker best med 10px margin utenfor boksen og 30px margin inn i boksen. Da får man litt bedre bruk av plass men fortsatt det samme fordeler med luft, lesbarhet og visuell stil som komponenten har på desktop.

![image](https://user-images.githubusercontent.com/8871429/41723019-555efd34-756a-11e8-9a86-dce780de03e4.png)
