### ISSUE TITLE
ffe-core doesn't export ES5

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#299]
#### Which package is this issue related to?
ffe-core

#### Describe your issue (screenshots welcome!)
When we build ffe-core, it creates some javascript files for variables, which can be imported. Unfortunately, the index file contains a trailing comma for functions, which are not ES5.

This leads to the build process failing whenever you use tools such as `create-react-app`.

**Comment by ivarni** [comment]
Sounds like a good idea to run it through Babel then :)

**Comment by selbekk** [comment]
Running all of node_modules through Babel is slow, and is not supported in certain build tools (`create-react-app` is one of them). In my opinion, it's better to just export ES5-compiled code

**Comment by ivarni** [comment]
That's exactly what I'm suggesting you do :) Running it through babel ensures that it's ES5 and noone forgets what's in which spec and adds something that is not ES5 later.

**Comment by wkillerud** [comment]
Run the code-to-be-exported-by-ffe-core through Babel, that is @selbekk

**Comment by selbekk** [comment]
Fair enough, I don't mind adding Babel to the build process
