### ISSUE TITLE
Automate deployment of GitHub pages

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#3]
The process of building the html documentation and pushing it to the gh-pages-branch needs to be automated. Preferably our CI should be setup to do this. Travis has a write up, that might help: https://docs.travis-ci.com/user/deployment/pages/

`npm run build:htdocs` builds the documentation, which ends up in `dist`.

**Comment by kwltrs** [comment]
@wkillerud You are currently the expert on travis. Do think using travis to push to gh-pages is a good idea?

**Comment by wkillerud** [comment]
Sure, it looks like they have great support for this :) https://docs.travis-ci.com/user/deployment/pages/
I can set up a PR with a suggested config. We should consider which account we create the access token with though, perhaps it's time for a dedicated automation account.

**Comment by wkillerud** [comment]
Solved by #78 and #89. Still TODO is to create a dedicated account and replace the GitHub token on Travis.

**Comment by wkillerud** [comment]
@kwltrs, can you sort out the dedicated account and new token? I can help with the config if you need :)

**Comment by selbekk** [comment]
Should we close this issue and create a new one for creating a new dedicated account? This issue seems to be resolved.

**Comment by wkillerud** [comment]
Created #96 to track the remaining work
