### ISSUE TITLE
peerDependency-warnings after upgrading to ffe-core 13.x

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#304]
#### Which package is this issue related to?

All packages with a peerDependency on `ffe-core`

#### Describe your issue

The only breaking change in `ffe-core@13.0.0` is the removal of `ffe-section-wrapper` and `ffe-content-container` with modifiers. This should be non-breaking for all the other packages we ship in FFE. The packages should be updated with 13.x as a valid peerDependency after verifying they don't use any removed classes.

#### What is the expected behavior? 

No peerDependency warnings should be issued when using `ffe-core@13.0.0`

#### What is the actual behavior?

Warnings en-masse

#### Steps to reproduce

Upgrade to `ffe-core@13.0.0` and install for instance `ffe-accordion`. See peerDependency warning.

**Comment by wkillerud** [comment]
@benmatthews volunteered to fix this :man_dancing:

**Comment by ivarni** [comment]
I could also do it since it's kinda my fault... let me know.

**Comment by benmatthews** [comment]
@ivarni It's no problem, will fix pronto ;-)
