### ISSUE TITLE
Feedback på UX guidelines - 

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#320]
Jeg har laget et forslag til hvordan vi kan brukerteste guidelines i komponentbibliotek. 
Kanskje vi kan følge samme mal til de andre sidene også. Det er bare en enkel tommel opp/tommel ned konsept. 

Bare å klikke seg rundt i disse skissene for å se flyten: 
https://sparebank1.invisionapp.com/share/85DVRWVRF#/257697116_Desktop_HD_Floating_Q
(Oppdatert basert på feedback fra William) 

Hva tenker dere? Yay or Nay. Vi må ihvertfall finne en eller flere metoder å teste dokumentasjonen vår på. :)

**Comment by wkillerud** [comment]
All for en feedback-component som det der 👍 Tenker dog at den kanskje blir litt voldsom om vi skal ha den på bunnen av hver Bruk-seksjon, hvertfall sånn siden er i dag med en lang scroll.

Finnes mange approacher, men MSDN har en variant med en liten modal nede til høyre som ekspanderer om du trykker Nei. Se f.eks. https://docs.microsoft.com/en-us/dotnet/standard/get-started (den husker at du har vært innom og viser ikke boksen på nytt på en stund, så hvis du vil teste flere ganger må du bruke et nytt privat nettleservindu).

Et alternativ er å gjøre den litt mindre. Tenker størrelse ala TertiaryButton kanskje er nok?

**Comment by hodoea** [comment]
Ah ja det har du helt rett i. Glemte den lange scrollen vår :P Jeg tror en sånn "floating" feedback-component som MSDN sin kunne vært det beste. Jeg kan lage en versjon som det i stedet, og se hvordan det kan bli.  :)

**Comment by hdaljord** [comment]
Jeg lurer på om det blir tydelig nok hva man gir tilbakemelding på når den flyter slik på siden eller om den burde knyttes tydeligere opp mot den seksjonen den gjelder? Hvis jeg trykker inn på Knapper i designguiden så vil jeg hele tiden kunne lese videre nedover på siden, videre til typografi etc., dvs. det er ikke bare teksten om knapper som vises. 

Eller er det tenkt at feedbacken alltid skal være for alt på hele siden? Vil feedbacken da være nyttig nok hvis man ikke tydelig kan gi feedback på en seksjon/et kapittel? (Siden dokumentasjonen sikkert ikke vil være like bra på alt hele tida.)

**Comment by hodoea** [comment]
@hdaljord Ja, det blir en utfordring. Tanken var at man kunne gi feedback på den seksjonen man har lest. Men det blir litt vanskelig med den første skissen hvor jeg gjorde ettersom vi har en veldig lang scroll og man kan noen ganger se flere seksjoner på en gang.  Hvis det jeg skrev lager mening. 

Akkurat nå er det slik at vi bare tar imot feedback på hele siden i denne skissen. Men kan sikkert se om jeg finner noe andre tilnærminger på netter. :) 

Kan kanskje legge inn: "komponent som bør forbedres" som placeholder tekst for å trigge dem til å svare på det først før de skriver inn selve feedbacken. Slik vi har her på Github når man først åpner en issue... ?
