### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#322]
Jeg klarer ikke å finne innholdet til komponenter.. Fant bare en fil som heter index.md, der var det bare one-linern til komponentbiblioteket. :( 

Kan vi legge til dette under de ulike overskriftene? For mye tekst? 

**Ikoner**

Vi bruker ikoner for å skape bedre navigasjon og for å tydeliggjøre hvilket produkt og tjeneste vi snakker om i vår kommunikasjon.
Ikoner skal hjelpe kunden med å raskt identifisere og skille mellom ulikt innhold slik at de skaper verdi for brukeren. Ikonene er også bærere av SpareBank 1s visuelle identitet.

Ikonene skal være tydelige i sin utforming.
Ikonene skal oppleves som relevante og informative i den konteksten de presenteres og dermed bidra til at brukeren forstår innholdet raskere.

**Kort**

Bruk et kort når du skal vise innhold som:
	
-Består av en samling, består av flere type elementer f.eks bilder, illustrasjoner, tekst
-Ikke krever direkte sammenligning med bilder eller tekst. 
-Inneholder interaktiv innhold, lik-funksjon eller andre aksjonspunkter.
-Ville ellers vært i en detaljliste men trenger mer innhold for å supplementere bilde

_Mulig å bruke bulletpoints her?_

**Meldinger**

Målet med meldinger er å bekrefte og skape trygghet hos brukeren, slik at hun/han opplever kontroll over situasjonen.

Prinsipper:
Relevante og informative
Meldingsboksen er responsive, tilpasses innholdets lengde og skaleres etter flaten den vises i.
Teksten skal være forståelig og vennlig (følge retningslinjer for stil og tone) 
Vi skiller på meldinger som er fra systemet og de som er fra SpareBank 1.

Meldingsbokser brukes når man skal informere brukeren om diverse endringer/oppdateringer. Dette kan f.eks være når systemet er nede eller at betalingen er gjennomført. Hold innholdet kort og konsist, det skal være relevante tips eller informasjon som brukeren behøver å vite. 

**Spinnere**

Det er mye som skjer i bakgrunnen i et system når innholdet lastes inn, med spinnere kan vi kommunisere tydelig ut til brukeren at innholdet er i ferd med å vises snart. 
Det er best practice å benytte seg av spinnere dersom ventetiden varer lengre enn tre sekunder.
Dersom siden bruker mer enn 10 sekunder på å laste inn innholdet, vurder å bruke en notifikasjon med forklarende tekst.

**Comment by wkillerud** [comment]
Can do :) 

Teksten til seksjonene i komponentbiblioteket er ikke alltid like lette å finne nei. "Bruk"-seksjonene ligger i filer som heter `USAGE.md` i den pakka det gjelder. Så for ikoner ville det vært fila `packages/ffe-icons-react/USAGE.md`.

**Comment by wkillerud** [comment]
Når det er sagt så er det ikke noe i veien for å flytte de filene med bruksdokumentasjon. Den tekniske dokumentasjonen må ligge i nærheten av koden da men.

Hvor gir det mening å ha innholdet? I filer under `styleguide-content/komponenter/` med filnavn likt overskriften? F.eks. `styleguide-content/komponenter/ikoner.md`?  @hodoea

**Comment by hodoea** [comment]
Takk! Er det mulig å lage en hyperlenke til "stil og tone" siden når vi refererer til stil og tone ? :)

**Comment by hodoea** [comment]
Ja @wkillerud jeg tror det kan være fint å ha all innholdet under styleguide-content.  -> (styleguide-content/komponenter/ikoner.md) 

Så lenge det ikke lager noe problemer for dere. :)

**Comment by wkillerud** [comment]
Da lager jeg en ny pull request i løpet av dagen hvor jeg flytter de filene :) Det skal ikke være noe problem 👍
