### ISSUE TITLE
Manglende visuell sporing i venstremeny

### ISSUE THREAD

**Issue by sigrunl** [SpareBank1/designsystem#324]
Det mangler visuell sporing i venstremeny som viser hvilken komponent man er på. Se vedlagt bilde for hvordan vi ønsker at det ser ut. Hvis man er på knapper, skal dette vises i menyen. Dette gjelder i hvert fall på mac, både Chrome og Safari.

<img width="247" alt="screen shot 2018-06-29 at 09 27 10" src="https://user-images.githubusercontent.com/38528602/42078978-aeb36720-7b7e-11e8-828c-e6369948b505.png">

**Comment by antidecaf** [comment]
Fixed in #430
