### ISSUE TITLE
Consider removing all `peerDependencies`

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#33]
#### Which package is this issue related to?

:globe_with_meridians: All the things

#### Describe your issue

When using packages with a React and Less version we have a `peerDependency` on the Less version from the React version. A lot of Less packages also have a `peerDependency` on `@sb1/ffe-core` (even some React packages, like accordion do this). [These tend to get out of sync](https://github.com/SpareBank1/designsystem/search?utf8=%E2%9C%93&q=%22peerDependencies%22&type=), as it seems Lerna ignores them. This again creates a whole set of warnings on `npm install` that _this and that peer dependency is missing_. Some of these peerDependency requirements may also conflict for absolutely no reason.

The peerDependencies were originally added to give some kind of hint that you need this other package for the package to work as intended. For React and Less pairs I feel this is a given, and the peerDependencies just add noise.

What I'm suggesting is that we remove it all.

`@sb1/ffe-core` is a bit tricky. Maybe now that we use Lerna we could instead make `@sb1/ffe-core` a _direct_ dependency? This way we:

- Can remove `peerDependencies` (:+1:)
- A breaking change in `core` also triggers a major release of all dependencies, regardless of feature use (:+1: / :-1: )

**Comment by henrikhermansen** [comment]
How do we keep track of version requirements between packages?
Say you add a new modifier to `ffe-buttons`.
When you add a property to utilize this modifier in `ffe-buttons-react` the consumers need to know that you need minimum version x.y.z of `ffe-buttons` to actually use the new prop in `ffe-buttons-react`.

Without peerDependencies I guess you need to manually check change logs.
Is this good enough?
Are there other solutions?

**Comment by wkillerud** [comment]
A valid concern. Communicating that is difficult. 

Maybe it's OK to expect consumers to upgrade both packages (and check the logs of both) when wanting to use a new feature?

Lerna (for valid reasons) [delegates to us to maintain peerDependencies](https://github.com/lerna/lerna/issues/1018).  May be it's just one of those things we have to deal with...

**Comment by selbekk** [comment]
IMO there are three things we need to decide on:

1. If a React component depends on a different local React component package - should it be listed as a dependency, or as a peer dependency + dev dependency?
2. If a React component applies classes that's provided from a different local LESS package - should it be listed as a peer dependency, or not at all?
3. If a LESS package depends on a different LESS package (i.e. ffe-core), should it be listed in dependencies, or as a peer dependency + dev dependency?

**Comment by selbekk** [comment]
> A breaking change in core also triggers a major release of all dependencies, regardless of feature use (👍 / 👎 )

How would adding `ffe-core` as a direct dependency trigger this? Quite the contrary - if it's a direct dependency, a mere patch of the consumer should do the trick?

----

With regards to the "react-package-requires-a-certain-less-package"-challenge, we could communicate that through the changelog of ffe-buttons-react. 

There are, however, two different approaches we could take:

- **Import the `less` directly in the component.** This requires the consumer to have a `less-loader` set up in their webpack config (oh, and they need to use webpack or parcel or something that handles non-JS file bundling). That might be too big of a requirement for us - what do you think?
- **Add less dependency as a direct dependency of the react package.** This would allow us to re-export the less-files as a part of the React package, and they can then be imported in the consumer's main less-file.

Are there other ideas?

**Comment by wkillerud** [comment]
> How would adding ffe-core as a direct dependency trigger this? Quite the contrary - if it's a direct dependency, a mere patch of the consumer should do the trick?

Maybe my memory is off here, but I could have sworn a breaking change in `icons-react` lead to a whole set of other breaking changes. Or was that a mishap with Lerna scope?

> There are, however, two different approaches we could take:
>  - Import the less directly in the component. This requires the consumer to have a `less-loader` set up in their webpack config (oh, and they need to use webpack or parcel or something that handles non-JS file bundling). That might be too big of a requirement for us - what do you think?

I don't think we should make decisions about the toolchain of consumers at that level, no. We would have to check how duplicate styles were handled as well.

> - Add less dependency as a direct dependency of the react package. This would allow us to re-export the less-files as a part of the React package, and they can then be imported in the consumer's main less-file.

This could work. React consumers would have one package to manage. Cleaner `package.json`. It would have to come with a proper warning that the semantic versioning only applies to the React code - if they have some custom markup they should stick to using the standalone Less package.

That makes it dangerous to mix patterns though - using both React and other frameworks/static HTML. The React package could introduce changes to the DOM in a minor or patch leaving a consumer importing Less from the standalone package with broken styling for those React components.

**Comment by wkillerud** [comment]
> That makes it dangerous to mix patterns though - using both React and other frameworks/static HTML. The React package could introduce changes to the DOM in a minor or patch leaving a consumer importing Less from the standalone package with broken styling for those React components.

This could be "solved" by telling people to lock their versions, but that effectively means no semver for React packages for those consumers.

**Comment by selbekk** [comment]
Me and @wkillerud had a quick talk about this. Basically the worry about approach number 2 is that for people (like @wkillerud and myself) that would end up using both the React component and the LESS packages directly, this would lead to a lot of trouble if not handled with some care. 

Now how would you ever end up in a situation like that, you say? Well in our case, we are migrating a large application from `backbone-marionette` to React piece by piece, and we currently have about ~half of the code migrated. If we were to go with approach number two, we would need to keep a very close eye on changes in the React package, which then would include a potentially breaking LESS file (requiring changes in the DOM structure for example). 

We kind of concluded that those consumers would be left to their own devices. We cannot optimize our workflow for a very small subset of consumers - even if we are one of them.

**Comment by ivarni** [comment]
FWIW the reason we decided to use peer-deps over regular deps + a less-loader was to avoid a situation were a consumer of N different react-packages ended up with anywhere from 2 to N different versions of i.e. the `ffe-core` less package.

The peer-dep was meant to indicate which versions the different intemediate modules relied on and basically act as a red flag once a consumer put themselves in a situation where they could not possibly be able to pick the correct less-package version, in which case they'd need go to make a PR to bring offending packages up to their required versions.

To move the cognitive load of this away from consumers, maybe a requirement for someone creating a breaking version of any one ffe module would should be to find and update all its downstream modules as well?

**Comment by ivarni** [comment]
After all, the ones breaking the stuff should perhaps also take the job of cleaning up the aftermath, either that or the maintainers should step in and fix things before a PR is merged / release is made.

**Comment by selbekk** [comment]
Good points! This cleanup job is much easier now due to our monorepo - I think it’s something the one releasing can do.

**Comment by TorgeirHeim** [comment]
I agree with your point @ivarni. FFE should be seen as library and it does not make sense to have its sub-parts depend on different versions of dependencies.

**Comment by wkillerud** [comment]
I'm not sure we reached an actionable conclusion here. A suggestion was raised to declare what are now `peerDependencies` as actual `dependencies`, with or without the `-react` package acting as an intermediary (exporting all the Less it needs).

To me it sounds like we'd be introducing more complexity to a system that sort of works as it is. Although `peerDependencies` can get out of sync we can fix those issues as they come.

I'll close this issue for now. If anyone has input on the subject then feel free to comment or open a new issue :+1:
