### ISSUE TITLE
Remove ffe-expandable-react

### ISSUE THREAD

**Issue by kwltrs** [SpareBank1/designsystem#34]
ffe-expandable-react has a deprecation notice on top of its [README.md](https://github.com/SpareBank1/designsystem/blob/d5bb1f7fa7b15411b707999469ee3814c3ae9a81/packages/ffe-expandable-react/README.md). There is no version of this component published within the sb1 scope yet and it is save to remove from here from github.

**Comment by selbekk** [comment]
I'll get right on it!
