### ISSUE TITLE
all: peerDependency warnings due to wrong version of ffe-core, others

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#34]
#### Which package is this issue related to?

:globe_with_meridians: All the things

#### Describe your issue

We get a bunch of peerDependency warnings when installing the new scoped FFE packages. This creates a lot of noise in the logs.

#### What is the expected behavior? 

No warnings should be printed :tada: 

#### What is the actual behavior?

So many warnings :see_no_evil: 

#### Steps to reproduce

Run `npm install @sb1/ffe-core @sb1/ffe-accordion @sb1/ffe-accordion-react` for instance. See warnings in log.

**Comment by wkillerud** [comment]
See also question raised in #33. This bug should be patched regardless.

**Comment by wkillerud** [comment]
PR #36 should resolve this issue.

**Comment by selbekk** [comment]
Edit: Moved comment to #33

**Comment by wkillerud** [comment]
@selbekk We should perhaps move this discussion to #33?

**Comment by selbekk** [comment]
Oops, didn't see that issue. Moved my comment there!

**Comment by wkillerud** [comment]
Fixed in #36
