### ISSUE TITLE
FieldMessage is missing icons in IE

### ISSUE THREAD

**Issue by marthall** [SpareBank1/designsystem#342]
#### Which package is this issue related to?
`ffe-form`

#### Describe your issue (screenshots welcome!)
The newest version of `ffe-form` is missing icons on `FieldMessage` (See https://design.sparebank1.no/styleguidist/index.html#errorfieldmessage in IE). This is due to IE not supporting data-URI with non-base64 encoded svg's (ref. https://stackoverflow.com/a/27322138/1163878). The errors were introduced in https://github.com/SpareBank1/designsystem/commit/0baa0a88655c724462ab3af2b78aa0f51e91a74e#diff-f022b40960b75ca7f943838227dc8056

#### What is the expected behavior? 
Icons in error/info/success message

#### What is the actual behavior?
Empty circle in IE

#### Steps to reproduce
Open https://design.sparebank1.no/styleguidist/index.html#errorfieldmessage in IE

**Comment by antidecaf** [comment]
Fixed via #343

**Comment by marthall** [comment]
This was actually not fixed in last PR due to some minor issues. New PR opened
