### ISSUE TITLE
SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#358]
A recent upgrade of JSDom (v. 11.12) includes support for window.localStorage and other features. This in turn causes all Jest tests to fail with:

`SecurityError: localStorage is not available for opaque origins`

For reference, see https://github.com/facebook/jest/issues/6766

**Comment by kwltrs** [comment]
Will be fixed in jest: facebook/jest#6792

**Comment by ivarni** [comment]
The workaround untill they do is to add the `testUrl` option

**Comment by antidecaf** [comment]
The fix has been released in jest 23.5.0
