### ISSUE TITLE
AccountSelector 'pagination scrolling', render window, performance optimalisation

### ISSUE THREAD

**Issue by ksawerysb1** [SpareBank1/designsystem#367]
#### Which package is this issue related to?
ffe-account-selector-react
#### Describe your issue (screenshots welcome!)
When populating the component with massive amount of data we should just render a data window that is visible to the scroll position instead of the whole dataset. A lot of data generates too much eventing and virtual dom diffing and JS garbage collection problems so we should use selective rendering techniques to make the component useful for big datasets.
#### What is the expected behavior? 
No lagging, no crashing of browsers on limited memory machines when big datasets populate the component. 
#### What is the actual behavior?
Performance problems on big datasets.
#### Steps to reproduce
Populate the component with thousands of rows.

**Comment by ivarni** [comment]
We've been using [react-window](https://github.com/bvaughn/react-window) recently for a massive (~3000 elements) select-dropdown.

Worked like a charm.

**Comment by ksawerysb1** [comment]
The issue can be extended to all searchable dropdowns with custom rows and rendering that might slow down the experience with big datasets.

**Comment by antidecaf** [comment]
Is this a problem that occurs on a regular basis? As in, should we fix it in ffe-account-selector-react/whatever other relevant components, or leave it up to the consumer to fix in their apps?

**Comment by ksawerysb1** [comment]
@antidecaf I suppose the best place to fix this is ffe-account-selector-react. It should be easy to pick a component and avoid reinventing the wheel.
