### ISSUE TITLE
Checkbox performance of check animation

### ISSUE THREAD

**Issue by ksawerysb1** [SpareBank1/designsystem#368]
#### Which package is this issue related to?
ffe-checkbox-react
#### Describe your issue (screenshots welcome!)
A massive amount of checkboxes on one page that start the "check" animation at the same time might cause perfomance problems. Would be good to have a "light" version without the custom animation and other eye candy that might slow down the frontend performance if a massive amount of data is to be displayed. 
#### What is the expected behavior? 
Performance that is similar to the default browser `<input type="checkbox"/>`, no browser crash or slowdown. A "fast"/"lightweight" feature toggle on the component to give the developer an option to use  a lot of checkboxes on a single page. 
#### What is the actual behavior?
Thousands of checkbox animations triggered at the same time cause performance problems, browser might hang or crash.
#### Steps to reproduce
Render thousands of (checked) checkboxes on one page. To simulate slower machines use cpu throttling or a VM with limited resources. 
Compare performance with the default `<input type="checkbox"/>`.

**Comment by ivarni** [comment]
I am thinking that we don't need the animation if the checkbox is rendered as checked the first time, only if it goes from unchecked to checked but I've no idea how that could be done in an orderly manner.

**Comment by ksawerysb1** [comment]
Yes, a kind of only onclick animation might solve the animation problem on data load/re-load.
I haven't been digging down every performance problem with the component but I have made a comparison of perfomance with the FFE component and default input checkbox in thousands, and there was a massive difference in browser responsiveness between the two.

**Comment by kwltrs** [comment]
Is this a real world issue, like do we actually have thousands of checkboxes on a page?

**Comment by ksawerysb1** [comment]
There are forms where clients want no pagination and hundreds of rows with multiple checkboxes.
Couple of hundreds might still work but when we are in the thousands some browsers just can't handle it, especially in IE with limited memory.
Otherwise we have to change functionality just to be able to use better looking checkboxes...

**Comment by ksawerysb1** [comment]
Also it seems that generally displaying massive amounts of react components on one page is a problem compared to the vanilla html equivalents. The optimal situation would be if we didn't have to think about what underlying framework we use for rendering when it comes to the amount of data we want to display. That is rendering 10000 `<input type="checkbox"> `(which was no problem before "reactification") having the same performance (responsiveness) as 10000 FFE checkboxes (same goes to all other components).
