### ISSUE TITLE
Datepicker - not able to open again on iPhone Safari

### ISSUE THREAD

**Issue by cecilieboe** [SpareBank1/designsystem#371]
#### Which package is this issue related to?
ffe-datepicker-react

#### Describe your issue (screenshots welcome!)
* Open datepicker in Safari on iPhone (SE) by clicking on the prechosen date
* Choose a date -> the datepicker closes but still has focus
* Click on the datepicker again to try to repopen it - not possible

Also, clicking outside the datepicker when it is open does not make it close.

#### What is the expected behavior? 
* Able to reopen the datepicker
* Able to close the datepicker by clicking outside it

#### What is the actual behavior?
* Not able to reopen the datepicker
* Datepicker does not close when clicking outside it

#### Steps to reproduce
See description above

**Comment by antidecaf** [comment]
It appears tapping the label will open the datepicker, but not tapping the actual input.
