### ISSUE TITLE
Future-proof React 17 components

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#372]
#### Which package is this issue related to?
A subset of our React packages:
- `ffe-account-selector-react`
- `ffe-datepicker-react`
- `ffe-decorators-react`
- `ffe-tables-react`

#### Describe your issue (screenshots welcome!)
In React 17, a few lifecycle methods (`componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate`) will be deprecated and removed. 

In order to simplify this coming update, we should rewrite all components so that they use the modern alternatives. 

To ensure that people still running older versions of React still can use our component library, any usage of [`static getDerivedStateFromProps`](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) and [`getSnapshotBeforeUpdate`](https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate) must lead to polyfilling the component in question with the `react-lifecycle-compat` polyfill. You can find it here: https://github.com/reactjs/react-lifecycles-compat

**Comment by ivarni** [comment]
deprecated **and** removed? 😱

**Comment by selbekk** [comment]
Well, they are renamed to `UNSAFE_componentWill*`, so you can still use them for a while longer if you don't have the time to rewrite.

**Comment by kwltrs** [comment]
This is road map material. If there is no other reason for changing the lifecycle callbacks (and thus forcing consumers to upgrade react or polyfilling stuff) than avoiding deprecation warnings, I feel we should wait until an upgrade would make it more worth it.

**Comment by selbekk** [comment]
Just for reference - the polyfill is 916 bytes gzipped, and will most likely be included in all large libraries (react-redux, react-router etc) for the foreseeable future. In other words - there isn't a real cost connected to this.

Since this imo needs to be done at some point - what's the reasoning for not doing it now?

**Comment by kwltrs** [comment]
The cost isn't the file size of the polyfill, but the cost of development when having to upgrade or polyfill out of the blue.

**Comment by selbekk** [comment]
That cost is fully contained within FFE - the polyfill is applied in FFE code only, and will make our components backwards compatible, delaying the cost of upgrading as well.

**Comment by ivarni** [comment]
As far as the deprecated lifecycle callbacks are concerned, only the *UNSAFE_* prefixed names will work in 17.x but for anyone using very old versions those names will not work so using them would potentially be a breaking change. It seems better to rewrite the components that use these to instead use one of the alternatives.
