### ISSUE TITLE
Save space for error messages in order to avoid page jumps on validation

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#381]
#### Which package is this issue related to?

ffe-form

#### Describe your issue (screenshots welcome!)

In some instances the page layout may jump when validation error messages are inserted, because an extra line of content is injected into the page flow.

Without error message:

![image](https://user-images.githubusercontent.com/463847/44525238-a2dbd080-a6e0-11e8-9b77-87f16ec278f4.png)

With error message:

![image](https://user-images.githubusercontent.com/463847/44525254-af602900-a6e0-11e8-8ca4-4add50e0ccf0.png)

This can be avoided by saving the space needed for an error message by default (padding, height, etc), then positioning the error message `absolute` or in other ways style it so that it does not affect the height of its containing block.

#### What is the expected behavior? 

The page flow should not change on validation.

#### What is the actual behavior?

The page jumps.

**Comment by ivarni** [comment]
For this to work, we'll have to require that no error message ever wraps to the next line, right?

**Comment by antidecaf** [comment]
The consensus seems to be that as a general guideline they shouldn't wrap, and in instances where the error message needs to be more than one line of text for whatever reason, we are willing to live with the layout shift.

**Comment by ivarni** [comment]
Then I guess `absolute` positioning is out of the question :)

Maybe it's possible to do something with collapsing margins?

**Comment by antidecaf** [comment]
Yeah, good point. :) Collapsing margins may indeed be a better approach.

**Comment by ivarni** [comment]
![Peek 2019-05-09 11-51](https://user-images.githubusercontent.com/379849/57444761-2af30d80-7251-11e9-8d4c-3176fcf39d36.gif)

@antidecaf You were thinking about something like this? Anything that makes the error-message larger than lineheight will still shift the layout.

I obviously had to increase the bottom margin of inputgroups (well, actually inputs contained in inputgroups) to leave open room for the error, I am unsure if that is a breaking change or not? And should I put in an opt-out prop for those that absolutely do not want the extra margins for some reason and rather would take the layout shift?

Also, haven't tested this with inline/text-like but can do that if we still want this.

**Comment by antidecaf** [comment]
Yes, this is pretty much what I had in mind. I'm not really sure if this is really a breaking change either, but there will be visual diffs, I suppose. Anyway, given the age of this issue, perhaps we should run it by the designers at the next forum?

**Comment by ivarni** [comment]
@antidecaf Sure, but given previous experiences with doing that it's gonna end up burying the issue completely :D Anyway, it's fairly easy to solve with collapsing margins if they ever get back to us on it.

**Comment by antidecaf** [comment]
@ivarni Lol, I mean, if you already have an implementation ready anyway, you might as well send a PR. :sunglasses:

**Comment by ivarni** [comment]
@antidecaf That was what I was thinking, and then we can instead ask if they want us to remove it. It needs some polishing but there's not a lot of work really.

**Comment by ivarni** [comment]
![30lwj1](https://user-images.githubusercontent.com/379849/57515475-065f6a00-7313-11e9-91fa-f77884ca2260.jpg)

**Comment by ivarni** [comment]
@antidecaf The radio blocks are giving me grief..

```html
<fieldset class="ffe-fieldset ffe-input-group">
    <legend class="ffe-form-label ffe-form-label--block">Velg ja eller nei</legend>
    <div class="ffe-radio-block" />
    <div class="ffe-radio-block" />
    <div class="ffe-field-error-message">Feil valg</div>
</fieldset>
 ```

Given the above HTML, a selector like 
```css
.ffe-fieldset {
    .ffe-radio-block:last-child {
        margin-bottom: 30px;
    }
}
```

isn't matching the last radio-block because there is a different child in the mix. `:last-of-type` also fails to match. It stops matching the moment the div with the error message shows up.

Any tips?

**Comment by ivarni** [comment]
This [is supposed to work](https://codepen.io/anon/pen/pmywNQ) so I must be doing something wrong somewhere

**Comment by antidecaf** [comment]
`last-of-type` doesn't target the last element with a class, but the last one of a given type of element afaik. So in this case, `.ffe-field-error-message` is the last of type `div` and thus your selector would only be valid if the last div inside the container had the `.ffe-radio-block` class. Maybe the error message should be a paragraph in stead of a div?

**Comment by ivarni** [comment]
@antidecaf Ah, that makes sense. I always get the Benny Hill theme playing in my head when I write CSS and this would be why.

So there's no way of writing a selector to hit the last element of class `.ffe-radio-block` in this instance? I suppose the error message could be a `p` though, just feels like this should be possible without changing it.

**Comment by antidecaf** [comment]
I'm not entirely sure if this works, but maybe fooling the definition of type using an attribute selector might do the trick? Something along the lines of:
`[class='ffe-radio-block']:last-of-type`

**Comment by ivarni** [comment]
I'll try that later, and if not I can swap the error element to a `p`.

`:first-of-type` did work, so I could do
```css
.ffe-radio-block {
    margin-top: -10px;
    margin-bottom: 30px;

   &:first-of-type {
       margin-top: 20px;
   }
}
```
But I kinda threw up in my mouth a little so unless your trick works I'll go with a `p`.
