### ISSUE TITLE
Grid vs spacing

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#388]
[ffe-grid](https://github.com/SpareBank1/designsystem/tree/develop/packages/ffe-grid)[(-react)](https://github.com/SpareBank1/designsystem/tree/develop/packages/ffe-icons-react) comes with gutters, which makes it difficult to nest grids or use it in any other context than page layout. This has caused some issues in cases where it has been used for internal layout in components or sections. At the moment ffe-grid is the only alternative for creating layouts, and we need to figure out how to handle this in components.

One suggestion (originally intended to standardize spacing in general) is to remove all hardcoded spacing from the grid and other components, to be replaced by a set of predefined variables throughout the design system. In the case of ffe-grid, could removing the gutters altogether in favor of letting the contents of each column deal with spacing be a possible way forward?

Input wanted!

**Comment by ivarni** [comment]
If we have to go down that road I would much rather see an option to turn the padding off than it being removed. I'd prefer to not have to synchronize spacing across all the components in my app just to have content line up vertically across rows.

Or maybe rename this to `ffe-layout` and create a new grid or something, though to be honest there are already tons of grid-libraries around one could use if the goal is just to not have to deal with flexbox in components?

**Comment by nataliefl** [comment]
Is there a reason padding was chosen over margins for the grid? I see margin collapse as useful for solving some of these issues. Edit: I see now that the horizontal margins does not collapse, making them less useful in this case.

**Comment by antidecaf** [comment]
Another suggestion is to add a `--no-spacing` (or something) modifier to `.ffe-grid` in order to allow for using the grid in internal/component layouts. That way we won't have to refactor every implementation, but still be able to nest grids within grids.
