### ISSUE TITLE
Contributing: Hjelp designere bidra til designsystemet

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#39]
Contributing-guiden er veldig utviklersenteret. Hvordan hjelper vi designerne komme i gang som bidragsytere? Hva er de oftest stilte spørsmålene? Hvordan er workflowen?

Vi har gjort noen undersøkelser internt, men vi må få dokumentert det her på Github :writing_hand:

**Comment by selbekk** [comment]
Burde vi dele opp contributing i en design- og en utviklerdel? Det er to veldige forskjellige domener med veldig forskjellige behov.

**Comment by hodoea** [comment]
God idè! Jeg skal ta en liten gjennomgang av Github med designavdelingen på fredag, forhåpentligvis onboarde flere av de og legge til de i github repoet. Btw må man lage en pull request for å endre tekst i readme og contribute?

**Comment by selbekk** [comment]
Jepp. Det gjør du ganske enkelt ved å finne dokumentasjonen du vil endre på (f.eks. `CONTRIBUTE.md`) og trykke på blyanten øverst i høyre hjørne. Da får du opp en editor som gjør at du kan endre ting.

Dette burde stå i CONTRIBUTE.md etterhvert - eller gjør det det i ditt nye PR @wkillerud ?

**Comment by wkillerud** [comment]
Jeg lenker til de relevante hjelpesidene til Github for det ja @selbekk

**Comment by hodoea** [comment]
@selbekk Ja, jeg la merke til edit ikonet, men viste seg at jeg ikke hadde write-access  så da kom det "fork" mulighet opp. :) Skal prøve igjen, Anders la meg til nå.

**Comment by wkillerud** [comment]
Da er "runde én" med forbedringer i boks. Jeg lar issuet være åpent en stund til (i hvertfall til påske), så om det er noen endringsønsker eller forslag så er det bare å slenge inn en kommentar :dancing_men: 

Det med god dokumentasjon er jo et evighetsprosjekt, så etter påske lukker jeg denne saken så får vi heller lage nye om vi kommer på noe lurt :smile:
