### ISSUE TITLE
Missing necessary dependencies

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#399]
#### Which package is this issue related to?
ffe-form-react
ffe-system-message-react

#### Describe your issue (screenshots welcome!)
The mentioned packages depends on `react-collapse`,
but does not have dependency on its peerDependency `react-motion`.

This issue became apparent to me when `react-motion` was removed
as a dependency from `ffe-accordion-react`.

#### What is the expected behavior? 
I expect packages to have a dependency on packages which are
peer dependencies of the packages that the package depends on..
You know what I mean!

#### What is the actual behavior?
The mentioned packages does not have the necessary dependencies.

**Comment by ivarni** [comment]
This begs the question.... how many dependencies would a dependency have if a peer dependency was a dependency?
