### ISSUE TITLE
Expand button "X" animates in from the top-right corner

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#4]
When the expand button animates in its "close X" the X comes down from and is animated out to the top right. This animation looks odd and should perhaps be redesigned. Extract the attached ZIP to see a video recording of the issue. 

[Knapp.zip](https://github.com/SpareBank1/designsystem/files/1758543/Knapp.zip)

Relevant code can be found here: https://github.com/SpareBank1/designsystem/blob/master/packages/ffe-buttons/less/expand-button.less

**Comment by selbekk** [comment]
This will be fixed by the pending button rewrite PR

**Comment by wkillerud** [comment]
Fixed by #27
