### ISSUE TITLE
ffe-searchable-dropdown-react: Turn off browsers default autocomplete

### ISSUE THREAD

**Issue by lotorvik** [SpareBank1/designsystem#410]
#### Which package is this issue related to?
ffe-searchable-dropdown-react

#### Describe your issue (screenshots welcome!)
The browsers default autocomplete gives suggestions in addition to the autocomplete list from this component.
![autocomplete](https://user-images.githubusercontent.com/866562/45750290-b8c0b080-bc0e-11e8-868c-6b2e9a29ba0b.png)

This is solved by adding autcomplete="off" to the input field. For React the correct value is autoComplete: 'off' that ned to be added to InputField.js. I know ffe recomend sending in these values as props, but I'm not sure if this is needed here. The two only valid options are on and off and there is no reason to ever wanting this to be on.  I know there are some quirks with the autcomplete where it do not work unless you send and invalid value like off, but I think that is more related to login fields. You can read more about autocomplete here https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

#### What is the expected behavior?
Do not get suggestions from the browser when you click the search input. 

#### What is the actual behavior?
You do get a popup with previous suggestions in addition to the components suggestions, when clicking the search input

#### Steps to reproduce
- Complete a form registration with an item from the dropdown
- Go back to the form and click the empty search field and get previous suggestions

**Comment by ivarni** [comment]
+1 on just always disabling it

**Comment by pethel** [comment]
I just used this component and I think you have to do it on the actual <form/> element in Chrome.

**Comment by lotorvik** [comment]
Yeah doing it on the actual input element is what i suggested. I have tested this on the project SAM and it solves the problem.

PS: I messed up and did not know I could only have one PR active a time, so the autocomplete="off" got included in https://github.com/SpareBank1/designsystem/pull/413 ...

**Comment by benmatthews** [comment]
+1 for always disabling it - this should be the default behaviour as this is how you expect the component to work.

**Comment by kwltrs** [comment]
Resolved by #413
