### ISSUE TITLE
Designsystem do not build on windows

### ISSUE THREAD

**Issue by lotorvik** [SpareBank1/designsystem#411]
#### Which package is this issue related to?
ffe-chart-donut-react and ffe-sb1-logos

#### Describe your issue (screenshots welcome!)
Designsystem do not build on windows

#### What is the expected behavior? 
It should build the same way on Windows as it does on Mac OS and Linux

#### What is the actual behavior?
It fail when you try and build on Windows

ffe-chart-donut-react/package.json fail with:
>  'cp' is not recognized as an internal or external command, operable program or batch file.

It is becouse we use the cp command under build in package.json and  that is not a valid command on Windows. Should probably replace cp with a node package that is platform independant

ffe-sb1-logos/package.json fails with:
> '.' is not recognized as an internal or external command, operable program or batch file.

If we change `"build": "./bin/build-preview.js"` to `"build": "node ./bin/build-preview.js"` it runs on windows. Not sure if this causes problems for Mac OS and Linux.

#### Steps to reproduce
Run `npm run-script build` on a Windows machine

**Comment by ivarni** [comment]
https://www.npmjs.com/package/cpy looks like a good option for copying.

Travis will build the branch if you open a PR, if `ffe-sb1-logos` builds fine there it should be good.

**Comment by lotorvik** [comment]
I did not get cpy to work in the the npm script. Instead of using time to get it to work I tried a different package and [copyfiles](https://www.npmjs.com/package/copyfiles) worked as expected.

**Comment by lotorvik** [comment]
Closing since it is fixed in #413
