### ISSUE TITLE
Peer dependencies are not maintained (need update for ffe-core@14)

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#415]
#### Which package is this issue related to?
Many of our packages

#### Describe your issue (screenshots welcome!)
I have just now installed all the newest versions of ffe-packages,
but peer dependencies are not updated for ffe-core@14.
All of the following warnings are just noise - all packages works fine with ffe-core@14:

```
npm WARN @sb1/ffe-buttons@8.0.7 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-buttons-react@11.1.7 requires a peer of @sb1/ffe-buttons@^7.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-context-message@3.0.18 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-core-react@3.2.2 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-datepicker@5.0.32 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-form-react@3.2.3 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-grid@10.0.4 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-grid-react@9.0.2 requires a peer of @sb1/ffe-grid@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-layout-legacy@1.0.2 requires a peer of @sb1/ffe-core@^12.2.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-lists@5.0.17 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-message-box@6.0.5 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-searchable-dropdown-react@6.0.9 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-spinner@3.0.17 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-tables@9.0.16 requires a peer of @sb1/ffe-core@^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
```

#### What is the expected behavior? 
I expect peerDependency warnings to be of significance.

#### What is the actual behavior?
PeerDependencies are not maintained, and thus their warnings become noise instead of useful information.

#### Steps to reproduce
Upgrade to ffe-core@14 and run npm install.

#### Other notes
This issue is in one way just a simple task to update peerDependencies.
I also hope it will serve as a reminder that if you create a new major version of a package,
please check and update packages which has your package as a peerDependency.

**Comment by henrikhermansen** [comment]
It seems this problem applies to some react packages and their peerDependencies of their style packages as well:
```
npm WARN @sb1/ffe-accordion-react@6.1.0 requires a peer of @sb1/ffe-accordion@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-buttons-react@11.1.7 requires a peer of @sb1/ffe-buttons@^7.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-grid-react@9.0.2 requires a peer of @sb1/ffe-grid@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sb1/ffe-tabs-react@4.0.1 requires a peer of @sb1/ffe-tabs@^4.1.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by kwltrs** [comment]
Upgrading of dependencies is done by lerna, but it seems lerna does not upgrade peer dependencies anymore since https://github.com/lerna/lerna/pull/1187.
(Possibly related issue: https://github.com/lerna/lerna/issues/1575).

**Comment by selbekk** [comment]
Perhaps we should... just skip peer dependencies then? I agree that the warnings are a huge PITA when installing these packages - we should at least do _something_ about it

**Comment by ivarni** [comment]
We need **some** way to tell a consumer of package A which version(s) of package B it supports? If someone installs a new major of a less-package they might need a corresponding bump for the -react package.

Can't we just add a reminder to the create PR template and see if that helps people remember to do it?

**Comment by selbekk** [comment]
I'm okay with that :+1:

**Comment by kwltrs** [comment]
The Real Problem™ is that we currently don't have any setup for testing the backward compatibility of an internal peer dependencies. Thus it is hard to tell where to set the lower limit for the version range of a peer dependency. Should we just require the latest major release in `peerDependencies` and leave to a consumer to take the risk of using an older version?

**Comment by ivarni** [comment]
We don't have a way to do it automatically, but that doesn't mean we don't have a way to do it (or rather, the person making the breaking change has a way to do it).

If we're just automatically requiring the latest major we might as well omit it completely.

**Comment by ivarni** [comment]
I've changed my mind on this to be honest. Especially in light of [greenkeeper](https://github.com/SpareBank1/designsystem/pull/644) bugging us with new peer-deps even though the current `>=`  versions that were set already covers the new one.

It's noise, we're not able to maintain it and if we explicitly mention intercrossing dependencies in the changelog anyone updating to a new major can be made aware of it that way instead.

I think we can cover this by spending more than 20 seconds on writing commit messages so we get a better description in the changelog about which new versions depend on which new versions of other packages.
