### ISSUE TITLE
ButtonGroup does not use fill widht

### ISSUE THREAD

**Issue by pethel** [SpareBank1/designsystem#418]
`<ButtonGroup />` does not use full width on mobile when placed in a standard `<GridCol/>`. In this case its because the `<GridCol/>` has a `display: flex`. In the documentation this is not an issue. 

Is this something that should be fixed? I would assume it standard to use the `<ButtonGroup />` as child of `<GridCol/>` in real life applications. 

![image](https://user-images.githubusercontent.com/2248579/45941076-ceeaba00-bfdc-11e8-9f64-b77971c5c459.png)

**Comment by antidecaf** [comment]
Both `GridCol` and `ButtonGroup` render elements with `display: flex`. It's a bit difficult to tell what might be wrong in this case without seeing the actual implementation. A few things to double check:

* Is the button group column wrapped in it's own `GridRow`?
* Is there a modifier in use somewhere to align text or contents to the left?
* Are the buttons the standard variety or the inline version?

For reference, a fairly standard implementation with no modifiers:

```js
<Grid>
    <GridRow>
        <GridCol>
            <ButtonGroup>
                <ActionButton>Neste</ActionButton>
                <TertiaryButton element="a" href="#buttongroup">
                    Lenke
                </TertiaryButton>
            </ButtonGroup>
        </GridCol>
    </GridRow>
</Grid>
```

![image](https://user-images.githubusercontent.com/463847/45943441-9b149200-bfe6-11e8-85a8-1ce156823b56.png)

**Comment by pethel** [comment]
This is my implementation. The center prop on the `<GridCol />` I beleive is the difference
```
<Grid noTopPadding={ true }>
   <GridRow>
      <GridCol sm={ 12 } lg={ { cols: 6, offset: 3 } } center={ true }>
          <ButtonGroup thin={ true }>
              { page > 0 && (<SecondaryButton type="button" onClick={ this.previous }>{ backButtonText </SecondaryButton> ) }
              { !isLastPage && (<PrimaryButton type="submit">{ primaryButtonText }</PrimaryButton>) }
              { isLastPage && (<ActionButton type="submit" isLoading={ submitting }>{ actionButtonText </ActionButton>) }
         </ButtonGroup>
      </GridCol>
  </GridRow>
</Grid>
```

**Comment by antidecaf** [comment]
I just tested this with no issues.

![image](https://user-images.githubusercontent.com/463847/45944785-afa75900-bfeb-11e8-9653-77dd822c7503.png)

The center prop aligns items to the center of the column, which doesn't seem to happen in your case. In the screenshot there also seems to be a `TertiaryButton` present, but I can't see it in your snippet. The fact that everything is left aligned makes it look like some styling is missing. Have you checked that all dependencies are up to date? If no luck, send me a message on hipchat and we can take a look at it together. :)

**Comment by pethel** [comment]
The TertiaryButton is not present and rendered in another component. Well then I have to investigate more

**Comment by antidecaf** [comment]
Turns out buttongroups do not occupy 100% width by default after all. PR coming up!
