### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by benmatthews** [SpareBank1/designsystem#419]
#### Which package is this issue related to?
ffe-sb1-logos

#### Describe your issue (screenshots welcome!)
There is no favicon.ico file available in FFE.

#### What is the expected behavior? 
The favicon is available - e.g. from ffe-sb1-logos package.

#### What is the actual behavior?
Each project has to provide the favicon.ico from somewhere - probably downloaded from sparebank1.no and saved to local project.

#### Steps to reproduce
N/A

**Comment by kwltrs** [comment]
:+1:

**Comment by selbekk** [comment]
Scope creepy feature suggestion: Adding more shareable assets there as well. App icons etc would also be great to share from the same place.
