### ISSUE TITLE
Make tab component smarter!

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#434]
#### Which package is this issue related to?
ffe-tabs-react

#### Describe your feature request
I'd like to request that we include a tabs component that handles the logic of switching between tabs. It's a mundane task to implement, and you'll most likely forget to attach at least some of the required aria labels.

#### Example

I've created a sample implementation here:

https://codesandbox.io/s/j34kvyw0x5

The core implementation is flexible enough for us to implement most (if not any) design, and I think it's accessible-ish by now.

What do you think? Is this something we want into our component library, or is this userland stuff?

**Comment by selbekk** [comment]
I'll try it out in an app first, and come with a pull request later if people like this.

How should we make the API? It'll be a pretty breaking change for the existing API, since we now can handle the state for the consumers - so creating a new set of components could be an option.

**Comment by ivarni** [comment]
Break all the changes in my opinion, otherwise we'll have to maintain two sets of visually identical components and also make it more confusioning for new consumers.

But I think that in general it's a good thing to let things be "battle tested" a little in an actual app (or maybe even two?) before adding it to FFE.

**Comment by selbekk** [comment]
> But I think that in general it's a good thing to let things be "battle tested" a little in an actual app (or maybe even two?) before adding it to FFE.

I agree. I'll add it to the project I'm currently working on as a first test :)

**Comment by hdaljord** [comment]
Jeg satt akkurat og så på TabButtonGroup og TabButton og ser at disse ikke setter riktig role og fant dette issuet. Jeg vet at selbekk ikke er her lenger, men er det noen som vet om denne er testet og om vi bør jobbe videre med den?

Dagens TabButtonGroup setter role="group", men burde hatt role="tablist". Deretter skulle hver TabButton hatt role="tab". 

Jeg ser at eksempelet i issuet ikke implementerer helt korrekt tastaturnavigasjon, da eksempelet gjør at ikke-aktive faner kommer inn i tabrekkefølgen før tabpanel, mens det egentlig bare er aktiv fane som skal være i tabrekkefølge og så skal man navigere til inaktive faner vha piltaster. Dvs. eksempelet kan ikke brukes helt slik det står, men det kan jobbes videre med.

**Comment by antidecaf** [comment]
Kjenner ikke til hvor langt dette kom, men ser ikke noen åpenbare grunner til å ikke fikse det hvis det er trivielt. :)

**Comment by selbekk** [comment]
👻👻👻

**Comment by kwltrs** [comment]
Blir fikset med #1338
