### ISSUE TITLE
The header could use a z-index

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#436]
#### Which package is this issue related to?

`ffe-header`

#### Describe your issue (screenshots welcome!)

We have a massive background circle in one of apps that is basically used for creating a "rounded" divider line in one of our apps. We're using z-index to hide it on mobile screens.

The ffe-header does not come with a z-index and disappears behind this background.

I can't imagine anyone ever wanting the header to be hidden under other content on the sreen so I suggest giving it a z-index of **over 9000**.

Alternatively we can override the style locally if someone sees an issue with setting a z-index on the `.ffe-header` class.

**Comment by antidecaf** [comment]
Z-index is specified for `ffe-header__user-nav-list` and `ffe-header__site-nav-list`. If you need it on the root class, feel free to submit a PR!
