### ISSUE TITLE
ffe-formatters: minDecimals for formatPercentage

### ISSUE THREAD

**Issue by cecilieboe** [SpareBank1/designsystem#438]
#### Which package is this issue related to?
ffe-formatters

#### Describe your issue (screenshots welcome!)
I want to use formatPercentage to show "1,00 %", but by now it is only possible to specify the maximum number of decimals, not the minimum number, so formatPercentage(1) gives "1 %".

#### What is the expected behavior? 
I would like to be able to get "1,00 %" as the formatted percentage.

#### What is the actual behavior?
It is not possible to get "1,00 %" as the output of formatPercentage.

#### Steps to reproduce
formatPercentage(1)

**Comment by kwltrs** [comment]
Fixed by #439
