### ISSUE TITLE
Tertiary button has no underline in inline button group

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#446]
#### Which package is this issue related to?

ffe-buttons

#### Describe your issue (screenshots welcome!)
Tertiary button lacks underline when it is used in an inline button group:

![image](https://user-images.githubusercontent.com/36953762/46403867-f55ad480-c703-11e8-9ee1-ae91371b1b2d.png)

#### What is the expected behavior? 
I expect tertiary button to always have an underline, as it has in all other button groups. 

![image](https://user-images.githubusercontent.com/36953762/46403963-32bf6200-c704-11e8-9b57-ede0fe5df5e3.png)

#### What is the actual behavior?
No underline when placed inside an inline button group.
#### Steps to reproduce

This can be seen in the design guide at https://design.sparebank1.no/styleguidist/index.html#!/ButtonGroup, scroll down to Inline

**Comment by hdaljord** [comment]
I can create a PR for this, but probably not before next week.

**Comment by benmatthews** [comment]
The underline is created with a pseudo element which has `display:inline` so it has 0 width because it has no content.

```
.ffe-inline-button--tertiary {
    align-content: center;
    color: @ffe-blue-azure;
    flex-wrap: wrap;

    &::after {
        border-bottom: solid 1px currentColor;
        content: ' ';
        width: 100%;
    }
}
```

I think you can fix this by just adding `display:inherit` to the pseudo element ?
