### ISSUE TITLE
Disable sat/sun in Datepicker

### ISSUE THREAD

**Issue by mvmagnussen** [SpareBank1/designsystem#453]
package: ffe-datepicker-react

issue: add ability to allow the user to pick business days only, ie. saturdays and sundays (possibly bank holidays as well) are disabled

**Comment by ivarni** [comment]
Could the consumer provide a function `isEnabledDay(..)` or something that returns true/false and then the datepicker can just use that to check if it should disable each day in the current view? That way we'll cover all the potential usecases for disabling days in one swoop.

**Comment by selbekk** [comment]
that's a neat approach @ivarni - +1 on that one.

**Comment by ivarni** [comment]
@mvmagnussen Is still desired functionality? What should a disabled date look like in the pop-up? What should happen if the user manually enters a disabled date?
