### ISSUE TITLE
Adding background color class to a row cause row content to fill entire width

### ISSUE THREAD

**Issue by nataliefl** [SpareBank1/designsystem#454]
#### Which package is this issue related to?
ffe-grid
#### Describe your issue (screenshots welcome!)
Adding a row color class e.g. **ffe-grid__row--bg-green mint** cause the row to fill the width of the container, which makes sense, but the content also moves with it. 
#### What is the expected behavior? 
I expect the row to fill max-width and the content inside it to remain where it is. Ignoring the base width set by @ffe-grid-width should be a separate class if anything.

#### Steps to reproduce
https://codepen.io/magnus-lien/pen/vVyQPw?editors=1100#0

**Comment by ivarni** [comment]
When using a background color you need to wrap the columns inside the row in a `<div class="ffe-grid__row-wrapper">`

https://codepen.io/anon/pen/jeyLzG?editors=1100#0

This used to be documented before we migrated to using styleguidist but seems to have been lost in that process.

**Comment by nataliefl** [comment]
@ivarni I found it documented in the package readme but missing in the examples inlined in the less file (which I used).
