### ISSUE TITLE
X instead of check support in CheckList

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#471]
#### Which package is this issue related to?

ffe-lists

#### Describe your issue (screenshots welcome!)

I am using `ffe-check-list` to show a list of features for a given product - some of which are included and some that are not. I want to use our `KryssIkon` icon in `@ffe-red` for noting when something is not.

I've created a local override, which looks like this:

![screenshot of how the not included checkmark would look like](https://user-images.githubusercontent.com/1307267/47498904-e678c500-d85e-11e8-9a95-b45e0884872f.png)

I've implemented it with a class on the `li` element (`ffe-check-list__item--nope`), but I'm open for suggestions on how it could be solved.

**Comment by antidecaf** [comment]
LGTM!
