### ISSUE TITLE
Gjøre det ulovlig/umulig å skrive inn en dato utenfor gyldig datointervall i ffe-datepicker-react

### ISSUE THREAD

**Issue by GeirLoken** [SpareBank1/designsystem#481]
#### Which package is this issue related to?
ffe-datepicker-react

#### Describe your issue (screenshots welcome!)
Ønsker å gjøre det umulig å endre til en dato før minDate eller etter maxDate ved å skrive inn en dato i tekstfeltet.

#### What is the expected behavior? 
Valgt dato settes tilbake til forrige valgte dato dersom man skriver inn en dato utenfor lovlig datointervall.

#### What is the actual behavior?
Valgt dato settes til en ulovlig dato.

#### Steps to reproduce
Sett maxDate til dagens dato og skriv inn morgendagens dato. Se at valgt dato blir morgendagens dato, selv om denne ikke kan velges i datovelgeren.

**Comment by hdaljord** [comment]
Er det ikke bedre å få en tilbakemelding om hva som er godkjent datointervall enn at datoen bare forandres uten at brukeren får en melding om det? Jeg tror jeg bare ville blitt irritert og antatt at det var en feil om et felt bare forandret verdi uten at jeg forstod hvorfor.

**Comment by GeirLoken** [comment]
Jo, blir nok vanskelig å lage en løsning som håndterer det på noen annen måte enn med en valideringsfeil. Dette var nok bare en av flere ting som har gjort god validering av fra- til-dato litt vanskelig for min del. Etter å ha jobbet litt mer med det, og sett på tilsvarende løsninger i andre use-caser i nettbanken, er det kanskje en felleskomponent for å velge Fra- til-dato jeg hadde ønsket meg. Kan sikkert lukke denne saken.
