### ISSUE TITLE
Datepicker - don't open calendar when "external" change of min- or maxDate results in invalid date interval

### ISSUE THREAD

**Issue by GeirLoken** [SpareBank1/designsystem#482]
#### Which package is this issue related to?
ffe-datepicker-react

#### Describe your issue (screenshots welcome!)
An "external" change in min- or maxDate makes the datepicker pop up if the selected date is outside the valid date range after the change.
![image](https://user-images.githubusercontent.com/43747501/47713414-82794680-dc3a-11e8-9ebc-db2475ad1deb.png)

#### What is the expected behavior? 
The datepicker should not pop up when a change in min- or maxDate has resulted in an invalid date range.

#### What is the actual behavior?
The datepicker pops up even if focus is somewhere else.

#### Steps to reproduce
Create two date fields, "From" and "To". "From" has the date selected in "To" as maxDate, and "To" has the date selected in "From" as minDate.
When changing "From" to a date later than "To", the focus remains in "From", but the calendar/datepicker pops up in "To".

**Comment by torkjels** [comment]
I believe this is solved by https://github.com/SpareBank1/designsystem/pull/663.
