### ISSUE TITLE
Accordion with screen reader

### ISSUE THREAD

**Issue by 42tte** [SpareBank1/designsystem#503]
#### Which package is this issue related to?
ffe-accordion-react

#### Describe your issue (screenshots welcome!)
Needs more testing but usability seems to suffer from extensive/wrong use of wai-aria. Make sure they are needed, used correctly and that they are placed on the correct elements. Examples of things that might be wrong:
* role=tablist & tab on correct elements?
* aria-labelledby might hide real content on element
* no aria-controls on expander
* 

#### Steps to reproduce
Use a screen reader on https://design.sparebank1.no/styleguidist/index.html#!/Accordion

**Comment by pethel** [comment]
#956 skall løse dene.
