### ISSUE TITLE
ffe-grid kaster unødvending warning

### ISSUE THREAD

**Issue by sskogen** [SpareBank1/designsystem#511]
https://github.com/SpareBank1/designsystem/blob/2f7dca400ad87030377fb45072539fcff99884e3/packages/ffe-grid-react/src/utils.dev.js#L29-L50

doc'en beskriver at man skal bruke maks 6 kolonner på medium og 4 på small, men da fylles ikke hele bredden slik det er implementert nå. For å fylle hele bredde på medium og small, må 12 kolonner benyttes, og da får man denne warningen i console. Foreslår å fjerne warning og endre doc. Om man skal endre implementasjon, vil det nok brekke i alle applikasjoner som bruker grid og har designet for små og mellomstore skjermer.

**Comment by antidecaf** [comment]
Relatert issue: #281 

Min personlige oppfatning er at disse warningene er overflødige og bør fjernes helt, men det er delte meninger om dette.

**Comment by ivarni** [comment]
Kan du forklare nærmere hva du mener med at det ikke fyller hele bredden, for det syns jeg høres rart ut. Hvis det er paddingen på utsiden av gridden du tenker på så er det et bevisst valg.

**Comment by selbekk** [comment]
Vi har teknisk sett en 12-kolonnes grid på alle skjermstørrelser. Så når vi sier at du har 4 på liten skjerm og 6 på medium skjerm, mener vi at antallet kolonner må være delbart på henholdsvis 3 eller 2.

Med andre ord - lovlige kolonner på liten skjerm er 3, 6, 9 og 12. Lovlige kolonner på medium skjerm er 2, 4, 6, 8, 10 og 12.

På den måten får vi 4 kolonner (fullbredde delt på 4) på liten skjerm og 6 kolonner på medium skjerm.

Kanskje vi kan forbedre dokumentasjonen litt, så dette gir mer mening?

**Comment by ivarni** [comment]
Kanskje vi bare skal fikse APIet sånn man faktisk angir kolonner som 1, 2, 3 eller 4 på små skjermer og ikke 3, 6, 9 og 12. Det er ikke første gang det dukker opp forvirring rundt dette.

Så kan vi i samme slengen slanke bort en god del CSS-klasser som aldri var tenkt brukt.

**Comment by selbekk** [comment]
Det er en _veldig_ breaking change da - da burde vi i så fall lage en codemod e.l. for å lette overgangen.

**Comment by ivarni** [comment]
Ja, det er ganske breaking og ikke nødvendigvis enkelt å lage en codemod for (hva skal den gjøre der det er brukt "ulovlig" antall kolonner feks), men kanskje det fortsatt er mindre støy enn å ta denne diskusjonen på nytt 4 ganger i året?

Inline-grid biten bør vel i så fall få sine egne komponenter, det bør løse #281 i samme slengen. Hvis jeg forstår det riktig så er det ikke noen retningslinjer rundt dette med totalt antall kolonner for inline-gridden, stemmer det @antidecaf ?

**Comment by sskogen** [comment]
Det var bare en misoppfatning fra min side, mest fordi det er en forskjell på hva som blir beskrevet som kolonner i warningen/doc'en, og hva som gjelder teknisk. 

Når det er sagt, har vi noen få behov for f.eks. knapper til å være sentrert og dekke halve bredden (altså 6 tekniske kolonner) på medium skjerm md={{cols: 6, offset: 3}}. Man kan få til ca det samme visuelt sett ved å bruke md={{cols: 8, offset: 2}}, men da må man også sette maksbredde på knapp og sentrere den horisontalt i sin kolonne. For min del skulle jeg gjerne sluppet warnings i consolen for dette, men det er vel en annen diskusjon.

**Comment by antidecaf** [comment]
Det stemmer, @ivarni!
