### ISSUE TITLE
New button

### ISSUE THREAD

**Issue by ChriBran1** [SpareBank1/designsystem#512]
Vi trenger en ny versjon av en secondary button som er litt
lavere og som passer bedre inn i mindre flater
f.eks. kontoliste og andre flater på mobil.

Fokus states og hvordan knappen er bygd opp
er det samme, kun høyden og størrelse på typografi
er endret. Fargen på teksten er også litt mørkere.
![secondary button mini](https://user-images.githubusercontent.com/37210461/48706876-de156f00-ebfd-11e8-9f5c-7c13a3d952db.png)

**Comment by antidecaf** [comment]
Er dette en separat knapp, eller en variant av sekundærknapp? Burde tilsvarende varianter legges til av alle de forskjellige knappetypene? @sirioc @adidick

**Comment by ChriBran1** [comment]
Jeg tenker dette er en mindre variant av sekundærknapp.
(Mulig vi burde ha mindre varianter av alle knappene våre? Kondenserte elementer som knapper er fortsatt litt store)
Størrelsen på vanlige knapper er 44 i høyden.
Kondenserte knapper har 38 i høyden.
Vår variant er 30 i høyden, samtidig som den bruker "small" typografi (14px)

**Comment by selbekk** [comment]
Hvordan skal denne knappen oppføre seg på større flater?

**Comment by ChriBran1** [comment]
Den oppfører seg likt på større flater. Vi har den liggende ute på desktop i dag også. Hvis man har mye luft kan man bruke større knapp, men denne versjonen er kun tenkt der man har liten plass f.eks. i kontoliste både på mobil og desktop.

**Comment by selbekk** [comment]
Jeg skjønner. Skal den se lik ut for "luftig" og "condensed"-baserte sider? Eller skal den være enda mindre i condensed-versjon?

**Comment by ChriBran1** [comment]
Hvis du har en "luftig" side tenker jeg du bruker større knapp. (Vanlig secondary button)
Versjonen vi diskuterer her er nesten helt lik secondary button vi har i dag, bare mindre. 
Den er også litt mindre enn kondensert secondary button :)

**Comment by selbekk** [comment]
Condensed-versjonen av FFE var jo i utgangspunktet tenkt brukt på fortrinnsvis BM-sider som har høy informasjonstetthet, og burde brukes overalt (condensed grid, condensed knapper, you name it). 

Ikke-condensed-versjonen av FFE - det jeg kaller "luftig"-versjonen - er ment brukt i alle aldre tilfeller. Det er helt sikkert tilfeller der man vil trenge en liten knapp som her (jeg forstår bruksområdet godt), jeg bare lurer på om vi skal gjøre noen tilpasninger for denne knappen på slike condensed sider? Men da høres det kanskje ikke sånn ut.

Har du et godt navn på denne "mini-secondary"-en? :)

**Comment by ChriBran1** [comment]
Jeg skjønner :)
Grunnen til at vi lagde en enda mindre condensed versjon, var at vi trengte en enda mindre knapp enkelte steder. Vi kan kalle den "mini-socondary" eller "secondary-small" siden knappen tar utgangspunkt i small font 14px?

**Comment by adidick-zz** [comment]
Hvor bruker vi den condensed varianten i dag? Er det at den fungere ikke helt optimalt og at vi kunne bare endre det til det som dere trenger nå? Ellers blir den nye størrelsen for liten i "condensed" kontekst?

Grunnen at jeg spør er at jeg husker når den condensed varianten ble laget og tenkte at det var ikke en valdig stor (eller stor nok) forksjell mellom det og den vanlig secondary knapp. Trenger vi tre varianter eller kan vi bare endre "condensed" til å være mindre i størrelse?

Det er kanskje også lurt å se på størrelsen ift 8pt grid for å "future-proof" det og passe på at det passer inn på den ny kommende grid/avstand system.

**Comment by ChriBran1** [comment]
Godt poeng @adidick :)
Jeg opplever at det ikke er så stor kontrast mellom vanlig secondary og condesed, og vi ser et behov for en enda mindre knapp. Mulig vi godt kunne trenge tre versjoner av alle knapper? En stor (vanlig), mellom og minst.

**Comment by hdaljord** [comment]
Dersom det skal være tre ulike størrelser syns jeg størrelsesforholdet burde framgå tydelig av navngivningen på knappene. Det er (for meg) vanskelig å vite hvilken som faktisk er minst av condensed og secondary-mini/secondary-small uten å sjekke implementasjon/dokumentasjon. Kanskje secondary-mini er tydelig nok, men kanskje det er bedre med noe slikt som extra-condensed?

Men egentlig lurte jeg også på om dette kanskje heller bare var en endring av condensed-knappen. Det blir mange valg om man skal ha vanlig, condensed og mini/extra-condensed.

**Comment by antidecaf** [comment]
Tre naturlige størrelser er kanskje liten, vanlig og ekstra stor, sånn i utgangspunktet? Dette kunne med fordel vært modifiere tilgjengelig for alle knapper, sånn for å holde et mønster tydelig. Men om behovet er der er et annet spørsmål. Enig i at to forskjellige condensed-varianter virker litt rart.

**Comment by ivarni** [comment]
Var ikke behovet noe som passet bedre inn i små flater som feks mobil? Hva med å bare endre den vanlige knappen så den passer bra inn på mobil så trenger man ikke noen ny type knapp?

**Comment by antidecaf** [comment]
Behovet var noe som passer inn i små flater som inni tabeller eller lister, også på mobil, sånn jeg forstår screenshotet øverst. Vanlige knapper (også condensed) funker vel i utgangspunktet på mobil isolert sett, men blir i overkant beefy i den typen informasjonstunge kontekster.

**Comment by ChriBran1** [comment]
Extra condensed var et fint navn @hdaljord 
Vi ser behovet for å ha mindre knapper på mobil - i f.eks. kontolista og andre steder med liten plass, men den vanlige knappen blir fort stor og klumpete der @ivarni 
Tidligere har vi brukt tertiary button steder med liten plass, men denne ser litt "desktop" ut

**Comment by ivarni** [comment]
Så kanskje en ny type "tabell-knapp" eller lignende er bedre? Dersom denne bare er tenkt brukt på de stedene? Extra condensed ville i hvert fall ikke sagt meg noe om *hvor* den er tenkt brukt.

**Comment by hdaljord** [comment]
@ChriBran1 Jeg er litt usikker på hvordan tertiary button ser "litt desktop" ut, jeg syns nemlig den ser litt "link" ut og ikke helt knapp i det hele tatt ;) </digresjon>

**Comment by ChriBran1** [comment]
Kanskje vi kan beholde den vanlige størrelsen (den største) og erstatte condensed med vår nye knapp (med eventuelle justeringer). Slik blir det sterkere kontrast mellom de to knappene
, og man har fortsatt bare to ulike størrelser?

**Comment by ChriBran1** [comment]
Helt enig @hdaljord
