### ISSUE TITLE
Switch/toggle 

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#519]
Vi jobber med å få ut Push notifikasjoner i mobilbanken, og har behov for en komponent som har lik design og oppførsel som en native switch/toggle. 

I første skisse så har vi brukt en checkmark men det blir litt misvisende for konteksten vår. 

![checkbox](https://user-images.githubusercontent.com/8971560/48904185-e2d85e00-ee5d-11e8-9bb1-9d90ebead530.png)

Forslag til ny komponent i bruk:

![push-switch](https://user-images.githubusercontent.com/8971560/48904261-131ffc80-ee5e-11e8-9a02-582a3ed7a867.png)

**Comment by ivarni** [comment]
På min Android telefon er forøvrig disse blå og ikke grønne.

![screenshot_20181122-140518_settings](https://user-images.githubusercontent.com/379849/48904843-07cdd080-ee60-11e8-9c1e-16ae6fc1f657.jpg)

**Comment by hodoea** [comment]
Ja sorry det er sant, jeg har jo Android selv. Burde husket på det :)  Kan sikkert se på hvilken farge vi lander på :) 

<img width="700" alt="skjermbilde 2018-11-22 kl 14 26 17" src="https://user-images.githubusercontent.com/8971560/48905729-a3604080-ee62-11e8-82e3-27e32e07cb38.png">

**Comment by antidecaf** [comment]
Er det noe mål å gjenskape en implementasjon fra en spesifikk plattform? Det viktigste er vel å følge konvensjonen rundt selve interaksjonen. Har sett disse i et utall farger og former rundt forbi. :)

**Comment by hodoea** [comment]
Nei

Det er ikke noe mål å gjenskape en plattform. Ja, enig det viktigste er
patternet. Kan du dele noen screenshots av de du har sett?

**Comment by hdaljord** [comment]
Fargen som brukes bør vel fortrinnsvis knyttes opp mot vår visuelle profil heller enn kjørende plattform? Velger du ios eller android vil det alltid være "feil" for noen.

**Comment by hodoea** [comment]
De jeg har lagt ved tidligere er knyttet opp til vår visuelle profil(fargekoden til blue cobalt og green shamrock) Mulig det er bedre å bruke grønn, da det symboliserer bedre noe man slår av og på. Merk at jeg er Android bruker :P Så jeg favoriserer ikke iOS. Grønn gir mer mening.

![bla](https://user-images.githubusercontent.com/8971560/48935832-4f5c6700-ef09-11e8-890e-ab706ef29ddc.png)
![gronn](https://user-images.githubusercontent.com/8971560/48935833-4f5c6700-ef09-11e8-8ab1-5a145d52d0cb.png)

**Comment by hdaljord** [comment]
Fargevalget bør sikkert tas opp i gdforum, @adidick

**Comment by antidecaf** [comment]
For eksempler på utforming kan du egentlig bare bildegoogle "toggle switch design" eller noe lignende. :)

Vil gjette at mange tolker grønt som "på" by default, men tipper at både den blå og den grønne funker helt fint.

**Comment by hodoea** [comment]
@hdaljord Jeg diskuterer fargevalget med Heidi. :) Jeg har også tatt dette med @adidick igår :)

**Comment by hodoea** [comment]
Kan dette fungere som guidelines?
<img width="498" alt="skjermbilde 2018-12-06 kl 11 49 40" src="https://user-images.githubusercontent.com/8971560/49579680-3910cb00-f94d-11e8-85f6-f9b916f35395.png">

**Comment by adidick-zz** [comment]
@hodoea En annen viktig prinsipp ift toggle switcheser:
"**Deliver immediate results** - Toggle switches should take immediate effect and should not require the user to click Save or Submit to apply the new state."
Jeg tror dette arktikelen har kankje vært delt før?
https://www.nngroup.com/articles/toggle-switch-guidelines/

**Comment by hodoea** [comment]
Takk, jeg så den artikkelen. Det er der jeg har hentet det fra før, men jeg glemte å ta med den setningen. Sånn. @adidick 
<img width="498" alt="skjermbilde 2018-12-06 kl 11 49 40" src="https://user-images.githubusercontent.com/8971560/49579643-21d1dd80-f94d-11e8-93d0-31a4a8897395.png">
