### ISSUE TITLE
BulletList is missing condensed prop

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#525]
#### Which package is this issue related to?

`ffe-lists-react`

#### Describe your issue (screenshots welcome!)

There's a `--condensed` modifer for `.ffe-bullet-list` but the React component does not have a prop for turning it on.

This might be an  issue for the other flavours of lists as well.

#### What is the expected behavior? 

Writing

```xml
<BulletList condensed={true}>
    <BulletListItem>Forever alone</BulletListItem>
</BulletList>
```

#### What is the actual behavior?

Having to write

```xml
<BulletList className="ffe-bullet-list--condensed">
    <BulletListItem>Forever alone</BulletListItem>
</BulletList>
```

**Comment by stianlik** [comment]
I'm preparing a PR for this issue.
