### ISSUE TITLE
Komponentbiblioteket på design.sparebank1.no laster ikke i IE 11

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#526]
#### Which package is this issue related to?
Komponentbiblioteket på design.sparebank1.no, det er mulig at dette er et styleguidist-problem, jeg har ikke undersøkt nærmere.

#### Describe your issue (screenshots welcome!)
Komponentbiblioteket laster aldri, blir bare stående med "Henter komponentbiblioteket..."

![image](https://user-images.githubusercontent.com/36953762/49066650-1df1dd00-f222-11e8-9418-d7737149dd60.png)

#### What is the expected behavior? 
At komponentbiblioteket lastes slik at det er mulig å se hvordan komponentene oppfører seg i IE11 uten å ta de i bruk et annet sted.

#### What is the actual behavior?
Se over.

#### Steps to reproduce
Åpne IE11, gå til design.sparebank1.no og velg komponenter.

**Comment by ivarni** [comment]
![image](https://user-images.githubusercontent.com/379849/49133507-ba7ab480-f2e0-11e8-9f4f-54dc71fcff66.png)

Ser at det er forsøkt å sette opp støtte for IE11 i Babel her:
https://github.com/SpareBank1/designsystem/blob/develop/babel.config.js
Men det er tydelig at det ikke fungerer.
