### ISSUE TITLE
Show active tab on design.sparebank1.no

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#54]
On our various sites we usually indicate the selected tab by highlighting with a line and/or color. See for instance https://www.sparebank1.no/nb/bank/privat/eiendom.html and notice the underline below PRIVAT and color highlight of Eiendom.

It would be nice to have some indication of the currently active tab on design.sparebank1.no as well.

Today:
![screen shot 2018-03-05 at 16 22 19-fullpage](https://user-images.githubusercontent.com/1223410/36983230-1b208462-2092-11e8-9f01-27b3b7d8879b.png)

Possible active state:
![screen shot 2018-03-05 at 16 23 52-fullpage](https://user-images.githubusercontent.com/1223410/36983249-239badba-2092-11e8-826c-f0f1aec1782f.png)

I like indicating active state with a line since seeing the slight shift in color is difficult even for me sometimes :see_no_evil:

**Comment by selbekk** [comment]
Is this design okay with you guys @adidick @hodoea ?

**Comment by antidecaf** [comment]
The active state exists in sketches and the Less/CSS (`.sb1ds-top-menu__item--active`) is in place. (It was implemented as a scrollspy in styleguidist before we decided to split the SPA into different pages.) All that remains at this point is some kind of toggling of the class.

**Comment by selbekk** [comment]
Is this something you want to follow up @antidecaf ? Can I assign it to you? =)

**Comment by antidecaf** [comment]
Assigned. :+1:

**Comment by adidick-zz** [comment]
There are plenty of small design tweaks to the layout that I can look at with you @antidecaf when we get the chance.
