### ISSUE TITLE
Meta: should we have labels for FFE and the design system?

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#55]
We're starting to see some open issues for design.sparebank1.no as well as FFE. Would it be helpful to add an **:rocket: ffe** and a **:dizzy:  design system** label (emojis pending) to help see at a glance which of the two the issue is about?

**Comment by selbekk** [comment]
Cool by me!

**Comment by gbrownlee** [comment]
Agreed.

**Comment by selbekk** [comment]
I'll fix!
