### ISSUE TITLE
Hvordan skal designsystemet forholde seg til forskjellige merkevarer?

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#584]
Legge til rette for at komponenter kan implementeres med andre visuelle profiler enn vår egen.

- Skinning?
- Egne forks?
- Splitte opp i egne repoer for styling og (react) implementasjoner?

**Comment by ivarni** [comment]
> Splitte opp i egne repoer for styling og (react) implementasjoner?

Det er vel det vi allerede har gjort?
