### ISSUE TITLE
Deling av listekomponent

### ISSUE THREAD

**Issue by andrewei** [SpareBank1/designsystem#597]
Hei,
Jeg har lyst til å bruke en komponent (se skjermbilde) som blir brukt på en underside av Sparebank1.no [link](https://www.sparebank1.no/nb/smn/bedrift/produkter/driv.html?icid=forside;;driv;;banner2;;smnnyhet;;bedrift#).  Jeg fant ikke komponenten i repoet deres. Har dere tilgang til komponenten og kan eksponere den eller har dere eventuelt mulighet til å lage en tilsvarende komponent?

![chrome_2019-03-26_14-33-45](https://user-images.githubusercontent.com/8640343/55001395-cba8a900-4fd4-11e9-99cb-61cb548fc422.png)

**Comment by antidecaf** [comment]
Hei! Dette er som du sier ikke en komponent som er en del av designsystemet, og vi har dessverre ikke mulighet til å eksponere den. Det nærmeste vi kommer er så vidt jeg kan se [Accordion](https://design.sparebank1.no/styleguidist/index.html#!/Accordion).

Nye komponenter lages fortrinnsvis av team som har behov for de, og legges til i designsystemet dersom flere har behov for samme funksjonalitet/pattern. Vi kommer med andre ord ikke til å legge til denne nå, men send gjerne en pull request dersom du sitter på en implementasjon du gjerne vil ha med. :)

**Comment by andrewei** [comment]
Kjekt å få avklart det :) Tusen takk for svar!
