### ISSUE TITLE
Adding type definition files (typescript) for react components

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#598]
#### Which package is this issue related to?
All ffe-XXX-react packages.

#### Describe your issue (screenshots welcome!)
None of the react components includes typescript definition files.
It would be an improvement for typescript users to include typings in the design system.

**Comment by hdaljord** [comment]
På noen av komponentene i ffe-form-react, eksempelvis InputGroup (se under), brukes label som en prop med en propType-definisjon som avviker fra HTML-attributtets definisjon. 'label' er et vanlig HTML-attributt, dersom vi skal støtte spread må vi ha kompatible typer med tilsvarende HTMLXxxxElement. Dvs. label må være string eller undefined.

Der man bruker rest-properties virker det for meg å være et dårlig pattern
å bruke vanlige html-attributter på andre ting.

Jeg ser for meg to løsninger:
- Innføre en ny prop på labelComponent som kan brukes dersom man vil ha en annen komponent som label og endre propTypes på label til string -> breaking change
- Deprecate label helt og lage en ny som heter noe slikt som groupLabel som har samme propTypes som den opprinnelige label hadde -> gir ikke breaking change, men styggere kode

Er det noen som har noen tanker om hvilken løsning som bør velges? Evt. har andre forslag?

```
InputGroup.propTypes = {
    /** Unless you only have one element in your `InputGroup` you will have to use the function-as-a-child pattern. */
    children: oneOfType([func, node]).isRequired,
    className: string,
    /** Use the ErrorFieldMessage component if you need more flexibility in how the content is rendered. */
    fieldMessage: oneOfType([string, node]),
    /** To just render a static, always visible tooltip, use this. */
    description: string,
    /** Use the Label component if you need more flexibility in how the content is rendered. */
    label: oneOfType([string, instanceOfComponent(Label)]),
    onTooltipToggle: func,
    /** Use the Tooltip component if you need more flexibility in how the content is rendered. */
    tooltip: oneOfType([bool, string, instanceOfComponent(Tooltip)]),
};

```

**Comment by ivarni** [comment]
I følge https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes er `label` kun definert som et attributt for `<track>` elementet, så det syns jeg nesten blir litt sært at vi skal måtte forholde oss til det, særlig i kontekst av en `InputGroup`. 

Begge løsningene er forøvrig breaking, det at man deprecater noe er det samme som å si at man kommer til å knekke det men at man bare velger å ikke gjøre det akkurat nå så hvis dette er noe som *må* fikses ville jeg foreslått det første.

**Comment by hdaljord** [comment]
@ivarni Takk for innspill :)

Jeg fant en bedre, og riktigere løsning (extende XxxHTMLAttributes<HTMLXxxElement> i stedet for HTMLProps<HTMLXxxElement>, den siste er den som drar inn rubbel og bit av HTML attributter).

**Comment by hdaljord** [comment]
I have added ts definitions for the packages we use in our projects. I'm not going to add more definitions now, so feel free to add definitions for other packages :)

**Comment by steffenz** [comment]
Veldig bra at du har fått på plass dette. Jeg digger TypeScript :smile: 
I og med at denne tråden har stoppet litt opp (og du har flere forskjellige PRs som allerede er merget), lukker jeg saken. Hvis du mener det er feil må du bare si fra, så skal vi få den gjenåpnet. Tenker at man eventuelt kan opprette egne issues/PRs per komponent man gjør endringer i fremover, i og med at du har gjort størsteparten av jobben i en stor en.
