### ISSUE TITLE
ffe-icons-react: build failure (Unexpected token)

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#599]
#### Which package is this issue related to?
ffe-icons-react

#### Describe your issue (screenshots welcome!)
Babel fails at the first generated icon component:

```
SyntaxError: jsx/atv-ikon.js: Unexpected token (5:12)
  3 | import { bool, string } from 'prop-types';
  4 | 
> 5 | const svg = <svg viewBox (...)
```

#### What is the expected behavior? 
Build should pass

#### What is the actual behavior?
Babel fails at the first generated icon component

#### Steps to reproduce
Pull the project
Navigate to `designsystem/packages/ffe-icons-react/`
Run `npm run build:cjs`

**Comment by ivarni** [comment]
I can't even get that far
```bash
➜  ffe-icons-react git:(master) npm install
npm WARN eslint-loader@2.1.2 requires a peer of webpack@>=2.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.

added 250 packages from 137 contributors in 14.458s
➜  ffe-icons-react git:(master) npm run build:cjs

> @sb1/ffe-icons-react@6.0.18 build:cjs /home/e6102/work/designsystem/packages/ffe-icons-react
> babel -d lib --env-name=cjs --root-mode=upward jsx

sh: 1: babel: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @sb1/ffe-icons-react@6.0.18 build:cjs: `babel -d lib --env-name=cjs --root-mode=upward jsx`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @sb1/ffe-icons-react@6.0.18 build:cjs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/e6102/.npm/_logs/2019-04-12T09_50_59_046Z-debug.log
```

Also tried `npm install` from the project root. If we're relying on a globally installed `babel` maybe that's the issue? No telling what version it ends up using.

`npm run build` (and `npm run build:all`) runs with no errors from project root for me 🤷‍♂️

**Comment by ivarni** [comment]
@antidecaf The build seems fine on Travis too, did this problem self-fix itself? 
https://travis-ci.org/SpareBank1/designsystem/branches

**Comment by antidecaf** [comment]
Yes, apparently some sort of magic has occurred. Closing this for now.
