### ISSUE TITLE
Alignment feil på FieldMessage

### ISSUE THREAD

**Issue by ariander** [SpareBank1/designsystem#609]
#### Which package is this issue related to? 
`ffe-form-react`

#### Describe your issue (screenshots welcome!)
![image](https://user-images.githubusercontent.com/62503/56655700-d0c04d00-6693-11e9-832f-f526b8884879.png)

Ser ut til at `margin-top: -3px` på `.ffe-field-info-message::before` løser det, men vet ikke om det er riktig løsning.

**Comment by ivarni** [comment]
Ser ut som det også kan fikses med
```
display: flex;
align-items: center;
```
på `.ffe-field-info-message`

**Comment by antidecaf** [comment]
^ Den løsningen gir av en eller annen grunn samme resultat som før, mens å fjerne `vertical-align: middle;` fra `.ffe-field-info-message::before` ser riktigere ut. Kan muligens skyldes whitespace i inline-elementer (teksten er inline, ikonet inline-block). Uansett verdt å dobbeltsjekke at det blir riktig overalt før man merger en PR.

**Comment by ivarni** [comment]
@antidecaf Yes, det funker fint. Testet manuelt med en parent med alle relevant verdier for `display` (block, inline-block, grid, flex) og det så fint ut.
