### ISSUE TITLE
ffe-buttons: Text is aligned left in block level buttons

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#61]
The text in block level buttons is aligned to the left, should be center. This bug is present despite both `text-align: center;` and `align-items: center;` (on the label element) being set.

![screenshot from 2018-03-07 15-19-09](https://user-images.githubusercontent.com/463847/37097393-99dc0684-221b-11e8-91d1-80cf81d5ca12.png)

**Comment by antidecaf** [comment]
@selbekk Would you like to take a look at this? This bug seems to have occurred after the ffe-buttons rewrite.

**Comment by selbekk** [comment]
Thanks! Yeah there's probably going to pop up a few of these - I'll fix em as they show up. Keep em coming!

**Comment by antidecaf** [comment]
@hodoea Hei
