### ISSUE TITLE
Mulighet for enkelt å velge år i datepicker. 

### ISSUE THREAD

**Issue by Eirik1977** [SpareBank1/designsystem#650]
Ser et behov for å enkelt kunne velge år i dato-velgeren. I dag må man klikke seg gjennom kalender måned for måned for å sette en dato som gjelder flere år frem i tid. (Vi er klar over at Datepicker støtter input også, men dette er kanskje ikke intuitivt)

**Comment by johann1301s** [comment]
Hei, jeg la inn en [pull request](https://github.com/SpareBank1/designsystem/pull/777#issue-346483941).

**Comment by Amanej** [comment]
Kanskje man skal lukke denne issuen, hvis det ikke er noe behov lenger. Ref pull request som ble konkludert med at dette ikke er behov.

@Eirik1977 @antidecaf

**Comment by antidecaf** [comment]
Nja, at det finnes behov for en enkel måte å velge år på tror jeg ikke det er noen uenighet om, selv om teamet som meldte inn issuet til å begynne med ikke trenger å få det på plass umiddelbart.
