### ISSUE TITLE
Ulogisk dynamisk oppdatering av årstall i datepicker ved inntasting av dato

### ISSUE THREAD

**Issue by fremtind-tony** [SpareBank1/designsystem#678]
#### Dersom man taster inn en dato manuelt i inputfeltet, f.eks. 02.03.2020, blir årstallet som vises øverst i kalenderen dynamisk oppdatert på en ulogisk måte som skaper en en dårlig brukeropplevelse.
<img width="344" alt="Screenshot 2019-08-21 at 09 47 25" src="https://user-images.githubusercontent.com/54317847/63412913-f28ad000-c3f8-11e9-8df6-6b4bc58a0418.png">
<img width="344" alt="Screenshot 2019-08-21 at 09 47 58" src="https://user-images.githubusercontent.com/54317847/63412918-f61e5700-c3f8-11e9-9609-4045f42d0210.png">
<img width="344" alt="Screenshot 2019-08-21 at 09 48 07" src="https://user-images.githubusercontent.com/54317847/63412925-fc143800-c3f8-11e9-98e4-72902fd4faf9.png">
<img width="344" alt="Screenshot 2019-08-21 at 09 48 17" src="https://user-images.githubusercontent.com/54317847/63412936-ffa7bf00-c3f8-11e9-8fe2-b015b33f4a93.png">

**Comment by steffenz** [comment]
Note to self: Kanskje vi burde vurdere en debounce effekt på 500ms e.l. Å bruke onBlur virker kanskje litt mot sin hensikt? :thinking:
