### ISSUE TITLE
Add Coveralls to the build

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#7]
[Coveralls](https://coveralls.io) is a really nice thing for monitoring test coverage and is relatively easy to integrate with Travis. It's also [free](https://coveralls.io/pricing) for opensource projects. It will find and comment on pull requests indicating if the coverage has gone up or down, an example of what that looks like can be seen [here](https://github.com/ivarni/get-selenium/pull/8).

**Comment by wkillerud** [comment]
Coveralls requires access to the organization the same as Travis. Could I get a :+1: from the core maintainers before adding it? Cc @kwltrs @gbrownlee @antidecaf

**Comment by gbrownlee** [comment]
Is this issue not resolved, @wkillerud ?

**Comment by wkillerud** [comment]
No @gbrownlee - I wanted to get a go-ahead before opening up the org to Coveralls :smile: Anders has given a thumbsup and I take it your comment is a blessing to :shipit: as well? :wink:

**Comment by selbekk** [comment]
I say fail the build if the test coverage decreases.

**Comment by wkillerud** [comment]
I'm thinking not allowing any decrease at all may be a bit harsh, but we can give it a try and see if it causes unnecessary problems.
