### ISSUE TITLE
ffe-buttons-react: element prop type should accept elementType

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#707]
#### Which package is this issue related to?
ffe-buttons-react
possibly others?

#### Describe your issue (screenshots welcome!)
Buttons are complaining when `Link` from `react-router-dom` is provided as `element`.
This component is wrapped in `React.forwardRef()`, and this creates an element object. This is fully usable as `element` for the buttons, but the prop types are complaining.

#### What is the expected behavior? 
I expect element objects created by things like `React.forwardRef()` and `React.memo()` to be accepted by the prop types for button's `element` property.

#### Suggested solution
Add the prop type `elementType` to the array of accepted types.
Be sure to do this for each button, and the base button components.

#### Steps to reproduce
The following code will work just fine, but will produce prop type warnings in the console:
```
<TertiaryButton element={ Link } to={ somePath }>
  Click me
</TertiaryButton>
```

#### Other notes
This issue might also apply to other packages and components.
_Possibly_ anywhere we have `element: oneOfType([func, string]),` we could add `elementType` to the list.

**Comment by ivarni** [comment]
Can't we just add `PropTypes.node` and be done with it? :)

**Comment by henrikhermansen** [comment]
> Can't we just add `PropTypes.node` and be done with it? :)

No, because it's not a `node` either. Here's an example showing what the various prop types are for:
```
const SomeComponent = () => <div>Hello world</div>;
const ComponentWithForwardRef = React.forwardRef(SomeComponent);

<MyComponent
  func={ SomeComponent }
  string={ 'div' }
  node={ <SomeComponent /> }
  elementType={ ComponentWithForwardRef }
/>
```
Note that `node` is not useful/usable for our buttons at all, but the three others are.

None of the types above are interchangeable, which is why we use `oneOfType`.

**Comment by ivarni** [comment]
Ah right, a node is just anything that can be rendered but a class reference can't be rendered directly.
