### ISSUE TITLE
"screen" i grid media queries

### ISSUE THREAD

**Issue by torkjels** [SpareBank1/designsystem#719]
#### Which package is this issue related to?
`ffe-grid` (og andre pakker, vil jeg tro)

#### Describe your issue (screenshots welcome!)
I `ffe-grid.less` starter de fleste media-queryene med `screen` eller `only screen`, noe som gjør print-styling betydelig "feil".

Dette skjermbildet:
![image](https://user-images.githubusercontent.com/3830142/66545977-2acaa700-eb3c-11e9-8bd6-b5c031400600.png)

Blir seende slik ut i print:
![image](https://user-images.githubusercontent.com/3830142/66545993-34540f00-eb3c-11e9-90a9-e6b68d6363ff.png)

#### What is the expected behavior? 
Hvis man fjerner `screen`-delen av media-queryene i grid blir det seende slik ut i print:
![image](https://user-images.githubusercontent.com/3830142/66546051-5baadc00-eb3c-11e9-939e-5200ef53c0b9.png)

Er det en spesiell grunn til at vi trenger `screen` og `only screen` i media queries, eller er det innafor å fjerne dem?

**Comment by ivarni** [comment]
Jeg kan ikke se for meg at det ligger en bevisst beslutning bak det, kanskje utover det at designsystemet nok følrst og fremst er tenkt å løse oppgaven med å vise ting på web og at print aldri har vært noe man har brukt så mye tid til å tenke på.

Hvis det ser bedre ut på print om man fjerner det ser jeg ikke problemet, hva tror du @antidecaf ?

**Comment by antidecaf** [comment]
Ingen bevisst grunn til at vi bruker `screen` så vidt jeg vet, nei. Det er absolutt innafor å fjerne!

**Comment by torkjels** [comment]
Jeg lagde et PR ( https://github.com/SpareBank1/designsystem/pull/728 ) på å fjerne disse i `ffe-grid`. Skal jeg like så greit gjøre det for alle andre pakker også? :thinking:

**Comment by ivarni** [comment]
@torkjels Hvis du har tid er det strålende :)

Legg gjerne med en referanse til denne saken i commit-meldingen så kommer det med i changeloggen som en link hit dersom noen skulle lure på hvorfor vi gjør det. Skal holde med f.eks 
```bash
git commit -m "Remove screen type from media queries, see #719"
```
