### ISSUE TITLE
Kontrollere hvordan siden vises før/når custom font lastes

### ISSUE THREAD

**Issue by lfbergee** [SpareBank1/designsystem#721]
### Which package is this issue related to?
`ffe-webfonts`

#### Describe your issue (screenshots welcome!)
Per i dag settes det ingen oppførsel på hvordan vi skal laste inn fonten, dermed er det opp til hver enkelt browser hvordan den ønsker å gjøre det. Ved å sette `font-display` kan vi kontrollere hvordan vi ønsker brukeropplevelsen å være

### Forslag
```
@font-face {
    font-family: 'MuseoSans-300';
    font-display: fallback;
    src: url('@{fonts-url}/2FDE32_0_0.woff2') format('woff2'),
        url('@{fonts-url}/2FDE32_0_0.woff') format('woff');
}
```

Ref: https://developers.google.com/web/updates/2016/02/font-display?utm_source=lighthouse&utm_medium=devtools

**Comment by ivarni** [comment]
Sounds good to me 👍
