### ISSUE TITLE
ffe-tooltip seems to be vertically misaligned

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#731]
#### Which package is this issue related to?

`ffe-tooltip`

#### Describe your issue (screenshots welcome!)

This seems to be misaligned to me

![image](https://user-images.githubusercontent.com/379849/66989571-e3589380-f0c4-11e9-834f-689cb1ed6bc3.png)

I think it looks better like this

![image](https://user-images.githubusercontent.com/379849/66989620-fd927180-f0c4-11e9-93aa-1ca31cb5b6ad.png)

#### Steps to reproduce

The current `line-height` is set to `22px`, updating it to `24px` seems to make it look more vertically centereder.

**Comment by gbrownlee** [comment]
Kan nesten ikke forklare gleden inni meg når jeg ser at @ivarni er blitt pikselpusher!

Støtter forøvrig forslaget. :)
