### ISSUE TITLE
ffe-core: add missing dark mode common styles overrides

### ISSUE THREAD

**Issue by mvmagnussen** [SpareBank1/designsystem#752]
Some overrides for dark mode are missing in ffe-core/less/darkmode-overrides.less. This issue will be expanded and fixed in batch.
-ffe-file-upload__button: button has no dark mode styling
-ffe-message-box__list: bullets have no dark mode styling

... to be continued.

**Comment by antidecaf** [comment]
@mvmagnussen Sjekket kjapt nå og det ser ut som begge disse har dark mode-styling. Er det noen andre steder det mangler, eller kan vi lukke dette issuet?

**Comment by mvmagnussen** [comment]
Issuet er steingammelt og er helt sikkert fikset nå ja, så bare å lukke 👍
