### ISSUE TITLE
ffe-knapper - kan ikke trykke på med space

### ISSUE THREAD

**Issue by marihr** [SpareBank1/designsystem#757]
#### Which package is this issue related to?
Button
#### What is the expected behavior? 
Trykker på space = trykker på knappen
#### What is the actual behavior?
Trykker ikke på knappen, scroller siden. Må bruke enter for å få trykket på knappen
#### Steps to reproduce
Finn en knapp, tab til den, trykk på space

**Comment by ivarni** [comment]
Jeg er usikker på om dette er en bug i FFE eller i en applikasjon som bruker buttons. I våre applikasjoner fungerer ffe-knapper fint med space.

Hvis du er på SB1 sitt nett kan du sjekke på feks https://alfa.test.sparebank1.no/privat/forsikring/pensjon/kjop
(fyll ut alder for å få fortsette)

**Comment by lfbergee** [comment]
Fungerer ikke å trykke på knappen med space i det eksempelet.

Browser: Firefox 71.0b5
OS: Red Hat 7.7

Ref WGAC:
```
When the button has focus:

    Space: Activates the button.
    Enter: Activates the button. 
```
https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-3


Det kan løses i applikasjonene, men burde vel være default oppførsel til knappen?

**Comment by ivarni** [comment]
Fungerer i Chrome, kanskje det er noe spesielt vi må gjøre i Firefox?

Vi har ikke gjort noe utover å legge på en helt vanlig `onClick` callback, og det er vel ikke noe mer magi som skjer i Button heller så da høres det ut som et issue i enten React eller Firefox? 

Forøvrig fungerte space for meg i Firefox 70.0.1 på Ubuntu 18.04.3 LTS

**Comment by ivarni** [comment]
So to be clear, the button in [this example](https://codesandbox.io/s/modern-cherry-7kkrd?fontsize=14) does not work in the latest version of Firefox?

(Ignore the lack of styling btw, didn't have time to fix that bit and it shouldn't matter for the purpose of testing `onClick`).

**Comment by hdaljord** [comment]
Det eksempelet fungerer fint i firefox her. Versjon 60.9.0esr (64-bit) på RHEL, høres ut som om det er et issue i den firefox-versjonen du har.

**Comment by lfbergee** [comment]
Codesandbox eksemplet viker.

I SB1 flyten du lenka til så viker det med Chat, men ikke med Annen sparing. Så antar problemet ligger på `a` som ser ut som button. Lenker skal jo strengt tatt ikke åpne med space, men blir litt rart når den ser ut som en knapp, men oppfører seg ikke som en.

Testet "annen sparing" knappen i lastest chrome på windows-linux-os-x, firefox esr, firefox developer edition og safari og alle gir den samme oppførselen.

**Comment by ivarni** [comment]
Hm... ja ser ut som det er issue når man bruker `a` som `element` prop til `BaseButton` ja.

Jeg er veldig usikker på hva som er riktig i det tilfellet, jeg... å beholde semantikken til lenka eller at ting oppfører seg som de elementene de ser ut som?

**Comment by lfbergee** [comment]
Ja, ente opp med å bli veldig usikker jeg også.

Ifølge WGAC så skal:
- knapper reagere på enter og space.
- lenker reagere på enter

Så for en skjermleser så er det rett at en lenke som ser ut som en knapp bare reagerer på enter, men for en tastaturbruker så ville jeg forventet at "walks like a duck, talks like a duck..."

**Comment by hdaljord** [comment]
Det du peker på der er det egentlige problemet. Hvis du skal ha noe som ser ut som en knapp, bruk en knapp, hvis du skal ha ei lenke bør du nok heller bruke noe som ser ut som ei lenke også. 

Hvis du må ha det som a vil jeg mene at det er bedre å legge på key-event-håndtering slik at det virker slik det ser ut som det skal også, det er nok verre at det oppleves som at knappen ikke virker ved space enn at det ei lenke også reagerer på SPACE.

**Comment by lfbergee** [comment]
Kanskje la det være en klient-problemstilling. Menja, enig i at lenker burde se ut som lenker og knapper som knapper.

**Comment by ivarni** [comment]
Sett at vi bestemmer oss for å håndtere det i FFE, *kan* vi i det hele tatt håndtere det her på en god måte?

I alle eksemplene i vår app er feks `element` ikke sendt inn som `"a"` men som en `Link`-komponent fra react-router så vi kan ikke gjøre spesialhåndtering basert på at vi ser det er en lenke (med mindre vi graver i DOMen etter render... men meh..) så skal vi lage en fiks for det her må vi basically sette på `onKeyDown` i alle tilfeller og samtidig sørge for at vi ikke brekker noen corner cases. Jeg syns det høres skummelt ut.

Eventuelt kan vi enten eksportere noen buttons av type `ActionLinkButton`, `PrimaryLinkButton` etc og satse på at consumer bruker den riktige? Eller overlate det til consumer fullstendig? Jeg blir mer og mer tilhenger av tanken om at FFE først og fremst skal tilby visuelle komponenter og ikke legge på mer oppførsel enn vi strengt tatt trenger.

Så jeg vet ikke jeg. Er det en lenke så er det jo riktig å bruke en `a` og ikke en knapp. Knapper bør vel strengt tatt ikke åpne lenker. Men samtidig er det jo ikke alltid det passer inn i designet med en lenke.

**Comment by hdaljord** [comment]
Jeg heller mot å la det være opp til de som bruker knappen, slik at de heller sender inn onKeyDown på knappen hvis det ikke er mulig å bruke ei lenke i stedet.

**Comment by ivarni** [comment]
Fun-fact, vi har en egen [ShortcutButton](https://design.sparebank1.no/styleguidist/index.html#!/ShortcutButton) i FFE som er tenkt brukt til nettopp dette scenarioet med en "knapp" som gjør en navigasjon. Den er merket med et sånn pil-ikon som skal forberede brukeren på at det vil være en navigasjon bort fra siden de var på ved klikk.

Problemet er å få overtalt designerne til å faktisk bruke den.

Men med den knappen kunne jo faktisk tvunget elementet til å bli en `<a>` siden det ligger i navnet at det er det den knappen skal være? Også kunne vi fjernet muligheten for å gjøre de andre knappene til `<a>` elementer? Men skulle vi gjort det måtte vi fått forankret det hos design er jeg redd.

**Comment by steffenz** [comment]
Etter å ha lest gjennom tråden her virker det som at det egentlig problemet her er at linker og knapper blir brukt litt om en annen, og at dette er noe som ligger litt utenfor hva ffe skal tilby (selv om vi nok kan få det på plass som et godt tips i dokumentasjonen). Ser ikke at det er noen stor uenighet om dette, og velger derfor å lukke saken inntil videre. Hvis noen mener det er helt feil vurdering er det bare å si fra, så skal vi ta den opp til vurdering på nytt :smile_cat:
