### ISSUE TITLE
Add horizontal selector

### ISSUE THREAD

**Issue by Amanej** [SpareBank1/designsystem#758]
#### Which package is this issue related to?
Adding a new feature / component
#### Describe your issue (screenshots welcome!)
Going to add a horizontal selector used in our teams app.
#### What is the expected behavior? 
A horizontal selector that lets users select a single value ie radio button.
#### What is the actual behavior?
See above
#### Steps to reproduce
Will be added, so this is not an issue but a feature.

**Comment by Amanej** [comment]
Created a pull request - https://github.com/SpareBank1/designsystem/pull/759

**Comment by hdaljord** [comment]
Reopen issue until PR is reviewed and accepted as a solution. 

Next time, could you please add a sketch in the issue to make it easier to see what the component look like? (I see you have it in the PR, but it would be event better to have it in this issue :) ).
