### ISSUE TITLE
Why is this open source? 

### ISSUE THREAD

**Issue by haavamoa** [SpareBank1/designsystem#760]
My company is in a phase of having more focus on a shared design system that should work across different platforms. I am trying to convince people that it should be open to the public and that the  source code for our component libraries should be open sourced.

Why did Sparebank1 chose to keep this open and open source? 

This designsystem and the open mindset is a great inspiration, keep ut the good work! 👌

**Comment by antidecaf** [comment]
Thanks for reaching out!

There are a few different reasons for why this project is open source. A couple of important ones off the top of my head:

* The contents of the design system needs to be available to third parties. Every so often, a product or campaign is developed by third parties, be it contractors, bureaus, remote teams or others who don't have access to our internal, hosted platforms. Being open source makes sharing assets and information a much simpler process.
* We would like to be a part of, and contribute back to, the open source community. Every moving part of this design system and the infrastructure surrounding it is based on open source software to begin with, so it makes sense for us to share our work in the same fashion.
* There is a big community of design system enthusiasts out there, and being open about ours enables us to be a part of that. We feel like the continuing exchange of experiences and knowledge is favorable to all parties involved, including us. Sharing is caring. :)

**Comment by gbrownlee** [comment]
There are several reasons for open sourcing a design system. Some of ours were as follows:
- Greater transparency encourages greater quality.
- A public system allows for easier access for developers and designers across all sourcing strategies.
- Recruitment processes can be more efficient when candidates can see how a company operates, codes or designs.
- One single method of accessing and procuring common code and design can reduce overhead or poor distribution of resources.
- Contributing back to the developer community with ideas and suggestions is our duty as consumers of open source code -- and it makes us feel good. 

Hope this can help you in deciding how to proceed. Also take a look at our most recent design system made by and for our insurance company Fremtind: https://github.com/fremtind/jokul

EDIT: I guess I should refresh more often... Totally support what @antidecaf said.

**Comment by haavamoa** [comment]
This was very helpful. Thank you! 👍
