### ISSUE TITLE
Mulig å fjerne "røkla" som fargekategori og bytte ut med følgende forslag?

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#80]
Noen av fargene under "røkla"( som vi må finne en ordentlig kategorinavn for btw) er WCAG farger. @heilysto nevnte dette sammen med Julia T(grafiske designere).

<img width="781" alt="skjermbilde 2018-03-09 kl 16 08 29" src="https://user-images.githubusercontent.com/8971560/37214102-45d936ac-23b4-11e8-9fb1-e8c5f0917201.png">

Jeg har et forslag her(se kategorinavn på screen under) @heilysto  :)

<img width="636" alt="skjermbilde 2018-03-09 kl 16 10 13" src="https://user-images.githubusercontent.com/8971560/37214155-6ec3ae4e-23b4-11e8-829f-68eba8b324dc.png">

**Comment by antidecaf** [comment]
Kategorinavnene er jo for så vidt greie, men dette adresserer strengt tatt ikke "røkla" (eller den nøytrale paletten). Kategoriene i screenshotet overlapper i stor grad med kategoriene som allerede ligger i oversikten. Hva gjør vi med fargene som ikke finnes i screenshotet?

**Comment by hodoea** [comment]
Vi har et forslag i loopen til farge-seksjonen i visuell identitet(bruk og eksempler:D) Kommer her i neste uke forhåpentligvis :)

**Comment by wkillerud** [comment]
Vet det er endringer i loopen for disse fargene og presentasjonen av dem. Kan bare skyte inn at dagens presentasjon med tekst oppå fargene feiler på WCAG kontrastsjekk for flere av dem. Testet med [dette verktøyet](https://www.deque.com/axe/). Om det nye designet også har tekst oppå fargene er det sikkert greit å ta høyde for :)

**Comment by antidecaf** [comment]
Skissene for den nye oversikten har også tekst oppå fargene. Dette er hvor Wave rapporterer om problemer:

![image](https://user-images.githubusercontent.com/463847/38724976-198ee0b6-3f06-11e8-8080-307d6ae2bedb.png)
![image](https://user-images.githubusercontent.com/463847/38724983-1e61ec5a-3f06-11e8-91ac-8b804a7ed493.png)
![image](https://user-images.githubusercontent.com/463847/38724989-21778030-3f06-11e8-8ccb-5e7ac94641f1.png)

**Comment by Heilysto** [comment]
Forslag til ny inndeling av farger og fjerning av røkla.
https://sparebank1.invisionapp.com/d/main#/console/12247316/257694951/preview

**Det er kommet inn forespørsel om vi skal operere med to fargenavn.**
1. På venstre side er fargene beskrevet som i profilhåndboken (https://merkevare.sparebank1.no/portal/doc?query=%7B%22rootIds%22%3A%5B5167%5D%2C%22limit%22%3A1%2C%22nodeIds%22%3A%5B%225179%22%5D%2C%22langId%22%3A1%2C%22incXP%22%3Atrue%2C%22docIds%22%3A%5B%2210360%22%5D%7D)
2. Til høyre er fargene beskrevet som i koden

Jeg tar gjerne en diskusjon på hvordan evt vi kan løse dette med kun én type navngivning:)

**Comment by wkillerud** [comment]
Ikke noe problem å endre navnet på venstre siden til de som brukes i profilhåndboken, det er en kjapp endring :+1: 

Vi burde nok da også endre navnet på fargene i koden der de ikke gir mening lenger, f.eks. Hovedblå og disse WCAG-variantene. Så er det lettere å oversette design til kode. Det blir dog en _breaking change_ - kanskje spare den endringen til vi har flere breaking changes i `@sb1/ffe-core` @antidecaf?

**Comment by antidecaf** [comment]
Det blir helt klart en breaking change. Og jeg synes kanskje vi bør ta en aldri så liten debatt om hvilket mønster vi vil bruke på variabel-navnene før vi endrer på de. Det er ikke så veldig lenge siden vi hadde en overhaling av fargenavnene i FFE, nettopp fordi navn som `ffe-x-WCAG`, `ffe-x-50` (forskjellige tints angitt i prosent) og lignende abstrakte ting var vanskelig å ha et bevisst forhold til i det daglige. :)

Navnene vi har i dag kom vi frem til ved å bruke et verktøy som genererer unike navn til hver farge, basert på fargekart fra en fargehandel (husker ikke helt navnet på verktøyet i farta). Fordelen er at hver farge har sitt eget unike navn som til en viss grad beskriver selve fargen. Ulempen er at de ikke henger sammen med navnene vi bruker i profilhåndboka.

Hva som er den beste løsninga er jeg neimen ikke sikker på. Kan jo for så vidt hende at problemet løser seg selv når vi nå får dokumentert hva de forskjellige fargene skal brukes til. :)

**Comment by wkillerud** [comment]
@Heilysto og/eller @hodoea , ta gjerne en titt på https://design.sparebank1.no/visuell-identitet.html#visuell-identitet_farger ved anledning og se om løsningen er innenfor :)

**Comment by hodoea** [comment]
Ok. Vi må se på de eksemplene som feiler i Contrast Checker. @Heilysto :)
@wkillerud  Btw jeg tror du tagget en feil bruker, mitt er "hodoea". 😆

**Comment by wkillerud** [comment]
Oops :sweat_smile:

**Comment by hodoea** [comment]
Vi lukker denne saken og lager en ny til "contrast checker" issuet. :) Håper det er greit
