### ISSUE TITLE
ffe-searchable-dropdown-react: wrong colors are set in dropdown list

### ISSUE THREAD

**Issue by mvmagnussen** [SpareBank1/designsystem#814]
#### Which package is this issue related to?

ffe-searchable-dropdown-react

#### Describe your issue (screenshots welcome!)

Colors set by js is wrong. Ideally, colors should not be set by js at all.
![image](https://user-images.githubusercontent.com/1208362/71575178-48306100-2aec-11ea-820d-74c82d0cee5f.png)

Caused by this inline styling: `<div style="padding: 8px; background: rgb(255, 145, 0);">`

#### What is the expected behavior? 

Font colors set to blue/grey in dropdown. Highlighted item background color set to blue.

#### What is the actual behavior?

Font colors set to black/grey in dropdown. Highlighted item background color set to orange.

#### Steps to reproduce
 
Go to https://design.sparebank1.no/styleguidist/index.html#!/SearchableDropdown and open the third dropdown from the top.

**Comment by pethel** [comment]
The code you are referring to is only part of `SearchableDropdown.md` to demonstrate the usage of `listElementBody`prop  to render a custom drop down elements. 

```
const CustomListElementBody = ({ item, isHighlighted }) => {
    return (
        <div
            style={{
                padding: '8px',
                background: isHighlighted ? '#ff9100' : 'white',
            }}
        >
            <div>{item.organizationName}</div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <SmallText>{item.organizationNumber}</SmallText>
                <SmallText>{item.quantityUnprocessedMessages} ulest</SmallText>
            </div>
        </div>
    );
};
```

`listElementBody={CustomListElementBody}`

The other examples are does not have inline styling. I do not think we should be shipping demo code to our clients.
