### ISSUE TITLE
ffe-searchable-dropdown-react: wrong colors for dark variant of component

### ISSUE THREAD

**Issue by mvmagnussen** [SpareBank1/designsystem#815]
#### Which package is this issue related to?

ffe-searchable-dropdown-react

#### Describe your issue (screenshots welcome!)

Compared to the dark variant of input and dropdown, the dark variant of searchable dropdown does not get the proper colors set. Please note that this is the dark variant of the component used for internal applications.

![image](https://user-images.githubusercontent.com/1208362/71575648-09030f80-2aee-11ea-8ebd-69c8fa2365c0.png)

#### What is the expected behavior? 

The searchable dropdown should have the same general styling as the regular dropdown component.

#### What is the actual behavior?

The searchable dropdown has the wrong background color in the input field, wrong field label color, wrong icon color etc.

#### Steps to reproduce

Visit https://design.sparebank1.no/styleguidist/index.html#!/SearchableDropdown and compare the dropdown at the very bottom of the page to the dropdow at the bottom of https://design.sparebank1.no/styleguidist/index.html#!/Dropdown.

**Comment by pethel** [comment]
Darkmode searchable dropdown #817
