### ISSUE TITLE
ffe-searchable-dropdown-react: Dropdown with initial value gives no hint that it's a dropdown

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#823]
#### Which package is this issue related to?
ffe-searchable-dropdown-react

#### Describe your issue (screenshots welcome!)
When you have a list with an initial value (i.e. a value the user has not selected himself) the shown element gives no hints that there are more available elements. The image below is taken from the designsystem documentation, the dropdown shows only one element and an X.

![image](https://user-images.githubusercontent.com/36953762/72065128-c5728780-32dd-11ea-83d8-c58a5512139f.png)

When I tried to use this dropdown in my project i could not understand where the rest of the elements had gone, and I'm afraid that the user won't understand that he or she needs to click the X before seeing more elements.

#### What is the expected behavior? 
The concrete use case is that we have an searchable dropdown with all the organizations the user has access to, and the same organization the user has chosen in Nettbank BM is used as initial value. The old searchable dropdown shows the arrow instead of the cross, which revealed the other elements. Now it looks like you only have access to one organization. 

#### Steps to reproduce
Just take a look at the designsystem documentation and imagine that you come to a page whit a preselected element.

**Comment by pethel** [comment]
Here is the example from downshift that we are using. 
https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fordered-examples%2F02-complete-autocomplete.js&moduleview=1

Here is react searchable dropdown, You get suggetions on focus but not unmatching elements.
https://react-autosuggest.js.org/

How would you like it to work?

**Comment by hdaljord** [comment]
Both the examples you link to are a bit different from the one in FFE. FFE shows an X when something is typed into the box (or prefilled, as the use case I describe), your first example always shows the arrow, and your second example shows no button at all. 

My concern is that the user will not understand that there are more elements (as I didn't either).

I'm not quite sure what the correct solution is, but it really does not feel right as it is now, for this use case. It might be quite right for another use case.

I think this is mostly a design issue now, and perhaps a technical issue later.

**Comment by gwtwod** [comment]
Could this be solved by just opening the dropdown on focus, which is how the other dropdowns already work? See https://design.sparebank1.no/styleguidist/index.html#!/Kontovelgerkomponenter and https://design.sparebank1.no/styleguidist/index.html#!/Dropdown ?

Seems pretty weird to me that SearchableDropdown doesn't open on focus

**Comment by pethel** [comment]
Please check out the branch and see if this is the way to go.
https://github.com/SpareBank1/designsystem/pull/849

**Comment by gwtwod** [comment]
Nice, the proposal in #849 doesn't re-open the dropdown if the input is already focused and the user clicks inside the input though (like when you've already made a selection and want to change it), which the other dropdowns do.

Also it seems the single-account selector actually shows the X in addition to the chevron today, doing that might also help solve this issue

Example from https://design.sparebank1.no/styleguidist/index.html#!/AccountSelector:
![accountdropdown](https://user-images.githubusercontent.com/40236320/74221438-6b852900-4cb2-11ea-8326-549f3d88f054.gif)

**Comment by pethel** [comment]
@gwtwod 
I made those changes first described. The second one about the button next to arrow I am really not sure. You miss on small devices. That was not part of the original design os I will leave that. 

But now focus when clicked even when it has focus should be fixed.

**Comment by hdaljord** [comment]
I'm sorry, but I haven't had time to try this out yet. Anyway, I think this needs to be run through ixd-forum as this is an interaction issue. Perhaps @sirioc can give a comment about how this should behave?

**Comment by sirioc** [comment]
Supert om det kan taes opp i IxD-forum. Ser at den ikke er optimal! 👍

**Comment by pethel** [comment]
@sirioc @hdaljord I think this pull request will restore its old behavior. If you want that functionality now its ready to merged after code review. If not. we wait

**Comment by hdaljord** [comment]
@pethel I have had a look at the PR and tried it out, I also discussed it with @sigrunl and we agree that this a good solution, and as you say, it restores the old behaviour. 

@sirioc If you think this should be discussed more in ixd-forum it could be done, but as the suggested change restores the old behaviour I think it should be merged as it is now anyway - it is better than the current version.

**Comment by steffenz** [comment]
I see that the referenced pull request has been successfully merged. It seems to me that this solves the issue, at the very least temporarily, and I suggest we create separate new issue(s) should this component be eligible for a "overhaul" down the road. 
If this isn't the case, please let me know and I will re-open the issue :smile:
