### ISSUE TITLE
"Hva er nytt" (changelog)

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#83]
Jeg har et forslag om å legge til en changelog på forsiden av design.sparebank1.no. Se screen under (plassering og layout er kun en skisse)

Kanskje det kan hjelpe oss med å vise at designsystemet er levende og at vi unngår forvirring fra andre om siden er oppdatert eller ikke..... 

![changelog- design sparebank1 no](https://user-images.githubusercontent.com/8971560/37286361-fa7391f8-2601-11e8-88fb-ac7a996a5a22.png)

**Comment by selbekk** [comment]
Fet idé!

En kompliserende faktor her er at vi ikke har en felles versjon for hele designsystemet. Hver "pakke" (knapper, meldingsbokser, inputfelt, datepickers etc) har hver sin versjon, så å vise et versjonsnummer kan være litt krøkkete. En annen kompliserende faktor er også at vi har to ting vi kunne pratet om her - selve designsystem-siden (og innholdet er) og komponentene som implementerer designsystemet.

Hvis hovedverdien vi prøver å tilføre er å vise brukerne våre at det er en oppdatert side, så kan vi kanskje dra ut litt statistikk ala det her:

> 21 bidragsytere endret 5.242 linjer med designsystem de siste 7 dagene.

Å spesifisere hva som er nytt kommer til å bli en manuell prosess, og det er enkelt å glemme dessverre. :(

**Comment by antidecaf** [comment]
God idé, en sånn oppsummering hadde vært kult å kunne vise frem!

Kunne det også vært mulig å bruke lista over [_alle_ commits](https://github.com/SpareBank1/designsystem/commits/master) i repoet til noe fornuftig? Ser ut som det skal være mulig å få tak i vha [Rest-apiet](https://developer.github.com/v3/repos/commits/) til github. For eksempel kunne vi prøvd å bruke den til å vise frem de ~10 siste commitene som tilsvarer en major release, eller noe i den duren. Mest for å vise frem noe konkret som har skjedd i systemet i nær fortid.

**Comment by selbekk** [comment]
Ulempen der er jo at vi skriver commitmeldingene våre på engelsk (gjerne med migrasjonsguider etc), som ikke gjør seg spesielt bra som en oppsummering

**Comment by kwltrs** [comment]
Som inspirasjon: det er mulig å få en CHANGELOG på root-nivå med `./node_modules/.bin/conventional-changelog --outfile CHANGELOG.md`.

Resultatet er da en changelog for hele historien: https://gist.github.com/kwltrs/8e08c6a524fa0a5c241c27d62dc3f010

Kanskje man kan tweake parameter og tagging slik man får noe brukbart?

**Comment by selbekk** [comment]
Er dette noe vi fortsatt ønsker å ha med, eller kan vi stenge dette issuet?

**Comment by hodoea** [comment]
Jeg tror det kan være fint å ha med(men jeg er den som foreslo det :P) 
Jeg kan bare lukke den imens. Til vi finner ut av om det er noe som skal prioriteres.
