### ISSUE TITLE
Dark mode is wonky on iOS

### ISSUE THREAD

**Issue by mvmagnussen** [SpareBank1/designsystem#830]
When opening design.sparebank1.no in Chrome/Safari on iOS and activates dark mode manually, when the OS is set to display light mode, the styling only partially changes to dark mode. 

![IMG_9007F922D08B-1](https://user-images.githubusercontent.com/1208362/72347407-68f5da80-36d8-11ea-8487-5aec7bbd51b1.jpeg)

Also, when the OS is set to display dark mode when loading design.sparebank1.no, this isn't detected automatically and you have to manually switch to dark mode using the menu toggle switch. 

When the OS is set to display in dark mode, the manual switching to dark mode works nicely.

**Comment by palok** [comment]
https://github.com/SpareBank1/designsystem/pull/835

**Comment by steffenz** [comment]
Jeg ser at saken det her refereres til er merget inn og avsluttet. Antar derfor at dette "issuet" også er løst. Hvis det mot formodning ikke skulle være riktig, er det bare å si fra :smile:
