### ISSUE TITLE
Readme: navn på fagledere :)

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#84]
Kan vi legge til navnet på faglederne i Readme: Anne Gundersen og Hans Huseklepp? 

![fagledere](https://user-images.githubusercontent.com/8971560/37287169-6cb5cb58-2604-11e8-9393-61d5b58852bb.png)

**Comment by wkillerud** [comment]
Det kan vi gjøre :) Har du lyst til å gjøre endringen via webgrensesnittet @hodoea, eller skal jeg lage en pull request?

**Comment by hodoea** [comment]
@wkillerud Jeg gjorde endringen via webgrensesnittet men jeg måtte fortsatt lage en pull request.. Så jeg gjorde det og satte deg på review. Håper det er greit

**Comment by wkillerud** [comment]
Supert, tusen takk! Merget inn nå, så da er det i boks :)
