### ISSUE TITLE
Datepicker jumps to the center of its parent if the user manually substitutes its datevalue with random text

### ISSUE THREAD

**Issue by JonasJore** [SpareBank1/designsystem#842]
#### Which package is this issue related to?
ffe-datepicker-react
#### Describe your issue (screenshots welcome!)
If the user manually removes the value of the datepicker and types in a random string instead. The datepicker will rerender to become centered inside its parent element.
![image](https://user-images.githubusercontent.com/15245356/73855751-cd6a0c80-4834-11ea-9d62-b9a8f1c6512e.png)
#### What is the expected behavior? 
For the datepicker to keep its behaviour and dont jump to the center.
#### What is the actual behavior?
The datepicker jumps to the center of its parent when the user is manually typing something into the inputfield of the datepicker.
#### Steps to reproduce
* Render a datepicker inside a div
* Position the datepicker all to the end or start of the parent div with `flexbox` (something like `align-self: flex-start`)
* Manually substitute the current date of the datepicker with a random text string.

**Comment by steffenz** [comment]
Hei!
Det er mulig jeg misforstår nå, men det kan virke som dette er forventet oppførsel. Du må eventuelt ha en ekstra ``<div/>`` rundt og heller sette ``display: flex`` på denne for å komme rundt problemet. Du må gjerne kommentere og/eller åpne saken igjen hvis du mener dette ikke er riktig.
