### ISSUE TITLE
Endre ikoner i komponent biblioteket

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#85]
Fikk en forespørsel fra en utvikler i Åpne Sider om ikoner i komponent biblioteket på design.sparebank1.no. som ikke stemte helt med det hun fikk i Invision. Dette bør vi endre slik at andre ikke blir forvirret :) 

<img width="973" alt="skjermbilde 2018-03-12 kl 15 12 28" src="https://user-images.githubusercontent.com/8971560/37288808-7a383fbe-2608-11e8-8bf3-578e8e58204e.png">
Denne har feil størrelse og farge

<img width="577" alt="skjermbilde 2018-03-12 kl 15 44 18" src="https://user-images.githubusercontent.com/8971560/37290633-1467cdda-260d-11e8-8dcb-974f88cc7d63.png">
Feil form og farge

Riktig versjon:

<img width="691" alt="skjermbilde 2018-03-12 kl 15 17 42" src="https://user-images.githubusercontent.com/8971560/37288833-88223580-2608-11e8-8605-0d24637c69f5.png">

<img width="760" alt="skjermbilde 2018-03-12 kl 15 19 21" src="https://user-images.githubusercontent.com/8971560/37288932-c46241fc-2608-11e8-82aa-a28e45d6b5e6.png">

Riktig versjon:
<img width="799" alt="skjermbilde 2018-03-12 kl 15 21 50" src="https://user-images.githubusercontent.com/8971560/37289080-1f9f9768-2609-11e8-99ba-90680f79b361.png">

**Comment by antidecaf** [comment]
@hodoea Den andre du nevner ("Noe er feil her") er en feilmelding som hører til skjemavalidering. Antar ikonet skal være det samme utropstegnet som i det nederste eksempelet, men hva er riktig størrelse og farge der?

**Comment by hodoea** [comment]
@antidecaf Det er jeg faktisk usikker på. Jeg har hørt med noen av GDerne for å være sikker. :)

**Comment by antidecaf** [comment]
@hodoea Den er god. Jeg sender en PR nå, der ikonene i alle fall er byttet til det riktige (gjelder alle field-messages). Kan justere størrelse og farge på de i tillegg når vi vet hva som er fasiten. :)
