### ISSUE TITLE
Feil bruk av header i ContextMessageReact 

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#877]
#### Which package is this issue related to?
ffe-context-message-react

Jeg ser at dette også gjelder andre meldingskomponenter som har en form for overskrift.

#### Describe your issue (screenshots welcome!)
Overskrifta i ContextMessage er implementert med html-elementet `header`. Dette blir ikke helt riktig bruk av elementet mtp accessibility, da header skal brukes til sideheaderen eller til en header i en section eller en article. Se https://www.w3.org/WAI/tutorials/page-structure/regions/

#### What is the expected behavior? 
Jeg ser for meg to alternative løsninger.
* Enten endre header til hX eller div stylet som hX
* Eller endre selve komponenten til section eller article

Den første løsningen er antakelig riktigst siden en kontektstuell melding antakelig ikke er en section eller article i seg selv. Jeg tror også at det bør være mulig å få satt meldingsoverskriftene som en Hx, da vil de dukke opp i outlinen for de som bruker strukturen til navigasjon, om man bare tillater div synes ikke overskrifta i outlinen.

#### Steps to reproduce
Dette er lett synlig i styleguiden, https://design.sparebank1.no/styleguidist/index.html#!/Kontekstuelle%20meldinger, view source.

**Comment by ivarni** [comment]
Blir vel ganske umulig å vite hvilken hX som er riktig så det er kanskje bedre å defaulte til en div men åpne for å sende inn ønsket element som en prop?

Evnt fortsette med header som default men legge til en prop for å spesifisere elementet?

**Comment by hdaljord** [comment]
Ja, jeg er enig, div som default og mulighet for å sende inn ønsket element er bedre.

Å fortsette med header er ikke riktig, så lenge ikke hele meldingselementet endres til section eller article.

**Comment by HeleneKassandra** [comment]
Hei, Jeg tenker å ta tak i dette issuet. 
I dag bruker headeren stylingen til h5, så tenker at det kanskje gir mening å defaulte til h5 eller er div bedre?
