### ISSUE TITLE
Opprette wiki med utvidet dokumentasjon

### ISSUE THREAD

**Issue by steffenz** [SpareBank1/designsystem#879]
I stedet for å ha fryktelig mye informasjon i ``CONTRIBUTE.MD`` filen bør vi heller kutte denne ned til det mest grunnleggende slik at folk kommer kjapt i gang. Mer detaljert informasjon kan vi heller ha i en wiki vi peker til fra dette dokumentet.

**Comment by ivarni** [comment]
Jeg tror noe av problemet er at vi ikke har en wiki som er tilgjengelig utenifra, og hele grunnen til at vi flyttet til GitHub i utgangspunktet var jo at vi skulle være tilgjengelige for eksterne ute hos bankene.

Men kanskje en statisk side under https://design.sparebank1.no/ kan fungere?

**Comment by steffenz** [comment]
Hei! Jeg burde kanskje presisert at denne blir [liggende på GitHub](https://github.com/SpareBank1/designsystem/wiki) og ikke i noe internt system. Planen min er å dokumentere litt mer detaljert hvordan man går fra issue til en ferdig pull request med litt skjermskudd, illustrasjoner og kodesnutter. Opprettet egentlig denne saken mest for å ha skjermskudd til å bruke :joy: 
Ellers er jeg veldig åpen for alt av forslag til å gjøre dette så bra som mulig!

**Comment by ivarni** [comment]
Ah, my bad, hadde gått meg hus forbi at det er wiki funksjonalitet på GH. Carry on :)
