### ISSUE TITLE
Informasjonsarkitektur på design.sparebank1.no

### ISSUE THREAD

**Issue by steffenz** [SpareBank1/designsystem#890]
Hvis vi ønsker et mer levende nettsted med plass til nytt innhold og en mer kontinuerlig oppdatering bør vi se på innholdsstrukturen. Samtidig er det viktig at vi ikke går "overboard" slik at det blir vanskelig og unnaturlig å finne frem i. Slår samtidig et slag for å bruke enkelt språk og navn på ting.

Jeg har sett på flere forskjellige slike sider, men må si at både Saleforce sitt [Lighning Design System](https://www.lightningdesignsystem.com/) treffer meg rent strukturmessig. Er ellers fan av Googles [Material](https://material.io/), men synes sidene deres er knotete å finne frem i. Det er likevel mye bra her vi kan la oss inspirere av.

## Dagens struktur 
* Kom i gang
  * For designere
  * For utviklere
  * Bidra
* Stil og tone
  * Våre verdier
  * Unikt for oss
  * Vår relasjon til kundene
  * Stil og tone 
* Visuell identitet
  * Farger
  * Ikoner
  * Typografi
  * Illustrasjoner
  * Animasjoner
* Universell utforming
  * WCAG 2.0
  * Tips og råd
  * Verktøy
* Komponenter 
  * [...]

## Forslag til ny struktur 
* Kom i gang (landingsside kombinerer alt fra forrige løsning)
* Retningslinjer
  * Introduksjon
  * Illustrasjoner
  * Animasjoner
  * Stil og tone
* Design tokens (knytte opp mot Figma - annet navn?) 
  * Introduksjon
  * Farger
  * Typografi
* Universell utforming  (kanskje slå sammen/endre noen punkter her)
  * Introduksjon
  * WCAG 2.0
  * Tips og råd
  * Verktøy
* Ikoner (utforsker der man kan laste ned/kopiere navn fra. Litt som i [Material](https://material.io/resources/icons/?style=baseline))
  * Kategorier basert på innhold (feks tilgjengelighet/maskinvare etc)? 
  * Mulighet å sortere på type (filled/outlined etc)? 
* For utviklere
  * Introduksjon
  * CSS rammeverk
  * React komponentbibliotek 
* Artikler (side med linker til Medium, som hos [Salesforce](https://www.lightningdesignsystem.com/articles/)) 

## Utfordringer knyttet til design og layout
Jeg liker veldig godt dagens løsning, men ser at det kanskje kan være hensiktsmessig å ha menyen nedover istedet for bortover, som på [Lighning Design System](https://www.lightningdesignsystem.com/). Da kan vi i større grad legge til og fjerne ting i fremtiden uten å bekymre oss for at ting tar for mye plass (som i sum kan føre til dårlig navngivning fordi vi korter ned ting). Dessuten kan vi da bruke prosentvis layout som tar opp hele skjermstørrelsen fremfor å sentrere i midten. Har man litt størrelse på skjermen er det digg å bruke plassen når man skal lese. 

## Etterord
Jeg valgte å opprette et GitHub Issue for å kunne motta tilbakemeldinger fra alle. Dette er veldig work in progress for øyebelikket. Har du forslag til endringer eller forbedringer er det bare å sitere eller kopiere fra dette innlegget og putte inn kommentarer.

## Relevante lenker
[10 Best Design Systems for 2019 - Webdesignerdepot](https://www.webdesignerdepot.com/2019/08/10-best-design-systems-for-2019/)
[Material Design](https://material.io/)
[What Are Design Tokens - CSS Tricks](https://css-tricks.com/what-are-design-tokens/)
[Design tokens with Figma - Prototypr](https://blog.prototypr.io/design-tokens-with-figma-aef25c42430f)

**Comment by kwltrs** [comment]
Liker forslaget. Ser ut som en veldig bra utgangspunkt.

Vi burde også ha inn informasjonen fra CONTRIBUTING.md/wiki'n.

**Comment by steffenz** [comment]
Enig! Det tenkte jeg på å legge inn under Kom i gang > Bidra punktet. Eventuelt med lenker direkte til GitHub wikien :smile:

**Comment by steffenz** [comment]
Flyttet til Trello.
