### ISSUE TITLE
Feil i eksempler på kontekstuelle meldinger

### ISSUE THREAD

**Issue by marianne-grov** [SpareBank1/designsystem#893]
**Beskrivelse av feilen**
Eksemplene i designsystemet bruker **heading** til å sette tittel, men riktig prop er **header**

**Steg for å gjenprodusere**
Se f.eks [ContextInfoMessage i designsystemet](https://design.sparebank1.no/styleguidist/index.html#!/ContextInfoMessage), hvor **heading** er satt, men tittelen ikke dukker opp. 

**Forventet oppførsel**
Eksemplene burde sette **header** i stedet for **heading**

**Skjermskudd**
![Screenshot from 2020-05-05 10-52-45](https://user-images.githubusercontent.com/3618008/81051182-94881500-8ec1-11ea-9815-366485965fe9.png)

**Comment by steffenz** [comment]
Hei! Tusen takk for hjelpen her, og godt observert! :smile: Jeg har nå løst feilen på de sidene som ser ut til å være berørte (i praksis alle sidene under kontekstmelding). Har søkt rundt i løsningen uten å finne flere tilfeller, men vet du om noen er det bare å si fra her, eller i den tilknytta PR'en.
Igjen, takk for hjelpen og beklager litt sent svar fra vår side. :tada:
