### ISSUE TITLE
FFE har ikke en konsistent focus-ring

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#897]
**Beskrivelse av feilen**
Det er litt varierende hvor og hvordan focus-styling er implementert
https://github.com/SpareBank1/designsystem/search?l=Less&q=%22%26%3Afocus%22

De aller fleste stedene er det brukt en `box-shadow` men parameterene varierer litt. 

For noen komponenter, feks lenker, er det ikke definert noe i det hele tatt og man faller tilbake på browser defaults. 

Etter at Chrome i [siste versjon byttet sin default til en svart boks](https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html) begynner dette å se litt rart ut.

Ved tab fra Shortcutbutton til lenka skifter focus-ringen nå farge i Chrome v83 

![image](https://user-images.githubusercontent.com/379849/83612450-b63cf080-a582-11ea-9613-f9be43b76cb4.png)

![image](https://user-images.githubusercontent.com/379849/83612502-c5bc3980-a582-11ea-8a67-759abed03ed6.png)

**Steg for å gjenprodusere**
Besøk https://design.sparebank1.no/styleguidist/index.html i Chrome v83 og tab rundt.
Sammenlign gjerne med Chrome v81.

**Forventet oppførsel**
Konsistent utseend på focus-markeringen for FFE komponenter

**Desktop (fyll ut feltene ):**
 - XUbuntu 14.04
 - Chome 
 - v83

**Tilleggsinformasjon**
Det hadde forøvrig også vært fint om FFE eksponerte noen klasser for focus-styling som vi kunne arve når vi implementerer egne komponenter i prosjektene, slik at vi kan sørge for en konsistent opplevelse i hele løsningen vi lager.

**Comment by ivarni** [comment]
Alternativt kunne vi kanskje bare fjernet den focus-stylingen vi har og overlatt det til browseren slik at brukerne får en opplevelse de er vant til fra andre nettsteder?

Generelt kommer det ofte mye ekstra arbeid ut av å prøve å kjempe mot accessibility-ting som browser-leverandører lager.

**Comment by antidecaf** [comment]
Vi har akkurat hatt Funka innom for å se på UU, og en av anbefalingene deres er at man tar seg av focus-styling på egenhånd. Browser-implementasjonene er ikke spesielt konsekvente, og ikke alle browsere har defaults som lever opp til gjeldende krav til UU.

**Comment by ivarni** [comment]
@antidecaf Da bør vi nok høre på dem, men bør kanskje ta en jobb for å gjøre det konsekvent på tvers av FFE komponenter og også gjøre det lett å bruke FFE's focus-style på egne komponenter :)

**Comment by HeleneKassandra** [comment]
Lukker denne, da det er implementert ny fokus styling etter vi implementerte justert visuell profil. Opprett gjerne nytt issue dersom det forsatt er ett problem
