### ISSUE TITLE
A11y sjekk fra axe-core liker ikke Accordion

### ISSUE THREAD

**Issue by lfbergee** [SpareBank1/designsystem#909]
**Beskrivelse av feilen**
Default sjekken til axe-core er ikke så happy med Accordion implementasjonen.

**Steg for å gjenprodusere**
Stegene du må ta for å fremprovosere feilen
1. Gå til https://design.sparebank1.no/styleguidist/index.html#!/Accordion
2. Kjør a11y test fra axe, (https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/?src=search)
3. ![image](https://user-images.githubusercontent.com/46530368/88640620-6f6d0200-d0be-11ea-9ebe-35b673fcfd5d.png)

**Forventet oppførsel**
A11y sjekkeren burde ikke kaste feil.

Antageligvis blir det en misforståelse fordi vi setter rollen tablist på ul, men listen er bare rene li-er uten noe aria-info. Det ligger på diven inni li-en. Mulig det kan løses ved å flytte aria infoen ut til lien. Men er ikke helt overbevist at ul-li er riktig semantikk her.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

**Skjermskudd**
Hvis det er hensiktsmessig og mulig kan ofte et skjermskudd beskrive bedre og kortere enn ord. 

**Desktop (fyll ut feltene ):**
 - Operativssystem: Red Hat 7.8
 - Nettleser: Firefox 77, Chromium 83

**Tilleggsinformasjon**
- Axe 4.5.2 beta
- cypress-axe 0.8.1

**Comment by lfbergee** [comment]
Høyst relatert til #503, så denne kan sikkert stenges til fordel for #503

**Comment by pethel** [comment]
Denne ble løst #956
