### ISSUE TITLE
Stil og tone -forslag

### ISSUE THREAD

**Issue by hodoea** [SpareBank1/designsystem#91]
Lurte på om vi kunne endre one-linern til stil og tone siden( akkurat nå er det egentlig one-linern til merkevare siden som vi endret til stil og tone)

Et forslag fra @christerjohnsrud:

<img width="741" alt="skjermbilde 2018-03-13 kl 15 04 43" src="https://user-images.githubusercontent.com/8971560/37349290-5cfc77e8-26d6-11e8-80eb-a91d6c93fc21.png">

Dette forslaget under kan ventes med:

Vi har også en del ressurspersoner som andre på huset kan sparre med på tekstforslag, kan det være en idé å legge ved det i denne siden?

<img width="856" alt="skjermbilde 2018-03-13 kl 15 56 19" src="https://user-images.githubusercontent.com/8971560/37349599-1b205d0c-26d7-11e8-8f3e-4b007aa9bb57.png">

<img width="863" alt="skjermbilde 2018-03-13 kl 15 54 55" src="https://user-images.githubusercontent.com/8971560/37349521-e87b855c-26d6-11e8-99ad-f8d8c61f72d0.png">

**Comment by wkillerud** [comment]
Veldig fint om vi kan legge til disse personene på siden ja - alltid fint å ha noen å spørre :) 

Jeg kan endre onelineren til forslaget :+1:

**Comment by hodoea** [comment]
Jobber med en ny skisse. Vi har stil og tone kurs på onsdag, så jeg skal få innspill på hvordan den siden kan forbedres. :) https://sparebank1.invisionapp.com/d/main#/console/12247316/257696242/preview

**Comment by antidecaf** [comment]
@hodoea Nice! Liker gjenbruken av tab-konseptet fra fargeoversikten.

**Comment by antidecaf** [comment]
@hodoea Er løsninga i invision-lenka opplest og vedtatt? For da kan vi i tilfelle bare implementere den. :)

**Comment by hodoea** [comment]
Nei, bare jeg som har mocket noe raskt..Og vi har en del ting som skal inn i stil og tone basert på workshops vi har hatt med marked. Ordliste og eksempler bl.a  🎉

Jeg, Heidi og Siri skal se på dette neste mandag :) Sier ifra når lenken er klar

**Comment by selbekk** [comment]
Fikk dere sett på dette @hodoea ? :)

**Comment by hodoea** [comment]
Ja, men vi ble enige om å vente litt med dette hvis jeg ikke husker feil? @sirioc og @heilysto?

**Comment by sirioc** [comment]
Stemmer @hodoea 👍

**Comment by selbekk** [comment]
Den er grei. Da lukker jeg denne saken enn så lenge, og så kan den gjenåpnes når enn dere har tid til å se på det :-)
