### ISSUE TITLE
Aria-invalid støttes ikke av role radio

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#912]
**Beskrivelse av feilen**

Travis feiler med denne eslint-erroren:

    /home/travis/build/SpareBank1/designsystem/packages/ffe-form-react/src/BaseRadioButton.js
    49:17  error  The attribute aria-invalid is not supported by the role radio. This role is implicit on the element input  jsx-a11y/role-supports-aria-props

Feilen har oppstått etter en oppdatering av `eslint-plugin-jsx-a11y` der regelen har blitt innført. Stemmer overens med dokumentasjonen av [WAI-ARIA](https://www.w3.org/TR/wai-aria-1.2/#radio), så det bør vurderes å fjerne støtte for `aria-invalid` fra `BaseRadioButton` i `ffe-form-react`.

**Comment by steffenz** [comment]
Kan vi lukke denne? Ble litt usikker når PR'en sier at det er en midlertidig endring :thinking: 
@kwltrs @antidecaf

**Comment by kwltrs** [comment]
Ikke lukke. PR'en fikser bare at denne bugen ikke brekker bygget, men ikke selve bugen.

**Comment by HeleneKassandra** [comment]
Naturlig å se på denne samtidig?  https://github.com/SpareBank1/designsystem/issues/1064
