### ISSUE TITLE
Slå sammen meldingskomponenter

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#917]
Vi har i dag tre separate pakker med meldingskomponenter: `ffe-message-box(-react)`, `ffe-context-message(-react)` og `ffe-system-message(-react)`. Disse har tilsynelatende samme oppgave og veldig små forskjeller i utseende og oppførsel, men hver sin implementasjon og styling som divergerer.

Kan vi slå sammen disse komponentene og heller legge til rette for nødvendige varianter i form av props og modifiere?

Meldingsbokser:

![image](https://user-images.githubusercontent.com/463847/89394325-3b23c200-d70c-11ea-914f-37d3da5a4742.png)

Systemmeldinger:

![image](https://user-images.githubusercontent.com/463847/89394182-0ca5e700-d70c-11ea-8504-84ad3324d653.png)

Kontekstuelle meldinger:

![image](https://user-images.githubusercontent.com/463847/89394120-f8fa8080-d70b-11ea-86b4-1a1c0b56e2ca.png)

**Comment by kwltrs** [comment]
(Backlog-session) Det blir for mye støy for andre å slå sammen de tre meldingskomponenter nå. Forslag: vi lager en ny komponent for alle typer meldinger og deprecater disse tre.
