### ISSUE TITLE
WCAG issue: Lenker eller tertiary-button på grønnfargen brukt i ulike meldingsbokser har for dårlig kontrast

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#928]
Eksemplifisert i bildet under. Her er  det brukt tertiary button inni en kontektstuell melding. I våre applikasjoner er dette et mønster som brukes flere steder: en eller annen meldingsboks med lys grønn bakgrunn med lenke eller knapp inni.

Kontrastratio er 4.3, kravet til WCAG AA er 4.5.

Skjermbilde:
![image](https://user-images.githubusercontent.com/36953762/90645632-7b1f9480-e236-11ea-834f-a58e545d1a7a.png)

Kontrast:
![image](https://user-images.githubusercontent.com/36953762/90645559-5e835c80-e236-11ea-8946-9cdc3d013d70.png)

**Comment by hdaljord** [comment]
Det samme gjelder på lys blå bakgrunn, der er kontrastratio 4.26, mens kravet er 4.5 (AA).

![image](https://user-images.githubusercontent.com/36953762/90858801-2c354480-e387-11ea-98c9-fe745b46012f.png)

**Comment by hdaljord** [comment]
@Heilysto: Vi kommer inntil videre til å bruke hovedblå på lenker i meldingsboksene med for dårlig kontrast (avklart med Ragnhild), men det bør kanskje opp i GD-forum og avklares hva som er riktig farge og så bør det rettes i designsystemet og FFE slik at det fungerer bra.

**Comment by andrea-sb1** [comment]
Fargen på lenker og TertiaryButtons er nå erstattet med ffe-farge-vann (#005aa4) og den grønne bakgrunnsfargen i meldingsboksene erstattet med ffe-farge-nordlys-30 (#c2e7da) som gir et kontrastforhold på 5.2:1 (WCAG AA)

Det blir nok aktuelt å se på om vi kan bedre kontrasten enda mer for lenker og TertiaryButtons i meldinger og på andre fargede bakgrunner, men per nå er ffe-farge-vann valgt farge for disse i SpareBank 1
