### ISSUE TITLE
Problemer med å konvertere base64 pdf'er fra ffe-file-upload tilbake til lesbare filer 

### ISSUE THREAD

**Issue by nataliefl** [SpareBank1/designsystem#964]
**Beskrivelse av feilen**
getFileContent (via FileReader.readAsDataURL) funksjonen i ffe-file-upload ser ut til å ødelegge PDF'er

**Steg for å gjenprodusere**

Jeg testet med [denne](http://www.orimi.com/pdf-test.pdf)

...

const content = getFileContent(pdfFile);
const encodedString = content.replace('data:application/pdf;base64,','')
const data = atob(encodedString);
const blob = new Blob([data],{'type':'pdf'});
const file = new File(blob,"filename.pdf",{type:"pdf"});

Kjør en diff på filstørrelsen før og etter konvertering eller evt. last den ned og forsøk å åpne den. I mitt tilfelle ble filen ulesbar.
Løste det isteden med å bruker FileReader.readAsArrayBuffer. Usikker på hvorfor dette skjer, jeg har sett eksempler på stackoverflow hvor de bruker readAsDataURL men noen har rapportert det samme problemet som jeg har opplevd og svaret de fikk var at binærformatet til PDF'er kan inneholde data som ikke lar seg konvertere til string. 

**Forventet oppførsel**
Forventer at filinnhold skal være konverterbart uavhengig av filtype

**Skjermskudd**

**Desktop (fyll ut feltene ):**
 - Operativssystem: Redhat
 - Nettleser Firefox
 - Versjonsnummer 78.4

**Comment by lundal-sb1** [comment]
Problemet er `atob()`. Dette er hva typescript sier om funksjonen:

> **This function is only provided for compatibility with legacy web platform APIs**
> **and should never be used in new code, because they use strings to represent**
> **binary data and predate the introduction of typed arrays in JavaScript.**
> **For code running using Node.js APIs, converting between base64-encoded strings**
> **and binary data should be performed using `Buffer.from(str, 'base64')` and`buf.toString('base64')`.**

**Comment by tuva-odegard** [comment]
Virker ikke som at dette er relevant for komponentene i designsystemet, så lukker den.
