### ISSUE TITLE
iOS sliter med å forstørre font størrelser satt i px

### ISSUE THREAD

**Issue by HeleneKassandra** [SpareBank1/designsystem#967]
**Beskrivelse av feilen**
Når man prøver å forstørre tekst i iOS, så fungerer det ikke, pga at font størrelser er hardkodet i px.
Feilen kan rettes ved å sette en default font-størrelse på html elementet, og deretter bruke rem istedenfor px i komponentene. 

**Steg for å gjenprodusere**
Prøv å forstørre teksten på iOS

**Forventet oppførsel**
Når man forstørrer forventer man at alle tekstene blir større og at innholdet forsatt har riktig spacing etc

**Comment by ghost** [comment]
Relevant artikkel: https://www.interactiveaccessibility.com/blog/text-resizing-web-pages-ios-using-dynamic-type#.X7PiZDUo--Y
