### ISSUE TITLE
ffe-grid(-react): Modifier for setting `text-align: center;`?

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#98]
#### Which package is this issue related to?

ffe-grid and ffe-grid-react

#### Describe your issue

When using the `center` modifier the boxes in the grid column get centered horizontally, but the content inside those boxes does not get centered.

Sometimes I'd like to center the text content as well. Now I have to add a custom class just to center some text.

Would it be OK to add a new modifier to the grid that also applies `text-align: center;`?

**Comment by antidecaf** [comment]
Do it! :v:

**Comment by selbekk** [comment]
On it! 💪🏿
