### ISSUE TITLE
AccordionItem kan ikke brukes separat fra Accordion, pga. implisitt avhengighet til prop

### ISSUE THREAD

**Issue by ghost** [SpareBank1/designsystem#983]
**Beskrivelse av feilen**
`AccordionItem` er implisitt avhengig av propen `headingLevel` som vil gi en runtime feil dersom `AccordionItem` brukes uavhengig av `Accordion`. Feilen kommer mest trolig fra denne linjen: [AccordionItem#32](https://github.com/SpareBank1/designsystem/blob/2ae5b6129a792d6aee50be46ae9eb5a7bba5bc1b/packages/ffe-accordion-react/src/AccordionItem.js#L32), hvor komponenten bruker en prop (`headingLevel`) som den forventer å få sendt ned fra en parent-komponent.

**Steg for å gjenprodusere**
1. Ta i bruk `AccordionItem` i en egen parent-komponent (_ikke_ bruke `Accordion`).
2. Bygg og kjør appen
3. I konsollet vil man få en feilmelding: **The tag <hundefined> is unrecognized in this browser**

**Forventet oppførsel**
Dersom man skal kunne bruke `AccordionItem` uavhengig av `Accordion` må interfacet reflektere dette. Dvs:

```typescript
export interface AccordionItemProps extends React.HTMLProps<HTMLDivElement> {
    heading: string | React.ReactElement;
    defaultOpen?: boolean;
    onToggleOpen?: (isOpen: boolean) => void;
    headingLevel?: 1 | 2 | 3 | 4 | 5 | 6;    // Legge til denne
}
```

**Comment by pethel** [comment]
Vad er i veien for og bruke en Accordion runt? Du går miste om tastatur navigasjon hvis du ikke implementerar det selv. Att headingLevel settes på Accordion og ikke AccordionItem gjorde jag før det ikke gir mening att ha olika heading nivåer. Jag synes ikke det du føreslår burde gjøres.

Jag mener att man ikke burde oppfordra til bruk av AccordionItems uten Accordion slik man gjør med denne endringen. Hvis folk bruker AccordionItems uten Accordion så får man som sagt ikke med seg pil tastatus navigasjon. (edited)

**Comment by ghost** [comment]
@pethel Det er et godt poeng. Antakeligvis har den som tok i bruk `AccordionItem` i vår app ikke tenkt over dette, men dette er lenge siden så eg har ikkje mulighet til å diskutere hvilke vurderinger som ble gjort. 

Lukker saken.
