### ISSUE TITLE
Accordion: Kunne ha kun 1. AccordionItem åpent om gangen

### ISSUE THREAD

**Issue by etse** [SpareBank1/designsystem#984]
**Beskrivelse:**

I vår applikasjon har vi et behov for å kun ha 1. `AccordionItem` åpent om gangen. Trykker man på et annet `AccordionItem` er det ønskelig at de andre lukkes. Frem til nå har vi løst dette med at applikasjonen vårt selv har håndtert logikken for om et `AccordionItem` er åpent eller lukket, ved å sende inn `isOpen` til hvert item. Når vi nå oppgraderte til nyeste versjon ser vi at dette propen ikke lenger er i bruk av `AccordionItem`, så logikken brakk.

**Forslag til løsning:**

Legge til en ny optional prop `isOpen` på `AccordionItem`, som hvis satt, vil overstyre state-variabelen `isExpanded`. Man får da mulighet til å ta kontroll over oppførsel selv om man ønsker. Dette vil også være likt med hvordan mange native-komponenter i react-fungerer. (f.eks. `value` på input-komponenter). Man får en oppførsel som fungerer fint out-of-the-box, som dekker 95% av behovene. Og når man har spesielle behov kan man overstyre.

**Mulig forbedringsforslag: (kanskje utenfor scope nå):**

Legge til en prop på `Accordion` hvor du kan skru på at kun 1. `AccordionItem` skal være åpent om gangen. Ser for meg dette er en oppførsel flere kan ønske i fremtiden, så kan fint komme out of the box. Men vet ikke om vi har tid til å implementere en god løsning på det nå. Og løsningen kan uansett bruke `isOpen`-propen vi legger til for å implementere det.

Om dere tenker dette høres ut som en grei løsning kan jeg fint lage en PR på det :)

**Comment by kwltrs** [comment]
Liker foreslag med at det blir en prop på `Accordion` bedre, dvs det forslaget som kanskje er utenfor scope. Er det mulig at dere tar en titt på den løsningsveien?

**Comment by etse** [comment]
Helst ikke, vi prøver bare å bli ferdig med å oppgradere ffe i mobilbanken, og fikse ulike ting som brakk. (PRen som er knyttet til denne saken legger egentlig bare tilbake funksjonalitet som forvant i en tidligere release). Og slik jeg forstår prioriteringene nå ender vi dessverre fort opp med å heller nedprioritere oppgaven om ting tar for lang tid, da vi har andre ting som brenner mer.

Forslaget med å bake det inn i `Accordion` ser jeg for meg uansett vil bruke `isOpen` om man trenger det i fremtiden. Så det legger til rette for det om noen har tid og behov for det. Eneste er at man må være litt smart med hvordan man lar `Accordion` skille på de ulike childsene. `AccordionItem` har ikke en `id` prop som required i dag, så man må finne en smart måte å kunne huske hvilken som er valgt som også funker om man f.eks. legger til eller fjerner `AccordionItem` dynamisk (index vil f.eks. fungere dårlig i slike situasjoner). 

Med andre ord, tror jeg det må gjøres litt tankearbeid rundt hvordan man vil implementere det på en generell måte i `Accordion`.
